assets/vue/components/signalement-form/TheSignalementAppForm.vue
#2607    
Envoi à Matomo de l'affichage de la modale qui indique qu'un signalement existe déjà.
Mais pas si un brouillon a déjà commencé.
`make tools-run`
`make matomo-disable-ssl`
=> [FO - Formulaire] Envoi événement à Matomo lorsqu'un signalement est en doublon 

src/Messenger/MessageHandler/PdfExportMessageHandler.php, templates/pdf/signalement.html.twig, tests/Unit/Service/Signalement/Export/SignalementExportPdfTest.php
#2776    
Ajout d'informations manquantes dans l'export PDF :
- Informations sur le propriétaire (nom / prénom / adresse)
- Présence de DPE
- Situations suspectées lors de la déclaration
Corrections d'infos existantes
- Nombre de personnes dans le foyer
=> [BO - Export PDF] Ajout d'informations manquantes

.scalingo/nginx/server.location
#2754   
L'ajout du header `Cross-Origin-Embedder-Policy "require-corp";` empêchait le chargement du script de matomo.js car celui-ci ne contient pas les en-têtes `Cross-Origin-Resource-Policy` ou `Cross-Origin-Embedder-Policy`.
* Transformation de l'en-tête `Cross-Origin-Embedder-Policy "require-corp";`  en `Cross-Origin-Embedder-Policy "unsafe-none";`
=> [Sécurité] Correction du chargement de matomo.js

src/EventListener/LoginListener.php
#2786 
- Ajout d'un try catch pour avoir l'id de l'user dans l'erreur remonté
- bypass du historyEntryManager pour que le flush soit fait dans la même transaction que l'update user
=> [QA login] Doctrine\DBAL\Exception\DeadlockException

assets/vue/components/signalement-form/matomo.ts, assets/vue/components/signalement-list/TheSignalementAppList.vue, assets/vue/components/signalement-list/components/SignalementListFilters.vue, assets/vue/components/signalement-list/store.ts, src/Controller/Back/AffectationController.php, src/DataFixtures/Files/Partner.yml, src/DataFixtures/Files/User.yml, src/Repository/SignalementRepository.php, src/Service/Signalement/SearchFilterOptionDataProvider.php, tests/Functional/Controller/BackArchivedAccountControllerTest.php, tests/Functional/Service/Signalement/SearchFilterOptionDataProviderTest.php
#2797    
Le bouton n'est plus limité aux SUPER ADMIN et RT. Il doit aussi être affiché aux agents (admin et user partenaire) si ces derniers ont des signalements importées.
*  Mise à jour de la méthode `countImported` pour compter le nombre de signalements importés pour l'utilisateur
* Permettre au cache de gérer l'invalidation via les tags
* Mise à jour des fixtures
Vider le pool de cache
```
make clear-pool pool="--all"
```
Importer des signalements du 38
```
make console app="import-signalement 38"
```
=> [BO - Liste des signalements] Ajouter la possibilité de voir les signalements importés aux agents

assets/vue/components/signalement-list/TheSignalementAppList.vue, assets/vue/components/signalement-list/components/SignalementListFilters.vue
#2796    
Rendre le overflow visible de manière statique en CSS au lieu de le faire en JS
* Suppression de l'affichage de l'overflow de manière dynamique
* Appliquer une règle CSS pour rendre le overflow statique
=> [BO - Liste] Listes étiquettes et partenaires tronquées

assets/vue/components/signalement-list/components/SignalementListCards.vue
#2801    
#2805 
Les statuts des affectations n'est plus limité aux admin et aux RT
* Suppression de la condition
* Ajout d'une bordure pour les nouveaux signalements
```
make npm-watch
```
=> [BO - Liste Signalement] Visibilité statuts affectations

src/Controller/Back/AffectationController.php, src/Controller/Back/BackTagController.php, src/Controller/Back/SignalementActionController.php, src/Controller/Back/SignalementController.php, src/Controller/Back/SignalementFileController.php, src/Dto/Request/Signalement/AdresseOccupantRequest.php, src/Dto/Request/Signalement/CompositionLogementRequest.php, src/Dto/Request/Signalement/CoordonneesBailleurRequest.php, src/Dto/Request/Signalement/CoordonneesFoyerRequest.php, src/Dto/Request/Signalement/CoordonneesTiersRequest.php, src/Dto/Request/Signalement/InformationsLogementRequest.php, src/Dto/Request/Signalement/ProcedureDemarchesRequest.php, src/Dto/Request/Signalement/SituationFoyerRequest.php, src/Dto/Request/Signalement/VisiteRequest.php, templates/back/signalement/view/edit-modals/edit-address.html.twig, tests/Functional/Controller/Back/BackTagControllerTest.php, tests/Functional/Controller/Back/SignalementActionControllerTest.php, tests/Functional/Controller/Back/SignalementControllerTest.php, tests/Functional/Controller/Back/SignalementFileControllerTest.php
#2740
- Ajout de contraintes sur les request correspondant au différente popup d'édition du signalement
- Contrôle des longueurs des champs pour les tags, suivis, cloture, description des doc, 
- Fix sur l'affectation (contrôle du partenaire)
=> [BO - Signalement] Contrôle des entrées des formulaires

migrations/Version20240709130023.php, scripts/upload-s3.sh, src/Command/AddBailleurLinkOnSignalementCommand.php, src/Command/ImportBailleurCommand.php, src/Controller/BailleurController.php, src/Entity/Bailleur.php, src/Entity/Signalement.php, src/Repository/BailleurRepository.php, src/Repository/SignalementRepository.php, src/Repository/TerritoryRepository.php, src/Service/Import/Bailleur/BailleurHeader.php, src/Service/Import/Bailleur/BailleurLoader.php, tests/Functional/Service/Import/Bailleur/BailleurLoaderTest.php, tests/Unit/Command/ImportBailleurCommandTest.php
#2340
- Adaptation de la commande `app:import-bailleur` pour importer le nouveau fichier bailleurs (elle supprime les bailleurs précédent qui ne corresponde pas)
- Modification de la recherche bailleur via l'autocomplete pour chercher aussi sur le nouveau champ "raison sociale"
- Ajout de la commande `app:add-bailleur-link-on-signalement
`
Travailler sur une copie de la base de prod
=> [BO] Normaliser les noms des bailleurs publics

src/Service/Intervention/InterventionDescriptionGenerator.php, tests/Unit/Service/Intervention/InterventionDescriptionGeneratorTest.php
#2808    
Mise à jour message arrêtés
* Fix typo message arrêtés
* Mise à jour message arrêtés mainlevée
```sh
````
=> [BO - SISH] Mise à jour message arrếtés

assets/vue/components/signalement-form/components/SignalementFormScreen.vue, src/Dto/Request/Signalement/AdresseOccupantRequest.php, src/Dto/Request/Signalement/CoordonneesBailleurRequest.php, src/Dto/Request/Signalement/SignalementDraftRequest.php, src/Entity/Signalement.php
#2803
Ajout de contrôle sur le format du code postal (5 chiffre) pour corriger le crash base de données en cas d'injection d'une valeur supérieur a 5 carractères
=> [QA][FO] limiter taille du code postal bailleur

migrations/Version20240712154158.php, src/Entity/Partner.php
#2806
Changement du type de la colonne `competence` de `Partner` afin de pouvoir enregistrer toutes les compétences sans avoir un crash base de données
=> [BO - Partenaires] Ajout de toutes les compétences impossible

migrations/Version20240711084455.php, src/Command/ImportSignalementCommand.php, src/Service/Import/Signalement/SignalementImportMapper.php, src/Service/Signalement/ReferenceGenerator.php, tests/Functional/Service/Signalement/ReferenceGeneratorTest.php
#2789    
- Fix de la commande d'import de signalements pour éviter les références non conformes
- Fix du service de génération de référence pour éviter de continuer à créer des références non conformes après import
- migration pour corriger les références des signalements de l'Oise et de la Seine-Maritime
=> [Signalements] Revoir les références des signalements importés

src/Controller/Back/PartnerController.php, src/Entity/Partner.php, src/Entity/User.php, src/Manager/UserManager.php
#2741   
Ajout de contrôles côté back sur les formulaires d'ajout et d'édition d'utilisateur.
Les champs Nom, Prénom et E-mail n'étaient pas vérifiés.
Mise en place d'une validation de l'entité avant enregistrement.
Pour tester, j'ai supprimé les `required` des champs de formulaire
=> [BO - Partenaires] Contrôle back des champs de formulaire d'ajout et édition d'utilisateurs

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, src/Dto/DemandeLienSignalement.php, src/Dto/Request/Signalement/CompositionLogementRequest.php, src/Dto/Request/Signalement/CoordonneesFoyerRequest.php, src/Dto/Request/Signalement/SignalementDraftRequest.php, tests/Functional/Controller/Back/SignalementEditControllerTest.php, tests/Unit/Dto/Request/Signalement/AdresseOccupantRequestTest.php, tests/Unit/Dto/Request/Signalement/CompositionLogementRequestTest.php, tests/Unit/Dto/Request/Signalement/CoordonneesFoyerRequestTest.php, tests/Unit/Dto/Request/Signalement/CoordonneesTiersRequestTest.php, tests/Unit/Dto/Request/Signalement/InformationsLogementRequestTest.php, tests/Unit/Dto/Request/Signalement/ProcedureDemarchesRequestTest.php, tests/Unit/Dto/Request/Signalement/SignalementDraftRequestTest.php, tests/Unit/Dto/Request/Signalement/SignalementSearchQueryTest.php, tests/Unit/Dto/Request/Signalement/SituationFoyerRequestTest.php, tools/histologe/histologe.postman_collection.json
#2738    
Ajout de contrôles supplémentaires sur le formulaire de dépôt de signalement. 
Travail effectué à partir : 
- Des fichiers json
- Ticket  https://github.com/MTES-MCT/histologe/issues/2782
* Ajout de contrôle choix multiple
* Ajout de contrôle de longueur max
* Ajout de contrôle de type
* Amélioration de la couverture de code sur le dépôt ét l’édition de signalement (78.54%)
=> [FO - Signalement] Contrôle des entrées de formulaire

assets/vue/components/signalement-list/components/SignalementListCards.vue
#2815    
Dans le listing, pour améliorer l'affichage des procédures constatées suite à une visite, il faudrait modifier l'icône utilisée pour mettre fr-icon-success-line
* Changement dans VueJS
=> [BO - Liste des signalements] Changer l'icône pour procédures constatées

assets/app.ts, assets/controllers/cookie_banner.js, assets/controllers/modale_cgu_bo.js, config/packages/twig.yaml, config/services.yaml, migrations/Version20240717081056.php, src/Controller/Back/CguController.php, src/Entity/User.php, src/Manager/UserManager.php, templates/back/base_bo.html.twig, templates/back/cgu_bo.html.twig, templates/base.html.twig
#2359   
Jusqu'ici, les mises à jour des CGU passaient inaperçu pour les agents qui les avaient déjà validées lors de l'activation de leur compte.
On met donc en place une modale pour pouvoir les valider.
* Ajout d'un paramètre qui stocke la dernière date de mise à jour des CGU
* Ajout d'un champ à l'entité User pour stocker la dernière version validée par l'utilisateur
* Dans la migration, on en profite pour dire que les utilisateurs dont le statut est actif ET qui ont une date de login renseignée, n'ont pas besoin de re-valider les CGU
* Modale présente dans tout le bo
* Fichier js correspondant
- `make execute-migration name=Version20240717081056 direction=up`
=> [BO - CGU] Ajout d'une modale de notification de mise à jour des CGU

assets/vue/components/signalement-list/TheSignalementAppList.vue, assets/vue/components/signalement-list/store.ts, src/Controller/Back/SignalementListController.php
#2816 
Suite à des retours de territoire, il faudrait afficher par défaut les signalements importés (on fait l'inverse actuellement)
Ainsi, les utilisateurs verront le filtre coché par défaut et pourront le décocher au besoin
* Changement de la route `back_signalement_list_json` pour passer `isImported` à '`oui`' si on n'a rien dans l'adresse
* Changement dans l'app VueJS également
=> [BO - Liste des signalements] Afficher par défaut les signalements importés

assets/vue/components/signalement-form/components/SignalementFormScreen.vue, assets/vue/components/signalement-form/services/componentValidator.ts, src/Dto/Request/Signalement/AdresseOccupantRequest.php
#2758   
Certaines adresses se sont retrouvées avec uniquement le numéro de rue, mais pas le nom de la voie.
On ajoute des contraintes de saisie pour l'adresse, côté FO et côté BO
- pas vide
- pas juste des chiffres
- minimum 6 caractères
- maximum 100 caractères
=> [Formulaire] Ajout de contraintes de saisies pour l'adresse, pour éviter d'avoir uniquement des chiffres

assets/vue/components/dashboard/TheHistoAppDashboard.vue, src/Form/PartnerType.php, src/Service/Statistics/ListTerritoryStatisticProvider.php, templates/_partials/_search_filter_form.html.twig, templates/back/account/index.html.twig, templates/back/expired-account/index.html.twig, templates/back/inactive-account/index.html.twig, templates/back/partner/index.html.twig, templates/back/partner/view.html.twig, templates/back/partner_archived/index.html.twig, templates/back/signalement_archived/index.html.twig
#2813    
Pour faciliter l'usage et la lecture je propose qu'on utilise le format numéro de département - Nom du territoire partout (pour les filtres et l'affichage des info dans les listes) ainsi que "Territoire" en titre de colonne pour tout l'existant et les futures fonctionnalités
* Changement en twig et VueJS
=> [BO - SA] Uniformiser le nom des territoires dans le BO

migrations/Version20240718194157.php
#2750    
Ajout d'index sur les tables suivi, signalement et job_event pour améliorer les performances de certaines requêtes.
Cf le ticket pour la description détaillée des gains de performances
* Ajout d'une migration
=> [QA - Dashboard] Ajout d'index pour améliorer des requêtes trop lentes

assets/controllers/front_suivi_signalement/front_suivi_signalement.js, src/Controller/Security/SecurityController.php
#2751   
Depuis la mise à jour du 20 juin et un changement dans le SecurityController, nous avons reçu 32000 erreurs d'ouvertures des fichiers miniatures sur la page de suivi usager.
Je n'ai pas réussi à reproduire ce pb par contre j'ai reproduit un pb similaire quand je laisse la page suivi usager ouverte longtemps avant de cliquer sur les photos.
Cela est dû au token qui n'est plus valide car la session est dépassée
Conversation ici : https://mattermost.incubateur.net/betagouv/pl/pnewaijo63fo8x9xxttgeqdh8a
* Création d'une route keep-alive qu'on appelle toutes les 10 minutes en js depuis la page de suivi usager pour prolonger la session
=> [QA] Appel à une route keep-alive pour garder la session active sur la page de suivi usager

src/Controller/SignalementController.php, src/DataFixtures/Files/Suivi.yml, src/DataFixtures/Loader/LoadSuiviData.php, src/Entity/Signalement.php, src/Entity/Suivi.php, src/Security/Voter/SignalementVoter.php, src/Service/Mailer/Mail/Signalement/SignalementAskBailDpeMailer.php, src/Service/Mailer/Mail/Signalement/SignalementClosedToUsagerMailer.php, src/Service/Mailer/Mail/Signalement/SignalementConfirmReceptionMailer.php, src/Service/Mailer/Mail/Signalement/SignalementValidationMailer.php, src/Service/Mailer/Mail/Suivi/SuiviNewCommentFrontMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCanceledMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCanceledToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteConfirmedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteEditedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteRescheduledToUsagerMailer.php, templates/emails/accuse_reception_email.html.twig, templates/emails/ask_bail_dpe_signalement_email.html.twig, templates/emails/closed_to_usager_signalement_email.html.twig, templates/emails/lien_suivi_signalement_email.html.twig, templates/emails/nouveau_suivi_signalement_email.html.twig, templates/front/_partials/_suivi_signalement_tab_suivi.html.twig, tests/Functional/Controller/Back/SignalementListControllerTest.php, tests/Functional/Controller/SignalementControllerTest.php, tests/Functional/Manager/Esabora/EsaboraManagerTest.php, tests/Functional/Service/Notification/NotificationCounterTest.php, tests/Unit/Entity/SignalementTest.php
#2818 
#2817    
Objectif : permettre à l'usager de s'exprimer après la clôture de son dossier pour que le RT puisse rouvrir le dossier si nécessaire.
Il faudrait créer un type de suivi spécifique pour ce commentaire. Cela nous permettra de mesurer combien il y en a.
Objectif : encourager les usagers à se rendre sur leur page de suivi grâce à un langage plus adapté
* Ajout d'un type de suivi TYPE_USAGER_POST_CLOTURE
* Modification de la page de suivi pour permettre de laisser UN SEUL suivi de type TYPE_USAGER_POST_CLOTURE dans les 30 jours suivant la cloture du signalement
* Ajout d'un suivi de type TYPE_USAGER_POST_CLOTURE dans les fixtures
* Mise à jour des mails envoyés pour parler de "dossier" et plus de "page de suivi"
=>   [FO - Page de suivi usager] Laisser la possibilité de mettre un dernier commentaire après clôture + contenu mails

assets/controllers/form_nde.js, src/Dto/StatisticsFilters.php, src/Manager/AffectationManager.php, src/Manager/SignalementManager.php
#2672 
#2753 
#2752 
#2673    
Arrondi sur la superficie et la consommation énergétique lors de l'édition de la non-décence énergétique
SignalementManager->findUsersAffectedToSignalement rendre $partnerToExclude nullable
Les dates peuvent être null lors du filtre sur les statistiques
Appel de setIsSynchronized sur une affectation que si celle-ci n'est pas null
* cf ci-dessus
=> [BO] Fix sur quelques bugs sentry

src/Entity/User.php, src/Form/PartnerType.php
#2602 
#2655    
Ne pas vérifier les mails usagers pour mettre un mail générique à un partenaire 
Un admin partenaire ne doit pas pouvoir modifier le type de son partenaire
* Modification du FormType PartnerType pour ne pas pouvoir modifier le type de partner si l'utilisateur n'est pas au moins RT et pour ne mettre une erreur sur l'email générique que si l'utilisateur ayant déjà cette adresse email a au moins un rôle userPartner
* Ajout d'une fonction isUsager dans l'entité User
=>  [BO - Partenaire] Ne pas vérifier les mails usagers pour le changement de mail et le changement de type de partenaire réservé aux RT et SA

src/Repository/TerritoryRepository.php
#2856    
on a rajouté l'indicatif departement sur les liste de territoire mais on à laissé le tri alphabétique (sur la page partenaire par exemple) c'est perturbant
* Retrait de l'orderBy Name dans la requête
=> [BO - Listes] Enlever le tri alphabétique sur les listes de territoires

templates/back/signalement/view/visites/visites-buttons.html.twig
#2863    
Afficher le bouton de rapport de visite même quand elle n'a pas été effectuée
=> [BO - Signalement] Afficher le bouton de rapport de visite même quand elle n'a pas été effectuée

src/Manager/SignalementManager.php, src/Service/Signalement/PostalCodeHomeChecker.php, src/Service/Signalement/SignalementBuilder.php, tests/Functional/Service/Signalement/PostalCodeHomeCheckerTest.php
#2761    
Certaines communes ont un code postal dans un territoire et un code insee dans l'autre.
Voir : https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement
Par conséquent, les signalements sont attribués au mauvais territoire et peuvent être refusés.
* Pas de changement sur le test de code postal de la page d'accueil
* Dans la saisie d'adresse, on récupère le CP et le code Insee, et on vérifie les premiers caractères du code Insee
* A la fin du signalement, on attribue au territoire qui correspond aux deux premier caractères du code Insee
`make console app="update-communes"`
=> [FO - Signalement] Modification de la méthode de vérification et d'attribution de territoire

src/Service/Signalement/SearchFilter.php
#2877   
Afficher tous les partenaires affectés, même si on filtre sur le partenaire
* Ajout d'une jointure si on filtre par ce biais, pour ne pas mélanger jointure de donnée et de filtre
=> [BO - Liste signalements] Afficher tous les partenaires affectés, même si on filtre sur le partenaire

migrations/Version20240726144731.php
#2885
Corrige l'erreur de déploiement Scalingo : "Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set." qui fait suite au remplacement des clé primaire dans #2857
=> [Migration] - Fix déploiement

src/Specification/Affectation/PartnerExcludeSpecification.php
#2893    
Erreur Sentry sur le type pour PartnerExcludeSpecification
* Correction de type
=> [QA - Sentry] Erreur de type pour PartnerExcludeSpecification

templates/back/signalement/view-old.html.twig
#2895    
Les modales de suppression et d'édition ne s'affichent plus dans l'ancienne version de la fiche signalement.
* Ajout des fichiers twig dans l'ancienne version
=> [FO - Signalement] Modales d'édition et suppression de photo

src/Dto/Request/Signalement/AdresseOccupantRequest.php, src/Dto/Request/Signalement/SignalementDraftRequest.php
#2898
Les code indee commencant par le numéro du département, pour la corse il contienne une lettre en seconde position. Correction du contrôle pour accepter ce format
=> [BUG] code insee de la corse refusé

src/Dto/SignalementAffectationListView.php, tests/Functional/Factory/SignalementAffectationListViewFactoryTest.php
#2905   
Par défaut le serializer s'applique sur les propriétés de classe, hasNde n'avait plus de propriété donc la valeur n'était plus retourné.
* Ajout de l'attribut de serialisation sur le getter `hasNde`
=> [BO - Liste] Badge NDE ne s'affiche plus

migrations/Version20240805165820.php, src/Entity/JobEvent.php, src/Entity/Signalement.php, src/Entity/Suivi.php
#2908   
Synchroniser les nouveaux indexes avec les entités appropriées
* Ajout des attributs PHP
```
make create-db
```
=> [QA] Migration - Synchroniser les nouveaux indexes avec les entités 

.docker/php-fpm/Dockerfile, .docker/php-worker/Dockerfile, composer.lock, tools/wiremock/composer.json, tools/wiremock/composer.lock
#2851
(basé sur la branche #2641 pour eviter les conflits sur dockerfile)
- Upgrade en PHP 8.3
- Upgrade xdebug pour être compatible avec la version de PHP
- Upgrade wiremock-php pour être compatible avec la version de PHP
`make build`
=> [Tech] Upgrade en PHP 8.3

templates/back/signalement/view/header.html.twig, templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig, templates/back/signalement/view/visites/visites-list.html.twig
#2870
#2872
#2890
Modification d'affichage dans la fiche signalement pour les visites et le bandeau d'info à destination des RT
=> [FO - Signalement] Affichage visite et bandeau d'information

assets/styles/histologe.scss, templates/back/inactive-account/index.html.twig, templates/back/notifications/index.html.twig, templates/back/partner/index.html.twig
#2910 
#2911
Tableaux admin page partenaires et notifications : fixé les bouton d'action sur une ligne
Tableau admin page comptes inactifs : faire en sorte que le tableau entre entièrement dans la page
=> [BO - Liste partenaires + liste notif] Affichage des boutons d'action

templates/back/signalement/view/tags.html.twig, templates/back/tags/index.html.twig
#2916  #2923   
- Mettre bouton suppression en bouton secondaire
- Augmenter l'espace vertical entre les lignes d'étiquettes
* Mise à jour classes CSS
=> [BO - Etiquettes] Correction UI

src/DataFixtures/Loader/LoadSignalementData.php, templates/back/tags/index.html.twig, tests/Functional/Controller/Back/SignalementListControllerTest.php
#2917
- Ajout du filtre territoire pour les SA accédant a une liste de signalement depuis la page étiquette
- Correction des fixture et tests afin que les tag en doublon (sur territoire différents) soit placé sur les bon signalement en fonction de son territoire
=> [BO - Etiquettes] Quand accès au signalement en tant que SA, il manque le filtre sur le territoire

assets/vue/components/common/HistoMultiSelect.vue
#2920    
Il existe un problème de focus  que j'ai pas réussi à identifier sur chrome, cependant la suppression du tabindex sur le composant rend le composant de nouveau fonctionnel
Inconvénient est que le composant n'est plus accessible via le clavier. Faudrait un autre ticket pour investiguer davantage ou attendre l'upgrade de ce composant avec le nouveau composant qui est en beta actuellement
https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants-beta/liste-deroulante-riche
* Suppression de l'attribut tabindex
```
make npm-build
```
=> [BO - Liste signalements] Les filtres sélections multiple ne fonctionnent plus

assets/controllers/back_signalement_view/back_view_signalement.js, src/Entity/Signalement.php, templates/back/signalement/view/tags.html.twig
#2918 
#2921 
#2922
- Les étiquettes sont à présent affiché dans tous les cas sur la fiche signalement (même si le signalement n'est pas éditable)
- Uniquement les étiquettes qui ne sont pas archivés sont affichées sur les signalements
- Impossible de sélectionner plusieurs fois une même etiquette dans la gestion des étiquette d'un signalement (via input de recherche)
`make npm-buil`
=> [BO - Signalement] Afficher les étiquettes sur les signalements fermés

config/packages/twig.yaml, src/Controller/Back/TagController.php, templates/back/nav_bo.html.twig, tests/Functional/Controller/Back/BackTagControllerTest.php
#2939
- Désactivation du TagController (et ses tests) lorsque la feature `FEATURE_SIGNALEMENT_VIEW_ENABLED` est inactive
- Retrait du lien du menu BO vers la nouvelle page etiquette si la feature est inactive
=> [BO] désactiver la nouvelle page etiquette

assets/vue/components/signalement-list/TheSignalementAppList.vue, assets/vue/components/signalement-list/components/SignalementListCards.vue, assets/vue/components/signalement-list/store.ts, src/Controller/Back/SignalementActionController.php, src/Controller/Back/SignalementController.php, src/Controller/SignalementController.php, src/Dto/SignalementAffectationListView.php, src/Factory/SignalementAffectationListViewFactory.php, src/Manager/SignalementManager.php, src/Repository/AffectationRepository.php, src/Repository/NotificationRepository.php, src/Repository/SignalementRepository.php, src/Security/Voter/SignalementVoter.php, src/Service/Signalement/SignalementAffectationHelper.php, templates/_partials/_demande-lien-signalement.html.twig, templates/back/signalement/list/index.html.twig, templates/front/_partials/_suivi_signalement_tab_suivi.html.twig, templates/front/suivi_signalement.html.twig, tests/Functional/Controller/Back/SignalementControllerTest.php, tests/Functional/Controller/SignalementControllerTest.php, tests/Functional/Factory/SignalementAffectationListViewFactoryTest.php, tests/Functional/Manager/SignalementManagerTest.php, tests/Functional/Repository/AffectationRepositoryTest.php, tests/Functional/Service/Signalement/PhotoHelperTest.php
#2780
Modification du processus de suppression (archivage) d'un signalement
* Seul les signalements clôturés ou archivés peuvent à présent être supprimés : centralisation de la logique de contrôle back et front dans le voter
* Remplacement de l'alerte de confirmation de suppression par une modale
* Suppression des notifications du signalement lors de l'archivage (+ suppression de l'ancienne route de suppression inutilisé)
* La fiche de suivi utilisateur reste accessible en lecture aprés archivage d'un signalement, ajout du formulaire de récupération de lien de signalement dans le cas d'un motif de refus pour doublon
* Quelques simplifications/optimisations de code
=> [BO - Modale Confirm] Modifier Modale "Suppression"

src/Controller/Back/SignalementController.php, templates/back/signalement/view/header-old.html.twig, templates/back/signalement/view/header.html.twig
#2941    
Ajout marge lorsque saut à la ligne sur les bouton
* Ajout marge ancienne et nouvelle fiche
* Ajout de la référence de signalement dans le message de confirmation lors la clôture d'un signalement
=> BO - Fiche signalement] Ajouter espace entre bouton rouvrir et télécharger

cron.json, src/Command/Cron/ClearStorageTmpFolderCommand.php, tests/Functional/Command/Cron/ClearStorageTmpFolderCommandTest.php
#2682    
Ajout commande suppression document dans le repertoire tmp
* Ajout de la commande
* Déclaration en tant que cron
=> [FO] Nettoyage du dossier tmp du bucket

assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js, migrations/Version20240819083216.php, src/Controller/Back/SignalementFileController.php, src/Controller/FileController.php, src/Controller/SignalementController.php, src/Controller/SignalementFileController.php, src/Entity/File.php, src/EventSubscriber/InterventionConfirmedSubscriber.php, src/EventSubscriber/InterventionEditedSubscriber.php, src/Factory/Interconnection/Oilhi/DossierMessageFactory.php, src/Manager/SuiviManager.php, src/Service/Signalement/SignalementFileProcessor.php, templates/back/signalement/view/photos-album.html.twig, templates/back/signalement/view/photos-documents.html.twig, templates/back/signalement/view/user-declaration-desordre-photo.html.twig, templates/back/signalement/view/visites/visite-item.html.twig, templates/back/signalement/view/visites/visites-buttons.html.twig, templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig, templates/base.html.twig, templates/front/_partials/_suivi_signalement_tab_infos.html.twig, tests/Functional/Controller/SecurityControllerTest.php, tests/Functional/Factory/Oilhi/DossierMessageFactoryTest.php, tests/Unit/Service/Signalement/SignalementFileProcessorTest.php
#2751
Mise en place d'une nouvelle route permettant de visualiser les documents uploadé sur des URL durable
* Ajout d'un uuid sur l'entité File
* Création de la nouvelle route `show_file` basé sur cet uuid
* Utilisation de cette nouvelle route de partout, on garde l'ancienne pour les suivi historique et les export PDF
`make execute-migration name=Version20240819083216 direction=up`
=> [QA] Erreur d'ouverture de fichier depuis MEP du 20 janvier

assets/controllers/back_signalement_view/back_view_signalement.js, templates/back/breadcrumb_bo.html.twig
#2957   
Le clic sur la lien  Liste des signalements doit nous afficher la liste filtré si des filtres sont présents.
* Ajout d'un data-attributes sur le lien du fil ariane 
```
make npm-watch
```
=> [BO - Fiche signalement] Le libellé Liste signalement du fil d’Ariane doit avoir le même comportement que le bouton retour actuel

Procfile, src/Messenger/MessageHandler/PdfExportMessageHandler.php
#2953   
Logger les erreurs d'export PDF pou avoir plus d'info sur sentry
* Ajout d'un try catch
* Redemarrer le worker toutes les heures (https://symfony.com/doc/current/messenger.html#:~:text=Don%27t%20Let%20Workers%20Run%20Forever)
```
```
=> [QA - Export PDF] Fournir un peu d’élément en cas de crash

src/Dto/Request/Signalement/VisiteRequest.php, src/Twig/AppExtension.php, templates/back/signalement/view/visites/modals/visites-modal-edit.html.twig, templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig, templates/back/signalement/view/visites/visite-item.html.twig, tests/Unit/Dto/Request/Signalement/VisiteRequestTest.php
#2955
Sur staging on a 5160 interventions 😱 crées sans date, je me demande comment c'est possible. 
J'ai vérifié en production tous les interventions ont bien une date.
https://histologe-staging.incubateur.net/bo/signalements/2f14a3f2-c91a-44c0-824c-9b3789f91c36
Bien qu'on aurait pas le bug à la prochaine MEP, j'ai quand même ajouter des contrôles supplémentaires et des contraintes coté entité intervention pour sécuriser.
* Gestion du cas de la date de visite vide
* Mise à jour condition d'affichage heure (heure non saisi (minuit) affiche 2h du matin) 
* Ajout de contrainte sur la date et le partenaire de l'entité intervention
Récupération de la base de staging
```
make load-data
```
=> [QA] Erreur affichage bloc visite

migrations/Version20240826130414.php
#2967    
Recréation de tags pour le 62 car lors de l'import de signalements les tags ont été mal créés.
On a des tags de type `CUA|CM|NON DECENCE` au lieu de 3 tags `CUA`, `CM` et `NON DECENCE`
* Création d'une migration qui récupère tous ces tags concaténés, en créé des nouveaux si besoin, les attache aux signalements concernés et archive les tags concaténés
- Créer 3 tags "concaténés" pour le territoire 62 (par exemple `CUA|CM|NON DECENCE`, `CC DU TERNOIS|CM|NON DECENCE` et `CAPSO|CM|NON DÉCENCE RÉSOLUE`)
- Les attribuer (pas forcément tous) aux signalements du 62 (en s'assurant qu'un tag est sur au moins 2 signalements)
- Archiver un de ces tags
- Noter quels tags pour quels signalements (pour vérifier après migration)
=>  [BO - Tag] Recréer les tags pour le territoire 62

config/app/widgets.yaml
#2977   
Les liens qui filtrent la liste des signalements ont sauté. Sûrement quand on a supprimé le code legacy.
=> [BO - Tableau de bord] Correction des liens qui filtrent la liste des signalements

Procfile
#2982    
Eviter de se faire spammer toutes les heures pour des "crash" de worker. 
Scalingo n'a pas de système native pour détecter un arrêt volontaire 
* Augmentation de la durée de vie du worker avant de redémarrage
n/a
=> [QA] Augmentation de la durée de vie du worker à 24H avant redemarrage

migrations/Version20240902085930.php
#2836    
Récupération de la liste des étiquettes en doublon pour regrouper et supprimer ce qui est en double.
Pour chaque doublon listé :
- on vérifie que l'étiquette à archiver est bien du même territoire et n'est pas archivée
- on récupère tous les signalements qui sont liés à l'étiquette à archiver
- si le signalement est déjà lié à la nouvelle étiquette, on supprime la liaison
- sinon, on remplace la liaison avec la nouvelle étiquette
- on archive l'étiquette
Utiliser la base de prod
=> [BO - Etiquettes] Regroupement des doublons d'étiquettes

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/vue/components/signalement-form/components/SignalementFormCounter.vue, src/Service/Signalement/SignalementBuilder.php
#2983   
Une nouvelle erreur Sentry est apparue : problème d'enregistrement du montant d'allocation.
Ce souci est du aux modification W3C sur le composant Counter : avant le champ était de type `number`, il est passé en type `text`. (Voir ici : https://github.com/MTES-MCT/histologe/commit/5fbb88fc82c0c61cb65884853b9e632c51bce1dd#diff-18a10404bf4d57a155f4cb5dec465c6ea5955693ec7e867db53e22dc8fb24c07)
Problème : si on passe en number et qu'il y a un caractère non-numérique, l'ensemble de la valeur saute. Et de toute façon, ce n'était pas compatible W3C tel quel.
* Ajout d'un pattern de vérification pour les valeurs numériques côté front
* Ajout d'un pattern de conversion pour les valeurs numériques côté back
=> [FO - Signalement] Restriction aux valeurs numériques pour le composant Counter

assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryItem.vue, assets/vue/components/signalement-form/components/SignalementFormUpload.vue
#2992
Faire en sorte que tous les éléments qui prennent le focus sur le formulaire de signalement soit marqué visuellement
* Modification de la structure et css des bloc item de sélection des désordre pour afficher un focus propre
* Modification de la structure et css des bouton d'upload afin d'afficher le focus qui n'était pas visible
ticket liés : #2991 #2993
=> [FO - Formulaire - Accessibilité - 10.7] Dans chaque page web, pour chaque élément recevant le focus, la prise de focus est-elle visible ?

cron.json, migrations/Version20240903092746.php, src/Command/Cron/ClearStorageOriginalFileCommand.php, src/Controller/Security/SecurityController.php, src/DataFixtures/Loader/LoadSignalementData.php, src/Entity/File.php, src/Repository/FileRepository.php, tests/Functional/Command/Cron/ClearStorageOriginalFileCommandTest.php
#2285
Ajout d'une commande qui sera joué en cron afin de supprimer tous les fichier originaux des File ayant les variant (resize) de généré
Par sécurité la commande supprime uniquement les File crée depuis plus d'un mois
=> [Optimisation] Commande pour supprimer les images originales quand miniature générées

assets/vue/components/common/HistoMultiSelect.vue, assets/vue/components/signalement-list/components/SignalementListFilters.vue, assets/vue/components/signalement-list/interfaces/filters.ts, assets/vue/components/signalement-list/services/badgeFilterLabelBuilder.ts, assets/vue/components/signalement-list/store.ts
#2963   
Ajout d'une option "Afficher les signalements sans affectations" pour les RT et les SA afin d'afficher les signalements sans partenaires affectés
* Création du bouton dans SignalementListFilters (et dans le store et le filters)
* Mise à jour de la fonction de création de badges
=> [BO - Filtres] Affectation partenaire -AUCUN

src/Entity/Affectation.php, src/Entity/File.php, src/Entity/Intervention.php, src/Entity/Notification.php, src/Entity/Partner.php, src/Entity/Signalement.php, src/Entity/Suivi.php, src/Entity/Tag.php, src/Entity/User.php, src/EventListener/AuthentificationHistoryListener.php, src/EventListener/EntityHistoryListener.php, src/Manager/HistoryEntryManager.php, src/Service/History/EntityComparator.php, tests/Functional/Manager/HistoryEntryManagerTest.php
Remplace https://github.com/MTES-MCT/histologe/pull/2997
#2555
Simplification de l'historisation des suppression : 
- On parcours tout les champs de l'entité supprimé en transformant les valeur de la même façon que lors de l’enregistrement d'un update (pour les données complexe comme les object et date)
- en conséquence suppression du groupe `'history_entry:read`
=> [Historique] simplifier l'historisation des suppression

assets/vue/components/signalement-form/services/componentValidator.ts, assets/vue/components/signalement-form/services/variableTester.ts
#2995   
La modification du pattern sur les champs numériques a fait apparaitre un souci de validation pour les champs dont la valeur est `null` (plutôt que `undefined` ou `vide`).
* Ajout de test sur les valeurs `null`
=> [FO - Signalement] Correction du validateur quand les valeurs sont égales à null

cron.json
#3002
Suppression des deux crontask dont les feature sont désactivé pour ne as dépasser la limite de 10.
Note de ces crontask dans le ticket #2627
=> [scalingo] ne pas dépasser 10 crontask

migrations/Version20240910091939.php
#2976 
Les fonctions lié à la timezone ne sont pas pris en charge par scalingo. Il est nécessaire de refaire la migration en PHP sans utiliser les fonctions natives de MYSQL
Voir réponse de scalingo => https://github.com/MTES-MCT/histologe/issues/2976#issuecomment-2340094147
* Ajout migration
1. Récupérer une base de prod
2. Exécuter `make load-data` en mettant un point d’arrêt sur la migration pour empêcher son exécution
4. Ouvrir un signalement sur la timezone *Europe/Paris* http://localhost:8080/bo/signalements/87fc12b9-ff1d-4fde-b916-c2c2f49f0c4c 
- Il est noté 11h sur la fiche avec 9h en base
5. Ouvir un signalement sur une autre timezone *America/Martinique* http://localhost:8080/bo/signalements/288e8117-c148-42ff-8b99-3cd16a214106
- Il est noté 11h sur la fiche avec 15h en base …
=> Refaire la migration des dates d'intervention liée aux fuseaus horaires

src/Command/Cron/ClearStorageOriginalFileCommand.php, src/Repository/FileRepository.php, tests/Functional/Command/Cron/ClearStorageOriginalFileCommandTest.php, tests/Functional/Controller/PartnerControllerTest.php
#3014
Optimisation du nombre de requête généré par la commande `app:clear-storage-original-file`
Jusqu’à présent l'update du champ `isOriginalDeleted` était fait unitairement, et déclenché en plus une requete d'historisation de l'entité `File`, un update de masse et maintenant fait après la suppression effective des fichiers ce qui permet aussi d'ignorer l'historisation (inutile ici)
=> [OPTI] update en masse sur commande clear-storage-original-file

src/Command/Cron/SynchronizeInterventionSISHCommand.php, src/Repository/JobEventRepository.php, tests/Functional/Repository/JobEventRepositoryTest.php, tests/Unit/Command/Cron/SynchronizeInterventionSISHCommandTest.php
#1824    
Problème de compteur dans le rapport envoyé par mail
* Aller chercher les informations via une requête 
* Supprimer les incrémentations  
```
make create-db
```
=> [BO - Esabora] Email de reporting - problème de compteur sur les synchronisations visite et arrête

src/Factory/SignalementExportFactory.php, src/Service/Signalement/Export/SignalementExportLoader.php, src/Utils/DateHelper.php, tests/Unit/Service/Signalement/Export/SignalementExportLoaderTest.php, tests/Unit/Utils/DateHelperTest.php
#3026   
La structure actuelle avec les infos de visite peut faire planter l'export, il faut donc vérifier que la chaîne est bien une date avant de créer un objet datetime
https://sentry.incubateur.net/organizations/betagouv/issues/120243/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=4
* Vérifie que la chaîne de date de visite est bien une date
* Vérification sur le tableau de géolocalisation
* Afficher l'export CSV avec toute les colonnes tant que le nouvel export n'est pas activé
*  Récupérer une base de prod
* `make load-data`
=> [BO - Export] Mauvais format date de visite

src/Service/Signalement/SignalementBuilder.php
#3008   
Lorsqu'on transforme des données de types string en nombres, on utilise un preg_replace qui supporte mal de recevoir des valeurs nulles.
On commence donc à vérifier si la donnée est vide, pour la retourner nulle directement.
=> [FO - Formulaire] Correction conversion de valeurs nulles

src/Controller/Back/BackStatistiquesController.php
#3009   
Dans les stats du BO, lorsque les dates ne sont pas définies, l'instantiation de l'objet `DateTime` ne fonctionne pas.
=> [BO - Statistiques] Correction conversion date quand non définie

src/Controller/Security/SecurityController.php, tests/Functional/Controller/SecurityControllerTest.php
#3010
En cas de suivi d'un lien d'export PDF sans être connecté le voter levé une exception not found au lieu d'une access denied (qui redirige vers la page de connexion)
=> [QA - sentry] NotFoundHttpException sur les exports pdf des signalements

assets/vue/components/signalement-list/TheSignalementAppList.vue
#3022    
Lors de l'affichage de la liste, la première requête en tant que super admin, qui récupère tous les signalements, prend un peu plus de temps à s'exécuter (Pas urgent mais optimisations à étudier). 
Pendant ce temps, il est possible d'appliquer un filtre, mais la première requête reste en cours et peut afficher ses résultats même si un filtre a été appliqué entre-temps.
La solution retenue est d'annuler la requête en cours dès qu'un filtre est appliqué, comme c'est déjà le cas pour les filtres en général.
* Utilisation d'`AbortController` pour annuler les requêtes en cours.
Le test avec les données des fixtures est impossible, il faut donc récupérer un jeu de donnée de production
* `make load-data `
* `make npm-watch`
* Ouvrir l'inspecteur du navigateur.
=> [BO - Filtre] Gestion de chevauchement de requête

migrations/Version20240916094002.php, src/Command/Cron/ClearStorageOriginalFileCommand.php, src/Repository/FileRepository.php
#3039
Correction d'une belle bourde dans la #3015 : en fin de commande la requête faisait un update sur tous les fichiers (datant de plus d'un mois) et non pas uniquement ceux traité.
=> [BUG] Fix command "app:clear-storage-original-file"

src/Service/Signalement/Export/SignalementExportFiltersDisplay.php
#3047
Fix de la méthode `getPartnersFilterValue` pour le cas ou le filtre "Afficher les signalements sans affectations uniquement" est sélectionné
=> [BO - Export] Impossible d'exporter quand filtre "sans affectation" actif

templates/back/signalement/view/partners.html.twig
#3044
Affichage des affectation même pour un signalement clôturé
(Cependant leurs statut sera toujours clôturées dans ce cas la)
=> [BO - Fiche signalement] Afficher les partenaires affectés + leur statut même après clôture

assets/styles/histologe.scss, src/Service/UserAvatar.php, templates/back/nav_bo.html.twig, templates/emails/profil_edit_email.html.twig, tests/Unit/Service/UserAvatarTest.php
#3042 
#3043 
#3045
- L'avatar s'affiche dans un cercle entouré d'une bordure (#3042)
- Le nom de l'utilisateur accolé à l'avatar est souligné (#3043)
- Le code de confirmation dans l'email de validation de l'email est sur un fond, en gras et plus gros que le reste du texte (#3045)
=> [BO - Dashboard / Menu / Profil] fix UI UX profil

src/Messenger/MessageHandler/ListExportMessageHandler.php
#3053
- Prise en compte de la timezone du territoire de l'utilisateur pour générer le nom du fichier d'export afin que l'heure corresponde a son fuseau et ne soit plus UTC
=> [BO - Export] Décalage horaire dans le nom du fichier

templates/back/signalement/view/header.html.twig, templates/back/signalement/view/tags.html.twig
#3040
Pour une meilleure lisibilité, il faudrait :
Passer tous les badges au-dessus du nom en bleu france
Mettre le badge "en cours" à droite du nom
Passer les badges des étiquettes en bleu info
* Changement de twig
=> [BO - Fiche signalement] Modifier couleurs / position des badges dans l'en-tête

src/Service/Signalement/Export/SignalementExportPdfGenerator.php
#3067
Augmentation du time out de snappy PDF (par defaut a 60 sec) afin de pouvoir générer des PDF avec plein plein d'images
=> [QA] The PDF generation...exceeded the timeout of 60 seconds.

assets/scripts/vue/components/common/HistoMultiSelect.vue, assets/scripts/vue/components/common/HistoSelect.vue, assets/scripts/vue/components/common/external/HistoDataTable.vue, assets/scripts/vue/components/dashboard/TheHistoAppDashboard.vue, assets/scripts/vue/components/dashboard/TheHistoDashboardCards.vue, assets/scripts/vue/components/signalement-list/components/SignalementListFilters.vue, assets/scripts/vue/components/stats/TheHistoAppStats.vue, assets/scripts/vue/components/stats/TheHistoStatsDetails.vue, assets/scripts/vue/components/stats/TheHistoStatsDetailsItem.vue, assets/scripts/vue/components/stats/TheHistoStatsFilters.vue
#3011   
Pour le dashboard,
-     il faut s'assurer qu'il y a bien une bordure et une ombre sur les widgets (voir capture ci-après)
-     RT et SA : passer les tableaux signalements par territoire / affectations des partenaires / ESABORA sur le design du DSFR (comme ceux sur la liste des partenaires et des étiquettes)
-     SA : passer le filtre territoire avec un fond gris comme ceux sur la liste des signalements
Pour la page stats
-     Passer les filtres avec un fond gris comme ceux sur la liste des signalements
-     Passer le tableau répartition par partenaire sur le design du DSFR
-     Pour les cartes avec les chiffres fixes : ajouter une bordure comme les widgets sur le dashboard (mais sans ombre) couleur #dddddd
-     Pour les graphs : ajouter une bordure couleur blue france (# …
=> [BO - stats et dashboard] uniformisation couleur fond

src/Controller/Back/ExportSignalementController.php, src/Service/Signalement/Export/SignalementExportFiltersDisplay.php
#3048    
Sur la page qui permet les exports PDF, on affiche les filtres sélectionnés.
Pour les utilisateurs / admin territoires, on affichait le filtre de territoire, alors qu'ils ne l'ont pas sélectionné (qu'il est juste là par défaut).
Pour les utilisateurs, on affichait le filtre de signalements importés, alors qu'ils ne peuvent pas le sélectionner non plus.
* Dans la fonction qui détermine les filtres à afficher, on fait des cas particuliers pour ces deux filtres.
=> [BO - Page export] Masquer les filtres territoire / import en fonction des rôles

src/Service/Signalement/Export/SignalementExportFiltersDisplay.php
#3077   
Les filtres automatiques provenant du dashboard mais non-éditables dans la liste des signalements n'étaient pas repris correctement dans la page d'export, tant en terme d'affichage que de filtre.
=> [BO - Export] Correction de la prise en compte et de l'affichage des filtres

assets/scripts/vue/components/signalement-list/components/SignalementListHeader.vue, src/Dto/Request/Signalement/SignalementSearchQuery.php, src/Repository/SignalementRepository.php
#3073
Ajout d'un tri par nom de commune dans la liste des signalements
=> [BO - Signalement] Ajouter option de tri Commune listing

templates/back/tags/index.html.twig
#3082
Dans la page outil admin -> étiquettes, afficher les tag sous forme de badge dans le tableau
=> [BO - Etiquettes] Mettre les étiquettes sous forme de label

src/Controller/Back/SignalementController.php, src/Controller/Back/SignalementListController.php, src/Dto/Request/Signalement/SignalementSearchQuery.php, src/Service/UrlHelper.php, tests/Unit/Service/UrlHelperTest.php
#3074
Ré afficher la liste de signalements filtrés après cloture d'un signalement
=> [BO - Signalement] Garder filtres actifs après cloture signalement

src/Controller/Back/BackStatistiquesController.php
#3075   
Les admin partenaires avaient le droit de voir la totalité des statistiques du territoire.
On limite à son partenaire.
=> [BO - Statistiques] Limiter les statistiques d'un admin partenaire à son seul partenaire

assets/scripts/vanilla/services/table_sortable.js, templates/back/partner/index.html.twig, templates/back/tags/index.html.twig
#3083   
Le tri par colonne dans certains tableaux du BO ne fonctionnait pas bien.
* Correction du tri sur la page étiquettes. J'ai du toucher au js minifié, je l'ai un peu ajusté pour comprendre certaines parties, mais c'est encore minifié pour certains passages...
* Correction du tri au passage sur la colonne territoire de la page de partenaires
* Ajustement du titre de la page partenaire
=> [BO - Etiquettes] Correction du tri

src/EventListener/ExceptionListener.php, src/Service/Mailer/Mail/Error/ErrorSignalementMailer.php
#3101    
Ignorer les erreurs 404 dans les alertes mail comme sur Sentry
* Mise à jour exceptionListener
* Mise à jour de l'objet du mail
=> [QA] Ignorer les erreurs 404 dans les alertes email

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/json/Signalement/questions_profile_tous.json, assets/scripts/vue/components/signalement-form/components/SignalementFormPhonefield.vue
#3035    
Dans les critères 11.X de l'accessibilité, il est indiqué que chaque champ doit avoir une étiquette.
J'ai fait le tour et il manquait 3 choses :
- sur la page de profil de déclarant, un `label` pour les deux premiers boutons radio
- sur la page de zone concernée (batiment/logement), un `label` pour les deux premiers boutons radio
- sur le composant Numéro de téléphone, il y avait un `label` rattaché au champ texte. La liste déroulante de pays n'avait donc pas d'étiquette.
* Ajout de nouvelles étiquettes sur les deux écrans spécifiques
* Remplacement du `label` du numéro de téléphone par un fieldset qui entoure les champs `select` et `input`
`npm run build / watch`
=> [FO - Signalement] Accessibilité : ajout d'étiquettes non-existantes

assets/scripts/vue/components/dashboard/TheHistoAppDashboard.vue, assets/scripts/vue/components/dashboard/requests.ts, package.json
#3103    
Augmentation du timeout pour les requêtes du dashboard dont une peut mettre plus de 15 secondes pour le super-admin
Correction d'un problème de chargement de widget entraînant des widgets non chargés correctement dans le tableau de bord ou `initKPI` peut répondre avant `initSettings`
Les modifications apportées garantissent que les réponses des services réponde dans l'ordre voulu
* Surcharge des fonction callback initSettings et initKPI par des promesses initSettingsWithPromise et initKPIWithPromise
* Gestion des promesses lors de l'appel via async/await pour garantir l'ordre des réponses.
* Augmentation du timeout de 15 à 30s
* Mise à jour de la config eslint
Charger la base de prod
```
make load-data
```
Builder les assets
```
make npm-watch
```
=> [BO -Tableau de bord] Problème chargement du tableau de bord

src/Controller/Back/SignalementVisitesController.php, src/Security/Voter/InterventionVoter.php, src/Security/Voter/SignalementVoter.php, templates/back/signalement/view/visites/visites-buttons.html.twig, templates/back/signalement/view/visites/visites-list.html.twig
#3100   
Les personnes qui ont le droit d'éditer (et par conséquent : confirmer, annuler, ajouter/supprimer des docs) une visite sont les suivantes : Super Admin, Admin du territoire du signalement, Utilisateur du partenaire qui est affecté à la visite.
Avant correction, tous les partenaires affectés au signalement et avec la compétence visite pouvaient éditer la visite.
* Ajout d'un voter SIGN_EDIT_VISITE aux droits différents de l'ajout de visite
=> [BO - Signalement] Correction de la possibilité d'éditer une visite si pas assigné

assets/scripts/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue
#3125   
Quand on ne choisit aucun désordres, en arrivant sur le page "Les désordres renseignés" on a une erreur : 
Et du coup on est coincés
* Dans deux composants vérification de l'existence de `focusableElement` avant de vérifier l'existence de `focusableElement[0]`
=> [FO - Formulaire] Bug quand on n'a choisi aucun désordre

migrations/Version20241001125833.php, src/Controller/FileController.php, src/Entity/Enum/DocumentType.php, src/Entity/File.php, src/Messenger/MessageHandler/ListExportMessageHandler.php, src/Service/Mailer/Mail/Signalement/SignalementListExportMailer.php, templates/emails/signalement_list_export.html.twig, tests/Functional/Messenger/MessageHandler/ListExportMessageHandlerTest.php
#3111    
Contrainte de poids des fichiers pour les pièces jointes : Remplacer la pièce jointe par un lien de téléchargement.
* Ajout d'une migration afin de rendre la colonne signalement optionnel
* Ajout d'un nouveau type de document
* Mise à jour handler
* Mise à jour template
```
make worker-stop
```
=> [BO - Export] Remplacer la pièce jointe de l'export par un lien téléchargeable en corps de mail

assets/scripts/vue/components/signalement-form/components/SignalementFormOverview.vue
#3118   
Sur l'écran des désordres, les boutons d'édition des différentes parties étaient bloqués à droite et le texte se mettait sur plusieurs lignes et était illisible.
* Modification des colonnes sur écran de petite taille
=> [FO - Formulaire] Amélioration de l'affichage responsive sur l'écran de récapitulatif

assets/scripts/vue/components/signalement-form/components/SignalementFormOverview.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormUpload.vue
#3119    
[Critère 11.9](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-9) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), l'intitulé de chaque [bouton](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#bouton-formulaire) est-il pertinent (hors cas particuliers) ?
* Ajout de aria-label sur les boutons aux intitulés peu clairs
=> [FO - Formulaire - Accessibilité - 11.9] Intitulés des boutons

assets/scripts/vue/components/signalement-form/components/SignalementFormCounter.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormDate.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormDisorderCategoryItem.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormEmailfield.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormPhonefield.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormRoomList.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormScreen.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormTextarea.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormTextfield.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormTime.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormUpload.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormYear.vue
#3091    
Mise à jour des classes css pour coller au dsfr lors d'erreur
Mise du focus sur le premier élément en erreur lors de la validation de l'écran
* Mise à jour des css sur tous les composants pouvant être en erreur
* Algo "vanilla" pour sélectionner le premier élément en erreur et mettre le focus dessus (en "VueJS" avec les `ref` c'était une usine à gaz)
=> [FO - Formulaire - Accessibilité - 12.8] Dans chaque page web, le focus est-il mis sur le premier élément en erreur lors de la validation ?

assets/scripts/vue/components/signalement-form/components/SignalementFormUpload.vue
#3145   
Sur le formulaire de dépôt de signalement, la suppression de fichier uploadé ne fonctionnait que si on venait de mettre le fichier. Elle ne fonctionnait pas en reprise de brouillon, ou au retour sur l'écran après navigation. Cela venait du fait que la suppression s'effectuait sur le tableau local des fichiers (uploadedFiles) et que ce tableau n'était pas initialisé au moment de l'affichage de l'écran.
* Initialisation de uploadedFiles avec les données du formStore au moment de la création du composant
=> [FO - formulaire] Correction d'un bug sur la suppression doc sur formulaire dépot de signalement

src/Controller/Back/WidgetController.php, src/Repository/NotificationRepository.php, src/Repository/SuiviRepository.php, tests/Functional/Repository/SuiviRepositoryTest.php
#3135
- Réduction du temps de chargement du widget KPI via l'optimisation de plusieurs requête
Différence d'exécution des requetes avant/aprés en SA (aucune requete sup a 3 secondes)
- Différence d'exécution des requetes avant/aprés en RT Marseille (aucune requête sup a 1 seconde)
* Passage de requete `LIKE '%term%'` en `LIKE 'term%'`
* Simplification et conditionnalité d'ajout de clause sur la requête la plus lente (qui remonte sur sentry)
=> [QA - Performance] Optimisation requête widget KPI

config/services.yaml
#3161   
Erreur d'envoi de call http sur l'envoi de mail
* Suppression de la décoration 
* Déclarer les services utilisant le service http custom de manière explicite
(Ex : http://localhost:8080/bo/signalements/00000000-0000-0000-2024-000000000003) OK
=> [TECH] Brevo utilise HttpClient pour les appels api - Ne pas décorer le service

migrations/Version20241009143155.php, src/Entity/JobEvent.php, src/Repository/JobEventRepository.php, src/Service/DashboardWidget/WidgetDataManager.php, src/Service/Interconnection/JobEventHttpClient.php, tests/Functional/Repository/JobEventRepositoryTest.php
#3136    
La requête des événements n'est pas complexe, malgré tout elle dépssait les 2 sec pour environ ~ 10000 enregistrement.
Des index ont été ajouté sur la table job_event il y'a quelques mois mais la requête n'en profite pas vraiment 
* Remplacement des LIKE ` %%` par `=` 
* Remplacement de `DATE_DIFF` par une comparaison classique de date 
|              | Avant Optimisation | Après Optimisation |
|-----------------------|--------------------|--------------------|
| Temps d'exécution     | > 2 s             | < 0.5 s              |
* Travailler avec la base de prod `make load-data`
> [!NOTE]  
> Rappel : Seul le premier appel fait une requête en base, les résultats des requêtes suivantes proviennent du cache
Supprimer le cache`make clear-pool pool="--all"`
=> [QA - Performance] Optimisation requête widget connexion esabora

migrations/Version20241004142515.php, src/DataFixtures/Files/NewSignalement.yml, src/DataFixtures/Files/SignalementDraft.yml, src/EventSubscriber/SignalementDraftCompletedSubscriber.php, src/Manager/SignalementDraftManager.php, tests/Functional/Manager/SignalementDraftManagerTest.php
#3134
- Ajout d'une contrainte unique sur le champ `created_from_id` de la table `signalement` afin d'éviter qu'un draft puisse créer des doublon de signalement (ce qui arrive à la marge quand le même draft est soumis a quelque secondes d'intervalle)
- Gestion de l'erreur lorsque le cas se produit afin de retourner le signalement existant
* Ajout d'une migration gardant uniquement un signalement par draft (mise a null des doublon en fonction de leur statut) + ajout de la contrainte unique
`make execute-migration name=Version20241004142515 direction=up`
Voila ce que j'ai fait pour tester le comportement (mais vous aurez peut être d'autre idée) :
- Remplacer dans `SignalementDraftManager` la ligne `if (SignalementDraftStatus::EN_SIGNALEMENT === $signalementDraft->getStatus()) {` par `if …
=> [Signalement BO] Gérer les doublons côté backend

templates/front/_partials/_suivi_signalement_tab_infos.html.twig
#3120    
Pour répondre au critère 11.12, il faut que l'usager puisse avoir accès également aux documents qu'il a envoyé dans le formulaire.
*Ajout des documents uploadés par l'usager sur la fiche usager
=> [FO - Fiche suivi usager - Accessibilité - 11.12] Ajout des documents uploadés par l'usager dans la fiche usager

src/DataFixtures/Files/Partner.yml, src/Entity/Partner.php, src/Factory/Interconnection/Oilhi/DossierMessageFactory.php, src/Messenger/InterconnectionBus.php, tests/Functional/Factory/Oilhi/DossierMessageFactoryTest.php, tests/Unit/Entity/PartnerTest.php
#3160   
A la base ça devait être déployé dans tous le 62 mais ajout prise en charge code insee 
* Mise à jour méthode `canSyncWithOilhi` pour prise en compte de code insee
make worker-stop & make worker-start
=> [OILHI] Activation connexion commune Beaudricourt

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, templates/_partials/signalement/add_suivi.html.twig
#3158    
Suite au constat que certains suivis restent en "suivi interne" alors qu'ils sont de toute évidence destinés à l'usager, il a été décidé de modifier l'intitulé du bouton "enregistrer" sur la modale d'ajout de suivi.
Si l'interrupteur "En cochant cette case, le suivi sera envoyé à l'usager"  est activé, le bouton doit s'appeler `Envoyer le suivi à l'usager` 
s'il n'est pas activé, alors le bouton doit s'appeler `Enregistrer le suivi interne` 
* Ajout d'un événement js
=> [BO - Fiche signalement] Modifier l'intitulé du bouton "Enregistrer" sur la modale d'ajout de suivi

README.md, assets/scripts/vue/components/dashboard/TheHistoAppDashboard.vue, assets/scripts/vue/components/signalement-list/TheSignalementAppList.vue, src/Entity/User.php, src/Form/SearchUserType.php, src/Service/Import/GridAffectation/GridAffectationLoader.php, src/Service/SearchUser.php, src/Service/UserExportLoader.php, templates/_partials/_modal_user_create.html.twig, templates/_partials/_modal_user_edit.html.twig, templates/back/partner/view.html.twig, templates/back/user/index.html.twig, tests/Functional/Service/Import/GridAffectation/GridAffectationLoaderTest.php, tests/Unit/Entity/PartnerTest.php, tests/Unit/Factory/UserFactoryTest.php, tests/Unit/Service/DashboardWidget/WidgetSettingsTest.php, tests/Unit/Service/UserAvatarTest.php
#3110    
Pour plus de compréhension de la part des utilisateurs, il faut enommer le rôle "utilisateur" en "agent"
et "Administrateur" en "administrateur partenaire".
Ces nouveaux noms avaient été introduits dans un tableau User::ROLESV2 pour la liste des utilisateurs
`npm run  watch`
=> [BO] Renommer le rôle "utilisateur" en "agent" (et unifier les noms de responsable territoire et admin partenaire)

assets/scripts/vue/components/signalement-form/TheSignalementAppForm.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue
#3112   
Reprise du ticket sur la désactivation des feuilles de style.
Après lectures, ce critère est surtout important pour bien vérifier que la structure et l'ordre de lecture du site est logique.
Il n'est donc pas utile de travailler sur l'ergonomie de cet affichage (taille des images notamment).
Par contre, il est important de mettre des attributs `hidden` quand les éléments sont cachés via css (`fr-hidden`) pour qu'ils ne soient pas interprétés par les lecteurs d'écran.
* Ajout d'attribut `hidden` sur 2 boutons
=> [FO - Signalement] Ajout d'attributs hidden sur certains éléments

Makefile, docker-compose.yml, src/Factory/SignalementExportFactory.php, src/Repository/SignalementRepository.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3133   
Problème signalé de départ : le nombre de visite était retourné sous la forme d'un float, ce qui n'avait pas trop de sens.
Après analyse, on découvre que la fonction MySQL `GROUP_CONCAT` possède une limite de taille.
Quand on fournit les détails d'une visite, on peut facilement dépasser cette limite.
* Augmentation de la limite
* Séparation des différents champs de visite en 4 éléments différents au sein du select
* Modification du séparateur des éléments
=> [BO - Export signalements] Correction limite de taille pour liste de visites

assets/scripts/vanilla/controllers/back_auto_affectation_rule/form_auto_affectation_rule.js, assets/scripts/vanilla/controllers/back_partner_view/form_partner.js, assets/scripts/vanilla/controllers/back_signalement_delete_file/back_signalement_delete_file.js, assets/scripts/vanilla/controllers/back_signalement_edit_file/back_signalement_edit_file.js, assets/scripts/vanilla/controllers/back_signalement_view/form_upload_documents.js, assets/scripts/vanilla/controllers/front_suivi_signalement/front_suivi_signalement.js, package-lock.json, package.json
#3167    
Il y a sur GitHub un nouveau module qui scanne d'éventuelles erreurs : https://github.com/MTES-MCT/histologe/security/code-scanning
* Modification de quelques fichiers javascript pour éviter des failles XSS, principalement en remplaçant `innerHTML` par `textContent` ou en utilisant `DOMPurify`
`Extracting text from a DOM node and interpreting it as HTML can lead to a cross-site scripting vulnerability.`
```
npm install
npm run watch
```
Dans tous les tests suivants, il faut vérifier que les textes remplacés en js dans les modales sont cohérents
=> [Sécurité] Correction des feedback codeQL

assets/styles/histologe.scss, templates/back/base_bo.html.twig, templates/base.html.twig, templates/bundles/SchebTwoFactorBundle/Authentication/form.html.twig, templates/bundles/TwigBundle/Exception/error.html.twig, templates/bundles/TwigBundle/Exception/error403.html.twig, templates/bundles/TwigBundle/Exception/error404.html.twig, templates/front/about.html.twig, templates/front/accessibilite.html.twig, templates/front/aides_travaux.html.twig, templates/front/cgu_agents.html.twig, templates/front/cgu_usagers.html.twig, templates/front/contact.html.twig, templates/front/index.html.twig, templates/front/mentions_legales.html.twig, templates/front/nouveau_formulaire.html.twig, templates/front/obligations_entretien.html.twig, templates/front/plan_du_site.html.twig, templates/front/politique_de_confidentialite.html.twig, templates/front/statistiques.html.twig, templates/front/suivi_signalement.html.twig, templates/security/login.html.twig, templates/security/login_activation.html.twig, templates/security/login_link_sent.html.twig, templates/security/reset_password.html.twig, templates/security/reset_password_new.html.twig, templates/skiplink.html.twig
#3184   
Ajout du lien d'évitement du DSFR.
Suite à l'audit accessibilité punaises, nous avions du enlever les liens d'évitement vers le menu et le menu secondaire.
Du coup je n'ai mis que des liens d'évitement vers le contenu et le footer.
* twig
=> [FO - Formulaire - Accessibilité - 12.7] Lien d'évitement

src/Controller/Back/IdossController.php
#3189    
Des optimisations sont à prévoir et observer si c'est utile
* Ajout d'un attribut pour rendre les routes innaccessible en prod
```
make cc env=prod
composer dump-env prod
```
=> [BO] Désactiver la page de debug idoss

assets/scripts/vue/components/signalement-form/components/SignalementFormCheckbox.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormComponentGenerator.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormScreen.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormSubscreen.vue, assets/scripts/vue/components/signalement-form/interfaces/interfaceComponent.ts, assets/scripts/vue/components/signalement-form/store.ts, src/DataFixtures/Files/signalement_draft_payload/locataire_all_in.json
#3115    
[Critère 11.5](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-5) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), les [champs de même nature](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champs-de-meme-nature) sont-ils regroupés, si nécessaire ?
Regrouper les différents inputs des désordres et de l'utilisation du service en 1 fieldset
* Création d'un composant qui gère la boucle de création de composant à la volée
* Utilisation de ce composant dans le SignalementFormScreen pour le body et le footer (malheureusement pas dans le SignalementFormSubscreen, cf commentaire)
* Inclusion de cette boucle de composant dans un fieldset si besoin
=> [FO - Formulaire - Accessibilité - 11.5 à 11.8] Champs de même nature

templates/_partials/_modal_cloture.html.twig, templates/back/signalement/view/header.html.twig
#3194    
Un RT qui est affecté à un ticket pouvait seulement "cloturer pour tous" et pas "cloturer son affectation".
On a remis le bouton "cloturer pour partenaire" dans la modale s'il est affecté au signalement, et remis le bouton "cloturer" dans la fiche si seule son affectation est fermée, mais pas le signalement.
* Modification de bouton sur la modale
* Modification de bouton dans le header du signalement
Faire un utilisateur avec un rôle agent dans le `partenaire 13-01`
Si vous pensez à d'autres tests...
=> [BO - Signalement] Droits de clôture pour RT

Makefile, src/Service/Interconnection/JobEventHttpClient.php
#3224    
Renvoyer la réponse HttpClient même en cas d'erreur 
* Suppression de MockResponse
_Couper le service de mock pour simuler des erreurs http_
```
make mock-stop
```
```
make worker-stop && make worker-start
```
=> [QA] Revoir type de retour en cas d'erreur de web-service

templates/back/signalement/view/photos-documents.html.twig
#3228 
Inversion de l'ordre d'affichage des documents de l'onglet document de la fiche signalement
=> [BO - Fiche signalement] Onglet Documents - Ordre Descendant

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, assets/styles/histologe.scss, templates/back/signalement/view/partners.html.twig
#3229
- Inversion de l'ordre des boutons "Affecter des partenaires" "Voir l'historique des affectations"
- Ajout de taille sur les colonne du tableau historique afin qu'il soit toujours alligné
=> [BO - Signalement] Affichage historique d'affectation

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, assets/styles/histologe.scss, src/Form/TerritoryType.php, src/Manager/HistoryEntryManager.php, src/Repository/PartnerRepository.php, tests/Functional/Controller/Back/BackUserControllerTest.php, tests/Functional/Controller/Back/HistoryEntryControllerTest.php, tests/Functional/Manager/HistoryEntryManagerTest.php
#3230   
- Pour éviter d'avoir un affichage contenant des tableaux vide et Un tableau "N/A" on les ignore (les ligne "N/A" sont conservé via le libellé "Système (automatique)" dans les autres partenaires. On supprime aussi la colonne "Id" qui a peu d’intérêt
- Correction d'un warning suite à la feature zonage sur les signalement n'ayant pas de latitude/longitude enregistré en base
- Correction d'un crash sur l'édition des territoire du fait que en prod les territoire on null dans le champ json `authorizedCodesInsee` contient `null` et non pas `[]`
Se mettre sur une copie de base de prod sur le signalement http://localhost:8080/bo/signalements/b8468aea-bae1-468b-887b-6ac15bf0d6e7
=> [BO - Signalement - Historique affectation] Affichage de partenaire N/A

cron.json, src/Controller/Back/HistoryEntryController.php, templates/back/signalement/view.html.twig, templates/back/signalement/view/partners.html.twig, tests/Functional/Controller/Back/BackUserControllerTest.php, tests/Functional/Controller/Back/HistoryEntryControllerTest.php
#3236
#3238
- Autorisation d'accès à la modale d'historique des affectations pour tous les utilisateurs ayant les droits d'affectations pour le signalement (en lien avec la nouvelle feature `FEATURE_PERMISSION_AFFECTATION`)
- Modification de fréquence du cron de suppression des images originale. Maintenant que le gros a été traité une fois tous les 5 jours semble ok selon les dernières métriques
=> [BO - Signalement - Historique affectation] Afficher le bouton pour tous les users avec les droits d'affectation

assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/scripts/vue/components/signalement-form/components/SignalementFormConfirmation.vue, templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig, templates/back/signalement/view/information/information-situation-foyer.html.twig
#3237    
Mise a jour question selon si l'occupant habite dans un parc public ou privée
* Mise à jour du json avec une condition
* Mise à jour du libéllé dans le BO
```
make npm-watch
```
=> [FO - Signalement] Modifier question Parc Public

assets/scripts/vanilla/controllers/back_partner_view/form_partner.js, templates/_partials/_modal_user_create.html.twig, templates/_partials/_modal_user_edit.html.twig
#3235   
Quelques améliorations apportées aux fenêtres pour créer et éditer les utilisateurs 
- Passage des notifs mails en pleine largeur
- Ajout d'une légende pour les droits d'affectation
- Ajout du toggle grisé et d'une info pour les utilisateurs Admin
J'en ai profité pour revoir quelques classes d'affichage des champs dans ces modale, pour correspondre aux classes dsfr actuelles, et aux marges correctes.
=> [BO - Utilisateurs] Amélioration modale de création / édition d'utilisateur

src/Service/UserExportLoader.php, templates/back/partner/index.html.twig, templates/back/partner/view.html.twig, templates/back/user/index.html.twig
#3251   
Pas mal de partenaires n'ont pas de type défini (à l'heure actuelle, environ 700 sur 6000).
Lors de l'export de la liste des utilisateurs, si le type de partenaire n'est pas défini, il y avait un plantage.
=> [QA] Correction appel méthode label() quand le partenaire n'a pas de type

assets/scripts/vue/components/signalement-form/components/SignalementFormPhonefield.vue
#3191    
Sur le formulaire, quand on affichait et remplissait un numéro de téléphone secondaire au format invalide (par exemple "banane"), le champ secondaire disparaissait, et on ne pouvait pas corriger le numéro, et donc pas passer à la page suivante (sans comprendre pourquoi car l'erreur était cachée aussi)
* On affiche le champ de téléphone secondaire dès qu'il est en erreur pour voir le feedback et pouvoir le corriger
=> [FO - Formulaire] Correction du blocage quand on renseigne des numéros de téléphones invalide pour le principal et le secondaire

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/dictionary.json, assets/scripts/vue/components/signalement-form/components/SignalementFormAddress.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormTextarea.vue, assets/scripts/vue/components/signalement-form/matomo.ts, assets/scripts/vue/components/signalement-form/services/disorderScreenNavigator.ts, assets/scripts/vue/components/signalement-form/services/variableTester.ts
#3219 
#3233
#3223
Le champ `Précisions sur les désordres` est déplacé dans un écran dédié avant l'écran de récap sur tous les désordres et devient obligatoire
Correction de 2 problèmes de dictionnaire dans le désordre "logement -électricité", et "logement - chauffage"
Correction d'un problème de validation sur le composant SignalementFormAddress
* Ajout d'un nouvel écran dans les 2 json de désordres
* Retrait du `SignalementFormTextarea` dans le composant `SignalementFormDisorderOverview` (car maintenant dans un écran séparé)
* Correction de la css custom dans le composant  `SignalementFormTextarea`
* Modification de `disorderScreenNavigator.ts` pour prendre en compte le nouvel écran
* Correction d'un label dans le json de désordres tiers (il manquait `dictionaryStore::` )
* Correction …
=> [FO] Ajout d'un écran pour le champ précisions sur les désordres et fix

src/Command/Clock/ScheduledTaskCommand.php
#3147    
* Option pour désactiver un cron applicatif 
```
ESABORA_CRON_SCHEDULE_SYNC_SCHS='*/1 * * * *'
ESABORA_CRON_SCHEDULE_SYNC_SISH=false
ESABORA_CRON_SCHEDULE_SYNC_SISH_INTERVENTION=false
```
=> [QA] Problème de synchro SCHS (Option pour désactiver un cron)

assets/scripts/vanilla/controllers/front_demande_lien_signalement/front_demande_lien_signalement.js, assets/scripts/vanilla/services/component_search_address.js, templates/back/signalement/view/edit-modals/edit-address.html.twig
#3256   
Application du même fonctionnement de navigation au clavier que pour le composant Vue dans le composant Vanilla
=> [FO/BO - Adresse] Application de la navigation clavier sur le composant d'adresse

src/Entity/Partner.php, tests/Unit/Entity/PartnerTest.php
#3271   
Activation de la synchronisation 
* Ajout des codes insee
* Stenay : 55502
* Bar-le-duc : 55029
* Verdun : 55545
=> [BO - OILHI] Liste Communes à activer

templates/front/_partials/_suivi_signalement_tab_infos.html.twig
#3273   
En complément du https://github.com/MTES-MCT/histologe/issues/3223 , il faudrait afficher dans la page de suivi usager le contenu du champ Précisions sur votre situation, à la suite des désordres
Si pas de précisions on met `Aucun commentaire`
* Changement du twig
=> [FO - page de suivi usager] Afficher les infos saisies dans le champ "précisions"

templates/back/nav_bo.html.twig
#3283    
Comme sur le menu actuel ajouter le nombre de notif après le libellé du menu notification
* Ajout du nombre entre parenthèse
```
FEATURE_ENABLE_MENU_HORIZONTALE=1
```
=> [BO - Menu] Ajouter nb de notif non lues dans le menu

src/Service/ImageManipulationHandler.php, src/Service/Interconnection/Idoss/IdossService.php, tests/Unit/Service/ImageInterventionHandlerTest.php
#3279
Les 4 dossiers en erreurs concerne des synchronisation ou l'on tente d'envoyer plus de 20 fichiers en un seul appel. Je n'ai pas retrouvé la trace dans la doc mais de mémoire c'était une limite IDOSS.
* Ajout d'une limite du nombre fichiers par appel idoss (les suivant se feront à la synchro suivante, par lot de 20)
* Retrait du check isImage de la #3285 car déja vérifié et ok
=> [BUG] erreur upload synchro IDOSS (nb files limit)

assets/scripts/vue/components/dashboard/TheHistoDashboardHeader.vue
#3284   
* Augmentation de la marge interne sur l'axe x
* Mise à jour de la média query 
```
make npm-watch
```
=> [BO - dashboard] Mettre la même marge sur le bandeau stats que pour le reste de la page

src/Command/Cron/SynchronizeIdossCommand.php, src/Service/ImageManipulationHandler.php, src/Service/Interconnection/Idoss/IdossService.php, tests/MockableResizeImage.php, tests/MockableThumbnailImage.php, tests/Unit/Service/ImageInterventionHandlerTest.php
#3279    
Voici les deux types d'erreur trouvé en base
* `The value of the form field "id" can only be a string, an array, or an instance of TextPart, "null" given. `
* `{"message":"Erreur lors du transfère de fichiers ! Dossier :","uuid":"xxx","id":"xxx","xxx":"MulterError: Unexpected field"}`
Toutes les payload se ressemblent (succès comme échec) donc difficile de voir d'ou vient le problème cependant j'ai remarqué qu'on essaie de récupérer un fichier de resize pour les documents (pdf)
Surement cette erreur, `The value of the form field "id" can only be a string, an array, or an instance of TextPart, "null" given. `
fichier xxx_resize.pdf n’existe pas et au moment de construire le data_part le fichier est null
Il faudrait avoir la vrai structure de la payload loggé dans la table pour …
=> [BUG] erreur upload synchro IDOSS

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json
#2608    
Sur l'écran où on sélectionne la zone concernée par les désordres, on modifie le contenu de la modale pour mettre les détails du logement avec de bullets points.
Sur l'écran d'introduction de sélection de désordres, on supprime la modale, et met directement le contenu sur l'écran
=> [FO - Signalement] Ajustement des modales de description des zones de désordres

assets/scripts/vanilla/controllers/form_visite.js, assets/scripts/vanilla/services/component_search_checkbox.js, assets/styles/histologe.scss, src/Entity/Enum/Qualification.php, src/Form/PartnerType.php, src/Form/Type/SearchCheckboxEnumType.php, templates/back/partner/_form.html.twig, templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig, templates/form/dsfr_theme.html.twig
#3105   
Remplacement du composant de sélection multiple
* Ajout d'un nouveau custom type de formulaire pour gérer les Enum dans un composant proche de celui déjà créé
=> [BO] Remplacement composant de sélection multiple

src/Twig/AppExtension.php, templates/back/signalement/view/information/information-bailleur.html.twig, templates/back/signalement/view/information/information-foyer.html.twig, templates/back/signalement/view/information/information-tiers.html.twig, templates/front/_partials/_suivi_signalement_tab_infos.html.twig, tests/Unit/Twig/AppExtensionTest.php
#3317   
Pour faciliter la lecture, on ajoute des espaces dans les numéros de téléphone de la fiche signalement et la fiche de suivi usager
=> [BO - Fiche signalement] Affichage des numéros de téléphone avec des espaces

src/Manager/SignalementManager.php, templates/pdf/signalement.html.twig
#3312   
Dans la fiche signalement du BO, l'enregistrement de données pour le préavis de départ était mal fait (prenait une autre valeur en compte)
`make worker-stop && make worker-start`
=> [BO - Fiche signalement] Correction de l'enregistrement de la valeur du préavis de départ

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/scripts/vue/components/signalement-form/components/SignalementFormComponentGenerator.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormDate.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormOverview.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormSelect.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormSubscreen.vue, assets/scripts/vue/components/signalement-form/interfaces/interfaceComponent.ts, assets/scripts/vue/components/signalement-form/store.ts, src/DataFixtures/Files/signalement_draft_payload/bailleur_occupant.json, src/DataFixtures/Files/signalement_draft_payload/locataire.json, src/DataFixtures/Files/signalement_draft_payload/step/validation_signalement/bailleur.json, src/DataFixtures/Files/signalement_draft_payload/step/validation_signalement/bailleur_occupant.json, src/DataFixtures/Files/signalement_draft_payload/step/validation_signalement/locataire.json, src/Dto/Request/Signalement/InformationsLogementRequest.php, src/Dto/Request/Signalement/SignalementDraftRequest.php, src/Entity/Model/TypeCompositionLogement.php, src/Factory/Signalement/TypeCompositionLogementFactory.php, src/Manager/SignalementManager.php, templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig, templates/back/signalement/view/information/information-logement.html.twig, templates/pdf/signalement.html.twig, tests/FixturesHelper.php, tests/Functional/Controller/Back/SignalementEditControllerTest.php, tests/Unit/Dto/Request/Signalement/InformationsLogementRequestTest.php, tests/Unit/Dto/Request/Signalement/SignalementDraftRequestTest.php
#3295   
Dans le FO, dans l'écran bail-dpe, on pourrait ajouter un champ obligatoire Quelle est la classe énergétique de votre logement ? avec un dropdown avec les lettres de A à G + une option "je ne sais pas"
:warning: on n'a pas ajouté la classe énergétique dans la fiche de suivi signalement, car il manque beaucoup de données, et un ticket spécial va être créé pour ça
* Ajout d'un composant `SignalementFormSelect` dans le formulaire
* Ajout de la question dans les 6 profils
* Retrait de la propriété `hint` dans le formulaire qui n'était utilisée que dans le composant `SignalementFormDate` et remplacement par la propriété `description`
* Ajout de la classe énergétique dans les fixtures
* Ajout de la classe énergétique dans le BO et dans l'export pdf
```
make …
```
=> [FO - Form] Ajouter un champ "classe énergétique"

assets/styles/histologe.scss, templates/back/base_bo.html.twig
#3331 
#3332
- Pleine largeur pour le fond gris sur les signalements refusés et clôturés
- Ajout de marge en bas dans le BO
=> [BO - Signalement] Pleine largeur pour le fond gris sur les signalements refusés et clôturés

docker-compose.yml, src/Controller/Back/ExportSignalementController.php, src/Controller/Back/SignalementListController.php
#3314    
Un effet de bord que je n'arrive pas à expliquer, quand on passe sur la liste des étiquettes pour faire un export, on se retrouve avec la session précédente. (Faut vraiment rafraîchir plusieurs fois la liste pour pour avoir la session à jour) 
Pour rappel, la session est mise à jour via la requête ajax
* Stocker la session des filtre coté front via un cookie 
* Vérifier lors de l'export le cookie dans un premier temps puis la session
=> [BO - Export] Effet de bord session sur les filtres

src/Controller/Back/HistoryEntryController.php, src/Controller/Back/SignalementController.php, src/Security/Voter/AssignmentVoter.php, templates/back/signalement/view.html.twig, templates/back/signalement/view/partners.html.twig
#3337    
la liste des partenaires affectes/affectations/ historique des affectations n est pas/plus accessible sur les signalements fermés
* Création d'un nouveau droit `ASSIGN_SEE` qui permet de voir les partenaires affectés et l'historique des affectation
* Renommage de `canPartnerAffectation` en `canSeePartnerAffectation` pour éclaircir ce que ça fait
=> [BO - Signalement] Régression sur l'affichage des partenaires affectés sur les signalements fermés

src/Command/FixScoreQualificationsCommand.php, src/Repository/SignalementRepository.php
#3328   
Il y a eu un bug entre la mise en prod du formulaire (14 février, 2.0.0) et la correcction ci-dessus  (8 mars, 2.0.3) : 
> Après analyse, pour le problème des désordres liés à la composition du logement, on affectait les désordres au signalement si la réponse à certaines questions était différente de "oui".
> Par exemple "la hauteur sous le plafond du logement est supérieur à 2 mètres". Si on ne répond pas oui, on a le désordre. Donc les Tiers déclarant qui ont répondu "je ne sais pas" ont un siignalement avec ce désordre.
La correction faite le 8 mars a permis de corriger ce pb, et a corrigé les signalements créés entre le 14 février et le 8 mars en enlevant ces désordres superflus, **mais sans recalculer les qualifications ni le score**.
* commande temporaire pour recalculer le …
=> [BO - signalements] Commande pour corriger les scores et qualifications des signalements créés entre le 14 février et le 8 mars

src/Controller/Back/SignalementFileController.php
#3348   
Dans la fiche signalement, si on upload un fichier et qu'on quitte la page plutôt que de fermer la fenêtre de modale, le fichier reste enregistré dans la BDD avec is_waiting_suivi=1
Quand le même auteur se connecte plus d'une heure plus tard et réupload un fichier en fermant la modale, alors le premier fichier est supprimé. Le deuxième n'est plus en waiting_suivi et un suivi est créé.
Mais si c'est un autre utilisateur qui se connecte et uploade un fichier plus d'une heure plus tard, alors ce tout premier fichier n'est pas supprimé, mais son waintig_suivi est passé à false, ce qui le rend visible dans la fiche signalement alors qu'aucun suivi n'a été ccréé.
* Modification de la route `back_signalement_file_waiting_suivi`
=> [BO - Signalement] Fichier en waiting_suivi ne devrait pas apparaitre

src/EventListener/Behaviour/DoctrineListenerRemoverTrait.php, src/Manager/HistoryEntryManager.php, tests/Unit/EventListener/Behaviour/DoctrineListenerRemoverTraitTest.php
#3346    
https://mattermost.incubateur.net/betagouv/pl/id3yw41jwjnd5rphe9w59gk8ce
Pour éviter les limitations liées au traitement de gros volumes de données, notamment en mode batch, ajout d’un trait permettant de désactiver les listeners et événements au choix.
* Ajout d'un trait 
```php
class Epci implements EntityHistoryInterface
{
/* .... */
public function getHistoryRegisteredEvent(): array
{
return [HistoryEntryEvent::CREATE];
}
}
```
=> [TECH] Option pour désactiver EntityHistoryListener

assets/scripts/vue/components/signalement-list/components/SignalementListCards.vue
#3350   
Quand le prénom de l'occupant est `null`, mais pas le nom de famille, la liste de signalements affiche "null" à la place du prénom
=> [BO - Liste signalement] Correction quand le prénom de l'occupant est null, mais pas le nom

src/Entity/Enum/MotifCloture.php
#3354   
Dans les motifs de clôtures de signalement, ajout du motif "Doublon"
=> [BO - Signalement] Ajout de motif DOUBLON pour les clôtures de signalement

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, config/packages/doctrine.yaml, src/Controller/Back/SignalementActionController.php, src/Repository/SuiviRepository.php
#3338  
L'option doctrine `use_savepoints` à true (transactions imbriquées) était obligatoire pour la montée de version vers Symfony 7 en raison de la mise à jour du bundle dama/doctrine-test-bundle en version 8.2.*.
Ce bundle est utilisé uniquement en environnement de test et peut donc être désactivé en prod.
L'erreur de "savepoint" signalée sur Sentry n'est pas liée à la création multiple d'un même suivi, mais plutôt à une utilisation répétée du bouton de soumission. Ça date de plusieurs année, la désactivation à la soumission de création de suivi n'a jamais été implémenté. 
Voir ce signalement de 2023 par exemple : 
https://histologe.beta.gouv.fr/bo/signalements/e3dab9ba-43c6-4e37-a0e5-4f5f046b44e1
La liste ici 
https://histologe-metabase.osc-fr1.scalingo.io/question/1351-doublon-de-sui …
=> [QA - Sentry] Suivi créés plusieurs fois, erreur d'execution de requête

templates/back/base_bo.html.twig
#3332   
Erreur dans la PR ici : https://github.com/MTES-MCT/histologe/pull/3333
La marge du bas avant footer n'a pas été mise en ligne au moment de la PR.
Erreur de ma part, probablement, qui n'a pas été aperçue.
=> [BO] Marge du bas avant footer

templates/back/header_main_menu.html.twig
#3368   
Mauvais lien sur le menu horizontal
* Remplacement du lien
=> [BO - Menu horizontal] Mauvais lien de documentation (Remplacement documentation par faq)

src/Form/PartnerPerimetreType.php, src/Form/TerritoryType.php, src/Form/ZoneType.php
#3362 #3363 #3364
- Sur l'édition du périmètre d'un partenaire les erreur de code insee s'affiche conformément au style du DSFR
- Sur le formulaire d'ajout/édition d'une zone les champs "Partenaires" et "Partenaires exclus" sont indiqués comme facultatif
- Sur les formulaires d'édition du périmètre, d'édition d'une zone et d'édition d'un territoire le bouton "Modifier" est renommer "Valider"
=> [BO - Partenaire / périmètre] Mettre les erreurs sous les champs

composer.json, composer.lock, src/Form/AutoAffectationRuleType.php, src/Specification/Affectation/CodeInseeSpecification.php, tests/Functional/Specification/Affectation/CodeInseeSpecificationTest.php
#3286   
Actuellement nous avons :
```
Code insee à inclure
Valeurs possibles : "all", "partner_list" ou une liste de codes insee séparés par des virgules.
Codes insee à exclure (facultatif)
Une liste de codes insee séparés par des virgules.
```
Il faudrait les renommer car quand on choisit "partner_list" cela doit prendre en comptes à la fois les codes insee du partenaire et les zones (geoloc)
* Ajout de la librairie `mjaschen/phpgeo` pour vérifier si un point se trouve dans un polygon
* Ajout de la librairie `longitude-one/wkt-parser` pour transformer un text wkt an tableaux lisibles
* Modification du formType pour renommer le paramètre `Code insee à inclure` en `Périmètre géographique à inclure`
* Adaptation de la spécification `CodeInseeSpecification` pour prendre en compte les zones …
=>  [BO - Auto-affectation] Transformer les règles "code insee" en règle "périmètre géographique"

assets/scripts/vue/components/signalement-list/store.ts, src/Dto/Request/Signalement/SignalementSearchQuery.php
#3316   
Il serait utile d'ajouter le tag "Assurantiel" dans le filtre Procédure suspectée de la liste des signalements
* Ajout d'assurantiel dans la liste du filtre procédure
=> [BO - Liste des signalements] Ajouter "assurantiel" dans le filtre procédure

src/Repository/SuiviRepository.php, src/Service/Signalement/SearchFilter.php
#3380
Dans le traitement des filtres de signalements les clés "delays_partner" et "delays_territory" (traités hors du `SearchFilter`) était les seules qui recevait des instances d'objets. Cela provoquait des erreurs sur la page d'export car ces objet était transformés en tableau vide lors de la conversion des filtre en json pour les stocker dans le cookie.
- Les clés "delays_partner" et "delays_territory" recoivent à présent l'id des objets
- Les fonctions utilisé par ces filtres sont adaptés en conséquence, c'est même plus logique étant donnée qu'elles n'utilisaient que l'id pour construire les requêtes
=> [QA - Sentry] Tableau envoyé au lieu de territoire

src/Service/Menu/MenuBuilder.php
#3402
Petit hack pour éviter de lancer la grosse requête sur tous les signalements quand un SA clique sur le menu `Signalements ->Liste`
Test temps de réponse sans le filtre ou avec sur la prod : 9300 -> 300 ms
=> [BO - optimisation] mettre un filtre par defaut sur liste de signalement SA

migrations/Version20241206084748.php, src/Entity/Signalement.php, src/Entity/Suivi.php
#3399
1
https://sentry.incubateur.net/organizations/betagouv/issues/127893/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1
https://sentry.incubateur.net/organizations/betagouv/issues/133207/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=4
Ajout d'un index composé sur Suivi afin accélérer cette requête (chargement du tableau de bord) 
Durée de la requête avant/après lors de mes essaies : 
pour SA : 2500 -> 570 ms
pour RT 13 : 730 -> 480ms
pour Agent marseille : 3800 -> 540ms
2
https://sentry.incubateur.net/organizations/betagouv/issues/137000/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1
Affichage de la page signalement FO …
=> [QA] optimisation requetes

assets/scripts/vue/components/common/external/chartjs/HistoChartDoughnut.vue, src/Service/Statistics/MotifClotureStatisticProvider.php, tests/Functional/Service/Statistics/MotifClotureStatisticProviderTest.php
#3412   
Correction d'initialisation du graphique avec les motifs de refus depuis l'ajout de DOUBLON
* J'ai aussi augmenté la hauteur des graphiques de type doughnuts pour pouvoir afficher la légende de ce graphique (qui est un peu grosse quand même...)
=> [BO - Statistiques] Correction d'initialisation du graphique avec les motifs de refus depuis l'ajout de DOUBLON

src/Entity/User.php
#3416
Suite au modification multi-territoire, le voter `SIGN_DELETE` n'avait pas une comparaison assez fine face au cas particulier de son utilisation dans `SignalementAffectationListViewFactory`
* Correction via une comparaison sur l'id des objets plutôt que sur les objets
=> [BO - Liste signalements] Je n'ai plus le bouton "supprimer" en tant que RT

templates/_partials/back/table.html.twig, templates/back/account/index.html.twig, templates/back/auto-affectation-rule/index.html.twig, templates/back/expired-account/index.html.twig, templates/back/idoss/log.html.twig, templates/back/inactive-account/index.html.twig, templates/back/notifications/index.html.twig, templates/back/partner/index.html.twig, templates/back/partner/view.html.twig, templates/back/partner_archived/index.html.twig, templates/back/signalement_archived/index.html.twig, templates/back/signalement_export/index.html.twig, templates/back/tags/index.html.twig, templates/back/territory/index.html.twig, templates/back/user/index.html.twig, templates/back/zone/index.html.twig, tests/Functional/Controller/BackArchivedAccountControllerTest.php
#3377   
Création d'un fichier twig à inclure en BO lorsqu'on crée un tableau.
Premier pas vers une standardisation.
* J'en ai profité pour retoucher quelques titres / descriptions de tableaux... C'était secondaire mais bon...
=> [BO - Tableaux] Template Twig pour les tableaux du BO

config/packages/messenger.yaml, migrations/Version20241209082922.php, src/Command/InitIdBanCommand.php, src/Entity/Signalement.php, src/EventSubscriber/SignalementDraftCompletedSubscriber.php, src/Manager/SignalementManager.php, src/Messenger/Message/SignalementUpdateFromAddressMessage.php, src/Messenger/MessageHandler/SignalementUpdateFromAddressMessageHandler.php, src/Service/BetaGouv/Response/RnbBuilding.php, src/Service/BetaGouv/RnbService.php, src/Service/Signalement/SignalementAddressUpdater.php, src/Service/Signalement/SignalementBuilder.php, tests/Functional/Manager/SignalementManagerTest.php, tests/Functional/Service/Signalement/PhotoHelperTest.php, tests/Functional/Service/Signalement/SignalementBuilderTest.php, tests/Unit/Service/BetaGouv/RnbServiceTest.php, tests/files/betagouv/get_api_rnb_buildings_response.json
#3359
Enregistrement du `rnb_id` lors de la soumission / édition d'un signalement sous les conditions suivantes : 
- L'adresse correspond a une adresse BAN avec un score > 0.9
- La clé de l'adresse correspond a un seul bâtiment coté RNB
* Ajout d'un champ `rnb_id_occupant` sur la table signalement
* A la soumission d'un signalement traitement des appels API sur l'adresse en asynchrone via le worker à travers `dispatchUpdateFromAddress`
* Traitement des appels API de l'adresse mis dans un service à part `SignalementAddressUpdater`
`make execute-migration name=Version20241209082922 direction=up`
`make worker-stop`
Déposer un signalement sur une adresse connue de la BAN (le worker doit être activé)
=> [API RNB] Integrer le BatID quand l'adresse retourne un seul résultat

src/Form/SearchUserType.php
#3417
Correction du champ "Type de partenaire" sur la page liste des utilisateurs qui était par défaut obligatoire alors qu'il ne le devait pas.
=> [BO - Utilisateurs] La recherche par nom / email ne fonctionne pas

src/Controller/Back/SuiviSummariesController.php, src/Messenger/Message/SuiviSummariesMessage.php, src/Messenger/MessageHandler/SuiviSummariesMessageHandler.php
#3423    
https://sentry.incubateur.net/organizations/betagouv/issues/137846
> The export of suivi summaries failed for the following reason : The identifier id is missing for a query of App\Entity\User
Le dernier suivi de type usager peut ne pas avoir d'utilisateur dans la table user, ce qui fait planter la demande de résumé pour le type `Relancés automatiquement, dernier suivi de type usager`
* Ajout d'un contrôle pour éviter d'aller faire une requête sur la table user s'il n'existe pas
* Travailler avec type primitifs au lieu d'objet d'entités (peut avoir des effets de bord sur la serialization/désérialisation du messsage) 
```
make load-data
make worker-stop && make worker-consume
```
=> [BO - Albert] Non réception de l'email selon le type de signalement choisi

src/Service/Interconnection/Esabora/EsaboraManager.php, src/Service/Interconnection/Esabora/Response/Model/DossierEventSCHS.php, tools/wiremock/src/Resources/Esabora/schs/ws_get_dossier_events.json
#3408    
Les premiers événements sont arrivés mais avec certaines propriétés null qui empeche l'enregistrement de suivi. il faut donc ajouter plus de contrôle. 
```json
{
"searchId": 27453,
"nbResults": 1,
"columnList": [
"SAS_R\u00e9f\u00e9rence",
"Evt_Date",
"Evt_Pr\u00e9sentation",
"Evt_Documents",
"Evty_Libell\u00e9"
],
"documentTypeList": {
"3": "e6_t1.evt_nomdoc"
},
"keyList": [
"i1.iaff_id",
"e6_t1.evt_id"
],
"rowList": [
{
"columnDataList": [
"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
null,
null,
null,
"Visite Hygi\u00e8ne de l'habitat"
],
"keyDataList": [
4,
925
]
}
]
}
```
* Rendre toutes les propriétés nullable `DossierEventSCHS`
* Ajout d'une réponse dans le mock pour simuler la prod
```
```
=> [QA - Sentry] Impossible d'enregistrer un événement SCHS

src/Repository/SignalementRepository.php
#3429
L'export de signalement de l'oise provoquait un crash, les causes étant : 
- Utilisation massive de `GROUP_CONCAT` dans la requête
- Augmentation `SET SESSION group_concat_max_len=32505856` provenant de #3149 (plus de crash sans l'option)
- Champ problématique : conclusion de visite (contenant du html et potentiellement très long)
Solution rapide : 
-  Augmentation du `memory_limit` sur la requête d'export de signalement
Défaut : 
- Ne règle pas le problème de concaténation : le champs conclusion de visites reste tronqué
Analyse : 
- La requête étant standard, on charge toutes les données même si l'on n'exporte pas les colonnes correspondante
- On fait une concaténation des informations de visite alors que seul leur nombre et les donnés de la dernière visite nous intéresse 
- …
=> [QA - BUG] crash export signalements

src/Factory/SignalementExportFactory.php, src/Repository/SignalementRepository.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3436
Désactivation de la colonne "Comm. de la dernière visite" pour éviter crash mémoire et DB
=> [BUG] crash export

migrations/Version20241213110913.php, src/Controller/Back/BackZoneController.php
#3443
- Ajout d'un contrainte de validation à la soumission du formulaire d'ajout/édition de zone afin de s'assurer que le WKT à un format valide et ne provoquera pas d'exception lors de son utilisation dans les requêtes
- Ajout d'une migration remplaçant les zones mal formaté existants (par un point arbitrairement situé sur la place de la comédie de Montpellier)
=> [BUG] crash affichage page d'une zone quand WKT mal formaté

src/Command/UpdateSishArreteProcedureCommand.php, src/DataFixtures/Files/Affectation.yml, src/DataFixtures/Files/Intervention.yml, src/DataFixtures/Files/NewSignalement.yml, src/Factory/InterventionFactory.php, src/Factory/SignalementAffectationListViewFactory.php, src/Manager/SignalementManager.php, src/Repository/InterventionRepository.php, src/Repository/SignalementRepository.php, src/Service/Interconnection/Esabora/DateParser.php, src/Service/Interconnection/Esabora/EsaboraManager.php, src/Service/Signalement/Qualification/SignalementQualificationUpdater.php, tests/Functional/Controller/Back/SignalementListControllerTest.php, tests/Functional/Controller/BackStatistiquesControllerTest.php, tests/Functional/Controller/StatistiquesControllerTest.php, tests/Functional/Manager/Esabora/EsaboraManagerTest.php, tests/Functional/Repository/AffectationRepositoryTest.php, tests/Unit/Service/Esabora/DateParserTest.php, tests/Unit/Service/Esabora/EsaboraManagerTest.php, tools/wiremock/src/Mock/Esabora/EsaboraSISHMock.php, tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas_termine.json, tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas_termine_insalubrite.json
#3366    
Mise à jour de la qualification aprés avoir enregistré un arrête. 
* Mise à jour du EsaboraManager pour enregistrer la procédure Insalubrité
* Ajouter de la procédure sur les arrêtés passés via une commande
1. 
```
```
2. Ouvrir le signalement 2024-10 et vérifier l'absence de procédure constatée
=> [BO - SISH] MAJ la qualification quand on récupère des arrêtés

src/Manager/SignalementManager.php, src/Service/Signalement/SignalementAddressUpdater.php, templates/back/signalement/view/header.html.twig, tests/Functional/EventSubscriber/SignalementViewedSubscriberTest.php
#3456
Les coordonnées géographique d'un signalement sont désormais uniquement sauvés quand l'adresse est précise (connu dans la BAN avec uns core > 0.9)
=> Enregistrer la géoloc uniquement sur les adresse exacte

src/Command/UpdateSignalementGeolocalisationCommand.php, tests/FixturesHelper.php, tests/Unit/Command/UpdateSignalementGeolocalisationCommandTest.php
#3448    
Ajout d'une option pour recalculer les geoloc depuis une date quelconque
* Mise à jour de la commande
=> [Tech] Mise à jour commande pour recalculer les geolocs des signalements depuis une date

src/Controller/Back/SuiviSummariesController.php, src/Form/SuiviSummariesType.php, src/Messenger/Message/SuiviSummariesMessage.php, src/Messenger/MessageHandler/SuiviSummariesMessageHandler.php
#3457
- Ajout dun paramètre "Role du prompt" (user ou system) pour les appel API Albert
- Ajout d'un paramètre "Température" (valeur de 0 a 2) censé données plus ou moins de liberté d'interprétation à l'IA
Note : Je n'ai vu aucune différence, j'ai l'impression que les paramètres ne sont pas pris en compte (à part peut être sur le modèle `AgentPublic/llama3-instruct-8b`)
=> [API Albert] test en envoyant le prompt en role "system"

src/Service/Signalement/SearchFilter.php
#3470 
Restriction du filtre territoire au SA sur la liste des signalements
=> [BUG - SECU] Liste des signalements RT

src/EventListener/EntityHistoryListener.php
#3455    
Les valeurs JSON avec un contenu identique mais un ordre de clés différent sont actuellement considérées comme différentes dans la logique de comparaison.
Ancienne valeurs
```
{
"arrete_type": "Arrêté L.511-19 - Insalubrité",
"arrete_numero": "2024/DD13/00664",
"arrete_mainlevee_date": "01/08/2024",
"arrete_mainlevee_numero": "2024-DD13-00173"
}
```
Nouvelles valeurs
```
{
"arrete_numero": "2024/DD13/00664",
"arrete_type": "Arrêté L.511-19 - Insalubrité",
"arrete_mainlevee_date": "01/08/2024",
"arrete_mainlevee_numero": "2024-DD13-00173"
}
```
Les valeurs sont identiques mais l'ordre est différent. 
N'ayant pas la main sur ce que UnitOfWork de doctrine renvoie, il serait plus sur de trier les clés de tableau avant de comparer. 
* Ajout d'un tri de tableau
```
make worker-stop && …
```
=> [QA] Comparaison des valeurs JSON indépendamment de l'ordre des clés

src/Service/Signalement/SearchFilterOptionDataProvider.php
#3475    
Régression sur la clé de cache pour les filtres de la liste
* Ajout du user-ud
`make load-data`
=> [BO - Signalements] Filtre Commune "quasi vide"

src/Entity/Intervention.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToPartnerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCanceledMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCanceledToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToUsagerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisitePastReminderToPartnerMailer.php, src/Service/Mailer/Mail/Suivi/SuiviVisiteRescheduledToUsagerMailer.php
#3472   
Correction du décalage horaire envoyé par e-mail aux usagers dans les notifications de visites.
=> [Mails - Visites] Correction du décalage horaire envoyé par e-mail aux usagers

src/Service/Interconnection/JobEventHttpClient.php
#3478    
Il y avait un problème d'interprétation si la réponse était `null` lors d'un appel http.
A la place, on retourne un tableau vide.
=> [Inter-connexions] Correction de retour null

src/Service/Signalement/AutoAssigner.php, src/Specification/Affectation/CodeInseeSpecification.php, tests/Unit/Service/AutoAssignerTest.php
#3468   
En cas de signalement sans géolocalisation, on ne fait pas l'auto-affectation, pour forcer les RT à passer sur ces signalements, et éviter des sauts d'affectation qui seraient utiles.
=> [Auto-Affectation] Ne pas affecter si la géolocalisation n'est pas définie

src/Command/RetryFailedEmailsCommand.php, src/Command/UpdateSignalementGeolocalisationCommand.php
#3496   
#3495 
Gérer la contrainte mémoire scalingo, limiter la plage de date à 1 mois 
Ne pas faire d'envoi sur les email "NC"
* Ajout d'1 mois à partir de la date de début au lieu de la date du jour 
* Ajout d'une condition pour ne pas envoyer aux mails "NC"
make load-data
=> [QA] Commande maj géolocalisation - limiter la plage de date à 1 mois

src/Form/ZoneType.php
#3490    
Des partenaires archivés apparaissent dans la liste déroulante 
* Exclure les partenaires archivés
=> [BO - Zone] Partenaires à affecter

src/Form/SearchZoneType.php
#3487
Suppression de l'attribut required du champ "Type de zone" dans les filtre de recherche de la page liste des zones
=> [BUG - BO Zone] retirer le required sur le filtre de recherche "type de zone"

src/Controller/Back/SignalementEditController.php, src/Dto/Request/Signalement/SignalementDraftRequest.php, src/Dto/Request/Signalement/SituationFoyerRequest.php, src/Service/Signalement/SignalementBuilder.php, src/Specification/Affectation/AllocataireSpecification.php, templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
#3486    
* Ajout de contrôle avant l'usage de `strtoupper` et `strtolower`
* Mise à jour de la contrainte de validation pour le numéro d'allocataire (longueur = 25 comme sur la table Signalement)
=> [QA - Sentry] Dépréciations et contrôle du numéro allocataire

src/Service/DashboardWidget/WidgetDataKpiBuilder.php
#3493    
Ajouter le paramètre isImported à toutes les cartes du widget par défaut
* Mise à jour coté service
=> [BUG - Liste des signalement] Signalements importés non affichés par défaut

assets/scripts/vue/components/signalement-list/components/SignalementListHeader.vue, assets/scripts/vue/components/signalement-list/store.ts, config/packages/doctrine.yaml, migrations/Version20241217195812.php, src/Entity/View/ViewLatestIntervention.php, src/Factory/SignalementExportFactory.php, src/Manager/SignalementManager.php, src/Repository/SignalementRepository.php, src/Service/Signalement/Export/SignalementExportLoader.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3437    
La fonction `GROUP_CONCAT` utilisée sur le champ détail de la table intervention provoque un plantage lors de l'export sur l'oise. Si le contenu de ce champ est volumineux ce qui est le cas ici avec du code HTML stocké, la fonction `GROUP_CONCAT` peut atteindre la limite au niveau de la mémoire. 
**Rappel du besoin est de récupérer la dernière intervention**  
Les tentatives de modification de requête ont échoué, la solution la plus efficace est de passer par une vue
* Création d'une vue pour les dernières interventions par signalements afin de faire une jointure sur cette vue et éviter les group concat qui peuvent être gourmande en mémoire 
* Afficher le bouton export uniquement si un filtre existe
* Divers optimisations coté doctrine et coté loader pour les gestions de la …
=> [BO - EXPORT] Réactiver la colonne "Comm. de la dernière visite" 

src/Factory/SignalementExportFactory.php
#3508   
Dans les exports, la valeur de Allocataire était à `Non` alors qu'elle s'affichait à `Non renseigné` sur la fiche.
Il s'avère qu'on enregistre une valeur vide quand c'est `Non renseigné` et qu'on ne prenait pas en compte cette valeur lors de l'export.
=> [BO - Export] Correction de la valeur de Allocataire quand elle est vide en BDD

cron.json, src/Command/RetryFailedEmailsCommand.php, src/Repository/FailedEmailRepository.php
#3355
Ajout d'un cron une fois par heure pour relancer les erreurs d'envoi d'email
Modification de la commande pour ne pas traiter : 
- Les erreurs enregistrées antérieures à 2025
- Les erreurs enregistrées correspondant à des email malformé
=> [Tech - email] Déclarer le cron pour la commande des mails en échec

src/Form/PartnerType.php, src/Repository/BailleurRepository.php
#3504    
Dans le formulaire d'édition de partenaire, si le territoire est null, on a une erreur sur la recherche des bailleurs sociaux.
=> [BO - Partenaire] Correction liste des bailleurs sociaux quand territoire null 

.github/workflows/main.yml
#3527    
> dpkg: dependency problems prevent configuration of wkhtmltox:
wkhtmltox depends on libssl1.1; however:
Package libssl1.1 is not installed.
Une dépendance nécessaire à wkhtmltopdf (libssl1.1) n'est plus disponible dans la version d'Ubuntu utilisée actuellement dans la CI (ubuntu-latest, qui pointe aujourd'hui vers Ubuntu 24.04).
Après investigation,  libssl1.1 est disponible que sur Ubuntu 20.04.
https://packages.ubuntu.com/search?keywords=libssl1.1&searchon=names&suite=focal&section=all
La solution la plus safe est de fixer la version d'Ubuntu utilisée dans la CI à 20.04, où cette dépendance est encore disponible.
> [!IMPORTANT]  
> ## Le projet [wkhtmltopdf](https://github.com/wkhtmltopdf/wkhtmltopdf) n'est plus maintenu
* Mise à jour yaml
=> [CI] Etape wkthtmltopdf KO

src/Controller/Back/SignalementActionController.php, templates/back/signalement/view.html.twig, templates/back/signalement/view/header.html.twig
#3413
Mise en cohérence de l'embarquement de la modale de réouverture d'un signalement pour le partenaire avec les régles d'affichage du bouton "Rouvrir pour xx" afin que le bouton ne puisse pas apparaître sans que la modale soit embarquée.  
- `make load-fixtures`
- Se connecter en super admin et "clôturer pour tous" le signalement http://localhost:8080/bo/signalements/00000000-0000-0000-2023-000000000015
- Se connecter avec user-13-05@histologe.fr et se rendre sur le même signalement
=> [BUG - BO] bouton "rouvrir pour xx"

src/Security/Voter/SignalementVoter.php, src/Service/Signalement/SignalementBuilder.php
#3518   
Dans le 69, via leur configuration particulière, l'ensemble des RT est notifié pour les nouveaux signalements, alors que le territoire est divisé en deux partenaires.
De plus, en accédant via l'url directe, ils pouvaient voir les signalements, ce qui ne devrait pas être le cas.
* Modification du voter pour accéder aux signalements pour prendre en compte la config des codes insee autorisés
* Modification de l'enregistrement des draft pour enregistrer la valeur du code insee depuis le front, et l'avoir à disposition pour filtrer les notifications
Utiliser la base de prod pour ne pas avoir à dupliquer les configurations.
En base, modifier le mot de passe d'un utilisateur dans le partenaire COR
=> [Notifications] Correction des notifications de nouveau signalement et d'accès à la fiche pour le 69

migrations/Version20250109113158.php, src/Service/Signalement/SignalementBuilder.php, tests/Functional/Service/Signalement/SignalementBuilderTest.php
#3533    
Quand on faisait un signalement en répondant "non" à la question "Recevez-vous une aide ou allocation logement ?", la réponse enregistrée était une chaîne vide, comme si on n'avait pas eu la question où qu'on avait répondu "je ne sais pas"
Cela était du à une modification de la fonction `resolveIsAllocataire` depuis l'ajout de la possibilité de répondre "je ne sais pas" pour quelque profils. https://github.com/MTES-MCT/histologe/issues/3389
Modification (et donc bug) en prod depuis le 20 décembre 2024
* Fix sur `resolveIsAllocataire`
* Création d'une migration pour corriger les signalements créés depuis le 20 décembre
Avant de descendre la branche, faire un signalement en répondant "NON" à la question
=> [FO - Formulaire] Non-enregistrement de la valeur "NON" pour la question is_allocataire

src/Controller/Back/ExportSignalementController.php, src/Controller/Back/SignalementListController.php
#3515
Chaque modifications de filtre sur la page liste des signalement lance une requête de mise à jour, si une requête est en cours elle est annulée coté javascript mais rien n'arrête le traitement PHP. Certaines requêtes étant beaucoup plus lente que d'autre (en fonction des filtres) et la session étant enregistré en fin de script, dans certains cas c'est une session de requête annulé qui est enregistré postérieurement à la dernière requête effectué.
* Sauvegarde des filtres de recherche en session dés le début du traitement pour éviter l’écrasement par une requête plus lente antérieure
* Sauvegarde des filtres tel que dans `SignalementSearchQuery` afin d'alléger la session
=> [BO - Signalement] Export CSV xls - non application des filtres

assets/scripts/vanilla/controllers/form_nde.js, migrations/Version20250102154204.php, src/Manager/SignalementManager.php, templates/_partials/_modal_edit_nde.html.twig
#3435    
Depuis le nouveau formulaire, on enregistre la vraie date d'entrée dans le logement.
Malheureusement, la modale pour éditer la NDE écrase cette donnée avec des dates arbitraires (01/01/1970 et 02/01/2023) qui servaient à savoir si on était avant ou après 2023.
Heureusement, on a conservé la donnée enregistrée à la base dans le formulaire.
- migration pour remplacer la colonne date_entree si elle est égale aux dates arbitraires, et qu'on a une date réelle d'enregistrée
- remplacement des boutons radio par un champ de saisie (identifique à celui de la modale d'édition annexe
- enregistrement dans le json de type_composition_logement pour la sauvegarder aux deux endroits
=> [BO - Date d'entrée] Correction du type de champ pour la date d'entrée du logement dans le formulaire NDE

config/app/csp.yaml
#3513    
Afin de pouvoir charger la page stat dans sites-facile, il faudrait autoriser l'url site-facile à pouvoir charger la page stat conformément aux règles de sécurité CSP.
* Changement de la directive `frame-ancestors` dans csp.yaml
=> [Sécurité] Autoriser un parent à charger l'url de la plateforme via un iframe

.github/workflows/main.yml
#3516   
On utilisait les versions `actions/cache@v1` et `actions/cache@v2` que GitHub va bientôt déprécier.
Ils encourageaient à passer en v3 ou v4, donc les deux passent en v4.
=> [Tech] Mise à jour de action/cache du workflow GitHub

src/Dto/Request/Signalement/SignalementDraftRequest.php
#3567   
Accepter zero comme valeur pour le nombre d'enfants
=> [FO - Formulaire] Accepter zero comme valeur pour le nombre d'enfants

src/Repository/SignalementRepository.php
#3569   
La liste des communes en tant que RT est vide. Elle ne devrait pas l'être et devrait contenir l'ensemble des communes des territoires de ses partenaires.
Tests sur les département dont on pré-charge les communes (sinon faire un `make console app="update-communes"`)
Idéalement `make clear-pool pool=--all` entre chaque test
=> [BO - Liste signalements] Correction de la liste des communes vide pour les RT

src/Factory/SignalementExportFactory.php
#3571   
Correction de transformation de donnée en majuscule si null de la valeur de `getInfoProcedureBailMoyen`
=> [QA] Correction de transformation de donnée en majuscule si null

src/DataFixtures/Files/Partner.yml, src/DataFixtures/Files/User.yml
#3583
Correction des nom de partenaires en doublons dans les fixtures
=> [QA - Fixtures] Mieux nommer les partenaires pour lier les utilisateurs au bon

src/Controller/Back/AffectationController.php, src/Controller/Back/HistoryEntryController.php, src/Controller/Back/SignalementController.php, src/Security/Voter/AffectationVoter.php, src/Security/Voter/SignalementVoter.php, templates/_partials/_modal_cloture.html.twig, templates/_partials/_modal_refus_affectation.html.twig, templates/back/signalement/view.html.twig, templates/back/signalement/view/header.html.twig, templates/back/signalement/view/partners.html.twig, templates/back/signalement/view/suivis.html.twig, tests/Functional/Controller/Back/SignalementActionControllerTest.php, tests/Functional/Controller/Back/SignalementControllerTest.php
#2367    
Modification des noms de variables utilisées dans les twig de la fiche signalement, pour les rendre plus explicites, ou utiliser des Voter quand nécessaire.
=> [Tech] Simplification des statuts dans le code twig de la fiche signalement

src/Command/Cron/SynchronizeEsaboraSCHSCommand.php, src/Service/Interconnection/Esabora/EsaboraManager.php, tests/Unit/Command/Cron/SynchronizeEsaboraSCHSCommandTest.php
#3597
Ignorer les événements sans date dans la liste de ceux retourner par ESABORA
=> [Esabora - SCHS] Ne pas récupérer les événements sans dates

src/Controller/Back/PartnerController.php, src/EventListener/EntityHistoryListener.php, tests/Functional/Controller/PartnerControllerTest.php
#3576
Bloque le déclenchement d'une boucle infini lors de l'enregistrement de suppression dans historyEntry (cas se présentant à la suppression d'un utilisateur multi-territoire d'un de ses partenaire)
Il semble que cela soit provoqué par le fait d'avoir des `orphanRemoval: true` sur les relation OneToMany Partner et User mais comme cela peut être utile et que le cas peut se représenter je préfère directement corriger dans le `EntityHistoryListener`
=> [BUG] Historique suppression UserPartner

assets/scripts/vanilla/controllers/back_partner_view/form_partner.js, src/Controller/Back/PartnerController.php, src/Entity/User.php, src/Form/UserPartnerType.php, templates/_partials/_modal_user_create_multi.html.twig
#3602 #3603 #3604  #3605
- Ajout d'un message d'information et changement de l'intitulé du bouton submit de la modale d'ajout d'un agent existant sur un partenaire
- Modification du message de succès suite à l'ajout d'un agent existant sur un partenaire
- Modification du label "Prenom" en "Prénom" sur le formulaire de création d'un agent
- Correction de la fonction `getPartnerInTerritoryOrFirstOne` qui retournait toujours le premiere partenaire de l'user et provoquait des problème de droits pour les utilisateur multi-territoire
=> Corrections multi-territoires

config/packages/twig.yaml, src/DataFixtures/Files/NewSignalement.yml, src/Repository/ZoneRepository.php, tests/Functional/Controller/ArchivedSignalementControllerTest.php, tests/Functional/Controller/BackStatistiquesControllerTest.php, tests/Functional/Repository/SignalementRepositoryTest.php, tests/Functional/Repository/ZoneRepositoryTest.php
#3592
Modification de la requête récupérant les signalements dans une zone afin de ne pas afficher dans la liste ceux en statut DRAF ni ARCHIVED 
=> [BO - Signalements] Zones - signalements archivés intégrés

scalingo.json, src/Controller/Security/SecurityController.php
#3552   
Les var d'env sur staging et les reviewApp étaient contradictoires entre `CLAMAV_SCAN_ENABLE` qui était à 1 et `CLAMD_DISABLE_DAEMON/FRESHCLAM_DISABLE_DAEMON` qui étaient configurées à true.
* Sur la staging, suppression des vars d'env `CLAMD_DISABLE_DAEMON` et `FRESHCLAM_DISABLE_DAEMON` pour laisser l'antivirus acctivé
* Dans le fichier [scalingo.json](https://github.com/MTES-MCT/histologe/blob/main/scalingo.json)  on passe `CLAMAV_SCAN_ENABLE` à false pour ne pas activer l'antivirus sur les reviewApp
=> [STAGING] Upload fichier impossible

src/Service/Signalement/SignalementFileProcessor.php, src/Service/UploadHandlerService.php
#3336   
J'ai fait le tour des erreurs sentry de ce type des 30 derniers jours.
Il y avait 2 cas possibles : 
- un type de fichier non supporté, mais le format n'est pas dans l'erreur
- un fichier vide, et la taille n'était pas vérifié avant de vérifier le format
* Amélioration du message d'erreur en cas de format non supporté
* Vérificcation de la taille du fichcier avant de vérifier le format
Désacctiver la vérification js
=> [QA - Sentry] Les fichiers de format ne sont pas pris en charge

src/Repository/SignalementRepository.php, src/Service/Signalement/SignalementAffectationHelper.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3586
Un signalement contenant un (très) grand nombre d'affectations peux résulter à une requête limité (par l'utilisation de `GROUP_CONCAT `pour `rawAffectations`). Dans ce cas la fonction `parseAffectations` provoque un crash car les données sont incomplètes et donc le statut renvoyé est invalide.
- Correction de la fonction `parseAffectations` pour qu'elle ignore le statut si il n'est pas disponible ou inconnu
- Ce la signifie que sur la liste des signaleement seul les xx affectations seront affichés (70 environs) mêm si il y'en à plus
=> [BO - List signalements] Si trop d'affectations sur un signalement, la liste ne s'affiche pas

composer.json, composer.lock, migrations/Version20250122140631.php, src/DataFixtures/Files/AutoAffectationRule.yml, src/Entity/AutoAffectationRule.php, src/Form/AutoAffectationRuleType.php, src/Repository/PartnerRepository.php, src/Service/Signalement/AutoAssigner.php, src/Specification/Affectation/CodeInseeSpecification.php, src/Validator/InseeToInclude.php, src/Validator/InseeToIncludeValidator.php, templates/back/auto-affectation-rule/index.html.twig, tests/FixturesHelper.php, tests/Functional/Controller/AutoAffectationRuleControllerTest.php, tests/Functional/Specification/Affectation/CodeInseeSpecificationTest.php, tests/Unit/Entity/AutoAffectationRuleTest.php, tests/Unit/Service/AutoAssignerTest.php, tests/Unit/Validator/InseeToIncludeValidatorTest.php
#3582    
Filtrer la liste des partenaires en amont des spécifications dans AutoAssigner en utilisant `partnerRepository->findByLocalization()` (la requête utilisée pour filtrer les partenaires en fonction de leur périmètre géographique pour l'affectation manuelle)
Pour la spécification `CodeInseeSpecification` on retire les options `all` et `partner_list`, on peut soit ne rien mettre, soit restreindre à une liste de code insee
* Suppression des librairies mjaschen/phpgeo et longitude-one/wkt-parser (plus nécessaires car le travail est fait en sql comme pour l'affectation manuelle)
* Changement des fixtures
* Changement de l'entité AutoAffectationRule, et migration associée
* Dans la migration, on modifie aussi les règles existantes pour transformer  `all` et `partner_list` en `null`
* …
=> [BO - Auto-Affectation] Filtrage des partenaires par périmètre géographique avant d'étudier les règles d'auto-affectation

migrations/Version20250129102407.php, src/Controller/SignalementController.php, src/Entity/Notification.php, src/EventSubscriber/InterventionCreatedSubscriber.php, src/Service/Import/Signalement/SignalementImportLoader.php, tests/Functional/EventSubscriber/InterventionCreatedSubscriberTest.php, tests/Functional/Service/Import/Signalement/SignalementImportLoaderTest.php
#3635
Suite à la MEP du 28/01 des doublons de suivi (arrêtés et visites) ont été généré dans la nuit du 29/01
- Migration pour supprimer les suivis (et leur notifications) générés en doublons
- Correction des appel `suiviManager->findOneBy` afin que la description soit correctement formaté et ne provoque plus la création de doublon
=> [BUG] doublonge des création de suivi pour arrétés au 29/01/2025

migrations/Version20250127183041.php, src/Controller/Back/SignalementEditController.php, src/Factory/Signalement/TypeCompositionLogementFactory.php, src/Manager/SignalementManager.php
#3426   
Revue des champs JSON posté depuis un nouveau formulaire. 
Pour rester cohérent, les champs JSON doivent rester synchronisé même si la colonne existe. 
* Mises à jour des propriétés manquantes champs de type JSON 
* Ajout de migration
Créer un nouveau signalement et travailler sur un signalement fraichement posté.
Executer `make load-data`
- `make execute-migration name="Version20250127183041" direction="up"`
=> [BO] Données de type doctrine ne se mettrait pas à jour

src/Controller/Back/ProfilController.php, src/Controller/Security/UserAccountController.php, src/Manager/UserManager.php, src/Security/FormLoginAuthenticator.php, src/Security/JsonLoginAuthenticator.php
#3566   
On n'a pas besoin d'aller si loin, on peut supprimer les variables de la RAM unset après leur utilisation, ça sera suffisant si je me limite au problème remonté cad stockés durablement
* Ecrabouillage et suppression des variables contenant des mots de passe dès que plus besoin
=> [Sécurité - Audit] Mots de passe persistant en clair dans la mémoire vive

assets/scripts/vanilla/services/form_helper.js, assets/scripts/vanilla/services/search_filter_form.js, composer.json, composer.lock, eslint.config.mjs, grumphp.yml, package-lock.json
#3641    
Phpstan est une tache de la CI et il est possible d'étendre les fonctionnalités de phpstan pour utiliser des extensions. 
Il en existe une qui blackliste les fonctions de debug php
* Installation de[ phpstan/extension-installer](https://github.com/phpstan/extension-installer) pour activer les extensions 
* Installation de l'extension [ekino/phpstan-banned-code](https://github.com/ekino/phpstan-banned-code) pour blackliste les fonctions de debug
* Mise de la conf eslint pour blacklist console.log
* Suppression des directives grumphp pour les fonction de blacklist
**EDIT** : ```make  npm-install```
```make composer```
```make npm-watch```
=> [CI] Blacklist les fonctions de debug

src/Controller/Back/AutoAssignerSimulatorController.php, src/Repository/PartnerRepository.php, src/Service/Signalement/AutoAssigner.php, templates/back/auto-affectation-rule/index.html.twig, templates/back/auto-assigner-simulator/index.html.twig, templates/back/auto-assigner-simulator/territory.html.twig
#3590
Mise en place d'un outil permettant de simuler le traitement d'auto affectation
- Ajout d'un bouton "Simulateur" sur la page "Règles d'affectation"
- Page d'index des territoire ayant des règles d'affectation pour ouvrir le simulateur sur ce territoire
- Page du simulateur pour un territoire. Affiche par défaut les 10 derniers signalement (nombre paramétrable via l'url  ex : `limit=100`, il est aussi possible de recherche un signalement particulier sur le territoire via l'url ex : `uuid=blabla`)
=> [Auto-affectation] Mettre en place un simulateur

assets/scripts/vue/components/signalement-view/utils/signalementUtils.ts
#3657   
Lorsque plusieurs filtres sont appliqués à la suite des autres, il faut que les requêtes précédentes s'annulent pour laisser la place aux nouvelles.
C'était fonctionnel, mais le test n'était plus valable.
=> [BO - Filtres signalements] Arrêt de requête en cours lors de mise à jour des filtres

.scalingo/nginx/server.location
#3563    
* Suppression de la conf nginx pour empecher les appels ajax cross domain (comportement par défaut)
```
make build
```
_Créer ce fichier et exécuter le sur un autre port (Utilisation du serveur interne vscode port : 5500)_
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Cors test</title>
</head>
<body>
<p>Cors test</p>
<script>
fetch('http://localhost:8080/statistiques-filter?territoire=all', {
method: 'GET',
})
.then(response => {
if (!response.ok) {
throw new Error(`Erreur HTTP : ${response.status}`);
}
return response.json();
})
.then(data => console.log('Réponse OK:', data))
.catch(error => console.error('Erreur CORS:', error));
</script>
</body>
</html>
````
=> [Sécurité - Audit] Absence de restriction CORS

public/js/zone_map.js
#3652   
Depuis la mise à jour de leaflet les marqueurs n'apparaissaient plus sur la carte des zones
* Changement de chemins vers les icones dans zone_map.js (utilisation des mêmes icones que pour la carto)
=> [BO - Zone] Changement de chemins pour les icônes des marqueurs

package.json
#3663    
Nous sommes en LTS en local. 
Et depuis notre premier make build de nov-2024 en node-22 mais la version est figé à une vielle LTS sur scalingo (suite à un ancien ticket)
https://nodejs.org/en/about/previous-releases
https://doc.scalingo.com/languages/nodejs/start#:~:text=when%20making%20commits.-,Specifying%20a%20Node.js%20Version,-In%20your%20engines
* Mise à jour avec la dernière LTS qui est la 22 qui correpond à la conf locale.
```
make build
````
=> [QA] Synchronisation des versions Node.js entre local et production

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json
#3661   
Les baux écrits sont devenus obligatoires depuis avril 2024. On affiche donc un message modifié, et on modifie le lien vers le site du service public.
Profils concernés : locataire, bailleur, tiers particulier, tiers pro, service de secours.
=> [FO - Signalement] Modification du texte concernant les baux manquants

src/Service/Signalement/SignalementAddressUpdater.php, tests/Functional/Controller/Back/SignalementEditControllerTest.php, tests/Functional/EventSubscriber/SignalementViewedSubscriberTest.php, tests/files/datagouv/get_api_ban_item_response_13202.json, tests/files/datagouv/get_api_ban_item_response_13203.json
#3673    
* Mocker Appel BAN API dans  SignalementViewedSubscriberTest et SignalementEditControllerTest pour éviter de faire planter les tests si l'API ne répond pas.
* Remplacer les appels par des mock
* Ajout json pour réprésenter les réponses à simuler
=> [QA] Mocker BAN API

migrations/Version20250204095010.php, src/Entity/Zone.php
#3650
Ajout du trait TimestampableTrait sur la table zone
`make execute-migration name=Version20250204095010 direction=up`
=> [TECH] Ajout du trait TimestampableTrait sur la table zone

tests/Functional/Controller/AffectationControllerTest.php
#3677
A la relecture d'une autre PR, je me suis demandé si l’utilisation du "sanitizer" n'avais pas provoqué une régression sur la création de suivi/envoi d'email lors de la première acceptation d'un affectation sur un signalement.
Ce n'était pas le cas, mais cela étant un peu difficile à vérifier j'ai préféré ajouté des tests dessus
Se connecter avec user-partenaire-multi-ter-34-30@histologe.fr
Le premier doit envoyer un mail est généré un suivi, le second non
=> Modification des test sur AffectationController

src/Security/Voter/SignalementVoter.php
#3678    
Suite à ce commit https://github.com/MTES-MCT/histologe/commit/edd1fc61cace63eb79da2796f4528062707c307b, nous avons perdu la possibilité d'ajouter des documents sur la fiche usager si nous sommes connectés au BO
* Correction du voter (si un utilisateur est connecté, on regarde le statut du signalement pour dire true ou false)
=> [FO - Suivi] Un utilisateur connecté au BO ne pouvait plus ajouter de docs/photos sur la page de suivi

assets/scripts/app-back-bo.ts, assets/scripts/vanilla/services/bo_modales.js, migrations/Version20250129155205.php, migrations/Version20250204083053.php, src/Controller/Back/PartnerController.php, src/Controller/Back/PopNotificationController.php, src/Entity/Partner.php, src/Entity/PopNotification.php, src/Entity/User.php, src/Manager/PopNotificationManager.php, src/Repository/PopNotificationRepository.php, templates/back/base_bo.html.twig, templates/back/pop-notification/index.html.twig, templates/back/profil/index.html.twig, templates/base.html.twig, tests/Functional/Manager/PopNotificationManagerTest.php
#3623
Ajout d'un système de notification par modale, pour indiquer à l'agent les modification effectués sur son comptes (ajout/retrait de partenaire)
make execute-migration name=Version20250204083053 direction=up
=> [BO - Agent multi territoires] Ajouter des modales à l'ajout / suppression d'un territoire

config/packages/security.yaml, src/Controller/Security/UserAccountController.php, src/Security/JsonLoginAuthenticator.php, src/Security/TokenAuthenticator.php
#3559
Le système de login est protégé correctement (pas uniquement sur l'IP) d’après ce que je comprends (système par défaut de loggin_throttling de Symfony
* Ajout du système de limitation sur les authentifications API
* Utilisation de l'email au lieu de l'IP pour la limitation sur le système d'activation du compte / changement mot de passe
=> [Sécurité - Audit] Modifier la protection anti-brute force

src/Command/TrimPartnerNamesCommand.php, src/Repository/PartnerRepository.php, src/Service/Import/GridAffectation/GridAffectationLoader.php
#3693   
Certains noms de partenaires (notamment en Gironde) ont un espace en début de nom. En l'occurence, il s'agit d'un espace insécable.
* Ajout d'une commande qui permet de nettoyer les noms
* Ajout d'un commentaire pour améliorer le `trim` lorsqu'on passera à php 8.4, lors de l'import de grille d'affectation
Utiliser la BDD de prod
=> [Partenaires] Ajout d'une commande pour supprimer les espaces en début de nom

src/Service/NotificationAndMailSender.php, tests/Functional/Service/NotificationAndMailSenderTest.php
#3694   
Suite de https://github.com/MTES-MCT/histologe/pull/3692 (ajout de test, et prise en compte des remarques d'emilien)
* Ajout d'un test
* Prise en compte des remarques d'Emilien
=> [BO - Notifications] Ajouter des tests

src/Controller/Back/SignalementController.php, src/Controller/Back/SignalementFileController.php, src/Security/Voter/FileVoter.php, src/Security/Voter/SignalementVoter.php, templates/back/signalement/view/tags.html.twig
#3687    
Rendre possible pour les RT :
-     L'ajout / retrait d'étiquettes d'un signalement en statut fermé
-     L'ajout de documents d'un signalement fermé, sans création de notifications ni de notifications email
- Modification des voter SIGN_EDIT, FILE_CREATE et FILE_EDIT pour renvoyer true si le signalement est fermé mais que l'utilisateur est RT ou SA
- Modification du signalementFileController pour s'assurer qu'on ne crée pas de suivi (et donc pas de notification ou e-mail) si le signalement est fermé
- Modification du signalementController pour envoyer au twig un canEditClosedSignalement
- Modification du twig pour faire apparaitre le bouton de gestion des étiquettes (les boutons d'ajout de photos et documents apparaissaient déjà et fonctionnaient mais cela créait un …
=> [BO - Signalement] Edition doc et etiquette pour les RT même si statut fermé

src/Controller/Back/SignalementFileController.php, templates/_partials/_modal_upload_files.html.twig
#3712    
Suite de https://github.com/MTES-MCT/histologe/pull/3705
Il ne faut pas créer non plus de suivi quand on supprime un fichier sur un signalement fermé.
Et on change le message d'alerte sur les modales d'uploads
* Changement de SignalementFileController
* Changement de _modal_upload_files.html.twig
=> [BO - Signalement] Suppression de document sur signalement fermé pour RT

src/Service/NotificationAndMailSender.php, tests/Functional/EventSubscriber/SignalementViewedSubscriberTest.php, tests/Functional/Service/Notification/NotificationCounterTest.php, tests/Functional/Service/NotificationAndMailSenderTest.php
#3626    
Quand un utilisateur créé un suivi, il ne doit pas avoir de notifications, mais les autres personnes de son partenaire si.
* Modification de NotificationAndMailSender
=> [Notifications] Ne pas envoyer à l'utilisateur qui a créé un suivi

.env, migrations/Version20250214125623.php, src/Controller/Back/SignalementController.php, src/Controller/HomepageController.php, src/Entity/Signalement.php, src/Repository/PartnerRepository.php, src/Service/NotificationAndMailSender.php
#3711
Quelques optimisations mineures pour régler une partie des alertes "bleues" qui remonte le plus souvent sur sentry
* Ajout d'un index sur la colonne cp_occupant du signalement. Permet d'accélerer d'un facteur 100 la requête de vérification de l'existence de doublon (draft =>signalement). Voir test sur une boucle lancant 50 de ses requêtes : 
* Préchargement de la liste de situations et critères à la visualisation d'un signalement BO afin d'éviter de les requeter unitairement
* Mise en cache (15 minutes) du total de signalement pour les stats sur la homepage (la requête commence a ralentir, et on a pas besoin de temps réel)
* Lors de la création/envoie de notifications suite à l'ajout d'un suivi (depuis BO ou FO) récupération de la liste des UserPartner et Partner d'un partenaire …
=> [Tech] Optimisations

assets/styles/histologe.scss, config/app/csp.yaml, src/Controller/IframeController.php, templates/_partials/_demande-lien-signalement.html.twig, templates/form/form-demande-lien-signalement.html.twig, templates/iframe/base-iframe.html.twig, templates/iframe/demande_lien_signalement.html.twig, templates/iframe/test.html.twig
#3666
Préparation de l'iframe "demand de lien du signalement" pour intégrer via sites-facile
* Ajout d'un template `base-iframe` qui importe uniquement les css et script à étendre pour gérer les éléments à intégrer en iframe
* Ajout d'un controller pour gérer les routes des éléments a inclure en iframe
* Ajout d'un style spécifique quand le formulaire de demande de lien est appellé via sa route iframe (vue avec Mathilde)
=> [FO - Sites Faciles] Prévoir iFrame récupération lien de suivi

src/Service/Signalement/SignalementAffectationHelper.php
#3720   
Certains statuts d'affectation sont vides. Pour éviter une erreur, on retourne une chaine vide.
=> [QA] Statut d'affectation vide

assets/scripts/app-back-bo.ts, assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, assets/styles/histologe.scss, migrations/Version20250210092800.php, src/Controller/Back/SignalementCreateController.php, src/Entity/Signalement.php, src/Form/SignalementAddressType.php, src/Repository/SignalementRepository.php, src/Security/Voter/SignalementVoter.php, src/Service/Signalement/PostalCodeHomeChecker.php, src/Service/Signalement/SignalementAddressUpdater.php, src/Service/Signalement/SignalementBoManager.php, templates/_partials/_modal_duplicate.html.twig, templates/back/signalement_create/_modal_duplicate_content.html.twig, templates/back/signalement_create/drafts.html.twig, templates/back/signalement_create/index.html.twig, templates/back/signalement_create/tabs/tab-adresse.html.twig, templates/form/dsfr_theme.html.twig, tests/Functional/Controller/Back/SignalementCreateControllerTest.php
#3644
Ajout du champ isLogementVacant nécéssaire
Mise en place du formulaire de l'onglet adresse du formulaire BO
- Création/Edition
- Détection de doublon
- Page brouillon (uniquement pour simplifier la navigation lors des tests à finaliser avec le #3643
`make execute-migration name=Version20250210092800 direction=up`
=> [BO - Formulaire pro] Faire l'onglet Adresse

assets/scripts/vue/components/dashboard/TheHistoDashboardCards.vue, assets/scripts/vue/components/front-stats/TheHistoFrontStatsTerritory.vue, assets/scripts/vue/components/stats/TheHistoStatsDetails.vue, src/Controller/Back/SignalementActionController.php, src/Controller/Back/SignalementController.php, src/Dto/Api/Response/SignalementResponse.php, src/Entity/Suivi.php, src/Manager/HistoryEntryManager.php, src/Manager/SuiviManager.php, src/Service/Signalement/Export/SignalementExportSelectableColumns.php, templates/back/signalement/view/header.html.twig, templates/front/_partials/_suivi_signalement_tab_suivi.html.twig, templates/front/index.html.twig, tests/Functional/Controller/SignalementControllerTest.php, tests/Functional/Manager/SuiviManagerTest.php
#3730    
Remplacer "clôturé" par "fermé" pour les signalements
* Remplacer "clôturé" par "fermé" pour les signalements
=> [Partout] Remplacer "clôturé" par "fermé" pour les signalements

src/Controller/Api/SignalementFileUpdateController.php, src/Controller/Api/SignalementFileUploadController.php, src/Dto/Api/Model/File.php, src/Dto/Api/Request/FileRequest.php, src/Dto/Api/Request/FilesUploadRequest.php, src/Entity/File.php, src/Entity/User.php, src/Event/FileUploadedEvent.php, src/EventSubscriber/FileUploadedSubscriber.php, src/Factory/Api/FileFactory.php, src/Factory/Api/SignalementResponseFactory.php, src/Security/Voter/FileVoter.php, src/Service/ImageManipulationHandler.php, src/Service/Signalement/SignalementFileProcessor.php, tests/Functional/Controller/Api/SignalementFileUpdateControllerTest.php, tests/Functional/Controller/Api/SignalementFileUploadControllerTest.php
#3622    
- Envisager un passage en asynchrone avant d'augmenter la  limitation afin d'éviter de long temps de réponse.
- Envisager une migration de doctrine à une autre solution de queuing (indépendant de la DB, plus performante) pour le transport des messages car la typologie de messages gérés en asynchrones  augmente (~ une dizaine). 
Le choix pourra se porter sur Redis car le service est dispo sur scalingo.
Autre avantage, ça permettra de réduire la charge en écriture sur la base de donnée.
Mise à disposition deux routes pour la gestion des documents (Limitation à 5 pour commencer et observer l'usage)
_1. Requête (Dépôt des fichiers)_
```
POST {{baseUrl}}/api/signalements/00000000-0000-0000-2022-000000000001/files
```
_2. Requête (Edition des fichiers déposés via uuid)_
```
PATCH …
```
=> [API] Ajout de documents

src/Controller/Api/SignalementController.php, src/Controller/Api/SignalementFileUploadController.php, src/Controller/Api/SuiviCreateController.php, src/Controller/Back/SignalementActionController.php, src/Dto/Api/Request/SuiviRequest.php, src/Dto/Api/Response/SignalementResponse.php, src/Dto/Api/Response/SuiviResponse.php, src/EventListener/SecurityApiExceptionListener.php, src/Validator/SanitizedLength.php, src/Validator/SanitizedLengthValidator.php, src/Validator/ValidFiles.php, src/Validator/ValidFilesValidator.php, tests/Functional/Controller/Api/SuiviCreateControllerTest.php, tests/Unit/Validator/SanitizedLengthValidatorTest.php
#3621   
* Le signalement doit être affecté au partenaire
* Les fichiers doivent être rattaché au signalement
=> [API] Création de suivi

assets/scripts/vue/components/signalement-form/TheSignalementAppForm.vue, assets/scripts/vue/components/signalement-form/store.ts, src/Controller/SignalementController.php, src/Service/Mailer/Mail/Signalement/ContinueFromDraftMailer.php, templates/front/formulaire_signalement.html.twig, tests/Functional/Controller/SignalementControllerTest.php
#3669   
Avec Sites Facile, on pourra ouvrir le formulaire depuis différents liens, selon le profil de l'utilisateur.
Pour lui éviter de re-saisir des informations qu'il pense avoir déjà choisies, on permet la pré-sélection des options avec un paramètre transmis via URL.
=> [FO - Signalement] Pouvoir initialiser le formulaire avec un profil

src/Controller/Back/SignalementActionController.php, src/Entity/Suivi.php, src/EventSubscriber/SignalementClosedSubscriber.php, src/EventSubscriber/SuiviCreatedSubscriber.php, src/Manager/SignalementManager.php, src/Repository/SignalementRepository.php, src/Service/NotificationAndMailSender.php, tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php, tests/Functional/Manager/SignalementManagerTest.php, tests/Functional/Service/NotificationAndMailSenderTest.php
#3681   
Suite à la suppression de l'ActivityListener, refactorisation de l'envoi de mail lors de l'acceptation, le refus ou la fermeture de signalements.
Les mails étaient envoyés jusqu'à présent dans des événements.
On les envoie dans l'événement de création de suivi, comme pour les autres mails.
=> [Suivis] Refactorisation de l'envoi de mail pour l'acceptation, le refus et la fermeture des signalements

assets/scripts/vanilla/controllers/back_signalement_view/form_upload_documents.js, assets/scripts/vanilla/controllers/front_suivi_signalement/front_suivi_signalement.js, src/Exception/File/UnsupportedFileFormatException.php, src/Service/Signalement/SignalementFileProcessor.php, src/Service/UploadHandlerService.php, tests/Functional/Service/UploadHandlerServiceTest.php
#3719
Utilisation du mimeType dans le message d'erreur de format des fichier plutôt que leur extension
=> [FO - Suivi] Différence entre extension et mimetype du fichier

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, assets/styles/histologe.scss, src/Controller/Back/SignalementFileController.php, src/Service/ImageManipulationHandler.php, templates/back/signalement/view/photos-album.html.twig, templates/base.html.twig
#3684
- Ajout de la possibilité de faire pivoter une image et d'enregistrer la rotation
- Correction du thème utilisé quand la gallerie photo est ouverte (thème sombre)
Pour la question de l'orientation par défaut en fonction des donnée exif, nous n'avons pas l'extension PHP activé nécessaire, je partage la doc consulté ici en cas de besoin : 
- https://image.intervention.io/v2/api/exif 
- https://image.intervention.io/v3/modifying/effects#image-orientation-according-to-exif-data
=> [BO - Photos] Pouvoir corriger l'orientation des photos

src/Controller/Back/SignalementActionController.php, src/Entity/Suivi.php, src/Manager/SuiviManager.php, tests/Functional/Manager/SuiviManagerTest.php
#3730   
Remettre "clôturé" plutôt que "fermé" pour les suivis de signalements 
* Remettre "clôturé" plutôt que "fermé" pour les suivis de signalements
=> [Suivis] Remettre "clôturé" plutôt que "fermé" pour les suivis de signalements 

migrations/Version20250221154939.php, src/EventSubscriber/SignalementDraftCompletedSubscriber.php, src/Manager/SignalementDraftManager.php
#3733
La commande `app:clear-entities` crashe en prod depuis le 2 Février. La raison tentative de suppression d'un `signalementDraft` référencé dans le champ `createdFrom` d'un `Signalement`.
Cela signifie que lors de la transformation d'un draft en signalement le draft n'a pas pris le statut 3EN_SIGNALEMENT3. Il s'agit d'un cas ultra minoritaire étant données qu'il y'a uniquement deux draft dans ce cas sur la prod.
* Ajout d'une migration pour passer les draft référencé comme signalement au bon statut "EN_SIGNALEMENT"
* Déplacement du `$signalementDraft->setStatus(SignalementDraftStatus::EN_SIGNALEMENT);` dans la transcation pour éviter que le cas puise se reproduire
Se mettre sur base de prod
=> [QA] Integrity constraint violation: 1451 Cannot delete or update a parent row

package.json, webpack.config.js
#3746   
Le démarrage de la commande `npm run watch` était de plus en plus lent.
Puisque nous créons 4 exports différents, le même travail est fait plusieurs fois.
Je propose donc 4 nouvelles commandes qui permettent de cibler les exports qui sont en cours de `watch` :
- `npm run watch-form` : formulaire de signalement
- `npm run watch-front-stats` : statistiques front
- `npm run watch-bo` : toutes les pages du bo
- `npm run watch-base` : toutes les autres pages
`npm run watch` continue de fonctionner comme avant si nécessaire.
=> [Tech] Optimisation de la commande npm run watch

.env, .env.sample, .github/workflows/main.yml, src/Controller/HomepageController.php, tests/Functional/Controller/HomepageControllerTest.php
#3584   
Afin de limiter les mails de support :
- on crée une nouvelle adresse `formulaire-contact` vers laquelle sont redirigés les mails qui viennent du formulaire de contact
- on désindexe la page de contact
- fait par ailleurs lors de la MEP : on met en place un répondeur automatique sur l'adresse `contact`
=> [Contact] Changement adresse mail du formulaire de contact

assets/scripts/vue/components/front-stats/TheHistoAppFrontStats.vue, src/Controller/IframeController.php, templates/iframe/statistiques.html.twig
#3667   
Préparation de l'iframe "Statistiques" pour intégrer via sites-facile
=> [FO - Sites Faciles] Prévoir iFrame statistiques front

assets/scripts/vue/components/signalement-form/TheSignalementAppForm.vue, assets/scripts/vue/components/signalement-form/requests.ts
#3758    
Quand on change plusieurs fois de profil (en passant d'occupant à tiers) , on est bloqué car les coordonnées ne sont pas remplies. 
https://sentry.incubateur.net/organizations/betagouv/issues/152236/events/3ea7ef598d6e4749a2a5c19d81bf1a1a/?project=61&referrer=next-event
* On n'enregistre pas le draft si on est sur l'écran de choix de profil
* On met à jour le profil dans le formData avant d'enregistrer le draft (pour avoir une donnée cohérente entre `profil` et `signalement_concerne_profil_detail_tiers` ou `signalement_concerne_profil_detail_occupant`
=> [FO - Form] Correction d'un bug en cas de chccangement de profil

src/Repository/SignalementRepository.php
#3761   
Les stats publiques comptent les resolutions sur les motifs de cloture
Mais si un signalement est reouvert, le motif etant toujours présent, le signalement est toujours comptabilisé
Ajouté la condition Statut CLOSED pour le décompte
* Modification de la fonction countByMotifCloture dans le SignalemmentRepository pour ne prendre en compte que les signalements au statu CLOSED
=> [FO - Stat Publiques] Modifier calcul resolution (ajout condition Statut Fermé)

src/Service/Mailer/Mail/AbstractNotificationMailer.php, tests/Functional/Controller/AffectationControllerTest.php
#3769
Ajout d'un destinataire to par défaut (correspondant au no-reply) lors de l'envoie avec destinataire masqué
=> [BUG - Email] Unable to send an email: to is missing

scripts/sync-db.sh, src/Controller/Security/SecurityController.php, src/Controller/SendEmailController.php, src/EventListener/ExceptionListener.php, src/Service/Mailer/Mail/Cron/CronMailer.php, src/Service/Mailer/Mail/Error/ErrorSignalementMailer.php, templates/emails/cron_email.html.twig, templates/emails/erreur_signalement_email.html.twig
#3745    
Envoi d'un mail lors de la synchro de bdd Metabase que ce soit en échec ou que cce soit un succès
* Création d'un controlleur spécifique `SendEmailController` qui utilise `CronMailer`
* Modification du `CronMailer` et du template `cron_email.html.twig` pour modifier titre et message pour avoir l'info erreur ou pas directement
* Mise à jour du script de synchro
* Revert des modifications du `SecurityController`, `ExceptionListener`, `ErrorSignalementMailer` et du template `erreur_signalement_email.html.twig` faites dans https://github.com/MTES-MCT/histologe/pull/3702
```
curl -X POST "http://localhost:8080/send-email" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer test" \
-d '{"title": "[Metabase] Synchronisation de Bdd", "timestamp": "2025-02-27 14:30:00", …
```
=> [Synchro Metabase] Recevoir mail quand OK

src/Service/Statistics/StatusStatisticProvider.php
#3772   
Depuis les changemenst sur les statuts de signalement, la stat de répartition par statut ne fonctionne pas
* Correction de StatusStatisticProvider.php
=> [FO - Stats] La répartition par statut ne s'affiche plus

assets/scripts/vanilla/controllers/activate_account/activate_account.js, assets/scripts/vanilla/controllers/form_modal_handler.js, src/Controller/Back/ProfilController.php, templates/back/profil/_modal_profil_password.html.twig, templates/back/profil/index.html.twig, tests/Functional/Controller/Back/ProfilControllerTest.php
#3560
Demande et vérification du mot de passe actuel lors du changement de mot de passe via la page profil du BO
* Ajout du champ mot de passe courant et vérification à la soumission
* Soumission ajax pour avoir un retour d'erreur directement dans la modale sans recharger la page
=> [Sécurité - Audit] Demander ancien mot de passe lors d'un changement de mot de passe

migrations/Version20250303140936.php, src/Command/RetryFailedEmailsCommand.php, src/Entity/FailedEmail.php, src/Manager/FailedEmailManager.php
#3771
- Ajout de la gestion du champ `isRecipientVisible`  dans FailedEmail afin d'être iso avec l'envoie classique 
- Suppression des email en erreur avec +de 900 tentative de renvoie (faisant suite au bug sur l'auto affectation)
make execute-migration name=Version20250303140936 direction=up
=> [BO - Command renvoi FailedEmail] Améliorer

templates/_partials/_demande-lien-signalement-container.html.twig, templates/_partials/_demande-lien-signalement-intro.html.twig, templates/front/contact.html.twig, templates/front/index.html.twig, templates/front/suivi_signalement.html.twig, templates/iframe/demande_lien_signalement.html.twig
#3666
On ne veux pas embarquer le titre et texte d'intro dans l'iframe de demande du lien de suivi
Vérifier les différentes pages
=> [FO - Sites Faciles] Adapter iFrame récupération lien de suivi

src/Controller/Security/UserAccountController.php, src/Repository/UserRepository.php, src/Security/FormLoginAuthenticator.php
#3786
Nous avons en stock quelques comptes ayant la même adresse email (un usager et un agent ) cela provoquait des problèmes :
- Si le compte user est antécédent à celui de l'agent : impossible d’utiliser le système de récupération de mot de passe
- Si le compte user est antécédent à celui de l'agent et actif : Impossible de se connecter
Sur base de prod tester avec l'emai posant soucis (voir mattermost)
=> [BUG] Fix request mdp perdu quand un autre compte "ROLE_USAGER" existe

src/Entity/Signalement.php, src/Service/Signalement/SignalementAddressUpdater.php, src/Utils/CommuneHelper.php, tests/Unit/Utils/CommuneHelperTest.php
#3795
Dans les ville avec arrondissements, le libellé de l'adresse retourné par la BAN contient le nom de la ville principale, mais la ville contient le nm de la ville avec l’arrondissement de précisé.
Hors quand on compare les deux, le score retourné par la BAN n'est plus fiable et on l'ignore 
Correctif pour ignorer l'arrondissement lors de cette comparaison
=> [BO - Signalement] Marseille Geoloc plus recuperee aupres de la BAN

.env, src/Form/SearchUserType.php, src/Repository/UserRepository.php, templates/back/partner/view.html.twig, templates/back/zone/index.html.twig, tests/Functional/Controller/Back/BackUserControllerTest.php
#3796   
Retirer de la liste des user (et du choix dans la liste des roles) pour les RT sur la page liste des utilisateurs
Retirer de l'onglet agent d'un partenaire
* Modification du SearchUserType
* Modification de findFiltered dans UserRepository
* Modification du template twig de la liste des agents d'un partenaire
* Ajustement des tests
=> [BO - utilisateurs - partenaires] Les utilisateurs API ne doivent pas être visibles (hors SA)

assets/scripts/vanilla/services/form_helper.js, src/Repository/PartnerRepository.php
#3792
Bug remonté par Arnaud lors de sont test sur le Rhône : 
La liste des partenaires n'est pas complète. Le bug fait suite à la PR #3776 (et existait probablement déjà avant mais uniquement ppour les partenaires avec des zones, donc moins visibles)
* Correction du paramètre paginator pour corriger le problème
* Correction de la requête pour éviter les query N+1 lors de l'affichage de la liste
=> [bug] pagination page partenaires

assets/scripts/app-back-bo.ts, assets/scripts/app.ts, assets/scripts/vanilla/controllers/back_signalement_view/form_upload_documents.js, assets/scripts/vanilla/controllers/front_suivi_signalement/front_suivi_signalement.js, assets/scripts/vanilla/services/modales_helper.js
#3764
Sur les modale d'upload de fichiers, les boutons (de fermeture et d'action) sont à présent bloqué tant que des uploads sont en cours
J'aurais voulu bloquer aussi la fermeture via clic à l'extérieur de la modale (ce qui arrive parfois par erreur) mais je n'ai pas trouvé comment
=> [BO - Signalement] Quand on upload un document et qu'on ferme la modale trop vite, le document n'est pas enregistré

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/scripts/vue/components/signalement-form/components/SignalementFormComponentGenerator.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormSubscreen.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormUploadDocuments.vue, src/Factory/FileFactory.php, src/Service/Signalement/SignalementDocumentTypeMapper.php
#3531   
On donne la possibilité au déclarant de déposer des fichiers plus librement en fin de parcours, sans les lier à des catégories existantes.
On sépare en deux entre photos (qui se rangent dans Photo de la situation) et documents (qui se rangent dans Autre)
* Ajout d'un composant `SignalementFormUploadDocuments` qui utilise `SignalementFormUploadPhotos` existant en modifiant son type.
* Ajout d'éléments dans l'écran "Précisions sur votre situation", en modifiant les textes selon les profils.
=> [FO - Signalement] Possibilité d'ajouter des documents libres en fin de parcours

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/dictionary.json, assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/json/Signalement/questions_profile_tous.json, src/Form/SignalementDraftSituationType.php
#3598   
Suite aux retours du PNLHI, nous avons convenu de faire les modifications suivantes : 
- Renommer la zone de désordres `Bâtiment` en `Bâtiment (et / ou parties communes)`
- Sur la page `avant de démarrer` remplacer `Après cette page, cela vous prendra environ 25 minutes pour signaler vos problèmes de logement.` par `Après cette page, cela vous prendra environ 25 minutes pour signaler les problèmes de logement.`
- Sur l'écran `introduction` pour l'adresse : remplacer `L'adresse du logement` par `L'adresse du logement ou de l'immeuble`
- Sur l'écran `signalement_concerne_profil` inverser le titre de la page et le label de la question : 
- le titre devient `Qui est concerné par votre signalement ?`
- le label de la question devient `Vous déposez un signalement...` 
- Dans le …
=> [Formulaire] Modification de texte suite aux retours du PNLHI

README.md, docs/SECURITY.md
#3734   
Ajouter une partie sécurité dans github
* Changement du readme.md et du security.md
=> [MSS] Rendre public une procédure permettant de signaler un problème de sécurité

templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
#3805    
Inverser les éléments sur la page de suivi usager, onglet Suivi du dossier
Basculer le Bloc Envoyer un message en 1er élément
Modifier ordre d'affichage des messages : du plus récent au plus ancien
* Changement du template twig de la page de suivi
=> [FO - Page de suivi] Modification Ordre affichage

src/Dto/Request/Signalement/CoordonneesTiersRequest.php, src/Entity/Model/InformationComplementaire.php, src/Manager/SignalementManager.php, templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig, templates/back/signalement/view/information/information-tiers.html.twig
#3763   
Quand le tiers-déclarant est un bailleur, il peut saisir sa date de naissance dans le formulaire.
Par contre, jusque-là, on ne l'affichait pas dans la fiche signalement.
=> [BO - Signalement] Pouvoir voir et éditer date de naissance bailleur quand tiers déclarant

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/dictionary.json, assets/scripts/vue/components/signalement-form/components/SignalementFormUpload.vue
#3809   
Quelques ajustements suite aux tests de Mathilde et Arnaud :
- ajout d'une barre de progression qui s'affiche quoiqu'il arrive jusqu'à la validation du fichier
- erreur de format de fichier qui s'affiche en plus des fichiers déjà uploadés
- modification de "Ne sait pas" en "Je ne sais pas"
- a des conséquences sur l'écran de résumé avant validation, mais ça me choque pas, personnellement)
`npm run watch-form`
=> [FO - Signalement] Ajustements pour ajouter des fichiers libres

docker-compose.yml
#3822    
Avant l'upgrade redis sur scalingo, mise à jour de l'env locale dans un premier temps
* Upgrade de la version de redis `docker-compose`
```
make build
```
=> [INFRA] Mise à jour Redis

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json
#3820   
Demande de la date de DPE et de la classe énergétique seulement si on répond "oui" à la question sur le DPE
* Changement des json
=> [FO - Signalement] Date DPE même si pas de DPE

src/Repository/SignalementRepository.php
#3847   
Dans la liste des signalements, le filtre sur les bailleurs sociaux fonctionne pour RT et SA, mais pas pour les agents, alors que le filtre est bien disponible pour tout le monde.
On rétablit donc son fonctionnement.
=> [BO - Liste signalements] Correction filtre Bailleur social pour agent

templates/front/_partials/_suivi_signalement_tab_infos.html.twig
#3857    
Retour de test de Mathilde, les boutons de suppression de fichier sur la page de suivi usager n'apparaissent pas
* Correction de l'appel au voter FRONT_FILE_DELETE dans le twig
=> [FO - Suivi usager] Pas de bouton de suppression d'image/doc

src/Service/DashboardWidget/WidgetDataKpiBuilder.php
#3853    
Je suis RT du 06
Je vais sur mon dashboard
Je clique sur le widget pour afficher la liste des partenaires non notifiables
J'arrive sur la liste
La liste est affichée, l'interrupteur pour afficher uniquement les partenaires non-notifiables est actif mais la liste n'est pas filtrée + un il a une erreur
* Suppression du territoire dans l'url si pas admin ou pas de territoire choisi
`make clear-pool pool=--all`
=> [BO - Partenaires] Filtre partenaire non notifiable ne fonctionne pas depuis le widget

assets/scripts/vanilla/controllers/front_suivi_signalement/front_suivi_signalement.js
#3862   
Je suis usager
Sur ma page de suivi, j'ajoute des photos à mon message
Les fichiers apparaissent en dessous du champ message, alignés à gauche
Vu que les fichiers n'ont pas les mêmes noms les boutons ne sont pas alignés et c'est pas top niveau UI
-> Faire 2 colonnes avec le nom du fichier dans la première, aligné à gauche et le bouton supprimer dans la seconde, aligné à droite
* modification du js d'ajout de fichiers
=> [FO - Page de suivi] Aligner les PJ à droite

assets/scripts/vanilla/controllers/back_signalement_edit_file/back_signalement_edit_file.js, assets/scripts/vanilla/controllers/back_signalement_view/form_upload_documents.js, assets/scripts/vanilla/controllers/front_suivi_signalement/front_suivi_signalement.js, assets/scripts/vue/components/signalement-form/components/SignalementFormUpload.vue, src/Command/UpdateSignalementDocumentFieldsCommand.php, src/Controller/Api/SignalementFileUpdateController.php, src/Controller/Back/ProfilController.php, src/Controller/SignalementController.php, src/DataFixtures/Loader/LoadFileData.php, src/DataFixtures/Loader/LoadInterventionData.php, src/DataFixtures/Loader/LoadSignalementData.php, src/Entity/Enum/DocumentType.php, src/Entity/File.php, src/Factory/FileFactory.php, src/Manager/FileManager.php, src/Manager/InterventionManager.php, src/Service/Import/Signalement/SignalementImportLoader.php, src/Service/Interconnection/Esabora/EsaboraManager.php, src/Service/Signalement/SignalementFileProcessor.php, src/Service/UploadHandlerService.php, src/Twig/AppExtension.php, templates/back/profil/_modal_profil_infos.html.twig, templates/back/signalement/view/visites/visite-item.html.twig, tests/Unit/Factory/FileFactoryTest.php
#3736   
Il faudrait accepter les PDF dans les photos car certaines personnes (les tiers surtout) ont les photos du logement dans des PDF et ne peuvent pas les uploader.
* Dans l'entité File, ajout de pdf dans IMAGE_MIME_TYPES et IMAGE_EXTENSION, et création d'un tableau RESIZABLE_MIME_TYPES sans le pdf
* Dans FileFactory->createInstanceFrom() détermination du fileType en fonction de l'extension (mise à jour de la fonction getFileType et utilisation systématique de celle-ci)
* Ajustements en conséquence de l'affichage  /édition des fichiers en divers endroits de la plateforme
=> [FO - Upload photos] Accepter le format PDF

config/services.yaml, src/Command/SanitizeInterventionsCommand.php, src/Entity/Behaviour/EntitySanitizerInterface.php, src/Entity/Intervention.php, src/EventListener/EntitySanitizerListener.php, src/Repository/InterventionRepository.php, templates/back/signalement/view/visites/visite-item.html.twig
#3839    
Retour de @numew 
> On autorise le HTML dans les description de visite, nous utilisons pour cette description un sanitizer html uniquement à l'affichage (dans twig) il faudrait le faire à l'insertion (comme pour les suivis, voir https://github.com/MTES-MCT/histologe/pull/3587). Autrement cela signifie que l'on est capable de retourner dans le payload GET de l'intervention du contenu malicieux. (il vaut sûrement mieux créer un ticket dédié pour ça)
La description peut être édité contrairement au suivi
* Ajout d'un nouveau listener pour nettoyer une entité qui implémente EntitySanitizerInterface
* Ajout d'une commande pour nettoyer les description des visites
=> [QA] Nettoyage des textes de descriptions des visites

templates/_partials/_modal_localisation.html.twig, templates/_partials/_modal_pick_localisation.html.twig, templates/_partials/_modal_refus_affectation.html.twig, templates/_partials/_modal_refus_signalement.html.twig, templates/_partials/_modal_reopen_signalement.html.twig, templates/_partials/_modal_user_transfer.html.twig
#3883   
Dans les modales de refus de signalement, le bouton d'annulation (qui ferme la modale) n'avait pas de type, et validait donc les formulaires.
Ajout d'un `type="button"` pour éviter ce comportement.
=> [BO - Signalement] Le bouton d'annulation de refus doit fermer la modale sans valider le formulaire

src/Controller/Back/SignalementController.php
#3872
Correction afin que les bouton d'édition du signalement apparaissent pour les SA quelque soit le statut du signalement
=> [BO - Signalement] SA doit pouvoir editer un signalement à tout moment

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, assets/scripts/vanilla/controllers/back_signalement_view/form_upload_documents.js, assets/styles/histologe.scss, src/Controller/Back/SignalementCreateController.php, src/Controller/Back/SignalementFileController.php, src/DataFixtures/Files/NewSignalement.yml, src/Form/SignalementDraftAddressType.php, src/Form/SignalementDraftLogementType.php, src/Form/SignalementDraftSituationType.php, templates/_partials/_modal_duplicate.html.twig, templates/_partials/_modal_upload_files.html.twig, templates/back/signalement/view.html.twig, templates/back/signalement_create/index.html.twig, templates/back/signalement_create/tabs/tab-logement.html.twig, templates/back/signalement_create/tabs/tab-situation.html.twig, tests/Functional/Controller/Back/SignalementCreateControllerTest.php, tests/Functional/Controller/Back/SignalementListControllerTest.php
#3787   
Pour éviter les rechargements de pages intempestifs, on valide le parcours et les fichiers en Ajax
* Quand on change d'onglet, on vérifie si il y a eu des modifications. Si oui, on sauvegarde avant de valider le changement d'onglet. Si il y a erreur pendant l'enregistrement, on reste sur l'onglet.
* Idem pour les bouton Précédent / Suivant
* Idem pour quand on ajoute un fichier
* Idem pour quand on supprime un fichier
* Le bouton finir plus tard redirige vers la liste des brouillons
Pour cela :
- utilisation d'événements attachés à window pour recharger les différents éléments
=> [BO - Formulaire pro] Parcours et gestion des fichiers en Ajax

src/Service/Signalement/SignalementAffectationHelper.php
#3884   
Dans la liste des signalements, le statut d'affectation en attente n'était pas bien retourné, et les nouvelles affectations n'était donc pas mises en avant.
=> [BO - Liste signalements] Mettre en valeur les nouvelles affectations

templates/_partials/signalement/signalement-typecomposition-etage.html.twig
#3892
Les signalement enregistré sur l'étage "SOUSOL" provoque une erreur en prod suite une typo, correction.
=> [QA - BUG] Crash d'affichage de certains signalements

config/app/competences.yaml, tests/Unit/Factory/PartnerFactoryTest.php
#3819    
Ajouter la compétence VISITE par défaut aux partenaire de type OPERATEURS
* Modification de competences.yaml
* ajout d'un test
=> [BO - Partenaires] Ajouter la compétences Visites par défaut aux partenaires Opérateurs visites et travaux

src/Command/Cron/NotifyAndArchiveInactiveAccountCommand.php, tests/Functional/Command/Cron/NotifyAndArchiveInactiveAccountCommandTest.php
#3894
- Ajout d'une option `--force` à la commande `app:notify-and-archive-inactive-accounts` afin de pouvoir tester l'archivage un autre jours que le 15 du mois
- Corrections afin que le tests de la commande fonctionne dans tous les cas (ajout de la prise en compte de la date d'archivage de l'utilisateur des fixtures en attente d'archivage
Ajouter `FEATURE_ARCHIVE_INACTIVE_ACCOUNT=1` dans son `env.test`
=> [Archivage agents] Pouvoir tester la commande à n'importe quelle date

config/packages/prod/monolog.yaml, config/packages/test/monolog.yaml, config/services.yaml, src/EventListener/MaintenanceListener.php, src/EventSubscriber/ApiRequestIdSubscriber.php, src/Service/ApiLogger.php, tests/ApiHelper.php, tests/Functional/Controller/Api/AffectationUpdateControllerTest.php, tests/Functional/Controller/Api/ArreteCreateControllerTest.php, tests/Functional/Controller/Api/SignalementControllerTest.php, tests/Functional/Controller/Api/SignalementFileUpdateControllerTest.php, tests/Functional/Controller/Api/SignalementFileUploadControllerTest.php, tests/Functional/Controller/Api/SuiviCreateControllerTest.php, tests/Functional/Controller/Api/VisiteCreateControllerTest.php, tests/Functional/Controller/Api/VisiteUploadDocumentsControllerTest.php, tests/Functional/Controller/SecurityControllerTest.php, tests/Functional/EventListener/MaintenanceListenerTest.php
#3817
Pour chaque appel à l'API : 
- Ajout d'un identifiant unique pour la requête que l'on retourne en tant que `X-Request-ID` dans le header de la réponse afin que l'utilisateur final puisse nous le transmettre.
- Ajout d'une ligne de log contenant toutes les informations concernant la requête et sa réponse ainsi que l'identifiant unique de la requête, l'id user et le temps d'exécution de la requête. (les données sensibles telles que le mot de passe et le token ne sont pas concervés en log)
Modification du `MaintenanceListener` afin de retourner un message de maintenance au format json pour les appels API si la feature est activé.
1. Configurer le projet en environnements de prod  afin de voir si les logs s'affichent bien en prod
`composer dump-env prod` 
2. Sur les routes API à tester …
=> [API] Améliorer le monitoring des requêtes et réponses

src/Repository/SignalementRepository.php, src/Service/Statistics/GlobalBackAnalyticsProvider.php, tests/Functional/Service/Statistics/GlobalBackAnalyticsProviderTest.php
#3920   
Correction du GlobalBackAnalyticsProvider pour les signalements refusés et archivés
* Correction du GlobalBackAnalyticsProvider
* Ajout d'un test
=> [BO - Stats] Signalements refuses et archives sont à 0

assets/scripts/vanilla/controllers/form_modal_handler.js, src/Controller/Back/SignalementActionController.php, templates/_partials/signalement/add_suivi.html.twig, templates/back/signalement/view/suivis.html.twig, tests/Functional/Controller/Back/SignalementActionControllerTest.php
#3875
- Passage de la soumission du formulaire d'ajout de suivi BO en ajax (via le système `data-ajax-form`)
- En cas de token invalide affichage du message d'erreur et demande de rechargement de la page (sans fermeture de la modale)
- En cas de déconnexion interception de la redirection afin d'afficher une alerte sans fermeture de la modale (généralisé pour toutes les modales utilisant le système `data-ajax-form`)
De cette façon les message ne devrait plus pouvoir être perdu, malgré le rechargement de page nécéssaire.
=> [BO - Signalement] perte de message quand temps d'attente trop long

src/Controller/Back/PartnerController.php, tests/Functional/Controller/PartnerControllerTest.php
#3924
Bug faisant suite à la mise en place des agents multi territoires :
Lors de l'ajout d'un agent si un usager avec le même email existe, un nouvel utilisateur est créé plutôt que d'upgrader le role de l'user existant.
- Correction du problème
- Ajout d'un test permettant de s'assurer qu'un doublon n'est pas généré
Pré-requis à la finalisation de #3854
=> [BUG] Bloquer la création d'un utilisateur avec même email à l'ajout d'un agent

.buildpacks, clamav/data/PDF_Containing_JavaScript.yar, config/packages/clamav.yaml, scalingo.json, src/Controller/Back/BackTerritoryController.php, src/Controller/SignalementController.php, src/Service/Signalement/SignalementFileProcessor.php
#3562    
Ajout de Yara pour détecter les pdf contenant du javascript.
* Utilisation d'un buildpack clamav contenant Yara
* Ajout d'une yara rule
Se procurer un pdf avec du js : https://community.adobe.com/havfw69955/attachments/havfw69955/acrobat-sdk/86720/1/JSCollectionDemo.pdf
Tests à faire sur la reviewApp https://histologe-staging-pr3901.osc-fr1.scalingo.io/
=> [Sécurité - Audit] Faille XSS avec fichier pdf contenant du javascript

templates/back/signalement/view/tabs.html.twig
#3874   
Activation de l'onglet Activité PDLHI même si le RT n'a pas encore validé le signalement
Ajout du nombre de suivi entre parenthèses dans le nom de l'onglet
=> [BO - Signalement] Activation de l'onglet Activité PDLHI même si le RT n'a pas encore validé le signalement

.env, assets/scripts/vanilla/services/maintenance_banner.js, config/packages/twig.yaml, config/services.yaml, templates/header.html.twig
#3933
- Ajout de la var d'env `FEATURE_BANNER_HISTOLOGE` pour pouvoir désactiver la banniere du changement de nom quand on le souhaite
- Correction de l'affichage de la banière qui n'apparaissait plus avec la var `FEATURE_SITES_FACILES=1`
- Déplacement du JS permettant de fermer la banière afin qu'il ne soit plus bloqué
=> [BUG] Fix banner changement de nom

src/Command/CreateApiPartnerUsersCommand.php, src/Manager/UserManager.php, tests/Functional/Command/CreateApiPartnerUsersCommandTest.php
#3808   
Afin de pouvoir utiliser l'API, on donne la possibilité de créer un compte en ligne de commande.
Et pour pouvoir tester sur la plateforme de demo, on donne aussi la possibilité de créer un partenaire de test.
- `make console app="create-api-partner-users --api_email=EMAIL_API --partner_id=ID_PARTNER"`
- `make console app="create-api-partner-users --api_email=EMAIL_API --zip=ZIP --partner_name=NOM_PARTNER --bo_email=EMAIL_AGENT"`
=> [API] Commande pour créer un utilisateur API

migrations/Version20250401111532.php, src/Controller/Back/SignalementController.php, src/Dto/SignalementExport.php, src/Entity/Signalement.php, src/Factory/SignalementExportFactory.php, src/Manager/SignalementManager.php, src/Repository/SignalementRepository.php, src/Service/Signalement/Export/SignalementExportHeader.php, src/Service/Signalement/Export/SignalementExportSelectableColumns.php, tests/Functional/Manager/SignalementManagerTest.php, tests/Functional/Service/Signalement/PhotoHelperTest.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3880
Possibilité de rajouter le "Commentaire de cloture" dans l'export des signalements
* Ajout d'une colonne "com_cloture" sur la table signalement
* Enregistrement de cette colonne pour les signalements existant en base (à partir du suivi correspondant)
* Enregistrement de cette colonne à la cloture pour tous d'un signalement
* Ajout de la colonne sur l'export
make execute-migration name=Version20250401111532 direction=up
=> [BO - Export signalements] Ajouter la colonne commentaire de clôture

templates/back/signalement/view/tabs.html.twig
#3874   
Sur un signalement, on doit se positionner sur l'onglet Situation si le signalement est en attente ou si l'affectation est en attente.
=> [BO - Signalement] Onglet Situation par défaut quand l'affectation est en attente

assets/scripts/vue/components/signalement-view/components/SignalementViewCarto.vue, config/app/csp.yaml, package-lock.json, package.json, public/js/zone_map.js, templates/back/zone/show.html.twig
#3951   
La lib de parsing wkt que nous utilisions utilisait des lib avec vulnérabilités et n'était plus mise à jour. Elle était d'ailleurs un peu lourde pour l'utilisation que nous en avions.
Remplacement par une lib plus simple :
- en Vue pour la page de Cartographie
- en Vanilla pour les pages de visualisation de zone individuelle
=> [QA] Modification de la lib de parsing wkt

assets/scripts/vanilla/controllers/form_visite.js, assets/styles/histologe.scss, migrations/Version20250328162438.php, src/Controller/Back/SignalementVisitesController.php, src/Dto/Request/Signalement/VisiteRequest.php, src/Entity/Intervention.php, src/Manager/InterventionManager.php, templates/back/signalement/view/visites/modals/visites-modal-add.html.twig, templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig, templates/back/signalement/view/visites/visite-item.html.twig, templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig, templates/back/signalement/view/visites/visites-list.html.twig, tests/Functional/Controller/Back/SignalementVisitesControllerTest.php, tests/Functional/Manager/InterventionManagerTest.php
#3742
Ajout de la possibilité de sélectionner un "Opérateur externe" lors de la création/modification d'une visite
* Ajout d'une colonne sur la table intervention pour enregistrer le nom de l'opérateur externe de visite
* Mise au propre du html des modale d'ajout/édition de visites
* Corrections et ajout de tests sur les visites
`make execute-migration name=Version20250328162438 direction=up`
=> [BO - Visites] Intervenant Visite - Externe

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js
#3950    
Quand on reste trop longtemps sur un onglet avant de valider, et qu'on perd le token, on n'est pas redirigé vers l'onglet de connexion, mais on reste bloqué sur "Sauvegarde en cours" sans comprendre ce qui se passe
* Si la réponse n'est pas du json, mais une redirection, bah on redirige
=> [BO - Formulaire pro] Gérer la perte de token

migrations/Version20250317105914.php, migrations/Version20250317145302.php, src/Entity/User.php, tests/Functional/Controller/PartnerControllerTest.php
#3825
Mise en place d'une contrainte unique sur le champs email de la table user afin fin d'éviter quelques problèmes  (le dernier soucis en date étant celui-ci https://sentry.incubateur.net/organizations/betagouv/issues/155480/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=17)
Pour cela il fallait supprimer les utilisateurs dupliqués, j'ai utilisé la requête suivante pour les détecter : 
`SELECT email, COUNT(id) as nombre_occurrences, 
GROUP_CONCAT(id ORDER BY id) as liste_ids, 
GROUP_CONCAT(statut ORDER BY id) as liste_statut, 
GROUP_CONCAT(roles ORDER BY id) as liste_roles 
FROM user GROUP BY email HAVING COUNT(id) > 1 ORDER BY nombre_occurrences DESC, email ASC;
`
J'ai ensuite géré un par un les différent cas : 
- Doublons de …
=> [QA - BUG] Crash login quand deux compte avec même email existe

src/Command/Cron/NotifyAndArchiveInactiveAccountCommand.php, tests/Functional/Command/Cron/NotifyAndArchiveInactiveAccountCommandTest.php
#3985    
La commande rencontrait des arrêts inattendus en raison des effets de bord liés à l’historisation. 
Un traitement en mode batch pourrais éviter ces effets de bord à condition de trouver le bon nombre (ni trop grand et ni trop petit nécessite des tests supplémentaire) 
Le plus efficace est de supprimer l'historisation pour l'instant. 
* Désactivons de l'historisation 
```
make load-data
```
=> [BO] Optimisation de la commande d’archivage des comptes inactifs avec batchs

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, assets/scripts/vanilla/services/component_search_checkbox.js, assets/styles/histologe.scss, migrations/Version20250331141709.php, src/Controller/Back/SignalementCreateController.php, src/DataFixtures/Files/DesordrePrecision.yml, src/Entity/Signalement.php, src/Form/SignalementDraftDesordresType.php, src/Service/Signalement/SignalementBoManager.php, src/Service/Signalement/SignalementDesordresProcessor.php, templates/back/signalement_create/tabs/tab-desordres.html.twig
#3647    
#3646
Gestion de l'onglet Désordres
**A noter : Mathilde est OK pour simplifier les modales d'édition de critères, pour qu'on liste les précisions liées avec des cases à cocher plutôt que de poser des questions avec des réponses multiples.** cf https://github.com/MTES-MCT/histologe/issues/3647#issuecomment-2730210043
Fait : 
Reste à faire : 
* Pour le choix des critères dans les modales Bâtiment et Logement, on a un formType `SignalementDraftDesordresType` qui récupère tous les `desordreCritere` et génère des selectbox à la volée. Ce formType ajoute aussi des checkbox de `desordrePrecision` pour les `desordreCritere` qui en ont plus d'une
* Dans `src/Controller/Back/SignalementCreateController.php` ajout du formType dans editSignalement, ainsi que d'un tableau de criteres …
=> [BO - Formulaire pro] Faire l'onglet Désordres

templates/pdf/signalement.html.twig
#3987    
Description en double
* Suppression de la description la plus récente
`make worker-stop && make worker-start`
=> [PDF signalement] La description occupant y est 2 fois

templates/back/base_bo.html.twig, templates/back/signalement/view.html.twig
#3534   
Ajout d'un bandeau d'information pour les signalements en attente de validation qui ont été créés via le formulaire pro
=> [BO - Signalement] Ajout d'un bandeau d'info quand le signalement a été créé par formulaire pro 

docs/EXPLOITATION.md, templates/back/partner/index.html.twig
#3993
#3994
Ajout d'un bandeau dans la liste des partenaires spécialement pour les RT pour leur demander d'être attentifs aux comptes utilisateurs.
Ajout d'information dans le document `EXPLOITATION.md` pour mettre en place le processus de vérification des accès par l'équipe qui exploite la plateforme.
=> [BO - Partenaires] Ajout de bandeau d'information pour la gestion des accès aux RT

src/Controller/Back/PartnerController.php, src/Entity/User.php, src/Form/UserPartnerType.php, templates/_partials/_modal_user_create_form.html.twig, templates/back/partner/view.html.twig
#4021
- Correction du bug empêchant l'ajout d'un agent sans notification mail
- Correction du feature flipping email de recap (création d'agent, badge "Récap" dans la liste des agents du partenaire)
=> [BUG - Création agent] Impossible de sélectionner "Non" sur "Recevoir les e-mails

README.md, migrations/Version20250428102700.php, src/Entity/Partner.php, src/Form/PartnerType.php, src/Repository/PartnerRepository.php, src/Service/NotificationAndMailSender.php, templates/back/partner/_form.html.twig, templates/back/partner/view.html.twig, templates/back/profil/index.html.twig, templates/front/cgu_agents.html.twig, tests/Functional/Controller/PartnerControllerTest.php
#3984
- Sur la page de profil d'un utilisateur on affiche en plus du nom/prénom et nom du partenaire de ses RT, l'email de contact du partenaire.
- A la création/modification d'un partenaire on demande l'email de contact et si il doit être notifié.
* Ajout du champ `emailNotifiable` sur `Partner`
* Adaptation des contrôle pour la feature "Partenaire non notifiable"
`make execute-migration name=Version20250428102700 direction=up`
=> [BO - Profile] Afficher l'e-mail des RT pour les agents

clamav/data/PDF_Malicious_PDF_JS_Heuristics.yar
#4017    
https://sentry.incubateur.net/organizations/betagouv/issues/169541/?project=61
Détection d'un fichier suspect depuis la MEP
```
select file.filename, created_at, is_suspicious from file where created_at > '2025-04-28 14:35' and filename  like '%.pdf';
```
```
yara -s clamav/data/PDF_Malicious_PDF_JS_Heuristics.yar scripts/local/pdf/photos-fissure-dans-le-mure-1-Metre-680f9a869642c.pdf
```
```
Malicious_PDF_JS_Heuristics scripts/local/pdf/photos-fissure-dans-le-mure-1-Metre-680f9a869642c.pdf
0x0:$pdf_tag1: %PDF-
0x10c3a7:$js_tag: /JS
0xfc2b7:$stream: stream\x0D\x0Aendobj\x0A2 0 obj\x0A<< /Producer (Adobe Acrobat T5)/Creator (Adobe Acrobat Reader (iOS))/CreationDate (D:20250428165105+02'00')/ModDate (D:20250428165105+02'00')>>\x0D\x0Aendobj\x0A3 0 obj\x0A<< /Type /Page/MediaBox [0 …
```
=> [Sécurité - ClamAV] Correction de la règle YARA pour éviter les faux positifs sur les PDF

src/Command/TrimSignalementFieldsCommand.php, src/Entity/Signalement.php, src/Repository/SignalementRepository.php
#4032   
Avec le nouveau formulaire de sécurité d'accès aux fiches de suivi, on vérifie la première lettre du prénom et du nom des usagers.
Dans certains cas, il y a des espaces en premier caractère.
* Migration pour supprimer les espaces de début et fin de chaine
* Suppression des espaces à l'enregistrement
Utilisation base de prod
=> [Signalements] Correction des espaces de début et fin de chaine de données mail, prénom et nom

migrations/Version20250502060650.php, src/Entity/Enum/InterventionType.php, src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php, src/Factory/InterventionFactory.php, src/Repository/SuiviRepository.php, src/Service/Interconnection/Esabora/EsaboraManager.php, src/Service/Intervention/InterventionDescriptionGenerator.php, tests/FixturesHelper.php, tests/Functional/Repository/SuiviRepositoryTest.php, tests/Unit/Factory/Esabora/DossierMessageSISHFactoryTest.php
#4006
#4007    
Évolutions demandées lors du dernier point technico-fonctionnelle
* Ajout d'une migration pour mettre à jour l'opération externe si non ARS
* Remplacer la récupération du dernier suivi partenaire par tous les suivi partenaires
* Mise à jour EsaboraManager pour la gestion de l'opérateur externe
``` 
make create-db
make worker-stop && make worker-start
```
=> [BO - Interconnexion SI-SH] Evolutions suivi et visites

migrations/Version20250505105401.php, src/Command/ImportGridAffectationCommand.php, src/Entity/UserPartner.php, src/Service/Import/GridAffectation/GridAffectationLoader.php, tests/Functional/Service/Import/GridAffectation/GridAffectationLoaderTest.php, tests/Unit/Command/ImportGridAffectationCommandTest.php
#4048    
Prise en compte du multi-territoire afin d'importer la Drome avec 4 utilisateurs qui sont sur un partenaire en Ardèche
* Mise à jour du GridAffectationLoader 
* Ajout d'une contrainte DB d'unicité sur le couple (user_id, partner_id)
```
make load-data
make mysql
>  update territory set is_active = 1 where id = 27;
> exit
```
=> [Import - Grille affectation] Prise en compte du multi territoire

src/Factory/SignalementExportFactory.php, tests/Unit/Factory/SignalementExportFactoryTest.php
#3962
Retrait des balises et caractères HTML des champs "Commentaire de clôture" et "Comm. de la dernière visite" dans l'export des signalement
=> [BO - Export XLS] Nettoyer les champs html (com de cloture, com de visite)

src/Controller/Back/BackStatistiquesController.php, src/Controller/Back/TagController.php, src/Controller/StatistiquesController.php
#3949   
Le ticket d'origine parlait d'ajouter du cache sur les stats publiques. Sur Matomo, il y a entre 10 et 15 visites par jour. Ce n'est pas énorme. Mise en place de cache de 2h.
Mise en place de cache de quelques minutes sur les stats BO. En analysant Matomo, c'est encore moins utile (à peu près le même nombre de visiteur). J'aurais du vérifier avant...
Pas convaincu de l'utilité de cette PR :)
=> [Statistiques] Ajout de cache pour optimiser les chargements

src/DataFixtures/Loader/LoadAffectationData.php, src/Entity/HistoryEntry.php, src/EventListener/AuthentificationHistoryListener.php, src/EventListener/EntityHistoryListener.php, src/EventSubscriber/HistoryEntryFlushSubscriber.php, src/Factory/HistoryEntryFactory.php, src/Manager/HistoryEntryManager.php, src/Service/History/HistoryEntryBuffer.php, tests/Functional/Manager/HistoryEntryManagerTest.php, tests/Unit/Service/History/HistoryEntryBufferTest.php
#4031
Nouvelle version du fonctionnement de l'historisation afin d'accélérer les traitement.
Les entité d'historisation sont enregistré au cours du process et persisté et sauvegardé uniquement en fin de traitement (commande / http request) cela évite les flush intempestif que chaque historisation déclenché jusqu’à présent.
Par exemple sur la commande d'archivage des utilisateur (base de prod) 
- Archivage d'env 3000 user, **durée inférieure à 30 seconde pour le total** (en retirant le flush intermédiaire via `BATCH_SIZE`)
- Dans la version précédente durée **supérieure à 8 minutes pour 50% du même traitement** 
=> [Tech - Historisation] Tentative d'optimisation pour les traitement en boucle

src/Service/Gouv/ProConnect/Model/ProConnectUser.php, src/Service/Gouv/ProConnect/Request/AuthorizationRequest.php, tests/Functional/Controller/Security/ProConnectControllerTest.php, tests/Unit/Service/Gouv/ProConnect/ProConnectAuthenticationTest.php, tests/Unit/Service/Gouv/ProConnect/ProConnectJwtParserTest.php
#4050    
Ne pas récupérer ces infos car il ne seront pas envoyé
* Supprimer la récupérations des données inutiles
```
````
=> [ProConnect] Limiter la récupération aux données essentiels (sub, uid, email) 

Makefile, src/Command/ImportGridAffectationCommand.php, src/Service/Import/GridAffectation/GridAffectationLoader.php
#4058   
Ne pas créer le partenaire quand il existe en base
* Mise à jour `GridAffectationLoader`
```
update territory set is_active = 0 where id=27;
```
=> [Import - Grille affectation] Prise en compte partenaire déjà existant

src/Entity/Suivi.php, src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php, tests/FixturesHelper.php, tests/Unit/Factory/Esabora/DossierMessageSISHFactoryTest.php
#4062   
Suite à #4040 il manque la personne (dont le nom du partenaire) qui a soumis le commentaire et la date 
* Ajout typage Suivi 
* Ajout des infos partenaire via la méthode `getCreatedByLabel` déjà existantes
``` 
make worker-stop && make worker-start
```
=> [BO - Interconnexion SI-SH] Ajouter date et partenaire (nom agent + nom partenaire) au suivi 

src/Form/SuiviSummariesType.php, src/Repository/SignalementRepository.php, tests/Functional/Repository/SignalementRepositoryTest.php
#4043
- Correction de la liste des modèles proposé par l'API Albert (qui ont évolué)
- Correction des requêtes pour récupérer les suivies a résumé (KO depuis la mise en place de l'enum `SignalementStatus`
- Ajout de tests sur ces reqûetes
- Modifier la clé Albert API dans la var d'env `ALBERT_API_KEY` (voir mattermost)
=> [Albert API] Correction des reqûetes et modèles proposés

templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
#4079   
Le premier onglet s’étend vers le bas sans raison et le second n'est pas cliquable
* Fermeture de balise du twig
=> [BUG - FO] Page suivi d'un signalement archivé

src/EventSubscriber/LogoutSubscriber.php, tests/Unit/EventSubscriber/LogoutSubscriberTest.php
#4067    
Appeler la déconnexion ProConnect s'il a une session ProConnect en cours
* Vérifier l'existence de la session ProConnect 
Test avec mock 
```
```
Pour TNR avec le vrai service mettre à jour les variables d'environnements
=> [ProConnect] Déconnexion - Ne pas appeler ProConnect pour un utilisateur ProConnect connecté via login/mot de passe

assets/scripts/vue/components/signalement-form/TheSignalementAppForm.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue, assets/scripts/vue/components/signalement-form/store.ts, src/Controller/SignalementController.php, src/Repository/SignalementRepository.php, src/Service/Signalement/SignalementDuplicateChecker.php, tests/Functional/Controller/SignalementControllerTest.php, tests/Unit/Service/Signalement/SignalementDuplicateCheckerTest.php
#3815   
Lorsqu'un signalement est en doublon depuis moins de 3 mois (90 jours), on modifie la modale pour ne pas permettre de créer de nouveau signalement.
* Calcul du nombre de jour de différence entre aujourd'hui et la date de création
* Ajustement de l'algo de calcul de doublon pour les villes avec arrondissements qui n'étaient pas considérées
=> [FO - Signalement] Bloquage de la création de signalement quand il existe un doublon de moins de 3 mois

migrations/Version20250506093843.php, src/Command/Cron/AbstractSynchronizeEsaboraCommand.php, src/Command/Cron/SynchronizeEsaboraSCHSCommand.php, src/Command/Cron/SynchronizeEsaboraSISHCommand.php, src/Command/Cron/SynchronizeInterventionSISHCommand.php, src/Command/PushEsaboraDossierCommand.php, src/Entity/Suivi.php, src/Manager/JobEventManager.php, src/Repository/AffectationRepository.php, src/Service/Interconnection/Esabora/AbstractEsaboraService.php, src/Service/Interconnection/Esabora/EsaboraManager.php, src/Service/Interconnection/Esabora/EsaboraSCHSService.php, src/Service/Interconnection/Esabora/EsaboraSISHService.php, src/Service/Interconnection/Esabora/EsaboraServiceInterface.php, src/Service/Interconnection/Esabora/Handler/InterventionArreteServiceHandler.php, src/Service/Interconnection/Esabora/Handler/InterventionSISHHandlerInterface.php, src/Service/Interconnection/Esabora/Handler/InterventionVisiteServiceHandler.php, src/Service/Interconnection/JobEventHttpClient.php, tests/Functional/Manager/Esabora/EsaboraManagerTest.php, tests/Functional/Repository/AffectationRepositoryTest.php, tests/Unit/Command/Cron/SynchronizeEsaboraSCHSCommandTest.php, tests/Unit/Command/Cron/SynchronizeEsaboraSISHCommandTest.php, tests/Unit/Command/Cron/SynchronizeInterventionSISHCommandTest.php, tests/Unit/Command/PushEsaboraDossierCommandTest.php, tests/Unit/Service/Esabora/EsaboraManagerTest.php, tests/Unit/Service/Esabora/EsaboraSCHSServiceTest.php, tests/Unit/Service/Esabora/EsaboraSISHServiceTest.php, tests/Unit/Service/Esabora/Handler/InterventionArreteServiceHandlerTest.php, tests/Unit/Service/Esabora/Handler/InterventionVisiteServiceHandlerTest.php
#4051
Optimisation des commandes de synchronisation Esabora via la réduction du nombre de requêtes et du nombre de flush opérés. 
La synchro SISH tourne actuellement sur un peu plus de 7000 affectations 
Test en condition réelle sur les 1000 première  : durée environ 15 minutes. (dont 99% de temps appel API)
Test en condition réelle sur les 1000 première en version précédente  : durée environ 23 minutes. (+50%)
Les performances s’applique sur les différente commandes : 
`app:sync-esabora-sish`
`app:sync-esabora-schs`
`app:sync-esabora-sish-intervention`
Ajout d'un index au passage, permettant de faire passer la requête `findExistingEventsForSCHS` de quelque seconde a quelque micro secondes
`make execute-migration name=Version20250506093843 direction=up`
=> [Tech - Perf] Synchro Esabora 

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, src/Controller/Back/SignalementCreateController.php, src/DataFixtures/Files/NewSignalement.yml, tests/Functional/Controller/Back/SignalementCreateControllerTest.php
#4077   
APrès la validation d'un brouillon de signalement par un RT, la règle de redirection change, on redirige directement sur le signalement créé.
Les agents sont toujours redirigés vers la liste des brouillons
* Changement de la redirection dans le controller pour les RT
* Ajout d'une fixture de brouillon de signalement fait par un agent
* Ajout de test
=> [BO - Formulaire pro] Modifier redirection pour les RT

.github/workflows/main.yml, src/Command/Cron/RemindInactiveUserCommand.php, src/Controller/Back/BackArchivedUsersController.php, tests/Functional/Command/Cron/RemindInactiveUserCommandTest.php, tests/Functional/Controller/BackArchivedUsersControllerTest.php
#4083 
#4084
- Fix d'un bug au désarchivage d'utilisateur (qui fait suite à l'ajout d'une containte unique `unique_user_partner` en base)
- Désactivation de la commande `app:remind-inactive-user` pour  éviter de dépasser les limitation d'envoi de mail sur staging
=> [BUG - BO] Désarchivage d'un user / [Tech] Staging : désactiver cron de rappel pour les utilisateurs inactifs

tests/Functional/Controller/SignalementControllerTest.php
#4089   
Authentification explicite d’un usager : correction de la régression liée à l’envoi de message, raison initiale de l’existence du test.
* Rollback sur la version 3.2.1 et ajout d'une authentification explicite
=> [TECH - CI] Corriger le test de soumission de message depuis la fiche signalement FO

src/Service/Signalement/SearchFilter.php, tests/Functional/Controller/Back/SignalementListControllerTest.php
#4104
La recherche de signalements sur des plage de date de création de signalement ET de date du dernier suivi ne fonctionnait pas correctement. En effet la même fonction gérant les deux date avec les même paramètre nommé, seule la date de dernier suivi etait prise en compte pour les deux filtres.
Correction de la fonction et ajout d'un tests
=> [BUG - Filtre Signalement] La date de dernier suivi écrase la date de dépot

src/Security/Voter/FileVoter.php
#4107    
Si je vais sur un signalement en attente de validation en tant qu'admin, je peux ajouter un fichier.
Par contre, quand je l'édite, l'accès est refusé.
Donc quand je sélectionne le type de document, celui-ci n'est pas enregistré.
C'est lié au voter FILE_EDIT qui vérifie le statut du signalement.
* Modification du FileVoter
=> [BO - Signalement] Edition type fichier sur Signalement en attente de validation

src/Dto/Api/Response/SignalementResponse.php, src/Dto/Request/Signalement/InformationsLogementRequest.php, src/Factory/Api/SignalementResponseFactory.php, src/Manager/SignalementManager.php, templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig, templates/back/signalement/view/information/information-logement.html.twig, templates/pdf/signalement.html.twig
#3895   
Dans le nouveau formulaire BO, on a ajouté le champ Logement vacant.
Mais il n'était pas affiché dans le BO (ni éditable), pas envoyé via l'API, pas affiché dans les PDFs
=> [BO - Signalement] Ajout du champ Logement vacant

templates/back/profil/_modal_profil_password.html.twig, templates/security/login.html.twig, templates/security/reset_password_new.html.twig
#3978   
Le bouton qui permet d'afficher ou masquer la saisie de mot de passe n'était pas accessible via tabulation.
=> [FO - Mot de passe] Tabulation sur le bouton d'affichage du mot de passe

src/EventSubscriber/LogoutSubscriber.php, tests/Unit/EventSubscriber/LogoutSubscriberTest.php
#4117 
Bien que l'erreur soit intercepté, il faudrait vérifier si c'est un usager avant de vérifier si c'est un utilisateur proconnect.
Traitement en dehors des bloc try/catch
* Ajout condition subscriber
* Mise à jour test
tail -f var/log/dev.log | grep "app."
=> [Logout - QA] Gestion deconnexion Usager

src/Service/Import/GridAffectation/GridAffectationLoader.php, tests/Functional/Service/Import/GridAffectation/GridAffectationLoaderTest.php
#4114 
#4115
Lors de l'import d'une grille la méthode de pré validation bloquait sur les utilisateurs déjà existants, alors que la méthode d'insertion à déjà été modifié pour les gérer en multi-territoire. C'est corrigé. Au passage ajout de notification mail pour les cas de multi territoire
Se mettre sur une base de prod
=> [Ouverture territoire - Import grille] Ignorer les utilisateurs existants lors de la phase de validation

migrations/Version20250516083935.php, src/Command/InitFilesExtensionCommand.php, src/Controller/Api/SignalementFileUpdateController.php, src/Controller/Back/SignalementFileController.php, src/Controller/SignalementFileController.php, src/Entity/File.php, src/Entity/Signalement.php, src/Factory/FileFactory.php, src/Manager/SuiviManager.php, src/Repository/FileRepository.php, templates/back/signalement/view/photos-documents.html.twig, templates/back/signalement/view/visites/visite-item.html.twig, templates/base.html.twig, templates/front/_partials/_suivi_signalement_tab_infos.html.twig, templates/pdf/signalement.html.twig, tests/FixturesHelper.php, tests/Functional/Controller/Api/SignalementFileUpdateControllerTest.php, tests/Functional/Manager/FileManagerTest.php, tests/Unit/Factory/FileFactoryTest.php
#3843   
Afin de remplacer l'attribut `fileType` de l'entité `File`, mise en place de l'attribut extension qui doit permettre de séparer les fichiers selon l'endroit où on souhaite l'afficher.
Dans cette PR, le fonctionnement métier ne doit pas changer.
* Ajout d'une colonne extension
* Remplacement de toutes les comparaisons sur le `fileType` par `isTypePhoto` ou `isTypeDocument`
* Conservation de `fileType` pour l'instant, au cas où un retour arrière est nécessaire
* Création d'une commande qui initialise la colonne `extension` pour les fichiers
`make execute-migration name=Version20250516083935 direction=up`
=> [Fichiers] Ajout d'un attribut extension pour remplacer le fileType à terme

templates/back/signalement/view/header.html.twig
#4131   
Une fois qu'un signalement créé depuis le BO est validé, l'information n'apparaît plus nulle part ce qui peut créer de la confusion, surtout si on a des signalements avec peu d'info
Il faudrait ajouter l'info sur la fiche
Je propose de le mettre dans l'en-tête `Dossier déposé le : dd/mm/yyyy depuis le formulaire pro` | `Dossier déposé le : dd/mm/yyyy depuis le formulaire usager` | `Dossier déposé le : dd/mm/yyyy par import`
* Modification du template twig
=> [BO - Signalement] Ajouter l'info création via BO sur la fiche

templates/back/signalement_drafts/need_validation_card.html.twig
#4129   
Je suis agent
J'ai créé un signalement depuis le BO
Il apparaît dans ma liste de brouillon comme en attente de validation
Quand je passe ma souris dessus, il y a un effet hover et le fond devient plus foncé
Il faudrait retirer ce hover parce que ça donne l'impression qu'il va se passer quelque chose si on clique sur le signalement, alors que non
* Suppression d'une classe css dans le template
=> [BO - Mes brouillons] Enlever le hover sur les signalements en attente de validation

src/Form/SignalementDraftCoordonneesType.php, templates/back/signalement_create/tabs/tab-coordonnees.html.twig
#4128   
dans l'onglet coordonnées
Il faut ajouter le champ Civilité avec bouton radio Madame et Monsieur
* Modification du formType et du template twig
=> [BO - Formulaire pro - onglet coordonnées] Ajouter la civilité pour l'occupant

assets/scripts/vanilla/controllers/form_visite.js
#4144   
Si je veux reprogrammer une visite existante (juste changer la date) qui est sur un opérateur externe, on me dit que c'est impossible car l'opérateur a déjà une visite. 
* Changement du js
=> [BO - Visite] Reprogrammation sur opérateur externe impossible

src/Controller/Back/SignalementController.php, src/Messenger/MessageHandler/PdfExportMessageHandler.php, src/Repository/InterventionRepository.php, templates/back/signalement/view/visites/visites-list.html.twig, templates/pdf/signalement.html.twig, tests/Unit/Service/Signalement/Export/SignalementExportPdfTest.php
#4085   
Réorganisation des visites par date
=> [BO - Visites] Réorganisation par date de visite

config/routes/scheb_2fa.yaml, src/Controller/Security/ProConnectController.php, src/Entity/User.php
#4147   
Ne plus proposer le 2FA au super admin si l’authentification se fait via ProConnect
* Mise à jour condition 2FA
Donner le rôle ROLE_ADMIN à proconnect@signal-logement.fr
Définir un mot de passe pour proconnect@signal-logement.fr
```
FEATURE_2FA_EMAIL_ENABLED=1
```
=> [BO - Auth] Ne pas proposer le 2FA pour un utilisateur ProConnect

migrations/Version20250527143737.php, src/Manager/AffectationManager.php, src/Service/Interconnection/Esabora/EsaboraManager.php
#4157
* Ajout d'une migration pour supprimer ces suivis vides
* Dans le cas d'un refus d'affectation via esabora retrait de l'appel au `dispatchAffectationAnsweredEvent` générant le suivi problèmatique
- Se mettre sur un copie base de prod
- Commenter le passage qui bloque les appel à esabora en local (chercher `url must contain "signal_logement_wiremock" when on localhost.`)
- Prendre un signalement avec un suivi vide (avec `SELECT s.id, s.created_at, s.is_public, s.type, s.context, si.id, si.uuid FROM `suivi` s inner join signalement si ON s.signalement_id = si.id where s.description = '' and type =1 ORDER BY s.created_at DESC; `)
=> [BUG - Suivi] Voir pourquoi on crée des suivi TYPE_AUTO complétement vide

src/Factory/Api/SignalementResponseFactory.php
#4169   
Correction de la gestion des étages vides dans l'API
=> [QA] Correction de la gestion des étages vides dans l'API

src/EventSubscriber/SignalementViewedSubscriber.php, src/Service/Signalement/SignalementBoManager.php
#4180
#4185
- Lorsqu'un utilisateur FO n'est pas lié a un user (cas d'occupant sans email), on ne rentre pas dans le process manquant les suivi comme lu
- Transformation du champ "MontantAllocation" en int avant de l’injecter dans l'objet signalement pour éviter erreur de typage
=> [QA] TypeError: "App\Repository\NotificationRepository::findUnseenNotificationsBy()

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js
#4171
Afin qu’après une soumission de suivi depuis le BO, la modale ne garde pas les informations préalablement soumise, on réinitialise ses valeurs à sa première ouverture
=> [BUG - BO] réinitialiser modale aprés soumission d'un suivi

src/Command/DeleteUselessSuivisAndNotifications.php, src/Repository/NotificationRepository.php, src/Repository/SuiviRepository.php
#4184   
Suite à un souci de décalage de dates UTC, des suivis (et notifications associées) ont été créés en trop.
* Création d'une commande qui permet de les supprimer
=> [Suivis] Commande pour supprimer les suivis et notifications créés en trop

src/Service/Interconnection/Idoss/IdossService.php, templates/back/signalement/view/header.html.twig
#4190 
#4191 
- Correction du lien vers la page des signalement filtré du bouton "signalement à la même adresse" : Ajout du paramètre `isImported=oui`
- Ajout d'un bloc try catch sur l'appel à `getFilePath` dans la fonction `getFilesPayload` afin de ne plus crasher la commande `app:synchronize-idoss` quand un fichier n'existe pas
=> [BUG] Filtre détection doublon adresse / Synchro IDOSS en cas de fichier inexistant

assets/scripts/vanilla/controllers/back_partner_view/form_partner.js, assets/scripts/vanilla/controllers/back_profil_edit_email/back_profil_edit_email.js
#4192   
Nous nous servons de l'événement `dsfr.conceal` pour détecter les fermetures de modales DSFR.
Historiquement, cet événement était envoyé en ouverture de page.
Ce n'est plus le cas depuis la mise à jour DSFR 1.13.1.
Dans la page Partenaire, pour la modale d'ajout d'utilisateur, nous nous en servons pour mettre à jour le formulaire.
* Modification de la méthode pour mettre à jour le formulaire d'ajout d'utilisateur
* Modification de méthode dans la page de profil utilisateur (c'est plus par sécurité, je n'ai pas l'impression que ça posait souci)
* Rien d'autre : normalement les autres fois où cet événement est utilisé, on n'a pas le même souci
=> [BO - Partenaire] Correction de l'ouverture de la modale d'ajout d'utilisateur

src/Controller/SignalementController.php, src/Repository/SuiviRepository.php
#4194   
Sur la carte Accès rapide du nouveau dashboard usager, il ne faudrait pas afficher les messages usagers
car c'est un peu bizarre en termes de parcours qu'on mette ton propre message en avant comme "nouveau"
* Modification de la requête pour exclure un suivi créé par l'usager du dernier suivi public retourné
=> [Fo - Suivi usager] Ne pas afficher les messages de l'usager sur la carte du dashboard

src/Security/Authenticator/CodeSuiviLoginAuthenticator.php, tests/Unit/Security/Authenticator/CodeSuiviLoginAuthenticatorTest.php
#4202
Le login utilisateur ne fonctionnait pas si la première lettre du nom ou prénom était accentué.
- Correction de ce cas d'usage
- Mise en place d'un controle sans prise en compte de l'accentuation (ex : on peux mettre "e" quand le prénom commence par "é")
- Ajout de tests
=> [BUG - FO] Login usager carractère accentué

src/Controller/Back/SignalementCreateController.php, src/Service/Signalement/ReferenceGenerator.php, src/Service/Signalement/SignalementBoManager.php
#4203   
Eviter de créer des références pour les signalements en brouillon
* Enregistrement d'une référence temporaire lorsque le brouillon est créé
* Enregistrement de la vraie référence au moment de la validation
=> [BO - Formulaire pro] Eviter de créer des références pour les signalements en brouillon

.github/workflows/playwright.yml, .gitignore, Makefile, tests/Functional/Service/Mailer/SummaryMailServiceTest.php, tests/e2e/package-lock.json, tests/e2e/package.json, tests/e2e/playwright.config.ts, tests/e2e/tests/basic.spec.ts
#3036   
Test d'utilisation de Playwright à la place de Cypress pour les tests e2e.
https://playwright.dev/docs/codegen#recording-a-test
Objectif : avoir un deuxième job non-bloquant qui fait les tests e2e dans la CI.
Ajout des fichiers :
* job GitHub Actions `.github/workflows/playwright.yml`
* Reprise de toutes les variables d'environnement, et installation complète du système
* configuration de playwright à la racine `tests/e2e/playwright.config.ts`
* description des tests `tests/e2e/tests/basic.spec.ts`
* installation npm indépendante pour ne pas venir court-circuiter les fonctionnalités actuelles standards `tests/e2e/package.json`
- cd `tests/e2e`
- `npx playwright install`
- `npx playwright install-deps`
- `npm i -D @playwright/test`
- `make test-e2e` (=> `npx playwright test`) …
=> [Tests - E2E] Initialisation de Playwright

tests/Functional/Service/Mailer/SummaryMailServiceTest.php, tests/Unit/Service/Gouv/Rial/Request/RialSearchLocauxParamsTest.php, tests/Unit/Service/Gouv/Rial/RialServiceTest.php, tools/wiremock/postman/proconnect.mock.postman_collection.json, tools/wiremock/src/Mock/ProConnect/ProConnectMock.php, tools/wiremock/src/Resources/ProConnect/openid-configuration.json
#4222    
Spécifier une route distincte pour éviter le conflit `/proconnect/token`
* Mise à jour de la route
* Correction namespace test 
```
```
=> [QA] Mock ProConnect KO - conflit avec RIAL

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, assets/scripts/vanilla/services/component/component_search_address.js, src/Form/SignalementDraftAddressType.php, templates/back/signalement_create/tabs/tab-adresse.html.twig
#4120   
Dans le formulaire pro, permettre de filtrer sur les territoires de l'utliisateur en cours
* Si l'utilisateur n'a qu'un territoire : champ caché avec le territoire de l'utilisateur
* Si multiterritoire : liste déroulante avec les territoires de l'utilisateur
* Si super admin : liste déroulante avec tous les territoires
Finalement, j'ai mis un double filtre :
- d'une part, au moment de la requête : utiliser le nom du département plutôt que le numéro, parce que pour certains départements (le 01), ça ne filtrait pas bien
- d'autre part, au moment de l'affichage : utiliser le numéro du département pour filtrer les résultats parce que parfois, il restait des résultats non voulus 
=> [BO - Formulaire pro] Filtre des adresses par territoires de l'utilisateur

src/Controller/Back/SignalementCreateController.php
#4221    
Correction lorsqu'on crée un signalement via le formulaire pro, dans lequel les éléments d'interconnexion n'étaient pas envoyées.
=> [BO - Formulaire pro] Envoi des infos d'interconnexion lors de la validation des affectations

src/Security/Authenticator/CodeSuiviLoginAuthenticator.php, tests/Unit/Security/Authenticator/CodeSuiviLoginAuthenticatorTest.php
#4226    
Manque la date de connexion pour l'usager
* Mise à jour `CodeSuiviLoginAuthenticator`
=> [Tech] La date de dernière connexion reste à null pour une connexion usager

src/Manager/SuiviManager.php, templates/back/signalement/view/photos-album.html.twig
#4242   
Correction création de suivi quand on ajoute une photo de visite non liée à une visite
=> [QA] Correction création de suivi quand on ajoute une photo de visite non liée à une visite

src/Controller/Back/NotificationController.php, src/Service/DashboardWidget/WidgetDataManagerCache.php
#4239   
Malgré une suppression des notifications, le widget Nouveau suivi n'était pas remis à 0 sur le dashboard.
--> en cause, une clé comprenant le zip concerné dans la création du cache, mais une clé sans zip dans la suppression du cache
* Ajout du tableau de territoires dans la clé de suppression du cache
* Modification de la fonction `invalidateCacheForUser` pour prendre en compte ces zip de territoire. (à noter que s'il y a plusieurs territoires, il faut supprimer le cache de tous les territoires ensemble + le cache de chacun des territoires, car on peut choisir le territoire côté dashboard, mais pas côté Notifications)
=> [BO - Dashboard] Pas de remise à 0 malgré suppression des notifications

scripts/sync-db.sh
#4255
Suite à la derniere maj de la cli de scalingo, l'affichage des addons a changé avec un nouveau séparateur `│` à la place de ` |`
* Remplacer le nouveau séparateur par l'ancien |
`make scalingo-update-cli`
`echo $addon_id`
```
=> [QA] Mise à jour du script de synchro de base de données

src/Command/PushIdossDossierCommand.php, src/Repository/AffectationRepository.php, tests/Unit/Command/PushIdossDossierCommandTest.php
#4257    
Ajout d'une commande PushIdossDossierCommand et de son test associé
Commande qui prend en argument l'uuid d'un signalement
* Création de la commande, de la requête et du fichier de test
=> [QA] Faire une commande pour pousser des dossiers iDoss en cas de pb

config/app/csp.yaml, src/Controller/Security/CspReportController.php, src/EventListener/ContentSecurityPolicyListener.php, templates/back/dashboard/index.html.twig, tests/Functional/Controller/Security/CspReportControllerTest.php
#2692   
Mettre en place une route qui capte les violations de CSP et les envoie à Sentry
* Changement de `ContentSecurityPolicyListener` pour inclure une `report-uri` définie dans le `csp.yaml`
* Création du controller
Désactiver uBlock, ou vérifier qu'il n'y a pas le paramètre `no-csp-reports: * true`
`<script>alert("violation CSP !");</script>`)
=> [QA] Faire du reporting d'erreurs CSP

assets/json/Signalement/desordres_profile_occupant.json, assets/json/Signalement/desordres_profile_tiers.json, assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_service_secours.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/scripts/vue/components/signalement-form/components/SignalementFormButton.vue, assets/scripts/vue/components/signalement-form/components/SignalementFormScreen.vue, assets/scripts/vue/components/signalement-form/store.ts, assets/styles/histologe.scss, config/packages/dev/web_profiler.yaml
#1674   
Ajouter un bouton `Finir plus tard` en bas de chaque page, à partir de la création du brouillon, (soit la page suivant la page coordonnées du déclarant, pour s'assurer que le check des doublons a déjà été fait)
Au clic sur le bouton par l usager, on envoie à l'usager un mail, le même que lorsque un doublon de brouillon même adresse+même déclarant est identifié. Puis l'usager est envoyé sur la page "un mail vous a été envoyé"
Petit changement css pour qu'en mobile les boutons suivant/précédent soit en pleine largeur
* Ajout d'un composant bouton "Finir plus tard" sur tous les écrans concernés pour tous les profils
* Modifications css pour la disposition des boutons du footer
* Modification du SignalementFormScreen pour créer une nouvelle action `finishLater`
=> [Formulaire usager] Enregistrer ma progression / finir plus tard

src/Form/SearchPartnerType.php, src/Repository/PartnerRepository.php, src/Service/ListFilters/SearchPartner.php, templates/back/partner/index.html.twig, tests/Functional/Repository/PartnerRepositoryTest.php
#4216   
Ajout filtre d'interconnection pour Super Admins dans la liste des partenaires du BO
=> [BO - Partenaires] Ajout filtre d'interconnection pour Super Admins

templates/back/signalement/view/suivis.html.twig
#4288   
> sur la page du signalement, je propose de mettre l'accusé de lecture non pas sous le nom du redacteur du suivi mais sous le Tag Visible par l usager, à droite
* Changement du twig
=> [Suivis - Accusés de lecture] BO - déplacer le badge

src/Controller/Security/SecurityController.php, src/Messenger/Message/Idoss/DossierMessage.php
#4267   
Correction d'erreurs Sentry pour des appels de fonction avec des chaines null
=> [QA] Correction appel de fonction avec des chaines null

src/Form/SearchPartnerType.php, src/Repository/PartnerRepository.php, src/Service/ListFilters/SearchPartner.php, templates/back/partner/index.html.twig, templates/form/dsfr_theme.html.twig, tests/Functional/Repository/PartnerRepositoryTest.php
#4284    
Ajouter un filtre "Connexions externes" : liste déroulante avec choix unique avec les valeurs :
- Tous les partenaires (par défaut)
- Avec connexion externe
- Sans connexion externe
Filtre sur les partenaires avec un interfaçage actif
* FormType
* ParnerRepository
* twig
* tests
=> [BO - Partenaires] Ajouter filtre interfaçage

assets/scripts/vue/components/signalement-view/TheSignalementAppList.vue, assets/scripts/vue/components/signalement-view/TheSignalementCartoApp.vue, assets/scripts/vue/components/signalement-view/components/SignalementViewFilters.vue, assets/scripts/vue/components/signalement-view/interfaces/filters.ts, assets/scripts/vue/components/signalement-view/store.ts, src/Controller/Back/CartographieController.php, src/Dto/Request/Signalement/SignalementSearchQuery.php, tests/Functional/Controller/CartographieControllerTest.php, tests/Unit/Dto/Request/Signalement/SignalementSearchQueryTest.php
#4283   
Je propose que le label cliquable permette d'ajouter le tracé de toutes les zones du territoire, indépendamment de s'il y a des signalements dans ces zones ou non
On peut leur mettre un label cliquable "Afficher les zones du territoire" au même titre qu'on "Afficher les signalements importés" / "mes affectations" pour les RT
* Ajout d'un bouton toggle dans la carto
* Adaptation de CartographieController pour prendre en compte ce bouton si des zones n'ont pas déjà été choisies
=> [BO - Zones / carto] Rendre les zones visibles

src/Command/Cron/AskFeedbackUsagerCommand.php, src/Entity/Suivi.php, src/Repository/SuiviRepository.php, src/Service/Signalement/SearchFilter.php, tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php, tests/Functional/Repository/SuiviRepositoryTest.php
#4319    
Suivi auto n'est plus égale à relance auto aujourd'hui car elle comprend des suivi de relance de visite du coup ajouter un filtre pour ne garder que les suivi de relance automatique.
* Mise à jour requête en ajoutant un filtre utilisé pour widget, liste et commande
* Mise à jour commande 
`make load-data`
` make clear-pool pool"=--all"`
cette fiche n'a que 2 suivi de relance et 1 suivi de visite
=> [BO - Signalement] Mise à jour requête widget et listing relance auto

src/Controller/Back/PartnerController.php, src/Entity/Partner.php, src/Form/PartnerType.php, templates/back/partner/_form.html.twig
#4332    
Lorsqu'on éditait un partenaire et mettait un nom vide, on avait une erreur 500.
* Utilisation du formtype pour éviter l'erreur 500 et avoir un affichage propre
=> [BO - Partenaire] Bloquer les noms vides sans avoir d'erreur 500

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, src/Form/SignalementDraftDesordresType.php, src/Service/Signalement/SignalementBoManager.php, templates/back/signalement_create/tabs/tab-desordres.html.twig
#4344   
Dans le formulaire pro, ajout des précisions de hauteur lorsque le plafond est trop bas
=> [BO - Formulaire Pro] Ajout des précisions de hauteur lorsque le plafond est trop bas

src/Security/Provider/SignalementUserProvider.php, tests/Unit/Security/Provider/SignalementUserProviderTest.php
#4353
Lors de l'authentification sur la page de suivi usager, on allait chercher le `User` avec l'adressse e-mail, mais elle peut être modifiée après la création, et le `User` récupéré n'est donc pas fiable.
Pour plus de fiabilité, on récupère en priorité via la liaison `getSignalementUsager`.
Cela permet notamment de mieux gérer les suivis qui ont été vus, car les notifications sont liées via `getSignalementUsager`.
=> [Suivi usager] Authentifier en priorité les usagers avec getSignalementUsager

templates/back/signalement/view/suivis.html.twig, templates/front/_partials/_suivi_signalement_tab_suivi.html.twig, templates/front/suivi_signalement_messages.html.twig, templates/pdf/signalement.html.twig
#4354
#4355
Correction de l'affichage de l'expéditeur quand usager avec compte pro
* Dans fiche signalement
* Dans page de suivi de signalement actuelle et à venir
* Dans pdf
`make worker-stop && make worker-start` (pour l'export pdf)
=> [Suivis] Correction de l'affichage de l'expéditeur quand usager avec compte pro

src/Controller/SignalementController.php, src/Dto/SuiviCategory.php, src/Service/SuiviCategorizerService.php, templates/front/_partials/_suivi_signalement_card.html.twig, templates/front/suivi_signalement_dashboard.html.twig, templates/front/suivi_signalement_messages.html.twig, tests/Functional/Controller/SignalementControllerTest.php
#4380
#4381
#4382
#4383
- Ajout d'une description "Si nécessaire, vous pouvez envoyer un dernier message avant le dd/mm/yyyy." sur la carte indiquant la fermeture du signalement
- Remplacement du titre "Suivre les échanges" par "Suivre vos échanges"
- En cas de déclarant occupant masquer le champ "Personne occupant le logement"
- Même quand le signalement est fermé/refusé/archivé la carte de l'accueil mène vers la page messagerie
=> [FO - Espace suivi usager] corrections

templates/pdf/base_pdf.html.twig, templates/pdf/signalement.html.twig
#4391
Modification du template de l'export PDF pour : 
- Que les tableaux ne dépasse jamais 100% de la largeur (même dans le cas de très long lien par exemple)
- Que le contenu des cellules soient alignés en haut (pour voir qui à déposé le suivi dés le départ en cas de long suivi)
=> [BO - Export PDF] Problème formatage Suivi tronquée

src/Controller/Back/NotificationController.php, templates/back/notifications/index.html.twig, tests/Functional/Controller/NotificationControllerTest.php
#4302
Sur la page de notification, préserver les filtre (ordre de tri, page) après les actions : 
- Marquer comme lu par lot
- Marque tout comme lu
- Suppression unitaire
- Suppression par lot
Les filtres son supprimés après l'action de suppression complète car ca ne fait pas sens de les garder.
=> [Notification - filtre] Conserver le tri selectionne

src/Service/Interconnection/Esabora/EsaboraManager.php, tests/Functional/Manager/Esabora/EsaboraManagerTest.php, tests/Unit/Service/Esabora/EsaboraManagerTest.php
#4420    
Mise à jour des messages de suivi automatique d'Esabora
* Mettre la mention par juste après le statut
```
```
=> [Interconnexion - SISH] Mise à jour message suivi

docs/API.md
#4424    
* Mise à jour des liens de doc d'API
=> [Doc] Corriger les lien vers la doc API

migrations/Version20250731142328.php
#4436
Migration pour corriger les statut d'affectation erronées "CLOSED" au lieu de "FERME". 
Elles sont toutes sur des signalements au statuts archivé mais ca provoque des crash lorsqu'elle sont hydratés (ex parcours de toutes les affectation du partenaire sur le controller `back_signalement_reopen`. Ou plus simplement sur la page SA des signalements archivés.
Je n'ai pas trouvé d’où provenait ce statu en erreur
=> [QA - BUG] Affectation avec le statut "CLOSED" au lieu de "FERME"

src/Controller/SignalementFileController.php
#4441
Ajout du feature flipping sur la redirection après surpression d'un document par l'usager afin qu'il n'envoie pas sur une page inexistante.
`FEATURE_SUIVI_ACTION=0`
=> [BUG - FO] Lien vers la route front_suivi_signalement_documents inaccessible

assets/scripts/vanilla/services/bo_modales.js, assets/scripts/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue, assets/styles/histologe.scss, migrations/Version20250801133849.php, src/Controller/Back/PartnerController.php, src/Controller/Back/PopNotificationController.php, src/Controller/Back/SubscriptionsChoiceController.php, src/DataFixtures/Files/Suivi.yml, src/DataFixtures/Loader/LoadAffectationData.php, src/Entity/User.php, src/Factory/UserFactory.php, src/Repository/UserSignalementSubscriptionRepository.php, templates/_partials/_modal_subscriptions_choice.twig, templates/back/base_bo.html.twig, tests/Functional/Controller/Back/SignalementListControllerTest.php, tests/Functional/Controller/Back/SubscriptionsChoiceControllerTest.php, tests/Functional/Service/Notification/NotificationCounterTest.php, tests/Unit/Factory/UserFactoryTest.php
#4341
Création de la modale de choix initial pour les abonnements aux signalements
- Choix : Tous les dossier -> Ne change rien.
- Choix : Dossier avec action -> Supprime les abonnement "legacy" pour les signalement sans suivi de l'user. 
Dans les deux cas : enregistre le choix comme effectué pour ne plus affiché la modale
`make execute-migration name=Version20250801133849 direction=up`
=> [BO - Signalements] Gestion par agent : Modale de choix initial - suivre tous les dossier / dossier avec interaction

templates/_partials/_modal_file_delete.html.twig, templates/front/_partials/_suivi_signalement_card.html.twig, templates/front/suivi_signalement_dashboard.html.twig, templates/front/suivi_signalement_documents.html.twig, templates/front/suivi_signalement_dossier.html.twig
#4383
#4454
#4455 
#4458
#4383 la tuile "Validation en cours" du dashboard usager devient un lien vers les détail du dossier (comme toutes les autres tuiles)
#4454 Ajout d'une précision concernant la suppression des photos
#4455 Dans la modale de suppression des doc (commune au BO et FO) prise en charge des nouvelle page FO pour retirerr la mention concernant le partage à l'usager
#4458 Modification du lien "Accéder au dossier" en "Retour à l'accueil du dossier"
=> [FO - Suivi usager] Petites corrections 

src/Manager/SignalementManager.php, src/Service/Signalement/SuiviSeenMarker.php
#4353    
Marquer les messages comme lus en l'absence de notifications via fallback sur la dernière réponse usager
* Ajout d'une fonction pour aller récupérer le dernier suivi usager.
=> [FO - Espace suivi - Messagerie] Marquer les messages comme lus en l'absence de notifications via fallback sur la dernière réponse usager

assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js, migrations/Version20250805124814.php, src/Controller/Back/ProfilController.php, src/Controller/Back/SignalementController.php, src/DataFixtures/Files/Affectation.yml, src/Entity/User.php, templates/_partials/_modal-duplicate-addresses.html.twig, templates/back/signalement/view/header.html.twig, tests/Functional/Controller/BackStatistiquesControllerTest.php
#4324
Le bouton [X Signalement à la mème adresse] et à présent visible pour tous (auparavant limité au RT)
- Au clic pour les non RT une modale s'affiche pour indiquer les problèmes de visibilité potentiels. Si je coche la case "Ne plus afficher ce message" et que je valide la modale (bouton "Voir la liste"), cette modale ne s'affichera plu pour l'user.
- Pas de changement pour ls RT/SA
* Ajout d'une colonne dans la table user pour savoir si la case "Ne plus afficher ce message" à été coché. (j'ai enregistré une date plutôt qu'un bool en envisageant une possible évolution : réaficher la modale une fois un certains délais passé)
`make ntm-build`
`make execute-migration name=Version20250805124814 direction=up`
=> [BO - Dossier] Ajouter bouton voir les doublons pour tous les agents / admin partenaire

assets/scripts/vue/components/signalement-view/components/SignalementListHeader.vue, assets/scripts/vue/components/signalement-view/utils/signalementUtils.ts
#4445    
* Suppression de l'initialisation  sur le composant parent
=> [BUG - BO Liste des signalement] Ordre de tri de l'URL non affiché dans  la selectbox

src/Service/Menu/MenuBuilder.php
#4432    
Appliquer le filtre showMySignalementsOnly pour les agents
* Ajoute la condition du feature flipping et limiter ce filtre aux agents
=> [BUG - BO Liste signalement] showMySignalementsOnly activé pour tous (hors SA) par défaut

migrations/Version20250813145232.php, src/Entity/File.php
#4482
Ajout d'un index sur le champ `is_standalone` de `File` pour optimiser la requête récupérant les documents type à joindre aux suivi. 
Avant
Aprés
`make execute-migration name=Version20250813145232 direction=up`
=> [Tech - Perf] Ajout d'un index sur le champ is_standalone de File

assets/scripts/vanilla/services/component/component_search_checkbox.js, assets/styles/histologe.scss, templates/_partials/signalement/add_suivi.html.twig, templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig, templates/form/dsfr_theme.html.twig
#4464
- Ajout d'un bouton de fermeture sur le composant search checkbox
- Séparation de la modale d'ajout de suivi en deux colonne pour éviter que le composant dépasse sur le bas de la modale
`make npm-watch`
=> [BO - Signalement]Suivi /Ajout doc Affichage

assets/scripts/vanilla/controllers/back_dashboard/tabs_loader.js, assets/scripts/vanilla/services/ui/list_filter_helper.js, tests/Functional/Controller/Back/SubscriptionsChoiceControllerTest.php, tests/Unit/Service/DashboardTabPanel/Kpi/CountAfermerTest.php, tests/Unit/Service/DashboardTabPanel/Kpi/CountDossiersMessagesUsagersTest.php, tests/Unit/Service/DashboardTabPanel/Kpi/TabCountKpiBuilderTest.php
#4512    
Ne pas surcharger le serveurs inutilement lors de changement d'onglet. Charger uniquement l'onglet en cours en supprimant les requêtes précédemment lancé 
* Mise à jour de la fonction initTabsLoader en implémentant AbortController
* Mise à jour namespace de quelques tests 
```
make npm-watch
```
Ouvrir l'inspecteur du navigateur
=> [BO - Dashboard] Tableau de bord V2 - Généralisation d'un abortController 

assets/scripts/vanilla/controllers/back_territory_management_document/back_territory_management_document_index.js, src/Controller/Back/AdminTerritoryFilesController.php, templates/back/admin-territory-files/index.html.twig
#4491   
Ajout de la modale qui s'affiche pour voir les détails d'un document (et sécurisation de la description pour pouvoir sauter des lignes)
=> [BO - Espace documentaire] Modale de détails de document

src/Command/InitSuiviCategoryCommand.php
#4546   
Remise en place de la commande InitSuiviCategoryCommand en ajoutant les modifications faites par la suite dans des migrations (cf en commentaire du fichier)
=> [Tech] Refaire la commande InitSuiviCategoryCommand

src/Messenger/Message/ListExportMessage.php, src/Messenger/MessageHandler/ListExportMessageHandler.php, src/Service/Signalement/Export/SignalementExportLoader.php, tests/Unit/Service/Signalement/Export/SignalementExportLoaderTest.php
#4545    
Tri par date impossible sur les fichiers excel du au format appliqué par défini qui est la chaine de caractère. 
Pas de format applicable sur les fichiers csv
* Appliquer le format date sur toutes les colonnes dates du fichiers excel.
* Exécution commande `make worker-stop && make worker-consume`
* Ouvrir mailcatcher
=> [BO - Liste signalements] Formatage des dates dans l'export xls/cxv

migrations/Version20250902133331.php, src/DataFixtures/Files/User.yml, src/DataFixtures/Files/UserApiPermission.yml, src/DataFixtures/Loader/LoadUserApiPermission.php, src/Entity/File.php, src/Entity/Suivi.php, src/Entity/User.php, src/Entity/UserApiPermission.php, src/Repository/UserApiPermissionRepository.php, tests/Functional/Controller/Back/BackUserControllerTest.php
#4537
- Création de la table `user_api_permission` et ajout de fixtures pour cette table
- Création d'un champ `partner_id` nullable dans les tables `Suivi `et `File`
=> [API] Socle admin de gestion utilisateurs api et permissions

src/Controller/Api/SignalementFileUploadController.php, src/Controller/Api/VisiteUploadDocumentsController.php, src/Dto/Api/Request/FilesUploadRequest.php
#4568    
Constaté lors des derniers tests ou une erreur 500 n'était pas géré lors d'upload de fichiers
* Gérer l'erreur de normalisation lorsqu'un tableau n'est pas poussé
=> [API] Upload de fichiers — erreur 500 quand un tableau de file n'est pas envoyé

src/Command/TrimSignalementFieldsCommand.php, src/Repository/SignalementRepository.php
#4567
- Copie de l'ancienne commande existante pour pouvoir la relancer https://github.com/MTES-MCT/histologe/pull/4035/files
=> [BUG] reprise de données prénom,nom pour appliquer un trim 

templates/base.html.twig
#4587   
Afin d'éviter de stocker des token potentiellement sensibles, on évite le tracking sur la page d'activation des comptes
=> [Matomo] Eviter le tracking sur la page d'activation avec token

assets/json/Signalement/questions_profile_bailleur.json, assets/json/Signalement/questions_profile_bailleur_occupant.json, assets/json/Signalement/questions_profile_locataire.json, assets/json/Signalement/questions_profile_tiers_particulier.json, assets/json/Signalement/questions_profile_tiers_pro.json, assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, assets/scripts/vue/components/signalement-form/components/SignalementFormOverview.vue, src/Dto/Api/Response/SignalementResponse.php, src/Dto/Request/Signalement/SignalementDraftRequest.php, src/Dto/Request/Signalement/SituationFoyerRequest.php, src/Entity/Model/SituationFoyer.php, src/Factory/Api/SignalementResponseFactory.php, src/Factory/Signalement/SituationFoyerFactory.php, src/Form/SignalementDraftSituationType.php, src/Manager/SignalementManager.php, src/Service/Signalement/SignalementBoManager.php, templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig, templates/back/signalement/view/information/information-situation-foyer.html.twig, templates/back/signalement_create/tabs/tab-situation.html.twig, templates/front/suivi_signalement_dossier.html.twig, tests/Functional/Controller/Back/SignalementEditControllerTest.php, tests/Unit/Dto/Request/Signalement/SignalementDraftRequestTest.php, tests/Unit/Dto/Request/Signalement/SituationFoyerRequestTest.php
#4528
Pour les occupants et tiers (hors secours)
Sur l'écran `travailleur_social`
Quand la réponse à la question `travailleur_social_accompagnement` est oui
Alors, on ajoute une question facultative, champ texte :
- Quel est le nom de la structure qui vous accompagne ? (occupants)
- Quel est le nom de la structure qui accompagne le foyer ? (tiers hors secours)
* Ajout de la nouvelle question dans les 5 json des 5 profils concernés pour le formulaire usager
* Ajout de cette information (ainqi des autres infos de travailleur social) dans le récap à la fin du formulaire (`SignalementFormOverview`)
* Ajout de cette information dans les différents Dto (api, édition bo, création bo)
* Ajout de cette information dans les factory, le form pour la création bo, et les manager
* Ajout de cette info …
=> [Fo - Formulaire] Accompagnement TS - Structure

assets/scripts/vue/components/signalement-view/components/SignalementViewFilters.vue
#4643   
Dans la liste des signalements, le bouton RT `Afficher mes affectations uniquement` deviendra inutile une fois le nouveau dashboard (et le système d'abonnements) activé.
=> [BO - Liste signalements] Conditionner l'affichage du bouton RT à l'activation du nouveau dashboard

templates/back/signalement/view/nde.html.twig
#4654   
Si les infos de NDE ne sont pas remplies mais qu'on a quand même saisi des informations dans la partie chauffage du signalement, on peut avoir des soucis d'affichage.
=> [BO - Signalement] Problème d'affichage de date pour la NDE

src/Service/Interconnection/JobEventHttpClient.php
#4651
```sql
select max(job_event.created_at), action, status, partner_type
from job_event
where service like 'esabora' and action like 'push%'
group by action, status, partner_type;
```
Le push n'est jamais appelé en mode batch donc on peut faire un flush toute de suite, contrairement au synchro
Il existe un effet de bord en cas d'erreur et n'est jamais flusher.
* Mise à jour de la condition pour ignorer la synchro pour flusher tous les push tout de suite
`make worker-stop && make worker-start`
`make mock-stop && make mock-start`
`
=> [Interconnexion] Absence de logs d'erreur SISH dans la table job_event depuis mai

assets/scripts/vue/components/signalement-form/TheSignalementAppForm.vue
#4646    
Ajout de l'adresse dans les erreurs d’incohérence entre le code postal et le code insee.
L'objectif est d'anticiper les mises à jour et comprendre pourquoi des adresse de Lyon et Marseille 
* Ajout de log
https://histologe-staging-pr4647.osc-fr1.scalingo.io/signalement
L'erreur JS est lié avec l'erreur PHP (je laisse l'erreur PHP car c'est le board qu'on regarde le plus)
https://sentry.incubateur.net/organizations/betagouv/issues/203137/?project=142&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=2
=> [QA] Investigation adresse Lyon qui renvoie le code insee commune au lieu du code insee arrondissements

migrations/Version20250930074948.php, src/Entity/EmailDeliveryIssue.php
#4683   
Données reçu trop longue pour le type varchar
* Mise à jour du type en longtext
=> [QA] Erreur Doctrine : Donnée trop longue pour la colonne reason webhook brevo

assets/scripts/app-back-bo.ts, assets/scripts/vanilla/services/component/component_search_autocomplete.js, src/Controller/Back/DashboardController.php, src/Form/SearchDashboardAverifierType.php, src/Form/Type/SearchAutocompleteType.php, templates/form/dsfr_theme.html.twig
#4631   
Dans l'onglet `A vérifier` du dashboard, on pouvait choisir des morceaux de communes, ce qui posait problème quand on allait sur la liste complète des signalements (qui elle ne prend que des noms de communes complets).
On limite à présent la recherche aux commune réelles.
* Utilisation d'un élément `datalist` associé au champ de saisie
- `npm run watch-bo`
- Tests plus simples sur base de production
=> [BO - Dashboard] Dans l'onglet A vérifier, limiter les recherches de communes dans une liste

assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js, migrations/Version20250929084507.php, src/Controller/Back/SignalementCreateController.php, src/Controller/Back/SignalementEditController.php, src/Service/Signalement/SignalementBoManager.php, src/Service/Signalement/SignalementBuilder.php, templates/back/signalement/view/tabs/tab-foyer.html.twig, templates/back/signalement_create/tabs/tab-coordonnees.html.twig, tests/Functional/Service/Signalement/SignalementBuilderTest.php
#4642
Suite à l'alerte concernant le signalement `2025-185` du `04` sur lequel un déclarant recevait des notification alors qu'il s’agissait d'un signalement LOCATAIRE, j'ai détecté et corrigé plusieurs problèmes.
Form BO : 
- On vide les champs concernant le déclarant avant validation du signalement pour les profils LOCATAIRE et BAILLEUR_OCCUPANT (afin d'éviter qu'un déclarant invisible puisse être notifié)
- On grise le label du téléphone déclarant sur l'onglet coordonnées
Form FO : 
- On ne copie plus les champs de l'occupant dans ceux du déclarant pour les profils LOCATAIRE et BAILLEUR_OCCUPANT (afin d'éviter en cas de modification du mail déclarant de continuer a notifier l'ancien
Fiche signalement BO : 
- Pour les anciens signalement (avant le nouveau form FO) si un déclarant …
=> [BUG - Form BO] informations déclarant enregistrées avec profil locataire

src/Controller/Api/ArreteCreateController.php, src/Controller/Api/SuiviCreateController.php, src/Controller/Api/VisiteCreateController.php, src/DataFixtures/Files/Affectation.yml, src/DataFixtures/Files/UserApiPermission.yml, src/EventListener/SecurityApiExceptionListener.php, src/Security/Voter/Api/ApiSignalementPartnerVoter.php, tests/Functional/Controller/Api/ArreteCreateControllerTest.php, tests/Functional/Controller/Api/SignalementListControllerTest.php, tests/Functional/Controller/Api/SuiviCreateControllerTest.php, tests/Functional/Controller/Api/UserGetMeControllerTest.php, tests/Functional/Controller/Api/VisiteCreateControllerTest.php, tests/Functional/Service/Security/PartnerAuthorizedResolverTest.php
#4682    
La territoire réunion ne comprenait pas pourquoi le message `'Vous n\'avez pas l\'autorisation d\'accéder à cette ressource.',`  lors d'une création de suivi
* Mise à jour de la documentation
* Expliquer la décision du voter https://symfony.com/blog/new-in-symfony-7-3-explaining-security-voter-decisions
* Utiliser la raison du voter au lieu du message générique `ACCESS_DENIED`
Tests à appliquer sur la création de suivi/visite et arrêtés
=> [API] Mettre en avant dans la doc et les erreurs la contrainte affectation EN_COURS pour toute nouvelle ressource (suivi, visite, arrete)

src/Form/SearchUserType.php, src/Repository/UserRepository.php, src/Service/DashboardTabPanel/TabBodyLoader/DossiersDernierActionTabBodyLoader.php, src/Service/DashboardTabPanel/TabDataManager.php, src/Service/ListFilters/SearchUser.php, templates/back/dashboard/tabs/accueil/_body_derniere_action_dossiers.html.twig, templates/back/partner/view.html.twig, templates/back/signalement/view/affectation/_item-with-action.html.twig, templates/back/signalement/view/information/information-foyer.html.twig, templates/back/signalement/view/information/information-tiers.html.twig, templates/back/user/index.html.twig, tests/Unit/Service/DashboardTabPanel/TabBodyLoader/DossiersDernierActionTabBodyLoaderTest.php
#4648    
Dans la liste des utilisateurs, et dans la liste des agents d'un partenaire, on montre qu'un agent a une adresse e-mail non délivrable
Dans la fiche du partenaire, on accole un ⚠️ à l'adresse e-mail du partenaire si elle est non délivrable
Dans la liste des utilisateurs on fait un filtre sur les adresses e-mail non délivrables
On ajoute un widget sur le dashboard qui mène vers la liste des utilisateurs filtrée
* Ajout du nouveau filtre dans SearchUserType et SearchUser
* Création du nouveau widget du dashboard
* Changement des listes d'utilisateurs en twig
Avant de commencer les tests (sur les fixtures), utiliser postman pour créer des EmailDeliveryIssue
=> [BO - Partenaires] Ajouter les partenaires avec mails non délivrables

src/Repository/SignalementRepository.php
#4660   
Sur le dashbaord, sur une base de prod datant de fin juillet.
En SA, dans l'onglet A vérifier, je filtre sur Lyon, j'ai 170 dossiers
je clique sur Afficher la liste complète, j'ai 163 dossiers
Même problème pour toutes les villes avec arrondissements
* Modification de la requête côté dashboard pour utiliser `CommuneHelper::COMMUNES_ARRONDISSEMENTS` comme dans la liste de signalements
Se mettre sur une base de prod
=> [BO - Dashboard] Incohérence onglet A verifier et liste signalements

migrations/Version20251006193044.php, src/EventSubscriber/AffectationAnsweredSubscriber.php
#4711
Suite à l'enregistrement des partenaire sur les suivi, on à aussi enregistré celui générant le message de validation de la première affectation. Hors dans ce cas la l'information n'est pas pertinente et l'usager ne doit pas en avoir connaissance.
- Migration pour corriger les suivi de la catégorie AFFECTATION_IS_ACCEPTED
- Modification du code de création des suivi de cette catégorie pour laisse le partner null
=> [BUG] Partenaire enregistré sur le suivi AFFECTATION_IS_ACCEPTED
