MTES-MCT/histologe

- templates/header.html.twig
Fix this issue: https://github.com/MTES-MCT/histologe/issues/493
> Fix: remove baseline from header

- cypress/e2e/spec.cy.js
- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
- templates/back/signalement/view.html.twig
- templates/pdf/signalement.html.twig
Feature for this issue: https://github.com/MTES-MCT/histologe/issues/506
> Form for Signalement: 3 questions added

- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
- Ajout d'une contrainte vérifiant que la superficie est un nombre
- Affichage du message d'erreur le cas échéant.
> add constraint number superficie

- public/css/histologe.css
- src/Entity/User.php
- templates/back/partner/_form.html.twig
Fix this issue: https://github.com/MTES-MCT/histologe/issues/523
> Partner users list: display last login date

- templates/emails/migration_pass_email.html.twig
:-D
https://github.com/MTES-MCT/histologe/issues/522
> fix wording

- src/Controller/Back/BackController.php
- tests/Functional/Controller/BackControllerTest.php
Eviter l'erreur 500 pour les utilisateurs aka ROLE_USER_PARTNER
Ajout d'un test fonctionnel
> add hotfix in order to check type of  variable

- src/Command/MigrateLegacyCommand.php
Fix qui permettra de migrer le territoire 06
> check date: bad date exist in 06

- src/Controller/Back/BackPartnerController.php
- src/Entity/Partner.php
- src/Repository/PartnerRepository.php
- templates/back/partner/index.html.twig
Lié à #575 
https://histologe-staging-pr580.osc-fr1.scalingo.io/
* Login: admin-01@histologe.fr
> Ajout pagination page partenaire

- composer.json
- src/Controller/Back/BackSignalementController.php
```
scalingo -a histologe-staging-pr587 run php -i | grep memory_limit
```
> update php memory limit scalingo container

- src/Command/FixSignalementTagCommand.php
- src/Command/MigrateLegacyCommand.php
- src/Manager/AbstractManager.php
- src/Manager/TagManager.php
```
make console app="fix-signalement-tag 04"
```
Lié à https://github.com/MTES-MCT/histologe/issues/590
> Script de reprise des étiquettes de signalement

- src/Controller/Back/BackSignalementActionController.php
Suite à retour d'Arnaud ici : https://github.com/MTES-MCT/histologe/issues/455
> reopening for current role

- src/Command/ClearNotificationCommand.php
- src/Command/FixNotificationLegacyCommand.php
- src/Repository/NotificationRepository.php
- src/Repository/SuiviRepository.php
Lié à https://github.com/MTES-MCT/histologe/issues/574
> add command notification

- src/Controller/FrontSignalementController.php
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/Territory.yml
- src/DataFixtures/Files/User.yml
- src/Service/Signalement/PostalCodeHomeChecker.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
Lié à https://github.com/MTES-MCT/histologe/issues/604
> Gérer les signalements venant du DOM-TOM

- tests/Functional/Manager/SignalementManagerTest.php
https://github.com/MTES-MCT/histologe/pull/612
> [Test] Optimisation du chargement de la page de signalement

- src/Controller/FrontSignalementController.php
Linked to https://github.com/MTES-MCT/histologe/issues/616
> Fix: view of signalement

- public/js/app.js
- templates/_partials/_signalement_steps_tabs.html.twig
Linked to https://github.com/MTES-MCT/histologe/issues/535
> create signalement step 2 block when previous visit

- assets/vue/components/stats/TheHistoStatsFilters.vue
Linked to https://github.com/MTES-MCT/histologe/issues/625
> back stats filters for non admin

- src/Controller/Back/BackStatistiquesController.php
fix for https://github.com/MTES-MCT/histologe/issues/641
> stats communes in alphabetical order

- assets/vue/components/stats/TheHistoAppStats.vue
- assets/vue/components/stats/TheHistoStatsDetails.vue
- assets/vue/components/stats/store.ts
- src/Controller/Back/BackStatistiquesController.php
Feature https://github.com/MTES-MCT/histologe/issues/561
> add motif cloture in back stats

- templates/back/signalement/view.html.twig
Fix for https://github.com/MTES-MCT/histologe/issues/622
> remove autorisation visite from signalement view

- src/Service/NotificationService.php
- templates/emails/affectation_email.html.twig
- templates/emails/login_link_email.html.twig
- templates/emails/lost_pass_email.html.twig
- templates/emails/nouveau_suivi_signalement_back_email.html.twig
- tests/Functional/Service/NotificationServiceTest.php
> Template wording email

- migrations/Version20221020154322.php
ErrorException
Warning: Undefined array key "INDECENCE"
https://sentry.incubateur.net/share/issue/dc5b351342da4296a12717db730a5abc/
> Mise à jour des signalement avec le motif clôture INDECENCE en NON_DENONCE

- .docker/php-fpm/Dockerfile
- .gitignore
- public/js/app.js
- src/Controller/Back/BackSignalementFileController.php
- src/Controller/FrontSignalementController.php
- src/Exception/MaxUploadSizeExceededException.php
- src/Service/UploadHandlerService.php
- tests/Functional/Service/UploadHandlerServiceTest.php
Mise à jour de la configuration PHP pour l'upload de fichier en local
```
make build
```
[FO] Upload sur formulaire usager `/signalement`
[FO] Usager reçoit un email de suivi signalement `/suivre-mon-signalement/code-suivi`
[BO] Upload fiche signalement  `/bo/s/uuid`
> Ajout contrainte de validation upload fichier

- Makefile
- composer.json
- composer.lock
- config/bundles.php
- config/packages/test/dama_doctrine_test_bundle.yaml
- config/services.yaml
- cron.json
- migrations/Version20221028155104.php
- phpunit.xml.dist
- src/Command/FixUserUuidCommand.php
- src/Command/RemindInactiveUserCommand.php
- src/Controller/Security/UserAccountController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/User.yml
- src/DataFixtures/Loader/LoadUserData.php
- src/Entity/Behaviour/TimestampableTrait.php
- src/Entity/User.php
- src/Exception/User/UserEmailNotFoundException.php
- src/Manager/UserManager.php
- src/Repository/UserRepository.php
- src/Service/Token/ActivationTokenGenerator.php
- symfony.lock
- templates/emails/login_link_email.html.twig
- templates/security/reset_password_new.html.twig
- tests/Functional/Command/RemindInactiveUserCommandTest.php
- tests/Functional/Controller/UserAccountControllerTest.php
- tests/Functional/Repository/UserRepositoryTest.php
Après sa création un utilisateur a 10 jours pour activer son compte avant qu'il ne reçoive un mail de relance. 
Le [CRON Scalingo](https://doc.scalingo.com/platform/app/task-scheduling/scalingo-scheduler) exécutera cette commande tous les 10 jours
```
php bin/console app:remind-inactive-user
```
https://github.com/MTES-MCT/histologe/issues/543
|Environnement | Dépendance | Description|
|---------------------|------------------------|-----------------|
|  all | symfony/uid | https://packagist.org/packages/symfony/uid
| test | dama/doctrine-test-bundle| https://packagist.org/packages/dama/doctrine-test-bundle
| Nouvelles colonnes  table `user` |
|---------------|
|  uuid |
|  created_at |
|  updated_at |
|  token |
|  token_expired_at |
| Commande …
> Tache planifiée d'envoi de mail de relance pour l'activation d'un compte

- src/Controller/Back/BackPartnerController.php
- src/Manager/AbstractManager.php
- src/Manager/UserManager.php
- src/Security/Voter/UserVoter.php
- src/Service/NotificationService.php
- templates/_partials/_modal_user_transfer.html.twig
- templates/back/partner/_form.html.twig
- templates/back/partner/edit.html.twig
- templates/emails/switch_account_email.html.twig
- templates/emails/transfer_account_email.html.twig
- tests/Functional/Manager/UserManagerTest.php
Le wording du mail est différent selon si l'utilisateur est actif ou non
> Envoi mail apres transfert de compte

- config/packages/twig.yaml
- templates/base.html.twig
Le code suivi est désactivé sur l'environnement de dev
> Matomo - Ajout du code suivi 

- src/Form/PartnerType.php
En cas d'absence de mail générique du partenaire, Il faut obligatoirement qu'au moins 1 compte utilisateur du partenaire accepte de recevoir les emails
A partir du moment ou j'ai des utilisateurs
Source WIKI : https://github.com/MTES-MCT/histologe/wiki/Emails#cas-particulier--ladresse-mail-g%C3%A9n%C3%A9rique
> Il faut obligatoirement qu'au moins 1 compte utilisateur du partenaire accepte de recevoir les emails

- cron.json
Une fois par semaine, les notifications de plus de 30 jours seront supprimées
> Activer le cron de suppression de notification de plus de 30 jours 

- src/EventListener/ActivityListener.php
#515 
Arrêter les notifications et les emails inutiles (en priorité celles liées à la validations des signalements et aussi celles reçus par les agents lorsqu'ils mettent u commentaire, **ils reçoivent un emails et une notif leur indiquant qu'ils viennent de mettre un commentaire)**
> Ne pas envoyer d'email de notification à l'utilisateur connecté

- public/js/app.js
- public/js/const.min.js
- src/Controller/FrontSignalementController.php
- src/Entity/Territory.php
- src/Service/Signalement/PostalCodeHomeChecker.php
- templates/_partials/_signalement_steps_tabs.html.twig
https://github.com/MTES-MCT/histologe/issues/673
Test : manually edit the code postal when creating a signalement
> add js control for manual rhone code postal

- public/js/app.js
New fix due to last comment in https://github.com/MTES-MCT/histologe/issues/673
=>
**Cas à résoudre :**
Je cherche une adresse dans le champ de recherche
Je sélectionne une adresse
Je change le code postal
Si on change le code postal, il faudrait supprimer le code Insee et le rechercher à nouveau pour être sur qu'il soit valide.
> fetch address when edit manually code postal or city in signalement

- templates/_partials/_modal_cloture.html.twig
https://github.com/MTES-MCT/histologe/issues/703
> add warning message in signalement cloture modal

- src/EventSubscriber/SignalementClosedSubscriber.php
> Ajout des suivi d'affectation pour la cloture d'un partenaire

- cypress/e2e/spec.cy.js
- migrations/Version20221207165536.php
- src/Command/MigrateLegacyCommand.php
- src/DataFixtures/Loader/LoadUserData.php
- src/Entity/User.php
- src/Factory/UserFactory.php
- src/Manager/UserManager.php
- templates/back/partner/_form.html.twig
- tests/Unit/Entity/PartnerTest.php
- tests/Unit/Factory/UserFactoryTest.php
> [BO] Supprimer la fonctionnalité "type de compte" avec compte générique.

- .env
- .env.sample
- .github/workflows/main.yml
- composer.json
- config/packages/test/web_profiler.yaml
- config/services.yaml
- src/Controller/HomepageController.php
- src/Service/NotificationService.php
- tests/Functional/Controller/HomepageControllerTest.php
- tests/Functional/Service/NotificationServiceTest.php
> [BO][Mailing]Mise à jour expéditeur e-mail transactionnel

- .env
- .env.sample
- config/services.yaml
- src/Command/AddUserCommand.php
- src/DataFixtures/Loader/LoadUserData.php
- src/Service/Signalement/Import/SignalementImportLoader.php
- src/Service/Signalement/Import/SignalementImportMapper.php
Lié à #761 
Suite de la PR #762
> [BO][Signalement] Import données historiques (Ajustement 81)

- cron.json
- src/Command/ImportGridAffectationCommand.php
- src/Service/NotificationService.php
- templates/emails/cron_email.html.twig
- tests/Unit/Command/ImportGridAffectationCommandTest.php
> [BO - Partenaire] Automatiser l'ouverture territoire pour le 2 janvier

- migrations/Version20221223225911.php
- src/Command/MigrateLegacyCommand.php
- src/Entity/Signalement.php
- src/Factory/SignalementFactory.php
- src/Service/Signalement/Import/SignalementImportLoader.php
- src/Service/Signalement/Import/SignalementImportMapper.php
> [BO][Signalement] Import données historiques (Ajustement 38)

- src/Controller/Back/BackAssignmentController.php
https://github.com/MTES-MCT/histologe/issues/738
> add suivi for affectation only if refused

- src/Controller/Back/BackController.php
Correction pour la liste des signalements filtrée par partenaire https://github.com/MTES-MCT/histologe/issues/778
> fix signalement list filter per partner

- assets/vue/components/common/HistoFranceMap.vue
Correction pour l'affichage responsive de la carte dans les statistiques publiques (Ticket lié https://github.com/MTES-MCT/histologe/issues/674)
> fix responsive for public stat map

- src/Controller/HomepageController.php
#[744](https://github.com/MTES-MCT/histologe/issues/744)   
Suppression des signalements archivés dans les stats
* Modification du décompte total pour les signalements en enlevant les archivés
> [FO- Home Page] - Bandeau Stats

- Makefile
- composer.lock
- cypress/e2e/spec.cy.js
- package-lock.json
- package.json
- public/js/app.js
- tests/Functional/Service/Files/HeicToJpegConverterTest.php
#895    
Des messages d'avertissements apparaissent après le composer install
* Corrections namespace PSR-4 sur `tests/Functional/Service/Files/HeicToJpegConverterTest.php`
* Mise à jour makefile, option `--dev` dans composer dépréciée
* Exécution composer update pour maj mineures
* Corrections test end to end, (menu statistiques non visible)
> [QA] Respect normes PSR-4

- docker-compose.yml
Lorsque phpMyAdmin, le login est à présent automatique. Evite les déconnexions intempestives.
> Mise en place du login automatique pour ouvrir phpMyAdmin

- src/Command/UpdateAlgoCriticiteCommand.php
- src/DataFixtures/Files/Criticite.yml
#896    
J'ai juste changé 3 scores à la demande d'Arnaud. Je remets les infos de la première PR
Amélioration du calcul de la criticité d'un signalement, en changeant les coefs des critères, les scores des criticités, en ajoutant un type batiment/logement au niveau du critère pour faire d'abord un calcul de la criticité sur ces deux sujets, puis une moyenne des deux. La notion de danger est déportée au niveau de la criticité et n'impacte plus le score (avant cela mettait le score à 100 automatiquement). 
Dans un premier temps, ce sont des nouvelles données (nouvelles colonnes) le temps de tester la pertinence de ce nouveau mode de calcul. Quand on aura validé ce fonctionnement, on supprimera les anciennes colonnes et on renommera les nouvelles colonnes.
* Migrations pour ajouter …
> [BO - Signalement] Evolution Algo criticité : Changes few scores (Arnaud demand)

- .docker/php-fpm/Dockerfile
- .docker/php-worker/Dockerfile
- .env
- .env.sample
- Makefile
- README.md
- config/packages/cache.yaml
- config/packages/framework.yaml
- docker-compose.yml
`make build`
#968    
Stocker les sessions dans une base de données clé-valeur afin de pouvoir 
* Installation du serveur redis via un service docker
* Installation de l’extension php-redis
* Configuration de la session 
* Mise à jour du makefile pour se connecter au container redis
```bash
$ make redis-cli
Log to redis-cli
127.0.0.1:6379> KEYS *
1) "sf_s4mrosbffven7cdqs5dgmddiivv"
2) "sf_som350j73qo0d2ms9ct1sn430vq"
127.0.0.1:6379> GET "sf_s4mrosbffven7cdqs5dgmddiivv"
"_sf2_attributes|a:3:{s:23:\"_security.last_username\";s:21:\"admin-01@histologe.fr\";s:19:\"_security.territory\";N;s:14:\"_security_main\";s:2885:\"O:75:\"Symfony\\Component\\Security\\Http\\Authenticator\\Token\\PostAuthenticationToken\":2:{i:0;s:4:\"main\";i:1;a:5:{i:0;O:15:\"App\\Entity\\User\":21:{s:19:\"\x00App\\Entit …
```
> [Performance] Mise en place de Redis afin de pouvoir faire de pouvoir multiplier le nombre de ressources coté infrastructure

- assets/vue/components/dashboard/TheHistoDashboardHeader.vue
Remplacement du hover par du click lorsque le dashboard est affiché en responsive
> Responsive du dashboard : remplacement du hover par du click

- assets/vue/components/dashboard/TheHistoDashboardTables.vue
https://sonarcloud.io/project/issues?resolved=false&types=BUG&pullRequest=1005&id=MTES-MCT_histologe&open=AYbFymSehVujzmUim0_B
Suppression d'une condition inutile remontée par SonarCloud
> Suppression d'une condition inutile remontée par SonarCloud

- src/Service/SearchFilterService.php
#970    
Correction sur le filtre fermé chez au moins un partenaire
* Ajout d'un contrôle sur le territoire
> [Performance] Correction filtre fermé chez au moins un partenaire

- assets/vue/components/dashboard/TheHistoAppDashboard.vue
- assets/vue/components/dashboard/TheHistoDashboardCards.vue
- assets/vue/components/dashboard/store.ts
- config/app/widgets.yaml
- package-lock.json
- src/Controller/Back/WidgetSettingsController.php
- src/Dto/CountSignalement.php
- src/Repository/AffectationRepository.php
- src/Repository/SignalementRepository.php
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
- src/Service/DashboardWidget/WidgetSettings.php
- src/Service/SearchFilterService.php
- tests/Unit/Service/DashboardWidget/WidgetSettingsTest.php
#935    
Modification du dashboard pour ajouter les cartes liées à la NDE
* Ajout de 2 cartes liées à la NDE
> [BO - Dashboard] Modification du dashboard pour ajouter les cartes liées à la NDE

- src/Service/Statistics/GlobalAnalyticsProvider.php
#941    
Correction régression stats "Foyer sorti du mal logement"
* MAJ condition
> [FO - Stat] Foyer sorti du mal logement

- src/Repository/SignalementRepository.php
#970    
Requête généré pas optimisé, correction query builder
* créer un QueryBuilder distinct pour la classe Affectation avec l'objet `_em`
> fix: fix query builder

- assets/styles/histologe.scss
- composer.lock
- public/js/app.js
- public/js/maps.js
- src/Repository/SignalementRepository.php
- src/Service/Signalement/SearchFilterOptionDataProvider.php
- src/Service/Statistics/GlobalAnalyticsProvider.php
- templates/front/signalement.html.twig
#797 
Ajout d'informations concernant les procédures, pour les usagers, lors de la dernière étape du formulaire de signalement
> [Signalement Front] Ajout informations sur la dernière étape pour les usagers 

- public/js/app.js
#928    
Modification du message d'erreur dans le formulaire de signalement
Je ne sais pas si vous avez une bonne idée pour tester, moi j'ai changé l'url du formulaire à la main pour voir :D
> [FO - Formulaire signalement] Modification du message d'erreur dans le formulaire de signalement

- templates/_partials/_modal_edit_nde.html.twig
#1093    
Augmentation de l'espace entre les différentes ligne du formulaire d'édition de la NDE
* idem
> [BO - Edition NDE] Augmenter l'espace entre les champs

- assets/controllers/form_nde.js
- public/js/app.js
- templates/_partials/_modal_edit_nde.html.twig
- templates/back/signalement/view.html.twig
#1092    
Changement automatique des champs conso et énergie, affichés en BO pour éditer la NDE
> [BO - Signalement - Edition NDE] Changement automatique des champs affichés en BO pour éditer la NDE

- assets/controllers/form_nde.js
- src/Manager/SignalementManager.php
- src/Service/Signalement/QualificationStatusService.php
#1094    
Fix d'erreurs quand on valide des changements sur la NDE
* Vérification sur des null et division par zéro
> [BO - Edition NDE] Impossible de valider les modifications

- assets/controllers/form_nde.js
- templates/_partials/_modal_edit_nde.html.twig
#1106    
Ajout d'informations et de controles dans la modale NDE
Attention : l'affichage a été revu en privé avec Mathilde et l'affichage ne correspond pas tout à fait au ticket.
* Modification texte introductif
* Ajout de champs obligatoires, et contrôle
* Ajout d'avertissement sur la date du bail
> [BO Signalement NDE] Ajout d'informations et de controles dans la modale NDE

- public/js/app.js
Correction du parcours dans l'édition de signalement
> Correction du parcours dans l'édition de signalement

- src/Service/Signalement/Qualification/SignalementQualificationUpdater.php
#995    
Correction de la commande d'initialisation des qualifications
> [Commande] Correction pour l'initialisation des qualifications

- src/Command/AskFeedbackUsagerCommand.php
#1135    
Commande de demande de feedback usager, créé le code de suivi s'il n'y en a pas
* Correction sur la commande
>  [Tâche auto] Commande de demande de feedback usager, créé le code de suivi s'il n'y en a pas

- templates/base.html.twig
#1138    
La carto ne s'affiche plus sur la fiche signalement
* Ajoute une condition sur la vue fiche signalement
> [Performance] Régression carto fiche signalement 

- templates/back/index.html.twig
#1138 
https://github.com/MTES-MCT/histologe/pull/1177
> [Performance] Suppression code obsolète

- templates/back/index.html.twig
- templates/back/signalement/view.html.twig
#995    
Renommer situation suspectee au lieu de procedure suspectee
* MAJ wording
> [BO - Criticité]  MAJ titre colonne sur le listing et sur le signalement pour les procédures

- src/Repository/JobEventRepository.php
> [BO - Esabora] Rollback requêtes événements

- public/js/app.js
#1109    
Erreur JS qui fait planter la pagination
* Suppression de code JS
* Suppression du canvas pour jauge inutilisé dans la cartographie
> [BO - Liste Signalements] La pagination ne fonctionne pas

- templates/front/signalement.html.twig
#1196    
Modification des textes sur la page de validation après dépôt du signalement
* Changement des textes
>  [FO - Page validation] Correction du texte

- assets/styles/histologe.scss
- templates/back/table_result.html.twig
#537    
Correction de l'affichage de la liste des signalements sur petits écrans
* Limite appliquée au nom des partenaires dans la liste des signalements
> [Liste signalements] Nombre de caractère maximal pour partenaires

- assets/app.ts
- assets/controllers/form_notification.js
- assets/styles/histologe.scss
- src/Controller/Back/NotificationController.php
- src/Repository/NotificationRepository.php
- templates/back/notifications/index.html.twig
- tests/Functional/Controller/NotificationControllerTest.php
#853    
Sélection individuelle des notifications pour supprimer ou marquer comme lue
* Ajout de cases à cocher et de formulaires spécifiques pour les notifications sélectionnées
> [Notifications] Pouvoir sélectionner les notifications pour supprimer ou marquer comme lue

- migrations/Version20230509154439.php
- src/Controller/Back/AffectationController.php
- src/Controller/Back/PartnerController.php
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Loader/LoadPartnerData.php
- src/Entity/Partner.php
- src/Form/PartnerType.php
- src/Repository/AffectationRepository.php
- src/Repository/JobEventRepository.php
- templates/back/partner/_form.html.twig
- templates/back/partner/view.html.twig
#1128    
Ajout d'une option d'activation et désactivation de la connexion à Esabora
* Ajout d'un champ à la table partenaire
* Migration pour activer automatiquement pour ceux qui ont l'url renseignée
* Modification du BO (ajout/édition/affichage partenaire)
* Connexion conditionnelle à Esabora
> [Partenaires] Option d'activation de la connexion à Esabora

- assets/styles/histologe.scss
- public/js/app.js
- templates/back/signalement/view.html.twig
#1041    
Désactivation du clic et du curseur sur les badges
> [BO Signalement] Désactivation du clic et du curseur sur les badges

- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Messenger/Message/DossierMessageSISH.php
- src/Service/Esabora/EsaboraSISHService.php
#1267    
Envoi de l’URL de la fiche signalement
* Mise à jour du message qui encapsule les données à envoyer au SAS
> [Esabora - Intégration SISH] Envoi URL fiche signalement

- templates/_partials/_signalement_step_avantpropos.html.twig
- templates/front/index.html.twig
- templates/front/signalement.html.twig
#1271   
Modification de quelques termes sur la homepage et le dépôt de signalement
> [Site public - homepage] Modif de texte

- src/DataFixtures/Files/Territory.yml
- src/Service/Signalement/PostalCodeHomeChecker.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
- tests/Functional/Service/Signalement/PostalCodeHomeCheckerTest.php
#1248    
Martinique à un code zip de 3 caractères comme tous les DOM-TOM et la corse
* Ajout du codezip de la martinique
> [Ouverture] Martnique

- public/robots.txt
#1288 
Ajout du fichier robots.txt
* Exclusion des dossiers /bo et /_up
> [QA] Ajout du fichier robots.txt

- src/Controller/FrontSignalementController.php
#1242 
Mail 3e relance : empêcher l'utilisateur de dire plusieurs fois qu'il veut continuer la procédure
* Mise à jour de la route front_suivi_signalement pour éviter de créer plusieurs fois un suivi "je veux continuer la procédure"
> [Relance Auto] Mail 3e relance : empêcher l'utilisateur de dire plusieurs fois qu'il veut continuer la procédure

- migrations/Version20230531140303.php
#1245    
Erreur de syntaxe en prod sur une requête update
https://sentry.incubateur.net/share/issue/a74a89674bfd4e1a83ed07ce588425b7/
* Mise à jour séparateur, ", " au lieu de "AND"
> [QA] Compatibilité syntaxe requete

- src/EventListener/ActivityListener.php
#1245    
Ne pas notifier les partenaires lors de la notification de première acceptation d'affectation
* Test sur la description du suivi dans ActivityListener :vomiting_face:
> [BO - Signalement] Ne pas notifier les partenaires lors de la notification de première acceptation d'affectation

- src/Service/Esabora/EsaboraManager.php
#1391    
Voir #1375 
* Correction contrôle sur statut 
Voir #1375 
Voir #1375
> [QA] Esabora - Ajout contrôle statut des dossiers

- src/Command/NotifyVisitsCommand.php
- src/Controller/Back/SignalementVisitesController.php
- src/EventSubscriber/InterventionCanceledSubscriber.php
- src/EventSubscriber/InterventionConfirmedSubscriber.php
- src/EventSubscriber/InterventionCreatedSubscriber.php
- src/EventSubscriber/InterventionEditedSubscriber.php
- src/EventSubscriber/InterventionRescheduledSubscriber.php
- templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig
- templates/emails/nouveau_suivi_visite_created_to_partner_email.html.twig
- templates/emails/nouveau_suivi_visite_created_to_usager_email.html.twig
- templates/emails/nouveau_suivi_visite_edited_email.html.twig
- templates/emails/nouveau_suivi_visite_future_reminder_to_usager_email.html.twig
- templates/emails/nouveau_suivi_visite_rescheduled_email.html.twig
#1416
https://mattermost.incubateur.net/betagouv/pl/f7qhi9r5airb9n5paf5s84wczc
* Ajoute un contrôle supplémentaire sur le partenaire
> [QA] Visites - Ajout contrôle sur l'existence partenaire sur une intervention

- assets/styles/histologe.scss
- templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-cancel.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-reschedule.html.twig
- templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig
#1419    
Etoile rouge pour les champs obligatoires dans les formulaires de visites
* Ajout règle css sur les légendes
> [BO - Visites] Etoile rouge pour les champs obligatoires

- assets/controllers/form_visite.js
#1419    
Correction de validation du formulaire pour les reprogrammation de visites passées
* Ajustement js
> [BO - Visites] Correction de validation du formulaire pour les reprogrammation de visites passées

- public/js/app.js
- src/Controller/FrontSignalementController.php
- src/Controller/Security/SecurityController.php
- src/Service/Signalement/PostalCodeHomeChecker.php
- tools/histologe/histologe.postman_collection.json
#1466   
Certains utilisateurs rencontrent des difficultés lorsqu'ils tentent de déposer un signalement.
Ce problème affecte spécifiquement les utilisateurs dont la saisie du signalement prend du temps. Après avoir reproduit le problème sur l'environnement de staging en démarrant un dépôt et en revenant plus d'une demi-heure plus tard pour le terminer et le valider, j'ai reçu une popup d'erreur.
Nous avons constaté qu'environ 5% des 146 signalements déposés jusqu'à présent sont concernés par ce problème. Maintenant que nous avons identifié la cause, nous travaillons activement sur une résolution pour permettre l'enregistrement correct des signalements, même pour les utilisateurs dont la saisie prend du temps.
* Ajout d'un WS `/signalement/csrf-token` afin de récupérer un csrf token de …
> [FO - Signalement] Problème d'enregistrement des signalements pour les utilisateurs avec une saisie prolongée

- tools/wiremock/src/Mock/Signalement/QuestionMock.php
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1423    
Propriété incorrecte dans un composant
Voir #1471
> [Back] Mock API - Correction objet value dans SignalementFormOnlyChoice

- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/SignalementFormWarning.vue
- assets/vue/components/signalement-form/exemple_socle.json
#1494    
Ajout du composant SignalementFormWarning
* création du composant SignalementFormWarning
> [Front] Créer le composant SignalementFormWarning

- assets/vue/components/signalement-form/SignalementFormCheckbox.vue
- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/exemple_socle.json
- assets/vue/components/signalement-form/store.ts
#1503      
Ajout du composant SignalementFormCheckbox
* création du composant SignalementFormCheckbox
> [Front] Créer le composant SignalementFormCheckbox

- src/Controller/QuestionController.php
- templates/front/nouveau_formulaire.html.twig
#1527    
Création endpoint afin que le formulaire soit testable sur staging
* Ajout endpoint questions
> [Back] Endpoint mock question pour déploiement

- assets/vue/components/signalement-form/SignalementFormScreen.vue
[#NumIssue   ](https://mattermost.incubateur.net/betagouv/pl/dyc7w5p373nyfc31jjrbk7uxca)
vérifie l'existence de body dans components pour faire les vérifications de validation avant de changer de screen
> fix bug on change screen

- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1582   
Ajout du composant résumé (Overview) pour nouveau formulaire
En mode statique (les libellés pourront évoluer dynamiquement).
Certaines parties ne sont pas encore remplies.
> [Front Vue] Ajout composant résumé pour nouveau formulaire

- assets/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue
#1595   
Correction d'affichage de multiples boutons radio dans le nouveau formulaire
> [FO - Formulaire] Correction d'affichage de multiples boutons radio

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormTime.vue
- assets/vue/components/signalement-form/components/SignalementFormYear.vue
#1539    
Ajout des composants Heure et Année pour le nouveau formulaire
> [FO - Formulaire] Ajout des composants Heure et Année

- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
#1593    
Correction pour avoir des checkbox fonctionnelles sur le nouveau formulaire
> [FO - Formulaire] Correction pour avoir des checkbox fonctionnelles

- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Factory/SignalementDraftFactory.php
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1603    
Mock manquants
* Tiers pro
* Tiers particulier
* Bailleur
* Bailleur occupant
* 
* MAJ des mock présent
* Ajout de nouveaux mock
* Adaptation SignalementRequestFactory
*Exemple qui liste les questions*
> [Back] Mock API - Récupération des questions profil restants (tiers pro, tiers particulier, bailleur et bailleur occupant)

- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/components/SignalementFormModalBackHome.vue
#1533    
Ajout modale de retour à l'accueil lors du clic dans le fil d'Ariane
> [Formulaire] Modale de retour à l'accueil

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/interfaces/interfaceMenuItem.ts
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1534    
Mise en place du fil d'Ariane compatible desktop et smartphone
* Catégorisation des écrans
* Deux fils d'Ariane différents
* Nombre fixe d'étapes sur smartphone
> [Front - Formulaire] Mise en place du fil d'Ariane compatible desktop et smartphone

- assets/styles/histologe.scss
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormButton.vue
- assets/vue/components/signalement-form/components/SignalementFormLink.vue
- assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1611    
Affichage des boutons dans tous les formats, avec les bonnes icones
> [Front - Formulaire] Affichage responsive des boutons

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormButton.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/store.ts
#1608    
Changement d'apparence des boutons au moment des appels serveurs
> [Front - Formulaire] Changement d'apparence des boutons au moment du chargement

- assets/styles/histologe.scss
- templates/_partials/_signalement_steps_tabs.html.twig
- templates/_partials/_signalement_upload.html.twig
#1630   
#1631   
Correction décalage pour les pièces jointes et couleur des boutons de suppression sur le formulaire de signalement
> [Front - Formulaire signalement] Correction décalage pour les pièces jointes et couleur des boutons de suppression

- assets/vue/components/front-stats/TheHistoAppFrontStats.vue
- assets/vue/components/stats/TheHistoStatsFilters.vue
#1635   
Ajustement taille icone Réinitialiser
> [BO - Statistiques] Ajustement taille icone Réinitialiser

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1611    
Suite de l'avancée de l'intégration : affichage des boutons radio
> [Front - Formulaire] Affichage des boutons radio

- assets/styles/histologe.scss
- public/js/app.js
- templates/_partials/_modal_closed_territory.html.twig
- templates/_partials/_signalement_step_nde.html.twig
- templates/_partials/_signalement_steps_tabs.html.twig
- templates/_partials/signalement/add_suivi.html.twig
- templates/back/account/_form.html.twig
#1630   
#1647   
Corrections diverses après la mise à jour du DSFR
Voir les tests
> [Front] Corrections diverses DSFR

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormUploadPhotos.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1626   
Création d'un composant spécifique répétable pour les uploads de photos dans les désordres
> [Front - Formulaire] Ajout composant UploadPhotos

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
- assets/vue/components/signalement-form/dictionary-store.ts
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/services/variableReplacer.ts
- assets/vue/components/signalement-form/store.ts
- src/Controller/QuestionController.php
- templates/front/nouveau_formulaire.html.twig
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/dictionary.json
#1655    
Gestion de certaines chaines de caractère dans un fichier de dictionnaire
> [Front - Formulaire] Gestion de certaines chaines de caractère dans un fichier de dictionnaire

- assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
- assets/vue/components/signalement-form/components/SignalementFormUploadPhotos.vue
#1657    
Affiche le nb de photos ajoutées à un critère
> [Front - Formulaire] Résumé des désordres : ajout d'un comptage de photos

- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
> [New form] Retour structure JSON

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/interfaces/interfaceMenuItem.ts
#1723   
Fonctionnement du clic sur le menu desktop
Pour l'instant, il ne permet de revenir qu'en arrière.
Je ne sais pas comment modéliser qu'on est déjà passé sur une partie, à part avec les slugs de réponses données...
> [Front - Formulaire] Fonctionnement du clic sur le menu

- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
#1733    
Voir commentaire de la PR
https://github.com/MTES-MCT/histologe/pull/1733#issuecomment-1722925751
> [FO] Ajout d'une contrainte numérique sur l'étage

- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1701   
Modification des labels de boutons pour ajout de bail et DPE
> [Front - Formulaire] Modification des labels de boutons pour ajout de bail et DPE

- cron.json
#1760   
Afin de voir le temps de traitement du cron des interventions
* Mise à jour cron.json
> [Esabora] Découper le cron SISH en deux crons 

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormButton.vue
#1766   
Correction affichage des boutons de type "lien"
> [Formulaire - Front] Correction affichage des boutons de type "lien"

- assets/styles/histologe.scss
- templates/back/signalement/view/photos-documents.html.twig
#1678   
Correction affichage icone pour ouvrir image
> [BO - Signalement] Correction icone ouvrir image

- assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
#1766    
Ajouter une icone + au bouton "ajouter un numéroé
* css dans SignalementFormPhoneField
> [New form] Style bouton ajouter un numéro

- assets/vue/components/signalement-form/components/SignalementFormConfirmation.vue
#1750   
Ajout bouton "Donner votre avis" à la fin du nouveau formulaire
> [Front - Formulaire] Ajout bouton "Donner votre avis"

- config/app/export_pdf.yaml
- config/services.yaml
- src/Controller/Back/SignalementFileController.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/File.php
- src/Messenger/Message/PdfExportMessage.php
- src/Messenger/MessageHandler/PdfExportMessageHandler.php
- src/Service/Signalement/Export/SignalementExportPdf.php
- templates/back/signalement/view/header.html.twig
- templates/emails/signalement_pdf_export.html.twig
- tests/Functional/Controller/SignalementFileControllerTest.php
- tests/Functional/Messenger/MessageHandler/PdfExportMessageHandlerTest.php
- tests/Unit/Service/Signalement/Export/SignalementExportPdfTest.php
#1677    
Reprendre https://github.com/MTES-MCT/histologe/pull/1854 pour les tests
> [Export] Généraliser l'export pdf avec envoi de mail

- templates/back/signalement/view/header.html.twig
#1886    
En attendant l'évolution avec lien de téléchargement et de faire des tests avec de vrai signalement
* Désactivation du bouton d'export
> [BO] Export PDF - Désactivation temporaire de la fonctionnalité

- src/Controller/Back/SignalementFileController.php
- tests/Functional/Controller/SignalementFileControllerTest.php
#1883   
Modification du message de confirmation lors de la demande d'export PDF
> [BO - Signalement] Modification du message de confirmation lors de la demande d'export PDF

- src/Command/SlugifyDocumentSignalementCommand.php
- src/Controller/Back/SignalementFileController.php
- src/Controller/FrontSignalementController.php
- src/Controller/Security/SecurityController.php
- src/Messenger/MessageHandler/PdfExportMessageHandler.php
- src/Security/Voter/FileVoter.php
- src/Service/Mailer/Mail/Signalement/SignalementPdfExportMailer.php
- src/Service/Signalement/Export/SignalementExportPdf.php
- src/Service/Signalement/Export/SignalementExportPdfGenerator.php
- src/Service/Signalement/SignalementFileProcessor.php
- src/Service/UploadHandlerService.php
- templates/back/signalement/view/header.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- tests/Functional/Controller/SecurityControllerTest.php
- tests/Functional/Messenger/MessageHandler/PdfExportMessageHandlerTest.php
- tests/Functional/Service/UploadHandlerServiceTest.php
- tests/Unit/Service/Signalement/Export/SignalementExportPdfTest.php
- tests/Unit/Service/Signalement/SignalementFileProcessorTest.php
#1886    
Du à la limitation du poids des pièces jointes dans les emails, permettre à l'utilisateur d'afficher la pièce jointe à partir d'un lien dans l'email d'export PDF
* Ajout d'une nouvelle méthode qui permet d'envoyer un fichier en locale vers le bucket sans passer par un formulaire
* Création du pdf en local afin de l'envoyer vers le Bucket S3
* Suppression de la pièce jointe et mise à jour du mail
* Correctif de la gestion des permissions sur l'affichage des fichiers 
* Limitation de l'export au signalement contenant moins de 20 photos
```
```
> [QA] Export PDF - Remplacer la pièce jointe par un lien de téléchargement dans le mail

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- templates/base.html.twig
- templates/front/nouveau_formulaire.html.twig
#1923    
Réactivation du header et footer sur version mobile
> [Front] Réactivation du header et footer sur version mobile

- assets/styles/histologe.scss
- templates/back/signalement/view/address-qualifications.html.twig
#1895    
Créé une classe css spécifique pour le bouton modifier de la page signalement (pour remettre l'aspect du dashboard comme avant)
* Création d'une classe css
> [BO - Dashboard] Augmenter taille police titre des widgets

- assets/styles/histologe.scss
- src/Controller/Back/SignalementEditController.php
- src/Controller/Back/SignalementListController.php
- templates/_partials/_modal_affectation.html.twig
- templates/_partials/_modal_dpe.html.twig
- templates/_partials/_modal_edit_nde.html.twig
- templates/_partials/signalement/add_suivi.html.twig
- templates/back/signalement/view/edit-modals/edit-address.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-bailleur.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-foyer.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig
- templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig
- templates/back/signalement/view/edit-modals/edit-procedure-demarches.html.twig
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/header.html.twig
- templates/back/signalement/view/information.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
PR faite suite à la disparition des commits de la vieille PR cf https://github.com/MTES-MCT/histologe/pull/1947
>  [BO - Signalement] Quelques améliorations UI 

- src/Dto/Request/Signalement/SignalementDraftRequest.php
- templates/back/signalement/view/information.html.twig
#1981   
Déplacement de la partie Composition du logement dans un bloc dans la fiche signalement
> [BO - Signalement] Déplacement de la partie Composition du logement dans un bloc

- templates/back/signalement/view/header.html.twig
#1910   
Préciser "tiers bailleur" dans l'entête
* Changement du twig
> [BO - Nouveau signalement] Préciser le type de déclarant dans l'en tête

- assets/vue/components/signalement-form/components/SignalementFormConfirmation.vue
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#2009   
Ajouter une marge avant le formulaire pour donner son avis
* Changement des json
* Changement du composant SignalementFormConfirmation pour prendre en compte la classe css
> [FO - Signalement - Ecran validation] Ajouter une marge avant la partie je donne mon avis

- config/packages/routing.yaml
- scripts/upload-s3.sh
- src/Command/ImportGridAffectationCommand.php
- src/Entity/User.php
- src/Service/Import/GridAffectation/GridAffectationLoader.php
- tests/FixturesHelper.php
- tests/Functional/Service/Import/GridAffectation/GridAffectationLoaderTest.php
- tests/Unit/Command/ImportGridAffectationCommandTest.php
#1985 
#1933 
#1279    
La Creuse a fourni une nouvelle grille d'affectation. La commande a donc évolué afin de prendre en compte le chargement de nouvelle grille d'affectation après l'ouverture.
> [!WARNING]  
> Le fichier de la Creuse déposé sur le bucket DEV n'est pas le fichier définitive [(voir commentaire)](https://github.com/MTES-MCT/histologe/issues/1985#issuecomment-1841250914)
- Construction automatique des URL(s) dans le contexte d'une commande.
- Ajout d'une note de rappel afin de renseigner les identifiants ARS du territoire.
- Évolution de la commande afin de gérer les nouvelles grilles de territoires de manière versionnée via une option.
- Gestion des contraintes en fonction du mode update.
- Réduction du bruit Sonar.
Afin de ne pas écraser la grille d'ouverture, une …
> [Ouverture de territoire] Pouvoir charger de multiples grilles d'affectation d'un territoire déjà ouvert

- src/Controller/Back/SignalementEditController.php
- src/Dto/Request/Signalement/CompositionLogementRequest.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
- templates/back/signalement/view/information.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
#1982   
Modale d'édition du bloc "Composition du logement"
> [BO - Signalement] Modale d'édition du bloc Composition du logement

- src/Service/Import/Signalement/SignalementImportMapper.php
#2039    
Ajout d'un trim sur les dates pour éviter des erreurs
* Modification de la commande
> [Reprise de données] Fix sur la commande d'import de signalement

- src/Controller/HomepageController.php
- templates/footer.html.twig
- templates/front/accessibilite.html.twig
#2027   
Ajout de la page de déclaration d'accessibilité et ajout d'un lien dans le footer pour y accéder
> [Accessibilité] Ajout de la page de déclaration d'accessibilité

- migrations/Version20231222132047.php
#2077    
Problème de référence
* Suppression des signalements
> [Reprise des signalement] Suppression des signalements importés de la Sarthe

- migrations/Version20231222132047.php
Voir PR https://github.com/MTES-MCT/histologe/pull/2078
> [Reprise des signalement] Suppression des signalements importés de la Sarthe 

- src/Controller/FrontSignalementController.php
#2081   
Suppression du test pour vérifier la correspondance entre code Insee et code postal
> [FO - Signalement] Suppression du test pour vérifier la correspondance entre code Insee et code postal

- src/Controller/Back/SignalementEditController.php
- src/Dto/Request/Signalement/CompositionLogementRequest.php
- src/Dto/Request/Signalement/InformationsLogementRequest.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
- templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig
- templates/back/signalement/view/information.html.twig
#2104   
Déplacement du type de logement dans la partie Composition du logement
> [BO - Signalement] Déplacement type de logement dans la partie Composition du logement

- src/EventListener/UserUpdatedListener.php
#2220 
Passage du listener `UserUpdateListener` sur l'événement `postUpdate` plutot que `onFlush` pour éviter un conflit de persistence
> [BO - Comptes user] Rattachement Partenaire impossible

- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
#2240   
Correction test suite fonctionnalité pour traitement des fichiers asynchrone
> [Tests] Correction test auto

- public/js/maps.js
#1552   
Suppression des désordres sur les éléments de la cartographie
> [BO - Cartographie] Suppression des désordres

- templates/back/signalement/view.html.twig
#2306    
Suite à retours partenaires, modification des titres des rubriques pour les photos et les documents
> [BO - Signalement] Modification des titres des parties avec les photos

- package-lock.json
Reverts MTES-MCT/histologe#2338
> Revert "Bump follow-redirects from 1.15.4 to 1.15.6"

- templates/front/cgu_agents.html.twig
- templates/front/politique_de_confidentialite.html.twig
#2349   
Mise à jour des pages CGU Pro et Politique de confidentialité 
Entrainera 3 tâches plus ou moins urgentes en lien.
> [FO - CGU] Mise à jour pages CGU Pro et Politique de confidentialité

- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
#2311   
Remplissage du champ texte de recherche d'adresse quand une option est sélectionnée
> [FO - Signalement] Remplissage du champ texte de recherche d'adresse quand une option est sélectionnée

- src/DataFixtures/Files/DesordrePrecision.yml
#2361    
Ce ticket concerne les fixtures, les labels ont été changés en prod
* Mise à jour des fixtures
>  [BO - Fiche signalement] Modifier les labels dans la composition du logement

- src/Controller/Back/ExportSignalementController.php
#2441 
Pour corriger la PR #2427 toujours dans l'objectif de réussir à trouver ce qui fait planter l'export CSV
> [QA] debug crash export csv #2441

- .github/workflows/main.yml
- tests/Functional/Controller/Back/SignalementListControllerTest.php
#2486    
Depuis l'upgrade de certaines dépendancesv (hypothèse), le crawler symfony ne fonctionne pas sur l'environnement de la CI 
* Tache d’exécution des tests est commenté en attendant d'investigué semaine pro
> [QA] Investigation tests instables

- .github/workflows/main.yml
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/Territory.yml
- src/DataFixtures/Files/User.yml
#2486    
Correction de la CI du à un mauvaise liaison dans les fixtures
* Correction sur le territoire du partenaire
* Archivage du partenaire et de l'utilisateur
> [QA] Troubleshooting CI 

- templates/back/signalement/view/photos-documents.html.twig
- templates/header.html.twig
#2492 #2495
#2492 Retrait d'un message de la fiche signalement BO
#2495 Modification du titre "A propos" en "Infos utiles" sur le front
> [BO - Photos usagers] Supprimer le message d'info

- templates/back/signalement/view/photos-documents.html.twig
#2493
BO : partie ajout de photo/docuement
- Utilisation des groupes de boutons
- Modification des icônes et couleur des boutons
- Ajout de textes explicatifs pour situation et procédure
> [BO - Doc et photos usager et partenaire] Ajustements UX / UI + ajout phrase en sous-titre

- .env
- .env.sample
- assets/styles/histologe.scss
- config/packages/twig.yaml
- config/services.yaml
- templates/back/base_bo.html.twig
- templates/base.html.twig
#2517    
Créer un accès à la doc 
* Rollback de la variable d'environnement CHATBOT_ENABLE
* Ajout d'un bouton en bas à droite avec un accès à la doc
```
CHATBOT_ENABLE=1
```
> [BO - Bot] Créer "faux Bot" lien vers la doc

- src/Form/PostalCodeSearchType.php
- templates/_partials/_modal_closed_territory.html.twig
- templates/base.html.twig
- templates/footer.html.twig
- templates/front/index.html.twig
- templates/header.html.twig
#2548    
Passe de correction html sur la page d'accueil et les parties transverses concernant la compatibilité W3C.
Je n'ai pas corrigé les `/>` sur les champs de formulaire, ça me semblait secondaire pour l'instant (et nécessitait de revoir le système complet de l'affichage des 2 formulaires de l'accueil.
> [FO - Accueil - Accessibilité] Compatibilité W3C

- migrations/Version20240513134105.php
#2482    
Mise à jour de la date d'une nouvelle migration exécuté il y'a quelque jour sur develop qui est avant la migration des création de table
* Mise à jour nom du fichier (Date)
* Ajout d'une condition si la migration a déjà été exécute (ce qui est le cas sur develop)
> [QA] Correction déploiement staging et environnement local - mise à jour dernière migration

- templates/front/accessibilite.html.twig
#2599    
Enlever [contact@histologe.info](mailto:contact@histologe.info) et mettre un lien vers la page contact
* Changement twig
> [FO - déclaration accessibilité] Modifier adresse mail 

- src/Manager/SuiviManager.php
- src/Service/Signalement/SignalementFileProcessor.php
- templates/back/signalement/view/address-qualifications.html.twig
- templates/base.html.twig
- templates/emails/affectation_email.html.twig
- templates/emails/lost_pass_email.html.twig
- templates/emails/new_signalement_email.html.twig
- templates/emails/nouveau_suivi_signalement_back_email.html.twig
- templates/emails/validation_signalement_email.html.twig
#2610    
Ajout de rel="noopener" dans les liens qui ouvrent un nouvel onglet
> [BO - email] mettre rel="noopener" dans les liens des mails

- cron.json
> Fix cron format

- src/DataFixtures/Files/DesordreCritere.yml
#2625    
Modification du label de 3 critères dans les fixtures (les commandes ont été jouées sur staging et en prod)
* Changement des fixtures
>   [BO - Désordres] Renommer certains labels de critères

- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Signalement.php
- src/Service/Idoss/IdossService.php
- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
#2660 
- Correction du nom d'un champs a envoyer a IDOSS
- Modification des fixtures pour tests (manuel) IDOSS
> Faire des tests avec tous les champs complété pour IDOSS

- config/packages/security.yaml
- src/Service/Signalement/SearchFilter.php
#2712
Correction et simplification de la requête sur le nouveau filtre "procédure"
> [BO - Dashboard] Problème sur le compteur NDE en cours

- src/Service/Signalement/SearchFilter.php
#2711    
Ce filtre doit retourner tous les signalement en cours ayant **au moins une affectation fermé** dont les signalements sont en cours
* Suppression d'une sous-requête
* Mise à jour d'une sous-requête pour ignorer les signalement fermé
**EDIT**
> [BO - Liste signalement] Revoir comportement filtre cloture pour 1 partenaire

- assets/styles/histologe.scss
- templates/back/notifications/index.html.twig
#2716
Ajout d'une classe CSS permettant de faire ds retou à la ligne sur les description de notification trop longue
Modifier un suivi donnant lieu a une notification pour qu'il contienne le mesage suivant : 
`Voici les documents demandés par email<br>Ajout de pièces au signalement<ul><li><a class="fr-link" target="_blank" rel="noopener" href="/_up/dpe-04-12-2023-ANCIENCOUVENTDESURSULINES-INDIVISIONDESCARPENTRIES-LIM-ContactDESCARPENTRIES-LIMFrederick-Thida-COLOCATIONESPRITGUYON-Contrat-ANCIENCOUVENTDESURSULINES-AppartementType4lotn35-Contrat-ANCIEN-666c12a10b256.pdf?folder=_up&t=___TOKEN___">_dpe_04_12_2023_ANCIENCOUVENTDESURSULINES_INDIVISIONDESCARPENTRIES_LIM__ContactDESCARPENTRIES&LIMFrederick&Thida_COLOCATIONESPRITGUYON_Contrat_ANCIENCOUVENTDESURSULINES_AppartementTyp …
> [BO- notifications] Gérer les retours à la ligne

- src/Controller/SignalementController.php
- src/Controller/SignalementFileController.php
- src/Entity/File.php
- src/Form/PostalCodeSearchType.php
#2739
- Ajout de contraintes sur le champ code postal de la homepage
- Ajout de contraintes sur le champ message de la page de suivi usager
- Ajout d'un contrôle sur le type de désordre lors de l'ajout d'une photo depuis la page de suivi usager
> [FO - Formulaires] Contrôle des entrées

- src/Controller/Back/SignalementListController.php
- src/Dto/SignalementAffectationListView.php
#2793    
Erreur critique aléatoire apparu sur sentry, très difficile à reproduire
Ajout d'un groupe de sérialisation pour ignorer le parcours sur l'entité User
* Ajout du groupe et prise en compte du groupe dans la réponse
> [QA] Logique exception sur User::getEmailAuthCode

- src/Controller/Back/SignalementFileController.php
- src/Entity/Partner.php
#2825 
#2824    
Check sur l'existence de chainess avant de faire des opérations dessus
* [QA - ajout d'image] Ne pas vérifier la taille de la description de l'image si elle est null
* [QA - Partenaire] Vérifier l'existence de idossUrl avant de faire un str_ends_with
> [QA - Partenaire][QA - upload] Vérifier l'existence de chaîne

- assets/vue/components/signalement-form/services/componentValidator.ts
#2758    
Correction du contrôle de la saisie d'adresse quand celle-ci est facultative
> [FO - Signalement] Correction contrôle saisie adresse quand facultatif

- README.md
- package-lock.json
- package.json
- templates/back/account/index.html.twig
- templates/back/cgu_bo.html.twig
- templates/back/expired-account/index.html.twig
- templates/back/inactive-account/index.html.twig
- templates/back/notifications/index.html.twig
- templates/back/partner/index.html.twig
- templates/back/partner/view.html.twig
- templates/back/partner_archived/index.html.twig
- templates/back/signalement_archived/index.html.twig
- templates/footer.html.twig
- templates/front/aides_travaux.html.twig
- templates/front/politique_de_confidentialite.html.twig
#2838    
Passage en version 1.12.1 du DSFR
https://github.com/GouvernementFR/dsfr/releases/tag/v1.12.0
https://github.com/GouvernementFR/dsfr/releases/tag/v1.12.1
* Mise à jour DSFR 
* Mise à jour du footer selon les indications https://github.com/GouvernementFR/dsfr/pull/905 
* Mise à jour des tableaux pour se rapprocher de la nouvelle structure dsfr (hors mail)
`npm install`
> [FO - BO]Mettre à jour DSFR (v1.12.1)

- assets/styles/histologe.scss
- templates/back/signalement/view/criticite-qualifications.html.twig
- templates/back/signalement/view/nde.html.twig
- templates/back/signalement/view/partners.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- templates/back/signalement/view/tabs/tab-foyer.html.twig
- templates/back/signalement/view/tabs/tab-situation.html.twig
- templates/back/signalement/view/visites/visite-item.html.twig
- templates/back/signalement/view/visites/visites-buttons.html.twig
- templates/back/signalement/view/visites/visites-list.html.twig
#2868
#2869
#2870
#2871
#2872
#2873
Ajustements graphiques divers pour nouvelle fiche
> [BO - Signalement] Ajustements graphiques pour nouvelle fiche

- assets/controllers/front_suivi_signalement/front_suivi_signalement.js
- src/Controller/Security/SecurityController.php
#2901
Inverse de la PR #2837 qui n'a pas donnée de résultats
> [Tech] Supprimer l'appel à keep_session_alive

- src/Serializer/SignalementDraftRequestNormalizer.php
- tests/Functional/Controller/SignalementControllerTest.php
#2860    
Correction de la bizarrerie détecté par phpstan
* Ajout des DTO supportant la dénormalisation
> [QA] Truc bizarre sur src/Serializer/SignalementDraftRequestNormalizer.php

- src/Controller/Back/SignalementController.php
- templates/_partials/_modal_upload_files.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- templates/back/signalement/view/tabs/tab-documents.html.twig
- templates/back/signalement/view/tabs/tab-situation.html.twig
#2892
- Modification de texte sur popup d'upload des documents en fonction du feature flag
- Ajout d'un bouton "Ajouter des documents usager" dans l'onglet documents
- Modification de l'affichage de la zone photo et doc de l'onglet situation (identique à la version actuelle)
> [BO - Signalement - Documents] Ajouter le bouton document situation + modifier les messages d'info dans les modales

- templates/back/signalement/view/header.html.twig
#2962   
Ajout de 3 tags dans le header de la fiche signalement
* Modification du twig
>  [Fiche Signalement] Ajout Tags

- src/Controller/HomepageController.php
- templates/footer.html.twig
- templates/front/plan_du_site.html.twig
#2948   
Ajout d'une page Plan du site, basée sur ce qui a été fait pour les Punaises
> [FO] Ajout page Plan du site

- src/Controller/Back/NotificationController.php
- src/Service/DashboardWidget/WidgetDataManagerCache.php
#2865   
Avec l'optimisation des requêtes sur les notifications (lues ou supprimées), on ne passait plus par le CacheInvalidationListener car requête en DQL. Il faut donc appeler "à la main" une fonction de suppression du cache
* Ajout d'une fonction invalidateCacheForUser dans le WidgetDataManagerCache
* Appel de cette fonction dans le NotificationController quand on supprime des notifications ou qu'on les marque comme lues
> [BO - notifications] Invalide la cache du dahboard quand on voit les notifications

- cron.json
- scripts/clean.sh
#3005    
Economie de cron
* Ajout d'un script shell qui exécute les commandes de purge
> [QA] Fusionner les commandes de purge d'entités et d'images temporaires

- tests/Unit/Factory/SignalementFactoryTest.php
#3061    
Test qui crash sur develop
* Correction test
> [QA] Correction test export

- templates/back/notifications/index.html.twig
#3076
Ajout du nom de la commune sous la référence dans la liste des notifications
> [BO - Notif] Ajouter le nom de la commune

- assets/scripts/vanilla/controllers/back_user_index/back_user_index.js
- assets/scripts/vanilla/services/component_search_checkbox.js
- assets/styles/histologe.scss
- config/packages/messenger.yaml
- src/Controller/Back/BackUserController.php
- src/Dto/SearchUser.php
- src/Form/SearchUserType.php
- src/Form/Type/SearchCheckboxType.php
- src/Messenger/Message/UserExportMessage.php
- src/Messenger/MessageHandler/UserExportMessageHandler.php
- src/Repository/UserRepository.php
- src/Service/Mailer/Mail/Signalement/SignalementUserExportMailer.php
- src/Service/Mailer/NotificationMailerType.php
- src/Service/SearchUser.php
- src/Service/UserExportLoader.php
- templates/back/signalement_export/index.html.twig
- templates/back/user/export.html.twig
- templates/back/user/index.html.twig
- templates/emails/signalement_user_export.html.twig
- templates/form/dsfr_theme.html.twig
- templates/form/form-choice-export-format.html.twig
- tests/Functional/Controller/Back/BackUserControllerTest.php
- tests/Functional/Messenger/MessageHandler/UserExportMessageHandlerTest.php
#3095
Ajout de la fonctionnalités d'export de la liste des utilisateurs
`make worker-stop`
> [BO - Liste utilisateurs] Fonction export utilisateurs

- composer.lock
#3156   
* Problème de déploiement (composant cache de symfony)
* Alerte phpoffice/phpspreadsheet ([dependantbot](https://github.com/MTES-MCT/histologe/security))
* Mise à jour composer(composer update)
```sh
-  ......
- Upgrading symfony/cache (v6.4.10 => v6.4.12): Extracting archive
- Upgrading phpoffice/phpspreadsheet (2.2.2 => 2.3.0): Extracting archive
-  .....
```
> [QA] Déploiement et sécurité

- templates/back/profil/_modal_profil_password.html.twig
- templates/back/user/index.html.twig
- templates/emails/account_soon_archived_email.html.twig
- templates/emails/nouveau_suivi_signalement_back_email.html.twig
- templates/emails/profil_edit_password.html.twig
- templates/emails/signalement_list_export.html.twig
- templates/emails/signalement_user_export.html.twig
- templates/front/accessibilite.html.twig
- templates/front/contact.html.twig
#3140   
Modification de contenu du mail de nouveau suivi
> [Notifications E-mails] Correction du contenu du mail de nouveau suivi

- src/Controller/Back/SignalementFileController.php
- src/Security/Voter/FileVoter.php
#3163
- Ajout de la permission de suppression de tous les documents pour les SA
- Pas de création de suivi/envoi de notification lors de la suppression d'un doc par SA (possibilité de crée un suivi à la main si besoin)
> [BO] feature SA suppression de photo/doc

- config/app/cron_scheduler.yaml
- src/Command/Clock/ScheduledTaskCommand.php
#3147   
La commande `php bin/console app:sync-esabora-schs` n'est plus lancé 
* Mise à jour yaml (je ne pense pas que le problème viennent de  la)
* Ajout de log pour checker la prise en charge de la commande par le scheduler
> [QA] Problème de synchro SCHS

- src/Controller/Back/AffectationController.php
- src/Controller/Back/TagController.php
- src/Service/Signalement/SearchFilterOptionDataProvider.php
#3204
Invalidation de cache à l'ajout/modification/suppression d'éiquette
make clear-pool pool=--all
> [BO - Signalement] Modification Etiquettes

- src/Service/Behaviour/SearchQueryTrait.php
- src/Service/SearchUser.php
#3255   
utiliser SearchQueryTrait dans SearchUser
* Modification searchUser
> [BO - Liste utilisateur] utiliser SearchQueryTrait dans SearchUser

- src/Controller/Back/SignalementVisitesController.php
- src/Controller/SignalementController.php
- src/Repository/SignalementRepository.php
- src/Service/Signalement/SignalementDraftHelper.php
- tests/Functional/Repository/SignalementRepositoryTest.php
#3274   
Corrections de plusieurs erreurs Sentry rares
* Ajout d'un test fonctionnel pour la fonction de récupération des signalements existants
* Ajout de tests divers sur les valeurs existantes ou non
> [QA] Correction de plusieurs erreurs Sentry

- composer.lock
#3292   
Mise à jour mineures des dépendances
dont symfony 6.4.15 https://symfony.com/blog/symfony-6-4-15-released
* composer update
> [Sécurité] Mise à jour dépendances dont symfony 6.4.15

- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
#3318    
Ajout du prénom s'il existe pour le bailleur
* Mise à jour DossierFactory
```
make worker-stop && make worker-start
```
> [SISH] Prénom bailleur

- src/Entity/Signalement.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementBuilder.php
- tests/FixturesHelper.php
#3386    
Prévenir les erreurs 
> Uncaught PHP Exception Error: "Typed property App\Entity\Signalement::xxxxxx must not be accessed before initialization" at Signalement.php 
* Typage des propriétés de la classe signalement
> [QA] Revoir classe Signalement ajout typage

- src/Controller/Api/SignalementController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/NewSignalement.yml
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/User.yml
- src/Dto/Api/Model/Desordre.php
- src/Repository/SignalementRepository.php
- src/Service/Signalement/SignalementDesordresProcessor.php
- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
- tests/Functional/Controller/Api/SignalementControllerTest.php
- tests/Functional/Controller/Back/SignalementListControllerTest.php
#3453
L'API déclenchait une erreur `Call to a member function getLabel() on array` lors du chargement d'un signalement contenant des désordre (version nouveau formulaire). Correction du bug
* Correction de la récupération des libellé des désordres dans `Dto/Api/Model/Desordre`
* Correction de la requête `findForAPI` qui cumulait leftJoin sur des relations multiple et clause limit qui provque des retours partiels
* Modification de fixtures pour pouvoir tester l'API sur un signalement version nouveau formulaire (user `api-02@histologe.fr`)
* Ajout de tests
> [BUG - API] Call to a member function getLabel() on array

- config/services.yaml
- src/Controller/Security/SecurityController.php
#3613    
CI KO depuis un merge PR
* Correction feedback php-stan
> [QA] Correction CI

- src/Repository/SuiviRepository.php
#3624
Suppression d'un dump dans une requête. Probable cause du bug dashboard remonté par mathilde sur staging
> Remove dump

- assets/scripts/app-back-bo.ts
- assets/scripts/vanilla/controllers/back_bailleur_view/back_bailleur_index.js
- src/Controller/Back/BackBailleurController.php
- src/Entity/Bailleur.php
- src/Form/BailleurType.php
- src/Form/SearchBailleurType.php
- src/Repository/BailleurRepository.php
- src/Service/ListFilters/SearchBailleur.php
- src/Service/Menu/MenuBuilder.php
- templates/back/bailleur/edit.html.twig
- templates/back/bailleur/index.html.twig
- templates/back/breadcrumb_bo.html.twig
- templates/back/territory/index.html.twig
- tests/Functional/Controller/Back/BackBailleurControllerTest.php
#3601
Ajout d'une page SA listant les bailleurs et leurs territoires associés 
Possibilité de :
- Recherche par nom/territoire
- Edition du nom du bailleur
- Suppression du bailleur si il n'est pa lié a un ou des signalements
> [FO-BO Signalement] Modifier dénomination bailleur

- src/Controller/Back/PartnerController.php
- tests/Functional/Controller/PartnerControllerTest.php
#3654    
Le changement de role n'était plus pris en compte dans l'édition d'agent
* Correction du PartnerController
* Ajout d'un test
> [BO - User] Modification Rôle impossible

- src/Service/NotificationAndMailSender.php
#3690    
Depuis la mise en prod de jeudi dernier, les utilisateurs ne recevant pas d'-emails, n'avais plus de notifications  dans l'app
* Différenciation des listes de destinataires d'e-mails et de notifications dans NotificationAndMailSender
> [BO - Notifications] Créer des notifications "app" même quand les notifications par mail sont désactivées

- src/EventListener/ExceptionListener.php
#3693    
Ignorer les notifications par mail pour le type d'exception Access Denied
* Ajouter l'exception à la liste d'exception à ignorer
> [TECH] Ne pas envoyer les mails d'erreur de type Access Denied

- assets/scripts/vue/components/stats/TheHistoAppStats.vue
- assets/scripts/vue/components/stats/TheHistoStatsFilters.vue
- assets/scripts/vue/components/stats/TheHistoStatsGlobal.vue
- assets/scripts/vue/components/stats/requests.ts
- assets/scripts/vue/components/stats/store.ts
- src/Controller/Back/BackStatistiquesController.php
- src/Dto/StatisticsFilters.php
- src/Repository/EpciRepository.php
- src/Repository/SignalementRepository.php
- src/Service/Statistics/ListEpciStatisticProvider.php
- tests/Functional/Controller/BackStatistiquesControllerTest.php
#3686
Ajout d'un filtre EPCI sur la partie stats
> [BO - Stats] Ajouter le filtre EPCI

- src/Service/Interconnection/Esabora/EsaboraManager.php
#3740
Correction d'un crash de typage `Argument #1 ($esaboraDossierStatus) must be of type string, null given`
> [QA] Error: App\Service\Interconnection\Esabora\EsaboraManager::shouldBeAcceptedViaEsabora()

- .github/workflows/main.yml
#3782
Fix CI https://github.com/actions/runner-images/issues/11101
> [TECH - CI] upgrade ubuntu version

- src/Service/NotificationAndMailSender.php
- tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
#3784
La PR #3711 à entraîné un petite effet de bord : les SA (uniquement) n'était plus notifié (notification interne) lors de la cloture pour tous d'un signalement. Cela a par effet ricochet crée un bug sur le widget "Cloture globales" qui se base sur ces notifications et donc resté avec ue valeur "aucun" depuis la MEP
- Ajout des SA pour les notification interne lors de la cloture d'un signalement
- Ajout d'un test de vérification
> [BUG] Notification SA cloture pour tous

- Makefile
- assets/scripts/vanilla/services/form_helper.js
- assets/scripts/vue/components/dashboard/TheHistoAppDashboard.vue
- assets/scripts/vue/components/dashboard/TheHistoDashboardCards.vue
- assets/scripts/vue/components/dashboard/store.ts
- config/app/widgets.yaml
- src/Controller/Back/PartnerController.php
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/User.yml
- src/Dto/CountPartner.php
- src/Form/PartnerType.php
- src/Form/SearchPartnerType.php
- src/Repository/PartnerRepository.php
- src/Service/DashboardWidget/WidgetDataKpi.php
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
- src/Service/DashboardWidget/WidgetDataManager.php
- src/Service/ListFilters/SearchPartner.php
- templates/back/partner/index.html.twig
- templates/back/partner/view.html.twig
- tests/Functional/Command/Cron/RemindInactiveUserCommandTest.php
- tests/Functional/Controller/Back/BackUserControllerTest.php
- tests/Functional/Controller/PartnerControllerTest.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Repository/PartnerRepositoryTest.php
- tests/Functional/Repository/UserRepositoryTest.php
- tests/Unit/Manager/WidgetDataManagerTest.php
- tests/Unit/Service/DashboardWidget/WidgetDataKpiTest.php
#3731    
* Supprimer les restrictions sur le mail du partenaire ou les suppressions/transfert/édition de dernier utilisateur notifiable
* RT : Ajouter un filtre dans la liste partenaire "partenaire non notifiable"
* Ajouter un widget sur le dashboard
* Ajouter un warning sur la liste des partenaires pour le RT (+ liste des agents pour l'admin partenaire)
* Ajout d'une carte sur l'app VueJS du Dashboard
* Suppression des restrictions dans le PartnerController et le PartnerType
* Dans le SearchPartnerType ajout d'une checkbox isNotNotifiable (et renommage de territory en territoire pour le lien depuis le dashboard)
* Dans le PartnerRepository, modification de getPartners, pour récupérer directement le isNotifiable pour chaque partenaire + possibilité de filtrer les partenaires pour ne …
> [BO - Notifications Email] Indiquer les partenaires sans notifications par e-mail

- src/Controller/Back/NotificationController.php
- src/Form/SearchNotificationType.php
- src/Repository/NotificationRepository.php
- src/Service/ListFilters/SearchNotification.php
- templates/back/notifications/index.html.twig
- tests/Functional/Controller/NotificationControllerTest.php
#3754
Ajout d'un filtre "Trier par" sur la page notifications
> [BO - Notifs] Ajouter fonctionnalité de tri

- assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js
- src/Controller/Back/SignalementCreateController.php
- src/Controller/Back/SignalementFileController.php
- src/Entity/Model/InformationComplementaire.php
- src/Factory/Signalement/InformationComplementaireFactory.php
- src/Form/SignalementDraftSituationType.php
- src/Security/Voter/FileVoter.php
- src/Service/Signalement/SignalementBoManager.php
- templates/_partials/_modal_upload_files.html.twig
- templates/back/signalement_create/index.html.twig
- templates/back/signalement_create/tabs/tab-situation.html.twig
#3755   
Ajout de l'onglet Situation selon le [prototype](https://xd.adobe.com/view/c9634c11-8b63-4a6b-a640-de9d30eb820e-9c30/screen/142a2922-c8a7-4da7-b890-51044923fab7/).
Ajout d'une question complémentaire citée dans le ticket (type d'allocation).
**Attention** : La gestion Ajax n'est pas encore effective. Cela pose notamment problème si l'onglet n'est pas validé et qu'on change d'onglet, ou alors qu'on ajoute/supprime des fichiers.
Un ticket a été créé ici : https://github.com/MTES-MCT/histologe/issues/3787
* Refonte pour mutualiser le js
* Modification du `FileVoter` pour accepter l'édition de fichier sur les signalements DRAFT
> [BO - Formulaire pro] Ajout de l'onglet Situation

- assets/scripts/vanilla/controllers/back_signalement_view/back_view_signalement.js
- assets/styles/histologe.scss
- src/Controller/Back/SignalementFileController.php
- templates/back/signalement/view/photos-album.html.twig
#3685   
Ajout d'une fonctionnalité de zoom dans l'album photo
* Ajout des 2 boutons dans le twig
* Ajout de script js pour gérer le zoom et le dezoom
* Modification de la css
> [BO - Photos] Pouvoir zoomer les photos

- package-lock.json
- package.json
#3823   
Suite à alerte npm, mise à jour d'Axios et autres packages
> [Tech] Mise à jour packages npm

- assets/json/Signalement/questions_profile_tous.json
#3844   
Ajout de `ou de l'immeuble` sur l'écran `adresse_logement_intro` (je ne l'avais fait que sur la page `introduction`)
* Modification du json
> [FO - Formulaire] Retour sur changement de texte PNLHI

- assets/scripts/vue/components/signalement-view/TheSignalementAppList.vue
- assets/scripts/vue/components/signalement-view/components/SignalementViewCarto.vue
- assets/scripts/vue/components/signalement-view/store.ts
- assets/scripts/vue/components/signalement-view/utils/signalementUtils.ts
- package-lock.json
- package.json
- src/Controller/Back/CartographieController.php
- src/Service/Signalement/SearchFilter.php
#3627
Affichage des zone sur la carto quand une ou des zone ont été sélectionnée dans les filtres.
`make npm-install`
> [BO - Cartographie] Mettre en surbrillance les zones

- .buildpacks
#3866    
* Utilisation de la version précédente de clamav
> [QA] Troubleshooting clamav

- README.md
- docs/API.md
#3890   
Mise en place d'une mini documentation versionnée qui pointe vers les docs automatiques existantes.
> [API] Documentation README

- src/Entity/Intervention.php
#3913    
Suite à ce commentaire https://github.com/MTES-MCT/histologe/pull/3868/files#r2003360896
* Suppression des modifs dans le getter car pas utile
> [QA] Avertissement sentry sur le détail des interventions

- assets/scripts/vue/components/front-stats/requests.ts
#3922    
Augmentation du timeout pour la requête des stats front
* Changement request.ts
> [FO - stats] timeout sur les stats

- config/app/csp.yaml
> [BUG IFRAME] Fix CSP

- migrations/Version20250401154338.php
- src/DataFixtures/Files/Territory.yml
- tests/Functional/Controller/Back/BackTerritoryControllerTest.php
#3912   
Suppression du territoire de l'Agglo de Pau
> [QA] Suppression du territoire de l'Agglo de Pau

- config/packages/nelmio_api_doc.yaml
- src/Entity/ApiUserToken.php
- templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig
#3945    
Compléter la doc avec l'info de la durée de validité du token
* Réduire la durée de validité
* Ajouter l'information dans la documentation
* Ajout du nouveau logo dans le swagger http://localhost:8080/api/doc/swagger
> [API] Documentation - Préciser la durée de validité du token

- src/Controller/Back/ProfilController.php
- src/Entity/User.php
- templates/back/profil/_modal_profil_infos.html.twig
#3954
- Limitation du champ "fonction" à 50 caractères
- Ajout de la mention "facultatif" sur le champ fonction dans la modal d'édition de la page pro
> [BO - Profile] Limiter le champ fonction à 50 caractères

- migrations/Version20250408132851.php
- src/Controller/Back/ProfilController.php
- templates/back/profil/index.html.twig
#3938   
Affichage des informations des RT sur la page de profil du BO
> [BO - Profil] Affichage des informations des RT

- config/packages/test/monolog.yaml
#3971    
Continuer de logger dans un fichier en environnement de test 
* Mise à jour monolog test
> [QA] Logger dans un fichier en environnement de test

- config/app/csp.yaml
#4022   
Iframe non visible
* Mise à jour CSP yaml
> [CSP] Site facile demo - Autoriser le chargement des iframes

- templates/security/login_suivi_signalement.html.twig
#4008   
Modification du texte d'introduction du formulaire d'authentification de la page suivi usager
> [Suivi usager] Modification du texte d'introduction du formulaire d'authentification

- assets/scripts/vanilla/controllers/back_signalement_view/pick-localisation.js
- assets/scripts/vanilla/services/component_search_address.js
- assets/scripts/vue/components/signalement-form/store.ts
- config/app/csp.yaml
- src/Service/Gouv/Ban/AddressService.php
#3965   
Modification de l'url de la BAN qui ne sera plus accessible en janvier 2026
> [Tech] Modification de l'url de la BAN

- templates/back/profil/_modal_profil_notification_email.html.twig
#4055
Ajout d'un saut de ligne
> [BO - Profil - Notif email] Retour à la ligne

- assets/scripts/vanilla/controllers/back_signalement_form/back_signalement_form.js
- src/Controller/Back/SignalementCreateController.php
- src/Form/SignalementDraftCoordonneesType.php
- src/Form/SignalementDraftSituationType.php
- src/Service/Signalement/SignalementBoManager.php
- templates/back/signalement_create/tabs/tab-coordonnees.html.twig
- templates/back/signalement_create/tabs/tab-situation.html.twig
#4030
- Ajout de la question date du DPE
- Ajout du choix "Propriétaire occupant" dans la liste des profils de l'onglet coordonées, qui dépend de l'option correspondante dans l'onglet adresse
- Contrôle des champs obligatoires sur l'onglet validation
> [FORM PRO] date DPE et gestion du profil

- src/Command/AffectationToPartnerCommand.php
#3973
Dans la première version de la commande, nous avons garder les affectations existantes dans leurs statuts initial. Il fallait en réalité passer celle "En attente" en "Accepté". La nouvelle version de la commande corrige ce cas particulier.
La seule possibilité pour tester la commande en condition réelle est de récupérer la base de prod de cette nuit (15/05) ou ultérieure.
> [Affectations] Partenaire VdM SHH, correction du statut

- src/Controller/Back/SignalementCreateController.php
- tests/Functional/Controller/Back/SignalementCreateControllerTest.php
#4095    
Création des usager occupant/déclarant
Il faut l'ajouter à l'étape validation du formulaire PRO
(la partie mise à jour de l'existant a été faite par Saidi directement en base)
* Modification du SignalementCreateController pour créer les user si besoin et les lier au signalement
> [TECH - Form PRO] Creation user usager automatique

- Makefile
- docs/SECURITY.md
- docs/incident-response/README.md
- docs/incident-response/procedure-database-deletion.md
- docs/incident-response/template-postmortem.md
- docs/incident-response/template-procedure.md
#4151   
Ajout procédure de la gestion d'incident d'une base de donnée
* Ajout documentation
> [Sécurité] Documentation gestion incident base de donnée

- assets/styles/histologe.scss
- src/Controller/SignalementController.php
- templates/front/_partials/_desordre.html.twig
- templates/front/_partials/_suivi_signalement_tab_infos.html.twig
- templates/front/suivi_signalement_dossier.html.twig
#4070
Mise en page de la nouvelle page "Détail du dossier" du suivi usager
> [FO - Suivi usager] Page d'info du signalement

- src/Command/PushEsaboraDossierCommand.php
- tests/Unit/Command/PushEsaboraDossierCommandTest.php
#4258    
Lever la restriction sur is-synchronized
* Correction commande et test
> [QA] Corriger la commande PushEsaboraDossierCommand

- src/Command/ImportGridAffectationCommand.php
- src/DataFixtures/Files/Territory.yml
- tests/Functional/Controller/Back/BackTerritoryControllerTest.php
- tests/Functional/Service/Signalement/PostalCodeHomeCheckerTest.php
#4296    
Mise à jour du lien
* Mise à jour du lien 
* Mise à jour fixtures territoire
> [QA] Mise à lien filtre partenaire commande grille d'affectation

- src/Controller/Back/InterconnexionController.php
- src/Form/SearchInterconnexionType.php
- src/Form/Type/TerritoryChoiceType.php
- src/Repository/JobEventRepository.php
- src/Service/ListFilters/SearchInterconnexion.php
- src/Service/Menu/MenuBuilder.php
- templates/back/interconnexion/index.html.twig
- tests/Functional/Controller/Back/InterconnexionControllerTest.php
#4279    
Création d'une page pour lister les job_event, avec filtre par territoire, partenaire et statut
On filtre sur les 30 derniers jours (ça fait déjà beaucoup d'éléments)
* Création du controller InterconnexionController
* Création du formtype SearchInterconnexion
* Création de 2 requêtes dans le jobeventrepository
* Ajout du lien dans le menu
* Création du twig
* Ajout de test
> [BO - Outils SA] Liste connexions SI externes

- src/Controller/Security/CspReportController.php
- tests/Functional/Controller/Security/CspReportControllerTest.php
> [Tech] Ignorer les erreurs CSP provoquées par des extensions navigateur

- src/Form/SearchInterconnexionType.php
- src/Repository/JobEventRepository.php
- src/Service/Interconnection/Esabora/EsaboraSCHSService.php
- src/Service/Interconnection/Idoss/IdossService.php
- src/Service/ListFilters/SearchInterconnexion.php
- templates/back/interconnexion/index.html.twig
- tests/Functional/Controller/Back/InterconnexionControllerTest.php
- tests/Functional/Repository/JobEventRepositoryTest.php
#4372    
Suite à un usage en condition réelle, il faudrait pouvoir ajouter les filtres suivants :
- référence
- événement (action)
* Changement de la requête dans JobEventREpository
* Changement du formtype et du ListFilter
* Ajout de tests
> [BO - Outils SA] Ajouter des filtres à la liste connexions SI externes

- templates/_partials/_modal_upload_files.html.twig
- templates/back/signalement/view/tabs.html.twig
#4415
Modification du nom de l'onglet "Documents" en "Documents et photos"
> [BO - Signalement] Renommer l'onglet Documents

- .docker/php-fpm/Dockerfile
- .docker/php-worker/Dockerfile
- config/services.yaml
- src/Controller/HomepageController.php
- templates/back/cgu_bo.html.twig
- templates/footer.html.twig
- templates/security/login.html.twig
- tests/Functional/Controller/Back/CguControllerTest.php
#4392    
Mise à jour des CGU
* Ajout d'un lien sur la page de connexion pour les afficher en modale
* Suppression d'un lien caduc dans le BO
> [BO - CGU] Mise à jour

- src/Controller/Back/AdminTerritoryFilesController.php
- src/Controller/Back/TerritoryManagementController.php
- src/Entity/Enum/DocumentType.php
- src/Form/SearchTerritoryFilesType.php
- src/Repository/FileRepository.php
- src/Service/ListFilters/SearchTerritoryFiles.php
- templates/back/admin-territory-files/index.html.twig
- templates/back/territory-management/index.html.twig
#4489   
Affichage de la liste des documents pour les admin.
Pour l'instant, aucune donnée de test n'a été ajoutée, et la structure de BDD n'a pas été modifiée, donc il n'y a pas encore de gestion par territoire.
> [BO - Espace documentaire] Liste des documents

- composer.lock
> [Tech] Fix CI

- tests/Functional/Command/Cron/RemindPendingDraftsCommandTest.php
> [Tech] Fix test RemindPendingDraftsCommandTest

- src/Controller/Back/AdminTerritoryFilesController.php
- src/Entity/File.php
- src/Form/AddTerritoryFileType.php
- src/Form/TerritoryFileType.php
- src/Security/Voter/FileVoter.php
- templates/back/admin-territory-files/edit.html.twig
- templates/back/admin-territory-files/index.html.twig
#4492  
Ecran de modification des détails d'un document
> [BO - Espace documentaire] Edition des détails des documents

- src/Controller/Back/AdminTerritoryFilesController.php
- tests/Functional/Controller/Back/AdminTerritoryFilesControllerTest.php
#4526   
Ajout de tests automatisés sur le controlleur
> [BO - Espace documentaire] Ajout de tests automatisés

- src/Controller/Back/AdminTerritoryFilesController.php
- src/Controller/Back/ArchivedSignalementController.php
- src/Controller/Back/AutoAffectationRuleController.php
- src/Controller/Back/BackAffectationWithoutSubscriptionController.php
- src/Controller/Back/BackArchivedPartnerController.php
- src/Controller/Back/BackArchivedUsersController.php
- src/Controller/Back/BackBailleurController.php
- src/Controller/Back/BackTerritoryController.php
- src/Controller/Back/BackUserController.php
- src/Controller/Back/BackZoneController.php
- src/Controller/Back/InterconnexionController.php
- src/Controller/Back/PartnerController.php
- src/Controller/Back/SignalementCreateController.php
- src/Controller/Back/TagController.php
- src/Controller/Back/TerritoryManagementController.php
- src/Controller/Back/UserApiPermissionController.php
- src/Form/SearchUserType.php
- src/Repository/UserRepository.php
- src/Service/Menu/MenuBuilder.php
- templates/back/user_api_permission/index.html.twig
#4556    
Afficher la liste des utilisateurs api
* Ajout nouveaux controller
* Remplacement injection service parameterbag par attribut autorwire
> [API] Interface admin de gestion permissions - Liste utilisateurs api
