MTES-MCT/histologe

- migrations/Version20220905105003.php
Lié à l'issue https://github.com/MTES-MCT/histologe/issues/481
La liste des éléments supprimer est dispo ici :
https://docs.google.com/spreadsheets/d/1YK1WzsiG4tacCwX2fLhhW2iIUKbC6osC/edit#gid=1898423288
32 critères désactivés sur la nouvelle migration exécuté lors du déploiement
https://histologe-pr499.osc-fr1.scalingo.io
```
email: admin-01@histologe.fr
password: histologe
```
> Désactivation des critères obsolètes

- src/Controller/Back/BackController.php
- templates/back/table_result.html.twig
Impossible de paginer sur les signalements
Le hotfix appliqué, génération des csrf token coté serveur
https://sentry.io/share/issue/a49685a8b3e04f659442e57185861b99/
```
Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Failed to start the session because headers have already been sent by "/app/var/cache/prod/twig/28/28f8844d559a09b35b4f8f958e5e9aad9b7d0a6f207e8a5423dce957cf41cd48.php" at line 44.")." at /build/b02e0bef-0fea-472c-8039-6565c02fe925/templates/back/table_result.html.twig line 67
```
> Hotfix: Problème de pagination des signalements ajax

- src/Repository/PartnerRepository.php
- tests/Functional/Repository/PartnerRepositoryTest.php
https://github.com/MTES-MCT/histologe/issues/566
Comme il n' y a pas de contrôle sur la création de partenaire qui vérifie si un partenaire est une commune c'est à dire présence de code insee donc il faut rajouter ce filtre pour avoir tous les partenaires génériques. 
A terme il faudra nettoyer les données et mettre `is_commune = 0` uniquement au partenaire générique et mettre les contrôles nécessaires niveau UI
> rollback add filter to select if partner is commune or not commune

- public/js/maps.js
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/User.yml
- src/DataFixtures/Loader/LoadPartnerData.php
- src/Repository/SignalementRepository.php
Sur les objets partielles au niveau de la récupération des résultats, différence entre le nombre d'objets récupérés et le nombre de résultats.
> The partial object problem in general does not apply to methods or queries where you do not retrieve the query result as objects. Examples are: Query#getArrayResult(), Query#getScalarResult(), Query#getSingleScalarResult(), etc.
Source : https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/partial-objects.html
La fonctionnalité a été dépréciée depuis la 2.9 `(doctrine/orm)`, la DQL devra donc être réécrite.
Sur le projet nous sommes en 2.12
```
$ composer show | grep doctrine/orm
doctrine/orm                         2.12.2    Object-Relational-Mapper for PHP
```
Etant donné qu'on ne récupère jamais 300 objets max …
> Cartographie: affichage des clusters de points des territoires

- src/Controller/Back/BackPartnerController.php
- src/Entity/Partner.php
- templates/back/partner/index.html.twig
LIé à https://github.com/MTES-MCT/histologe/issues/589
- En tant que super administrateur je dois voir apparaître le filtre territoire sur la page partenaire
- En tant que super administrateur, les partenaires de mon territoires doivent continuer à s'afficher
> Filtre territoire page partenaire pour le rôle administrateur

- src/EventSubscriber/UserAddedSubscriber.php
- src/Factory/UserFactory.php
- src/Service/GridAffectation/GridAffectationLoader.php
- tests/Unit/Factory/UserFactoryTest.php
Envoyer le nouveau lien d'activation de compte qui arrivent directement sur la saisie du mot de passe et non sur le formulaire d'oubli du mot de passe
> UserAddedSubscriber impacte l'import de la grille d'affectation

- .github/workflows/main.yml
- src/Command/ClearNotificationCommand.php
- src/Command/FixUserPasswordInactiveCommand.php
- src/Command/RemindInactiveUserCommand.php
- src/EventListener/ActivityListener.php
- src/Form/PartnerType.php
- src/Service/NotificationService.php
- templates/emails/cron_email.html.twig
- templates/emails/erreur_signalement_email.html.twig
- tests/Functional/Command/ClearNotificationCommandTest.php
- tests/Functional/Command/RemindInactiveUserCommandTest.php
https://sentry.incubateur.net/share/issue/797fa3a26fb74d3581c8d9f1dcffdbc7/
Suite à l'évolution de ne plus notifier l'utilisateur courant et de rendre le mail partenaire obligatoire
2 signalements n'ont pas trouvé d'utilisateur à notifier
Avant d'envoyer le mail, vérifier la présence d'utilisateur à notifier, logger en erreur le cas échéant afin de rentrer en contact avec le partenaire.
* Envoi mail notification pour les commandes exécuté via un cron
* Mise à jour du validateur partenaire (ignorer es utilisateurs inactifs)
* Mettre un mot de passe par défaut à tous les utilisateurs inactifs
> [BO] Vérifier qu'il existe au moins un utilisateur à notifier, loguez le cas échéant

- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/Suivi.yml
- src/DataFixtures/Files/User.yml
- src/EventListener/ActivityListener.php
- tests/Functional/Controller/BackAssignmentControllerTest.php
- tests/Functional/Manager/UserManagerTest.php
- tests/Unit/Factory/UserFactoryTest.php
Lié  à #741 
- MAJ des noms de partenaires, les rendre générique en rapport avec leur mails (facilite les tests)
- MAJ des affectations (+ cohérent)
> Réinitialiser la liste des destinataires après chaque envoi de mail

- README.md
- src/Controller/Back/BackAssignmentController.php
- src/Event/AffectationAnsweredEvent.php
- src/EventSubscriber/AffectationAnsweredSubscriber.php
- src/EventSubscriber/SignalementClosedSubscriber.php
- src/Factory/SuiviFactory.php
- src/Manager/AffectationManager.php
- src/Manager/SignalementManager.php
- src/Manager/SuiviManager.php
- src/Service/Sanitizer.php
- tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
- tests/Functional/Manager/AffectationManagerTest.php
- tests/Unit/Factory/SuiviFactoryTest.php
|Noms des routes  | Remarque         |
|------------------------|-----------------------|
| back_signalement_toggle_affectation |   Appelle Esabora |
| back_signalement_affectation_response |   - |
- Création et suppression des affectations délégué à `AffectationManager`.
- Création des suivi délégué aux classes `SuiviFactory`  et `SuiviManager`.
- Création d'une classe statique `Santizer` qui permet de nettoyer les messages de suivi.
- Ajout d'un `AffectationAnsweredEventSubscriber` qui va écouter l’événement `AffectationAnsweredEvent` correspondant aux réponses d'affectations.
- Ajout d'un test `AffectationManagerTest` qui couvre la suppression des affectations pour tous les partenaires ou plusieurs
> Préparation gestion des flux esabora lors de l'affectation

- cypress/e2e/spec.cy.js
- src/Controller/FrontSignalementController.php
- src/EventListener/ExceptionListener.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
#754 
- Prise en compte du `csrf_token` dans le formulaire usager
- Ne pas envoyer d'email lors d'une erreur 405 
- Vérification du code postal occupant
- Mise à jour des tests
> [Security] Empêcher les spams envoyés chaque matin

- cron.json
- scripts/open-territory.sh
#764 
Suite à une erreur de build
```
-----> cron.json detected, creating cron tasks
!     The deployment failed due to an error in the cron tasks creation
!     400 Bad Request → You exceeded the max amount of cron tasks possible (max is 5). Please contact the support to increase this limit.
```
> [BO] Automatiser l'ouverture territoire pour le 2 janvier 

- tests/Functional/Signalement/ReferenceGeneratorTest.php
Le test `testGenerateReferenceFromExistingSignalement` plante depuis 2023
> [Test][CI] Applique un mock pour la génération des références

- .docker/php-worker/Dockerfile
- .docker/php-worker/supervisord.conf
- .slugignore
- Makefile
- Procfile
- README.md
- config/packages/messenger.yaml
- docker-compose.yml
- migrations/Version20221201010259.php
- src/Command/SynchronizeEsaboraCommand.php
- src/Controller/Back/BackAssignmentController.php
- src/EventSubscriber/WorkerMessageEventSubscriber.php
- src/Messenger/Message/DossierMessage.php
- src/Messenger/MessageHandler/DossierMessageHandler.php
- src/Service/Esabora/DossierResponse.php
- src/Service/Esabora/EsaboraService.php
- templates/emails/cron_email.html.twig
- tests/Functional/Manager/JobEventManagerTest.php
- tests/Unit/EventSubscriber/WorkerMessageEventSubscriberTest.php
- tests/Unit/Factory/DossierMessageFactoryTest.php
- tests/Unit/Messenger/DossierMessageTrait.php
- tests/Unit/Messenger/MessageHandler/DossierMessageHandlerTest.php
- tests/Unit/Service/Esabora/DossierResponseTest.php
- tests/Unit/Service/Esabora/EsaboraServiceTest.php
#773
> Déployé sur https://histologe-staging-pr839.osc-fr1.scalingo.io/
Jusqu’à maintenant l'envoi des dossiers vers ESABORA lors dune affectation se faisait en synchrone. Des retours d'affectations impossible ont été remontés, il faut permettre l'affectation peu importe si l'envoi des dossiers vers ESABORA échoue ou réussit
> Une refonte a été effectué afin de permettre à terme l'envoi de dossier en asynchrone (voir PR #753) 
- Activation du mode asynchrone via le composant messenger 
- Ajout d'un nouveau service docker phpworker afin de dépiler les messages de queue
- Ajout de tache au Makefile afin de gérer le worker
- Mentionner le nombre de signalement synchronisé et non synchronisé dans le mail 
- Meilleure gestion des erreurs
- Activation du worker scalingo 
> Lancer `make build` …
> [BO - Signalement] Rendre possible les affectations abonnées à ESABORA lorsque la réponse ESABORA est KO

- composer.lock
2 packages have known vulnerabilities.
> symfony/http-kernel (v6.0.[16](https://github.com/MTES-MCT/histologe/actions/runs/4066686183/jobs/7003087779#step:13:17))
* [CVE-2022-24894][]: Prevent storing cookie headers in HttpCache
> symfony/security-bundle (v6.0.11)
* [CVE-[20](https://github.com/MTES-MCT/histologe/actions/runs/4066686183/jobs/7003087779#step:13:21)[22](https://github.com/MTES-MCT/histologe/actions/runs/4066686183/jobs/7003087779#step:13:23)-[24](https://github.com/MTES-MCT/histologe/actions/runs/4066686183/jobs/7003087779#step:13:25)895][]: Possible CSRF token fixation
[CVE-2022-24894]: 
[CVE-2022-24895]:
* Mise à jour des dépendances via `composer update` (Passage en 6.0.20)
> [Sécurité] Mise à jour des dépendances

- package.json
La version de node js n'est pas fixé et viens de passer en 19.6 et plante le déploiement
https://dashboard.scalingo.com/apps/osc-fr1/histologe/deploy/5c899908-f38b-460e-aa2f-c5e9122cd8d1
Elle devrait être fixé avec la version LTS (version LTS 18.x)
https://dashboard.scalingo.com/apps/osc-fr1/histologe-staging-pr878/deploy/583664e1-27f1-48f6-a1d9-751c701276fd
> [CD] Echec déploiement depuis Node 19.6 

- src/Controller/FrontSignalementController.php
- src/DataFixtures/Files/Territory.yml
- src/Service/Signalement/PostalCodeHomeChecker.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
- tests/Functional/Service/Signalement/PostalCodeHomeCheckerTest.php
#890    
Modification nécessaire afin d'ouvrir le territoire de la haute corse.
La Haute corse et la corse du sud ont des code postaux qui commencent par 20. 
https://www.annuaire-administration.com/code-postal/departement/haute-corse.html
https://www.annuaire-administration.com/code-postal/departement/corse-du-sud.html
* Modification de l'algorithme permettant de retourner le code zip territoire.
> [FO - Signalement] Permettre les dépôts de signalement pour le territoire Haute Corse

- migrations/Version20230206075100.php
- src/Command/UpdateSuiviTypeCommand.php
- src/Controller/Back/BackSignalementActionController.php
- src/Controller/Back/BackSignalementController.php
- src/Controller/Back/BackSignalementFileController.php
- src/Controller/FrontSignalementController.php
- src/DataFixtures/Files/Suivi.yml
- src/DataFixtures/Loader/LoadSuiviData.php
- src/Entity/Suivi.php
- src/Factory/SuiviFactory.php
- tests/Functional/Controller/BackAssignmentControllerTest.php
- tests/Functional/FormHandler/ContactFormHandlerTest.php
- tests/Functional/Manager/AffectationManagerTest.php
- tests/Functional/Manager/SuiviManagerTest.php
- tests/Unit/Entity/SuiviTest.php
- tests/Unit/Factory/SuiviFactoryTest.php
#867    
Ajout d'un type sur les suivis. Ce type peut avoir 3 valeurs : 
-     suivi automatique
-     suivi usager
-     suivi partenaire
```
public const TYPE_AUTO = 1;
public const TYPE_USAGER = 2;
public const TYPE_PARTNER = 3;
```
* Ajout d'une nouvelle colonne type sur la table Suivi, et création de la migration
* Définition de la valeur du type à tous les endroits où on créé un suivi (notamment dans le SuiviFactory)
* Création d'une commande pour mettre à jour le type pour tous les suivis existants `app:suivi-type-update`
-
>  [BO - Suivi] Distinguer les suivis automatiques des suivi utilisateurs 

- src/EventListener/ActivityListener.php
Repasser en PHP 8.0 / SF 6.0
```
$ mail build 
```
#841    
Les responsables territoires COR sont notifiés par e-mail des signalements MDL et ceux de la MDL sont notifiés par les signalements COR.
* Ajout d'une fonction qui récupère le partenaire selon le code INSEE du signalement, seul le territoire 69 est impactés (présence des codes INSEE dans le fichier de configuration)
> [Territoire 69] Filtrer les notifications par e-mail

- src/Command/CalculateNewCriticiteCommand.php
#954    
Création d'une commande pour calculer la nouvelle criticité de tous les signalements existants
* Création d'une commande
> [BO - Signalement] Faire une commande pour recalculer la criticité de tous les signalements en prod

- src/DataFixtures/Files/Criticite.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Loader/LoadCriticiteData.php
- src/DataFixtures/Loader/LoadSignalementData.php
Ajout de la qualification dans les fixtures des criticites, car elles sont faites en migration (pour la prod) et étaient écrasées par les fixtures. Ajout aussi d'une date d'entrée et de bail pour les 2 signalements NDE
* Liste
* des changements techniques
* apportés
> Add Data in fixtures criticites and signalements

- src/EventListener/ActivityListener.php
#957    
Correction sur le type de notification originale dans le mail "Aucun utilisateur notifiable pour le signalement" pour vérifier que ce ne sont pas des doublons purs, mais plusieurs cas différents sur un même signalement
* Correction sur le type de notification dans le mail
> [BO - notifications] Investiguer sur le doublons de mails "aucun utilisateur notifiable pour le signalement ..."

- migrations/Version20230224152702.php
- src/Controller/Back/BackSignalementController.php
- src/Controller/Back/BackSignalementQualificationController.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Criticite.php
- src/Entity/Enum/QualificationStatus.php
- src/Entity/SignalementQualification.php
- src/Security/Voter/SignalementVoter.php
- src/Service/Signalement/SignalementQualificationService.php
- templates/_partials/_modal_edit_nde.html.twig
- templates/back/signalement/view.html.twig
- tests/Functional/Controller/BackPartnerControllerTest.php
- tests/Functional/Controller/BackSignalementControllerTest.php
- tests/Functional/Controller/BackSignalementQualificationControllerTest.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Repository/PartnerRepositoryTest.php
- tests/Functional/Service/Signalement/SignalementQualificationServiceTest.php
- tests/Unit/Factory/CommuneFactoryTest.php
#932   
-     L'ajout d'une partie dédiée à la non décence énergétique dans la fiche signalement
-     Ouverture d'une modale pour éditer les informations
Spécs : https://github.com/MTES-MCT/histologe/wiki/Gestion-NDE/
[Maquette](https://xd.adobe.com/view/3fe7a859-dfae-4bc6-99a6-650ce6a179d5-6ab4/) fiche signalement avec infos non décence énergétique
* renommer desordres en criticites dans la table signalement_qualification
* création des signalement_qualification pour les signalements en fixtures
* création d'un enum QualificationStatus
* Dans BackSignalementController, récupération de la qualification et envoi des informations à la vue pour afficher la nouvelle partie sur la NDE
* Création d'une modale pour éditer ces informations
* Création de BackSignalementQualificationController …
> [BO - Signalement] Affichage des informations de non décence sur la fiche signalement

- assets/vue/components/dashboard/TheHistoAppDashboard.vue
[#988](https://github.com/MTES-MCT/histologe/issues/988) 
Correction de l'affichage des affectations des partenaires dans le tableau de bord pour les Responsables territoire
> [BO - Dashboard] Correction de l'affichage des affectations des partenaires dans le tableau de bord

- README.md
- assets/vue/components/dashboard/TheHistoDashboardTables.vue
- config/app/widgets.yaml
- config/services.yaml
- src/DataFixtures/Files/User.yml
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
#964
Activer les cartes cardSansSuivi et cardNouveauxSuivis pour les admin partenaires 
* Mise à jour des fixtures pour ajout utilisateurs avec le rôle ROLE_ADMIN_PARTNER
* Prise en compte du partenaire pour les utilisateurs avec le role ROLE_ADMIN_PARTNER
> [BO - Dashboard] Cartes inactives pour admin partenaire

- .docker/php-fpm/Dockerfile
- composer.json
- config/services.yaml
- scripts/postdeploy.sh
#969 
Revue de la check-list symfony pour vérifier que la plateforme et le serveur sont configurés pour des performances maximales.
https://symfony.com/doc/current/performance.html#:~:text=Production%20Server%20Checklist%3A
https://dashboard.scalingo.com/apps/osc-fr1/histologe-staging-pr983/deploy/list
* Ajout wkhtmltopdf en environnement de dev (on ne pouvait pas générer des pdf en local)
* MAJ composer.json afin de modifier la configuration par défaut du php.ini
https://doc.scalingo.com/languages/php/start
https://github.com/Scalingo/php-buildpack
> [Performance] Revue de la checklist performance recommandation symfony

- src/Dto/CountSignalement.php
- src/Entity/Suivi.php
- src/EventListener/ActivityListener.php
- src/Repository/NotificationRepository.php
- src/Repository/SignalementRepository.php
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
- src/Service/DashboardWidget/WidgetDataManagerCache.php
- templates/back/index.html.twig
- tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
- tests/Functional/EventSubscriber/SignalementViewedSubscriberTest.php
- tests/Unit/Dto/CountSignalementTest.php
#963  
Les compteurs des cartes clôturés globales et  partenaires doivent être mise à jour  selon les le signalement a été vu par l'utilisateur
* Mise à jour requête compteur clôtures globales
* Mise à jour requête compteur clôtures partenaires
* Mise à jour DTO CountSIgnalement
* Bandeau statistique liste de signalement caché
> [BO - Dashboard] Compteurs ne se mettent pas à jour (Clôtures global & partenaires)

- src/Controller/Back/BackCartographieController.php
- src/Controller/Back/BackController.php
- src/Service/SearchFilterService.php
#[941](https://github.com/MTES-MCT/histologe/issues/941)   
Correction pour l'affichage du nombre de filtres actifs quand on clique depuis le Dashboard
> Correction pour l'affichage du nombre de filtres actifs quand on clique depuis le Dashboard

- package.json
NO-TICKET   
La version node 18.15 est sorti https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V18.md#18.15.0
mais le buildpack scaling ne le prend pas en charge
Tous les déploiements sont en echec depuis
https://dashboard.scalingo.com/apps/osc-fr1/histologe-staging/deploy/list
* Forcer la version de node dans le package.json
> [CD] Forcer la version de node à 18.14.2

- package-lock.json
- src/EventSubscriber/SuiviCreatedSubscriber.php
#996    
Suite à `SuiviCreatedSubscriber` qui écoute les ajout de suivi en mettant à jour la date de dernier suivi dans la table signalement, une régression a été constaté sur les mises à jour de signalements. Plus aucune mise à jour est possible
Il faut garder en tête que les modifications d'un signalement entraîne la création d'un nouveau suivi,
```php
$signalement = $entity->getSignalement(); // deja persisté et en cours de flush
$signalement->setLastSuiviAt($entity->getCreatedAt());
````
Sur l’événement onFlush, le subscriber va récupérer un signalement déjà modifié et doit rajouter la date de dernier suivi. 
En gros pour faire simple je demande à doctrine de merger le signalement dans l'état avec la mise à jour effectué dans le onFlush donc ce n'est pas `computeChangeSet` mais …
> [BO - Signalement]  Régression mise à jour

- config/services.yaml
- src/Service/UploadHandlerService.php
- tests/Functional/Service/UploadHandlerServiceTest.php
#979 
Lors de la saisie d'un signalement, si l'usager envoie des fichiers, on stocke ces fichiers directement dans le dossier /tmp du cloud plutôt que sur le serveur.
* Stockage sur cloud direct à l'envoi
* Déplacement dans le bon dossier quand le signalement est validé
> Stockage des fichiers directement sur le cloud lors de la saisie d'un signalement

- templates/back/table_result.html.twig
#949    
Différencier les partenaires ayant refusés une affectation de ceux ayant clôturés le signalement pour leur partenaire.
* Changement de style des affectations partenaires dans la liste des signalements
> [BO - Affectation] Différencier visuellement les refus / clôture par partenaire

- migrations/Version20230313140816.php
- src/Controller/Back/BackStatistiquesController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Loader/LoadAffectationData.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Affectation.php
- src/Entity/Enum/MotifCloture.php
- src/Entity/Signalement.php
- src/EventSubscriber/SignalementClosedSubscriber.php
- src/Factory/SignalementFactory.php
- src/Factory/SuiviFactory.php
- src/Form/ClotureType.php
- src/Manager/AffectationManager.php
- src/Manager/SignalementManager.php
- src/Service/Import/Signalement/SignalementImportLoader.php
- src/Service/Import/Signalement/SignalementImportMapper.php
- src/Service/Statistics/FilteredBackAnalyticsProvider.php
- src/Service/Statistics/MotifClotureStatisticProvider.php
- tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Manager/SuiviManagerTest.php
- tests/Functional/Service/Import/Signalement/SignalementImportLoaderTest.php
- tests/Unit/Factory/SignalementFactoryTest.php
- tests/Unit/Factory/SuiviFactoryTest.php
#810 
#631
Ajout d'option pour les motifs de cloture.
Par défaut, aucun motif ne soit sélectionné et qu'on mette "Sélectionner un motif" en placeholder dans le champ
* Transformation de MotifCloture en vrai enum
* Modification du form pour utiliser l'enumType Symfony
* Modification du form pour ne pas avoir de motif sélectionné par défaut
* Migration pour changer les motifs de cloture existants pour les signalements et affectations
> [BO - Signalement] Compléter Motifs de cloture RT/Partenaires et Aucun motif sélectionné par défaut

- src/Command/UpdatePartnerAndCommuneNDECommand.php
Ajout des communes suivantes dans la liste des communes en zone permis de louer : 
|63650 | 63231 | La Monnerie-le-Montel | LA MONNERIE-LE MONTEL|
|63290 | 63291 | Puy-Guillaume | PUY-GUILLAUME|
* Ajout des codes insee dans la commande `app:update-partners-communes-nde`
> [NDE] add 2 communes in zone parmis de louer

- src/FormHandler/ContactFormHandler.php
- src/Repository/SignalementRepository.php
- tests/Functional/FormHandler/ContactFormHandlerTest.php
#1031    
Si la personne qui envoie un message via le formulaire de contact a fait plusieurs signalements, on envoie un mail plutôt que d'ajouter un suivi au signalement car on ne sait pas quel signalement est concerné
* Ajout d'un try/catch sur le code d'ajout de suivi
> [QA] formulaire de contact, possible d'avoir plusieurs signalements pour un déclarant

- assets/controllers/form_nde.js
- src/Controller/Back/BackSignalementQualificationController.php
- src/Controller/FrontSignalementController.php
- src/Dto/Request/Signalement/QualificationNDERequest.php
- src/Factory/SignalementQualificationFactory.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/QualificationStatusService.php
- src/Service/Statistics/MotifClotureStatisticProvider.php
- templates/_partials/_modal_edit_nde.html.twig
- templates/back/signalement/view.html.twig
- tests/Functional/Controller/BackSignalementQualificationControllerTest.php
#1049    
Correction de bugs et comportement inadéquats repérés pendant la démo
* Changements des champs dates en champs radiobutton avant/après pour dateDernierBail et dateDernierDPE
* Passages des valeurs des 3 champs dates pour '1970-01-01' et '2023-01-02'
* Correction du calcul du statut dans QualificationStatusService
* Correction de doublons dans MotifClotureStatisticProvider.php
- Mettre à jour la base de données et les fixtures
- `symfony console app:commune-filler`
- `symfony console app:update-partners-communes-nde`
- `npm run build`
> [NDE][BO - Signalements] 3 petits bugs relevés pendant la démo

- public/js/maps.js
#1059    
Vérification de la latitude et la longitude d'un signalement au moment de l'affichage sur la carto
* Ajout d'une contrainte dans le js pour être sûrs que ce sont des nombres
> [BO - Carto] Les signalements sur la carto ne sont pas cliquables

- src/Service/Statistics/GlobalAnalyticsProvider.php
[#Discussion mattermost liée   ](https://mattermost.incubateur.net/betagouv/pl/y1zhsemji7g5bp4e56kntasf6y)
Prends en compte les deux motifs de clotures : TRAVAUX_FAITS_OU_EN_COURS et RELOGEMENT_OCCUPANT
* Ajoute un motif dans le provider de stats
> [FO - Stat] Foyers sorti du mal logement : ajoute les relogements aux travaux faits

- src/DataFixtures/Loader/LoadSuiviData.php
- src/Repository/SignalementRepository.php
- templates/back/signalement/view.html.twig
#785   
Filtre territoire manquant sur widget Signalements acceptés mais sans suivi
* Prise en compte du filtre
> [BO - Dashboard] Filtre manquant widget Signalements acceptés mais sans suivi

- cron.json
- src/Command/AskFeedbackUsagerCommand.php
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/Suivi.yml
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Suivi.php
- src/EventListener/ActivityListener.php
- src/Factory/SuiviFactory.php
- src/FormHandler/ContactFormHandler.php
- src/Repository/SignalementRepository.php
- src/Repository/SuiviRepository.php
- src/Service/NotificationService.php
- src/Service/Signalement/SuiviHelper.php
- templates/back/signalement/view.html.twig
- templates/back/table_result.html.twig
- templates/emails/demande_feedback_usager_email.html.twig
- templates/front/suivi_signalement.html.twig
- tests/Functional/Command/AskFeedbackUsagerCommandTest.php
#800    
Envoyer un mail à l'occupant tous les mois pour savoir s'il est toujours dans le logement ou non
-     Signalement ouvert & validé
-     Au bout de 30 jours après validation du signalement, si pas de suivi partagé à l'usager
-     Puis tous les 30 jours, si pas de suivi partagé à l'usager
* Création d'un nouveau type de suivi, TECHNICAL, qui n'a pas d'auteur, et qui ne créé pas de notification
* Création d'une commande `app:ask-feeback-usager` qui récupère tous les signalements ouverts et validés, n'ayant eu aucun suivi technique, usager ou partenaire depuis 30 jours. Pour chacun de ces signalements, envoi du mail aux usagers et création d'un suivi technique 
* Ajout d'un job cron, tous les jours à 9h pour faire tourner cette commande
* Mise en forme différente de ces suivis …
> [Notification] en cas d absence de suivi partagé sur 30 jours, envoyer mail de suivi automatique / demander feedback à l usager

- src/Entity/Enum/MotifCloture.php
- src/Service/Statistics/MotifClotureStatisticProvider.php
#1066    
Modification du texte d'un motif de cloture.
On remplace `Responsabilité de l'occupant` par `Responsabilité de l'occupant / assurantiel`
> Modification du texte d'un motif de cloture

- templates/back/signalement/view.html.twig
#1084    
Correction pour laisser la zone NDE visible sur les signalements même si l'affectation est clôturée
Affecter un signalement NDE à différents partenaires
Utiliser un utilisateur dans un partenaire avec la compétence NDE
Accepter puis clôturer l'affectation
> [BO - Fiche signalement NDE] Correction pour laisser la zone NDE visible sur les signalements même si l'affectation est clôturée

- src/Controller/FrontSignalementController.php
- src/Form/PartnerType.php
#1087    
Beaucoup d’événements sentry à ce jour sur ces dépréciations
* La constante `FILTER_SANITIZE_STRING` est obsolète, la remplacer par 
https://www.php.net/manual/en/filter.filters.sanitize.php#:~:text=flags%20to%200.-,FILTER_SANITIZE_STRING,-%22string%22
> [QA] Correction code déprécié

- src/Command/AskFeedbackUsagerCommand.php
#1098 
Vérifie qu'il existe un code de suivi pour le signalement avant d'envoyer une demande de feedback à l'usager (erreur sentry https://sentry.incubateur.net/share/issue/1caa9c43ce4542cda7a606996e0ad7b9/)
* idem
> [Tâche auto] Commande de demande de feedback usager, Vérifie qu'il existe un code de suivi 

- src/Repository/SuiviRepository.php
#1101   
N'envoie pas de demande de feedback à l'usager pour des signalements importés
* Ajout d'une condition sur la requête
> [Tâche auto] Commande de demande de feedback usager, supprimer les signalements importés

- src/EventListener/ActivityListener.php
#1100    
Lorsqu'un usager ajoute un suivi (via contact ou formulaire suivi) il ne reçoit plus de notification pour son propre suivi
* On retire l'adresse mail de l'usager du tableau des adresses mails si elle correspond à l'adresse mail du créateur du Suivi
> [FO - suivi usager] Lorsqu'un usager ajoute un suivi (via contact ou formulaire suivi) il ne reçoit plus de notification pour son propre suivi

- src/Repository/SignalementRepository.php
#1111    
Affichage du tag NDE uniquement si avéré ou à vérifier dans la liste des signalements du BO
* Modification de la requête de récupération des infos de signalements
> [BO Liste signalements] Affichage du tag NDE uniquement si avéré ou à vérifier

- src/Controller/Back/BackSignalementFileController.php
- src/Controller/FrontSignalementController.php
- src/Controller/HomepageController.php
- src/Entity/Signalement.php
- src/Exception/File/MaxUploadSizeExceededException.php
- src/Exception/File/UnsupportedFileFormatException.php
- src/Form/ContactType.php
- src/Form/PostalCodeSearchType.php
- src/Service/UploadHandlerService.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
- tests/Functional/Controller/HomepageControllerTest.php
#902    
Suite aux erreurs Sentry, ajout de quelques contraintes de validation sur les formulaires suivants:
- [Homepage] Formulaire de saisie de code postal
- [Contact] Formulaire de contact
- [Signalement] Formulaire de signalement
* Ajout de contrainte de validation sur l'entité Signalement (cpOccupant, telProprio)
* Ajout de contrainte de validation sur le formulaire de contact 
* Ajout de contrainte de validation sur le formulaire de code postal
* Renvoie une exception si le format de fichier est HEIF/HEIC
> [QA] Contrainte de validation manquante formulaires

- assets/styles/histologe.scss
#1050    
Mise en place d'une largeur max pour les tableaux pour éviter des dépassements en largeur lors de copier-coller.
* Ajout d'une règle css sur les tableaux concernés
> [BO Notifications] Mise en place d'une largeur max pour les tableaux

- src/Controller/Back/SignalementController.php
- src/Service/Signalement/QualificationStatusService.php
- src/Twig/AppExtension.php
- templates/back/signalement/view.html.twig
- templates/base.html.twig
#1118    
Affichage de la qualification NDE sur la page signalement uniquement si avérée ou à vérifier
* Renommage controller BackSignalementController en SignalementController
* Ajout d'une variable pour tester si on affiche la zone / si on affiche la qualification
> [BO Signalement] Affichage de la qualification NDE sur la page signalement uniquement si avérée ou à vérifier

- src/Controller/Back/ExportSignalementController.php
- src/Dto/SignalementExport.php
- src/Entity/Enum/AffectationStatus.php
- src/Entity/Enum/SignalementStatus.php
- src/Factory/SignalementAffectationListViewFactory.php
- src/Factory/SignalementExportFactory.php
- src/Manager/SignalementManager.php
- src/Repository/SignalementRepository.php
- src/Service/Signalement/Export/SignalementExportHeader.php
- src/Service/Signalement/Export/SignalementExportLoader.php
- src/Service/Signalement/SignalementAffectationHelper.php
- tests/Unit/Factory/SignalementExportFactoryTest.php
- tests/Unit/Service/Signalement/Export/SignalementExportLoaderTest.php
- tests/UserHelper.php
#666 
Refactorisation de l'export des signalement avec mises à jour des colonnes et normalisation des valeurs des données
* Mise à jour des noms de colonnes
* MIse à jour des status, motif de cloture, date au bon format
* Création d'un service `SignalementExportLoader`
> [BO - Export] Revoir l'export des signalements

- migrations/Version20230407115407.php
#993    
Migration pour ajouter les territoires des partenaires des utilisateurs qui n'ont pas de territoire. Ceci pour permettre de voir si à nouveau des utilisateurs perdent leur territoire quand on aura sorti la nouvelle page partenaire
Aujourd'hui 295 utilisateurs concernés : https://histologe-metabase.osc-fr1.scalingo.io/question/103-user-non-usager-sans-territoire
* Ajout d'une migration
> [BO - utilisateurs] reprise de données : ajout des territoires aux utilisateurs sans territoires via partenaires

- migrations/Version20230411121503.php
#1136    
Création d'une migration attribuant 0 pour is_imported quand celui-ci est null
* création d'une migration
> [BO - signalements] corriger les signalements ayant null pour is_imported

- src/DataFixtures/Files/Suivi.yml
- src/Repository/SuiviRepository.php
#1135    
Changement du repo pour récupérer tous les signalements n'ayant pas eu de suivi public les 30 derniers jours
* Changement d'une fonction du repo
* Mise à jour des fixtures de suivi pour que les suivis "signalements validés" soient bien publics
> [Tâche auto] Commande de demande de feedback usager, pas de demande si aucun suivi partenaire ou usager

- src/Controller/FrontSignalementController.php
#1178    
Un tableau est passé dans l'url de suivi
https://sentry.incubateur.net/share/issue/2e361c3ff86e4f5fb103cb988034cc33/
* Ajout d'une condition afin de récupérer une chaine si un tableau est passé en paramètre d'url
> [QA] Problème de typage sur la récupération des emails (fiche suivi)

- src/Command/SynchronizeEsaboraCommand.php
- src/Repository/JobEventRepository.php
#1175    
En plus du code HTTP, inspecter la réponse de l'API esabora pour déterminer si c'est un succès ou un echec
* Ne plus seulement s'appuyer sur le code HTTP pour déterminer si un succès ou echec de la syncrhonisation
* Transformation du statut selon la réponse stocké en base
* apportés
> [BO - Esabora] Prendre en compte la réponse pour déterminer le statut

- src/Manager/AffectationManager.php
- src/Repository/JobEventRepository.php
- src/Service/Esabora/EsaboraService.php
- tests/Unit/Service/Esabora/DossierResponseTest.php
- tools/wiremock/src/Resources/Esabora/ws_etat_dossier_sas/etat_a_traiter.json
- tools/wiremock/src/Resources/Esabora/ws_etat_dossier_sas/etat_importe.json
- tools/wiremock/src/Resources/Esabora/ws_etat_dossier_sas/etat_non_importe.json
- tools/wiremock/src/Resources/Esabora/ws_etat_dossier_sas/etat_termine.json
#1185    
Des dossiers sont remis en attente car le service de mise à jour d'Histolloge s'appuie sur SAS_Etat alors qui faut le compléter par Doss_Etat. 
La mise à jour du statut par Esabora doit se faire à partir de deux champs renvoyé par l'API 
- SAS_Etat (A traiter / Non importé / Importé)
- Doss_Etat (en cours / terminé)
* Mise à jour des mock
* Mise à jour de l'algo prenant en compte les deux statuts pour le dossier cloturéé et en cours
> [BO - Esabora] Revoir la gestion des statuts retourné par l'API SAS_Etat ≠ Doss_Etat

- src/Factory/DossierMessageFactory.php
- tests/Unit/Factory/DossierMessageFactoryTest.php
#1204    
Suppression du numéro de rue lors de l'envoi du champ Adresse à Esabora
* Modification de la fonction d'envoi de champ
* Modification du test associé
J'avoue que j'ai testé qu'avec le test unitaire :o
> Correction de l'envoi du champ Adresse à Esabora

- templates/back/partner/view.html.twig
#1220    
Dans le BO, sur le détail d'un partenaire, il faudrait modifier l'en-tête de la colonne Emails en Notif. emails pour plus de clarté
* Changement d'un twig
> [BO - Partenaires] Modifier nom de la colonne "emails" sur la fiche partenaire

- config/app/competences.yaml
- config/services.yaml
- migrations/Version20230503082553.php
- src/Command/ImportGridAffectationCommand.php
- src/Entity/Partner.php
- src/EventSubscriber/UserUpdatedSubscriber.php
- src/Factory/PartnerFactory.php
- src/Manager/UserManager.php
- src/Service/Import/CsvParser.php
- src/Service/Import/GridAffectation/GridAffectationHeader.php
- src/Service/Import/GridAffectation/GridAffectationLoader.php
- tests/Functional/Service/Import/CsvParserTest.php
- tests/Unit/Command/ImportGridAffectationCommandTest.php
- tests/Unit/Factory/PartnerFactoryTest.php
#842   
Avoir le même implémentation technique que l'import de signalement.
Faire les vérifications avant de faire l'import.
Lister tous les pbs et ne pas faire de création. Liste de problèmes à copier-coller à l'équipe impact.
Sinon, processer le fichier, en prenant en compte les nouveaux types et en ajoutant les compétences par défaut
* Migration : ajout d'une date de modification et création pour les partenaires
* Changement de la commande import-grid-affectation , du loader lié, et de la définition des header pour prendre en compte tous les changements du ticket #842 
* Changement de la PartnerFactory pour prendre en compte les compétences par défaut
Créer un signalement sur la plateforme et récupérer le mail du déclarant ou de l'occupant
Dans l'idéal faire sa propre grille avec ou …
> [BO - Grille affectation] Amélioration de la commande de la grille affectation

- assets/vue/components/dashboard/TheHistoDashboardCards.vue
- src/Repository/SuiviRepository.php
#743    
Dans la liste, si on active le filtre "sans suivi depuis x jours", on ne doit pas avoir les signalements qui ont des suivis dans cet intervalle, sauf si ce sont des suivis techniques. Pareil dans le widget du tableau de bord.
* Ajout du type Suivi Automatique dans la sous-requête d'exclusion
> [BO - Tableau Bord] Le filtre "sans suivi" prend en compte les suivis partenaires, usagers et automatiques

- src/DataFixtures/Files/Suivi.yml
- src/Factory/SuiviFactory.php
- tests/Unit/Factory/SuiviFactoryTest.php
#1019    
Correction d'une faute d'orthographe sur le suivi automatique de cloture
* correction d'une faute
> [BO - Signalement] Suivi automatique clôture signalement - faute d'orthographe

- templates/back/signalement/view.html.twig
#627    
Correction de l'affichage des informations au survol des documents dans la page signalement
> [BO Signalement] Correction informations survol sur documents

- src/Factory/Esabora/AbstractDossierMessageFactory.php
- src/Service/Esabora/EsaboraSISHService.php
#1254    
Les noms des documents sont manquant à  l'envoi du dossier vers le SAS SISH 
* Ajout des informations manquantes dans la construction des pièces jointes
* Remplacement Image téléversé par le vrai nom du fichier 
`
> [Esabora - Intégration SISH] Envoi du nom image

- src/Controller/Back/CartographieController.php
- src/DataFixtures/Files/Signalement.yml
- src/Repository/SignalementRepository.php
- tests/Functional/Controller/CartographieControllerTest.php
- tests/Functional/Controller/SignalementListControllerTest.php
#1218    
Pour un utilisateur partenaire (pas resp territoire), la carto ne fonctionnait plus lors de l'application d'un filtre sur les statuts. En effet, on utilisait dans le searchFilterService `affectationStatus` (ligne 325) qui n'était pas défini dans la requête initiale de la liste des signalements pour la carto (`SignalementRepository.findAllWithGeoData()`). Cela générait une erreur : https://sentry.incubateur.net/share/issue/e100e4309f7b409dbac74465cd54bff7/
Pour éviter cela, et parce que la requête générée dans `SignalementRepository.findAllWithGeoData()` était en partie dépréciée (PARTIAL), on passe maintenant par `SignalementRepository.findSignalementAffectationQuery()` qui génère la requête de la liste des signalements et qui est compatible avec le searchFilterService. 
* Mise …
> [BO - Cartographie] Erreur lors du choix d'un statut pour un partenaire

- src/Command/AddUserCommand.php
- src/Controller/Back/PartnerController.php
#1173    
Dans la page partenaire, et dans la commande add-user, si un utilisateur existe déjà en tant qu'usager, on peut "l'ajouter" en tant que partenaire, c'est-à-dire changer son rôle et lui attribuer territoire et partenaire. 
* Changement du PartnerController
* Changement de AddUserCommand
> [BO - Utilisateur] Création utilisateur pour un déclarant partenaire déjà existant

- src/Entity/Enum/MotifCloture.php
- src/Service/Statistics/MotifClotureStatisticProvider.php
#1251    
Dans le BO, renommer les motifs de clôture suivants : 
- `Péril` devient `Mise en sécurité / Péril`
- `Logement décent` devient `Logement décent / Pas d'infraction` 
* Changement de l'enum MotifCloture, et du MotifClotureStatisticProvider
> [BO - Cloture signalement] Renommer des motifs de clôture

- src/Service/Import/GridAffectation/GridAffectationLoader.php
#842    
La grille ne peut pas s'importer si aucun utilisateur n'est affecté à un partenaire
* Ignorer les emails vides
* Vérifier l'email utilisateur uniquement s'utilisateur a un rôle 
[grille_affectation_78.csv](https://github.com/MTES-MCT/histologe/files/11531365/grille_affectation_78.csv)
> [BO - Grille affectation] Un partenaire sans utilisateur doit continuer à être ajouté

- src/Twig/AppExtension.php
- templates/back/signalement/view.html.twig
#1040    
Affichage du lien entre déclarant et occupant dans la fiche signalement
> [BO Signalement] Affichage du lien entre déclarant et occupant

- src/Controller/Back/SignalementController.php
- src/Controller/FrontSignalementController.php
- src/Repository/CriticiteRepository.php
- src/Service/Import/Signalement/SignalementImportLoader.php
- src/Service/Signalement/CriticiteCalculator.php
- tests/Functional/Service/Import/Signalement/SignalementImportLoaderTest.php
- tests/Functional/Service/Signalement/CriticiteCalculatorTest.php
#1206    
Evolution de la commande d'import de signalement avec prise en compte des :
* Situation(s) suspectée(s)
* Nouvel algo de criticité dans l'import des signalement
* Modification de `CriticiteCalculator` afin de l'utiliser en tant que service via l'injection de dépendance
* Prise en compte des algo de calcul de score et situations suspectées dans la commande d'import
* CriticiteRepository::findByLabel plus permissif avec envoi d'un tableau de criticité au lieu d'un objet ou null
La commande `./scripts/upload-s3.sh signalement 07` a été exécuté, le fichier est déjà sur le bucket de dev
> [Import de données] Evolution de la commande d'import - nouveau score et situations suspectées

- src/Controller/Back/AffectationController.php
- src/Manager/SuiviManager.php
#1245    
Mise en place du type technique pour les suivis automatiques créés lors de la première acceptation d'affectation
> [Affectation] Suivi automatique de type technique

- src/Entity/Signalement.php
- src/Factory/SignalementFactory.php
- src/Manager/SignalementManager.php
- src/Service/Import/Signalement/SignalementImportMapper.php
#1293    
Il existe du code déprécié dans l’exécution de la commande `app:import-signalement`
* Ne plus passer null dans les fonctions suivantes `mb_strtolower`, `trim` , `Enum::tryFrom`
Dans une autre branche, éxécuter la commande `make console app="import-signalement 07 -vv"` afin de constater les warning en local
> [QA] Gérer le code déprécié de la commande d'import de signalement

- src/DataFixtures/Files/Suivi.yml
- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Repository/SuiviRepository.php
- tests/FixturesHelper.php
- tests/Functional/Repository/SuiviRepositoryTest.php
- tests/Functional/Service/Notification/NotificationCounterTest.php
- tests/Unit/Factory/Esabora/DossierMessageSISHFactoryTest.php
#1291    
Le premier suivi d'un signalement après acceptation est toujours "Signalement validé" qui n'a très peu de valeurs pour l'ARS.
Il faudrait donc envoyer le premier suivi partenaire s'il existe. 
* Ajout de méthode dans SuiviRepository qui envoi le premier suivi selon le type 
```bash
$ make mock
$ make worker-start
```
```json 
{
"\\": "...."
"signalementCommentaire": "Ceci est le premier suivi de partenaire 13-01",
"\\": "...."
}
```
> [Intégration SISH] envoyer premier suivi partenaire #1291

- src/Kernel.php
#1290   
#739
Toute l'application est configuré en heure UTC
* MAJ Kernel avec timezone par défaut
```bash
$ make mock
$ make worker-start
```
```json 
{
"\\": "...."
"sasDateAffectation": "02\/06\/2023 10:40",
"\\": "...."
}
> [Intégration SISH] envoyer heure française plutôt qu'heure UTC

- src/Controller/Back/AffectationController.php
#1245    
Loupée lors de la correction précédente, des signalements avec des affectations ayant été acceptées avant cette nouvelle fonctionnalité se voient créer un suivi de première acceptation d'affectation
* Dans le controller, remise en place de la vérification du nombre d'affectation déjà acceptée
> [BO - signalement] hotfix - create suivi if there is no other affectation accepted

- src/Controller/Back/AffectationController.php
#1245    
Loupée lors de la correction précédente, des signalements avec des affectations ayant été acceptées avant cette nouvelle fonctionnalité se voient créer un suivi de première acceptation d'affectation
* Dans le controller, remise en place de la vérification du nombre d'affectation déjà acceptée
>  [BO - signalement] 1245 : hotfix - create suivi if there is no other affectation accepted

- src/Service/Esabora/Enum/EsaboraStatus.php
- src/Service/Esabora/EsaboraManager.php
- src/Service/Esabora/Response/DossierPushSISHResponse.php
- src/Service/Esabora/Response/DossierResponseInterface.php
- src/Service/Esabora/Response/DossierStateSCHSResponse.php
- src/Service/Esabora/Response/Model/DossierArreteSISH.php
- src/Service/Esabora/Response/Model/DossierVisiteSISH.php
- tests/Unit/Service/Esabora/Response/DossierArreteSISHCollectionResponseTest.php
- tests/Unit/Service/Esabora/Response/DossierVisiteSISHCollectionResponseTest.php
- tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas.json
- tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas_termine.json
- tools/wiremock/src/Resources/Esabora/sish/ws_visites_dossier_sas.json
- tools/wiremock/src/Resources/Esabora/sish/ws_visites_dossier_sas_en_cours.json
#1289    
#1286 
Voir spec: [Histologe/Santé Habitat] - Contrat d'interface - version 1.4
> Le web service "SISH_VISITES_DOSSIER_SAS" appelle la multicritère "SISH_VISITES_DOSSIER_SAS". 
Il permet d’obtenir la liste des visites enregistrées et en statut "Effectuée" sur un dossier importé par le sas.
Seules les visites avec le statut "Effectuée" sont retournées.
Si un dossier SISH a été créé depuis le sas mais qu'il ne contient aucune visite effectuée, la liste retournée sera vide.
Nom des colonnes renvoyées : 
• Sas_LogicielProvenance
• Reference_Dossier
• SISH_DossNum
• ~~SISH_VisiteDateEnreg~~
• SISH_VisiteDate 
• ~~SISH_VisiteObservations~~
• SISH_VisiteNum
• SISH_VisiteType
• ~~SISH_VisiteStatut~~
• ~~SISH_VisiteEtat~~
• SISH_VisitePar
> Le web service "SISH_ARRETES_DOSSIER_SAS" …
> [Intégration SISH] Mise à jour WS SISH_VISITES_DOSSIER_SAS / SISH_ARRETES_DOSSIER_SAS / SISH_ETAT_DOSSIER_SAS

- templates/_partials/_signalement_steps_tabs.html.twig
#927    
Ajout texte pour les tiers-déclarants sur la page de synthèse des signalements
> [FO - Signalement] Ajout texte pour les tiers-déclarants sur la page de synthèse

- public/js/const.min.js
- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
#1292    
Esabora a besoin d'avoir des adresses de proprio valide. Jusqu'à maintenant aucune suggestion d’adresse n'est faite sur le champ adresse du propriétaire, il faut donc permettre au formulaire de suggérer des adresses lors l'auto-complétion de ce champs.
* Conditionnement de la méthode searchAddress afin de permettre le remplissage sur 1 seul champs au lieu de 3
> [Intégration SISH] Ajouter contrôle sur adresse proprio

- src/Repository/PartnerRepository.php
- src/Repository/TerritoryRepository.php
- templates/_partials/_search_filter_form.html.twig
#713    
Tri des listes de territoires et partenaires par ordre alphabétique
`make clear-pool pool=cache.app`
> [BO] Classement des listes de territoires et partenaires par ordre alphabétique

- migrations/Version20230606161945.php
- src/Controller/Back/AffectationController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Loader/LoadAffectationData.php
- src/Entity/Affectation.php
- src/Repository/AffectationRepository.php
- tests/Functional/Repository/AffectationRepositoryTest.php
#1321   
Afin de distinguer les signalements affectés à un partenaire esabora avant ou après la MEP, il est nécessaire de rajouter un tag à la table Affectation
* Mise à jour de ta table affectation
```bash
make mock
```
> [Intégration SISH] Tagger les signalements affectés (sync avec esabora) afin de les cibler lors de la sync

- templates/back/signalement/view.html.twig
#1315    
Dans la partie "photos et documents", modifier la phrase de sous-titre pour :
Pour ajouter plusieurs photos ou documents à la fois, sélectionnez vos fichiers en maintenant la touche CTRL enfoncée.
* changement d'une phrase sur la fiche signalement
> [BO - Fiche signalement] Modifier phrase photo

- templates/front/signalement.html.twig
#1309    
Sur la page de validation, après dépôt du signalement. Modifier les contenus suivants : 
- Pour tous les types de procédure : modifier `Partenaires impliqués` en `Partenaires éventuels`
- Partie procédure de non décence
- Dans les mesures possibles, retirer la mention `Lettre de mise en demeure`
- Partie procédure d'infraction au RSD
- Dans les exemples de désordres : remplacer `La peinture est abîmée et contient du plomb` par `Les plafonds sont trop bas (moins de 2.20 m)`
- Dans les mesures possibles : remplacer `Arrêté municipal` par `Lettre de mise en demeure`
- Partie procédure d'insalubrité
- Dans les désordres : modifier le premier en `Il n'y a pas de fenêtre ni de ventilation dans mon logement`
- Dans les mesures possibles : remplacer `Arrêté municipal` par `Arrêté …
> [FO - Contenus] Corrections page de validation, après dépôt du signalement

- src/Service/Statistics/GlobalAnalyticsProvider.php
#1312    
Dans le compteur Foyers sortis du mal logement intégrer les motifs:
-     travaux faits
-     insalubrite
-     RSD
-     Peril
-     Relogement occupant
Changement du GlobalAnalyticsProvide, ajout des motifs de cloture dans getCountSignalementResoluData
> [FO-Statistiques] Page Stat publique

- migrations/Version20230608131408.php
- src/Entity/Intervention.php
- src/Factory/InterventionFactory.php
- src/Service/Esabora/EsaboraManager.php
- src/Service/Esabora/Response/Model/DossierArreteSISH.php
- tests/FixturesHelper.php
- tests/Unit/Entity/InterventionTest.php
- tests/Unit/Factory/InterventionFactoryTest.php
- tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas.json
- tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas_termine.json
#1332    
Suite à la dernière version du document d’interface avec les modifications apportées au web service des arrêtés.
* Prise en compte des champs concernant les mains levées
* Transformation du statut en miscule pour le we SAS_ETAT
* Ajout champs dans la table intervention
```bash
make mock
```
> [Intégration SISH] MAJ ARRETE WS

- public/js/maps.js
#1319    
Rendre possible l'affichage de la Martinique
* Changer les limites de la carte et le zoom minimal et par défaut pour inclure la Martinique
> [BO - Carto] rendre possible l'affichage de la Martinique

- src/Controller/Back/SignalementController.php
- src/Manager/AffectationManager.php
- src/Manager/SignalementManager.php
- tests/Functional/Manager/AffectationManagerTest.php
- tests/Functional/Manager/SignalementManagerTest.php
#1207    
Les infos diffèrent entre la partie suivi et l info dans le bloc partenaire lorsqu'un utilisateur cloture un signalement. 
* Utilisation de la fonction closeAffectation() de l'AffectationManager, et suppression de la fonction closeAffectation() du SignalementManager
> [BO - Signalement] Informations clôture

- src/Command/UpdateSignalementLastSuiviAtCommand.php
- src/Controller/Back/BackStatistiquesController.php
- src/Controller/HomepageController.php
- src/Dto/StatisticsFilters.php
- src/Repository/AffectationRepository.php
- src/Repository/SignalementRepository.php
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
- src/Service/Statistics/GlobalAnalyticsProvider.php
- src/Service/Statistics/GlobalBackAnalyticsProvider.php
- src/Service/Statistics/StatusStatisticProvider.php
- tests/Functional/Controller/BackStatistiquesControllerTest.php
#845    
En tant qu'agent d'un partenaire (Rôle Utilisateur) lorsque je me rends dans l'onglet Statistiques de mon Tableau de Bord je visualise les données relatives à la Totalité des signalements du Territoire
Cette vue ne devrait être accessible qu'au Responsable Territoire
Pour les Partenaires de Type Partenaire ou Commune, et les rôles Utilisateurs je ne devrais avoir sur la page Statistiques que les données relatives à mon Partenaire
* Ajout du partenaire dans les provider de statistiques
> [BO - Statistiques] Partenaires

- tests/Functional/Controller/BackStatistiquesControllerTest.php
#845    
Suppression de tests qui ne passent pas, car chaque jour qui passe la stat du délai moyen augmente...
* suppression de test
> [BO - Statistiques] Suppression de tests qui ne passent pas

- src/Service/DashboardWidget/WidgetDataManager.php
#739    
Le widget esabora est en vuejs non pris en compte par la configuration twig
* Transformer la date de synchro esabora avec la timezone Europe
> [Dashboard] Horodatage widget esabora

- src/Command/ImportSignalementCommand.php
- src/Entity/Tag.php
- src/Service/Import/Signalement/SignalementImportLoader.php
#1330    
Correction sur l'ajout des étiquettes et ajout d'une barre de progession lors de l'import de signalements
* Ajout d'une barre de progression en ligne de commande
* Persist en cascade sur les tags
* Diminution du nombre de signalements avant flush
> [Import signalements] Correction sur l'ajout des étiquettes et ajout d'une barre de progession

- src/Controller/Back/AffectationController.php
#1245    
Ne pas notifier la première acceptation d'affectation si le signalement est importé
* Test si le signalement est importé
> [BO - Signalement] Ne pas notifier la première acceptation d'affectation si le signalement est importé

- migrations/Version20230619151717.php
- public/js/app.js
- src/Controller/FrontSignalementController.php
- src/Controller/HomepageController.php
- src/Entity/Signalement.php
- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
- templates/back/signalement/view/information.html.twig
#1269    
Ajout d'un champ facultatif Date de naissance sur les signalements
La PR se base sur les visites pour ne pas faire deux fois le travail dans le BO
* Ajout du champ dans la base de données
* Ajout d'un champ facultatif dans le formulaire de signalement : obligatoire si l'occupant déclare ET qu'il est allocataire
* Affichage de la date de naissance dans le BO
Différents scénarii de signalements :
> [Signalement] Ajout d'un champ facultatif Date de naissance

- migrations/Version20230626144301.php
- src/Command/Cron/RemindInactiveUserCommand.php
- src/Command/ImportGridAffectationCommand.php
- src/Entity/User.php
- src/EventSubscriber/UserCreatedSubscriber.php
- src/Factory/UserFactory.php
- src/Service/Import/GridAffectation/GridAffectationLoader.php
#1370    
Ajout d'une option pour désactiver les notifications pour certains partenaires
* Désactivation du subscriber lors de la création d'un utilisateur lorsque le type de partenaire correspond à ceux qui sont ignorés
Partir d'une base neuve et ouvrir le mail catcher
> [Import partenaires] Ajout option pour désactiver les notifications pour certains partenaires

- src/EventListener/ActivityListener.php
#1384    
Lorsqu'un agent crée un suivi, ne pas notifier l'agent lui-même, ni les agents du même partenaire.
> [BO - Suivis] Ne pas notifier les utilisateurs du même partenaire que l'utilisateur qui crée le suivi

- migrations/Version20230530084228.php
- src/EventSubscriber/InterventionConfirmedSubscriber.php
- src/Service/Signalement/VisiteNotifier.php
- templates/back/signalement/view/visites/visites-list.html.twig
- templates/emails/nouveau_suivi_visite_confirmed_to_partner_email.html.twig
- templates/emails/nouveau_suivi_visite_confirmed_to_user_email.html.twig
Correction de la migration des dates de visites déjà renseignées
Correction de l'affichage des visites si aucun partenaire n'est lié
> [Visites] Correction de la migration des dates de visites déjà renseignées

- src/Controller/FrontSignalementController.php
#NumIssue   
On ne peut plus déposer de signalement si on n'est pas allocataire CAF (ou "ne sait pas") on reçoit une erreur 
`
Plateforme: localhost
Code erreur: 0
Message erreur: Failed to parse time string (--) at position 0 (-): Unexpected character
Documents: 0
Photos: 0
`
* Vérification des champs dans le FrontSignalementController
> [FO - dpot signalement] corrige le dépôt de signalement quand pas allocataire CAF

- templates/back/signalement/view/suivis.html.twig
#1413    
Régression de comportement suite à la refonte de la fiche signalement
Une tooltip avec les informations personnelles de l'agent doit apparaître au survol de la souris
* Englober les informations dans une div avec les classes et attributs associés.
> [BO - Fiche signalement] Afficher mail agent qui a redigé le suivi au survol

- src/Factory/Esabora/DossierMessageSISHFactory.php
#1430    
Erreur déclenchée lorsque lors d'une affectation avec comme valeur mode contact proprio à NULL
| mode_contact_proprio |
|----------------------|
| NULL                 |
| NULL                 |
| NULL                 |
* Vérifier que le mode contact proprio est un tableau
```
$ make worker-start
$ make mock
```
> [QA] Esabora - Erreur de type mode contact proprio

- templates/_partials/signalement/add_suivi.html.twig
#1415    
Modification de l'ordre des champs dans la modale d'ajout de suivi de la page signalement
* Modification de l'ordre des champs
> [BO - Suivis] Modification de l'ordre des champs dans la modale d'ajout de suivi

- assets/styles/histologe.scss
#1422    
Affichage de la fenêtre de refus de signalement au-dessus des autres éléments
* Règle css spécifique appliquée
> [BO - Signalement] Affichage de la fenêtre de refus au-dessus des autres éléments

- assets/styles/histologe.scss
#1418    
Disponibilité du bouton pour afficher tous les suivis même si le signalement est fermé
* Modification css appliquée au bouton
> [BO - Signalement] Disponibilité du bouton pour afficher tous les suivis même si le signalement est fermé

- src/Service/Signalement/VisiteNotifier.php
#1429    
Ne pas envoyer les mails de visites aux utilisateurs ayant désactivé les mails
* Condition ajoutée pour l'envoi de mails de visites
> [BO - Visites] Ne pas notifier par mail les utilisateurs ayant désactivé

- cron.json
- src/Command/Cron/NotifyVisitsCommand.php
#1419    
Déplacement de la commande de notification de visites en tant que commande CRON
* Déplacement de fichier et namespace
> [Commandes] Déplacement de la commande de notification de visites en tant que commande CRON

- templates/back/signalement/view.html.twig
- templates/back/signalement/view/header.html.twig
#1398    
Lorque le statut d'un signalement est ouvert mais que l'affectation d'un admin territoire est clôturée, on laisse tout de même le signalement accessible pour l'admin territoire
* Modification de condition dans twig pour la classe css `signalement-invalid`
> [BO - Signalement] Laisser accessible pour l'admin territoire si son affectation est clôturée mais que le signalement est ouvert

- assets/styles/histologe.scss
#1421    
Correction de l'affichage de la liste des documents à partager dans la modale d'ajout de suivi
* Modification css concernant le zindex du sous-menu
> [BO - Suivi] Correction affichage fenêtre de partage de document

- src/Service/Signalement/VisiteNotifier.php
#1419    
Ne pas notifier un agent à propos des visites si c'est un agent du même partenaire qui a fait la visite
* Restriction des utilisateurs à notifier
> [BO - Visites] Notifications pour agents uniquement si pas un agent qui remplit la visite

- templates/back/signalement/view/partners.html.twig
#1445   
Corrections sur l'affichage de la partie "partenaires affectés" sur la fiche signalement
* Affiche les partenaires affectés pour le rôle ADMIN_PARTNER
* N'affiche pas les partenaires pour utilisateurs et admin_partner si l'affectation est fermée ou non acceptée
> [BO - Signalement ] Corrections sur l'affichage des partenaires affectés sur un signalement dans la partie Activité PDLHI

- tools/histologe/histologe.postman_collection.json
- tools/wiremock/src/Mock/AppMock.php
- tools/wiremock/src/Mock/Signalement/QuestionMock.php
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1423    
Web service retournant les questions à poser avant de déterminer le profile
Par rapport à l'excel
* Slug avec des "_" au lieu des "-"
* Propriété customCss au lieu de css
* Nom des composants retournés
* Prise en compte d'un body et un footer de component pour le coté ui
* Présence du nom du store dans les conditions
```
$ make mock
```
> [Back] Mock API - Récupération des questions avant profil

- templates/base.html.twig
#1485    
Ajouter un document et vérifier que les douments apparaissent sous "Partager un document"
* Charrger le documents depuis la nouvelle table file
make console app="migrate-document-data 0"
> [BO -Signalement] Partager document en suivi

- migrations/Version20230720102750.php
- src/Entity/Enum/Profile.php
- src/Entity/Enum/ProfileDeclarant.php
- src/Entity/Enum/SignalementDraftStatus.php
- src/Entity/Signalement.php
- src/Entity/SignalementDraft.php
- src/Repository/SignalementDraftRepository.php
- tests/Unit/Entity/SignalementDraftTest.php
#1428    
Utilisé pour restituer le signalement en cours de saisie. 
| Nom de colonne | Description
|----------------|------------------|
| id             | L'identifiant unique de chaque signalement.
| uuid           | Un identifiant universel unique (UUID) pour chaque signalement.
| profile| Profil usager
| email    | Email de l'usager
| address    | Adresse de l'habitant
| payload        | La payload de la requête (le contenu du store)
| current_step   | Ecran en cours
| status         | en cours", "cul-de-sac" (par exemple assurantiel), "transformé en signalement"
| created_at    | Date de création
| updated_at     | Date de mise à jour
* Ajout de la table signalement_draft
```
make create-db
```
> [Back] Faire distinction entre nouveau signalement et ancien signalement

- src/Entity/Enum/InterventionType.php
- src/EventSubscriber/InterventionCreatedSubscriber.php
- src/Manager/UserManager.php
- src/Service/Esabora/EsaboraManager.php
- src/Service/Intervention/InterventionDescriptionGenerator.php
- templates/back/signalement/view/visites/visite-item.html.twig
- templates/back/signalement/view/visites/visites-list.html.twig
- tests/FixturesHelper.php
- tests/Functional/EventSubscriber/InterventionCreatedSubscriberTest.php
- tests/Functional/Manager/Esabora/EsaboraManagerTest.php
- tests/Unit/Entity/Enum/InterventionTypeTest.php
- tests/Unit/Service/Esabora/EsaboraManagerTest.php
- tests/Unit/Service/Intervention/InterventionDescriptionGeneratorTest.php
- tools/wiremock/src/Resources/Esabora/sish/ws_visites_dossier_sas_en_cours.json
#1476 
#1478    
#1477
**Etre plus permissif sur le type Visite de contrôle**
Test plus souple sur le libellé provenant d'ésabora en vérifiant si le champ "libellé de la visite" contient le mot "contrôle", en ignorant la casse.
**Ajout du type de visite s'il s'agit d'une visite de contrôle**
**Modification de l'affichage des arrêtés préfectoraux**
Actuellement, les arrêtés préfectoraux s'affichent dans le bloc de visite. Pour une meilleure organisation, il a été décidé de ne plus les afficher de cette manière, mais plutôt de créer un nouveau suivi dans le fil d'actualité des suivis. Toutefois, il faudra toujours les enregistrer en base de données en tant qu'intervention.
Pour être cohérent avec le fonctionnement de la plateforme dans la création de visite, la création d'une visite venant …
> [ESABORA] Ajustement arrêté préfectoral et visite de contrôle

- assets/vue/components/signalement-form/SignalementFormInfo.vue
- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/exemple_socle.json
#1493    
Ajout du composant SignalementFormInfo
* création du composant SignalementFormInfo
> [Front] Créer le composant SignalementFormInfo

- assets/vue/components/signalement-form/SignalementFormAriane.vue
- assets/vue/components/signalement-form/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/store.ts
#1473    
Ajout d'un fil d'ariane avec un indicateur de progression
* création du composant SignalementFormBreadCrumbs
* modification du store et de TheAppSignalementForm pour sauvegarder dans le store les écrans, et l'étape en cours
Ce composant n'a pas encore son comportement définitif car il y a des choses à caler avec Mathilde
> [Front] Fil d'ariane

- templates/back/signalement/view/photos-documents.html.twig
- templates/front/suivi_signalement.html.twig
#1509    
* Filtre sur la collections files
* Affichage des photos fiche suivi usager sur collection files
> [BO - Signalement ] Mention "Aucun document ou photo disponible" alors qu'il y a des photos

- src/DataFixtures/Files/Signalement.yml
- src/Repository/SuiviRepository.php
- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
- tests/Functional/Controller/BackStatistiquesControllerTest.php
- tests/Functional/Controller/SignalementListControllerTest.php
#1499 
La troisième requête (qui correspond à la première relance sur les signalements) n'incluaient pas les signalements n'ayant ni suivi technique, ni suivi public. Ce qui fait que des vieux signalements n'étaient jamais relancés (291 aujourd'hui)
On a changé cette requête pour inclure ces signalements si leur date de création est antérieure de 45 jours à aujourd'hui
* Mise à jour de Suivi Repository pour créer des requêtes différentes
* Mise à jour des fixtures pour ajouter un signalement ancien sans suivi public ni suivi technique
* Mise à jour des  tests
> [Relance auto] Correction sur la requête de première relance pour inclure les signalements n'ayant jamais eu ni suivi technique, ni suivi public

- assets/vue/components/signalement-form/SignalementFormAddress.vue
- assets/vue/components/signalement-form/SignalementFormOnlyChoice.vue
- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/address_subscreen.json
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/services.ts
- templates/front/nouveau_formulaire.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1492     
Au clic sur le bouton suite après détermination du profil, on rappelle l'API avec le profil pour avoir la suite des questions
- Modification de ajaxurl-questions pour enlever le profil "tous"
- Création d'une nouvelle fonction dans requests.ts pour appeler ajaxurl-questions avec le profil du déclarant
- Création d'un fichier services.ts avec des fonctions réutilisables 
- dans services.ts création d'une fonction updateProfil() pour enregistrer le profil dans le store en fonction des réponses aux questions
- dans l'application principale, mise à jour de changeScreenBySlug(), si on ne trouve pas le screenIndex du screen appelé, c'est qu'on n'a pas les informations dans le store. alors en fonction du slug du screen appelé, on peut rappeler l'api. Dans le cas présent, on met …
> [Front] Appel API avant de changer de screen

- migrations/Version20230726081531.php
- public/js/app.js
- public/js/const.js
- public/js/const.min.js
- src/DataFixtures/Files/Territory.yml
#1489    
Limiter le dépot des signalements aux communes de quimper (insee : 29232) et brest (insee: 29019)
* Migration pour mettre à jour la liste des codes insee autorisés sur le territoire 29
* Idem dans les fixtures
* Mise à jour JS pour afficher un message d'erreur si code postal hors communes autorisés
> [FO - Signalement] Finistère - limiter le dépot des signalements aux communes de quimper et brest 

- src/Service/Intervention/InterventionDescriptionGenerator.php
- tests/Unit/Service/Intervention/InterventionDescriptionGeneratorTest.php
- tools/wiremock/src/Resources/Esabora/sish/ws_arretes_dossier_sas_termine.json
#1522    
Mise à jour des libelles de suivi pour les arrêtes préfectoraux
```txt
L’arrêté [numéro arrêté] du [date] 
```
* Mise à jour des libellés
* Mise à jour de la condition pour les mainlevées
* Mise à jour du mock avec un arrêté sans numéro d'arrêté
```
$ make mock
```
> [Esabora] Mise à jour des libellés de suivi pour les arrêtés

- src/Service/Mailer/Mail/Suivi/SuiviNewCommentBackMailer.php
#1481    
Email de suivi généré depuis les commandes esabora ne renvoie pas l'url absolue
* Utilisation de la méthode de la classe abstraite prévue à cet effet
```
make mock
```
> [Email- Suivi] Lien email suivi ARS ESABORA

- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/store.ts
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1517    
Il est possible de répéter sur le même un composant SignalementFormSubscreen grâce à la propriété repeat voir json
{{count}} est un entier avec une boucle qui commence à 1 .
{{number}} est l'index courant pour chaque itération
{{count}} pouvant être défini l'écran précédent, ce n'est pas au chargement des données du screen (après l'appel api) qu'on gère cette répétition, mais à son affichage
* Ajustements sur le mock
* Création de fonctions de clonage et renommage des données de composants dans le store pour pouvoir évalier le {{formStore.data.xxx}} qui sert à définir le nombre d'itérations
* Appel de ces fonctions dans changeScreenBySlug()
> [Front] Gérer la propriété repeat sur un composant

- assets/vue/components/signalement-form/SignalementFormAddress.vue
- assets/vue/components/signalement-form/SignalementFormScreen.vue
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/store.ts
- templates/front/nouveau_formulaire.html.twig
#1459    
A chaque changement de screen, à partir du moment où on a adresse + email, on enregistre en base le signalement draft et on le met à jour
* Création de nouvelles fonctions dans requests pour faire des POST et des PUT
* Création d'une fonction saveSignalementDraft() appelée à chaque changement de screen, et qui fait soit un POST (création du signalement draft), soit un PUT (mise à jour du signalementDraft), soit rien si on n'a pas le tuple mail+adresse
```
make create-db
make mock
```
> [Front] Soumission formulaire sans désordres

- migrations/Version20230802101020.php
- src/DataFixtures/Loader/LoadSignalementData.php
- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
#1551    
Mise à jour des signalements
* Nouvelle migration qui met à jour les signalements non importés, en cours, considérés comme faits par l'occupant mais avec des infos de déclarant
https://histologe-metabase.osc-fr1.scalingo.io/question/324-signalement-non-importes-en-cours-consideres-comme-faits-par-loccupant-mais-avec-des-infos-de-declarant
> [BO Signalement] Déclarant Tiers

- src/DataFixtures/Files/Signalement.yml
- src/Service/Mailer/Mail/Signalement/SignalementFeedbackUsagerMailer.php
- src/Service/Mailer/Mail/Signalement/SignalementFeedbackUsagerThirdMailer.php
- templates/emails/demande_feedback_usager_email.html.twig
- templates/emails/demande_feedback_usager_third_email.html.twig
- tests/Functional/Command/Cron/AskFeedbackUsagerCommandTest.php
#1567    
Les mails de relance automatique sont toujours envoyé à l'occupant
* Ajout d'une condition sur les template de mail de relance automatique
> [BO- Relance automatique] Problème de correspondance mail entre le nom/prénom du déclarant et l'occupant

- src/Command/Cron/NotifyVisitsCommand.php
- src/Repository/SuiviRepository.php
- src/Service/Mailer/Mail/Signalement/SignalementClosedToOnePartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteConfirmedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToUsagerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteNeededMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisitePastReminderToPartnerMailer.php
#1470   
Jusqu'à présent, l'ensemble des agents d'un partenaire étaient prévenus à J+2 après une visite prévue pour remplir une conclusion.
On modifie pour que ceux qui sont notifiés soient :
- l'administrateur du partenaire affecté à la visite
- le dernier agent du partenaire affecté qui a fait un suivi sur ce signalement
- si il n'y en a pas, on prend le dernier agent du responsable territoire qui a fait un suivi sur ce signalement
* Modification de la commande de notification automatique
* Correction collatérale : Modification de l'appel de fonction pour la mise à jour du sujet de mails, car si on appelle plusieurs fois le même type de mail (comme dans la commande), le sujet ne bougeait plus une fois mis à jour.
> [BO - Visites] Envoi des notifications de rappel de visite J+2 uniquement pour agents concernés

- src/Command/Cron/NotifyVisitsCommand.php
- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Service/HtmlCleaner.php
- tests/Unit/Service/HtmlCleanerTest.php
#1573   
Le champ commentaire envoyé à SISH correspond au premier suivi envoyé. Il a de grandes chances de contenir du HTML qu'Esabora n'est pas en mesure d'afficher.
* Ajout d'une nouvelle classe de nettoyage appelée à cette occasion.
> [Esabora - SISH] Nettoyage des tags HTML avant envoi à SISH pour le champ commentaire

- src/Controller/Back/SignalementVisitesController.php
- src/Dto/Request/Signalement/VisiteRequest.php
- src/Manager/InterventionManager.php
- tests/Functional/Manager/InterventionManagerTest.php
#1449    
Ajout d'un contrôle sur la saisie de date de visite
> [BO - Visites] Ajout contrôle sur la saisie de date de visite

- src/Utils/AddressParser.php
- tests/Unit/Utils/AddressParserTest.php
#1580    
Certaines adresses de dossier ne sont pas parsable par AdressParser, en attendant d'avoir une stratégie et routine qui corrige les adresses, il faut permettre à AddressParser de parser les type d'adresse qui pose problème.
|  Adrresse                            | Problème rencontré                                    |  Commentaire       |
|-------------------------------------|---------------------------------------------------------|--------------------------|
| 123Rue de Canteraine       | Le numéro et le nom de la voie sont collés |
| 61/63 Route de Calais        | Présence de / | L'adresse sera envoyé telle quelle car le slash n'est pas toujours utilisé pour séparer les numéro va nécessiter un traitement en base de donnée, il existe 46 adresses avec présence de '\'
| 53, rue …
> [QA] Adresse invalide qui empêche l'envoi de dossier à esabora

- .github/workflows/main.yml
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormCounter.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/store.ts
- config/packages/twig.yaml
- templates/front/nouveau_formulaire.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1584    
* [config] Paramètre url dynamique pour twig
* [mock] Ajout écran désordres vides *ecran_intermediaire_les_desordres*
* [mock] Ajout écran *ecran_intermediaire_procedure*
* [mock] Ajout écran *utilisation_service*
* [mock] Ajout écran *informations_complementaires*
* [mock] Ajout écran *validation_signalement*
* [mock] Ajout écran *validation_signalement*
* [mock] Ajout écran "confirmation_signalement"
> [Back] Adaptation mock profil locataire

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/store.ts
- src/Controller/FrontNewSignalementController.php
- templates/front/nouveau_formulaire.html.twig
#1528    
Chargement des données d'un draft existant dans le nouveau formulaire
* Ajout d'une nouvelle route GET
* Récupération des données éventuelles avant le chargement des questions et remplissage du tableau de données
> [FO - Formulaire] Chargement des données d'un draft existant

- config/services.yaml
- src/Controller/FrontNewSignalementController.php
- src/Serializer/SignalementDraftRequestNormalizer.php
- src/Serializer/SignalementDraftRequestSerializer.php
- tests/Unit/Serializer/SignalementDraftRequestNormalizerTest.php
- tools/histologe/histologe.postman_collection.json
#1601   
Lors des différentes soumissions du formulaire les données répétables sont envoyés vers l'API sous ce format
```json
{
"profil": "locataire",
"type_logement_pieces_a_vivre_superficie_piece_1": 30,
"type_logement_pieces_a_vivre_superficie_piece_2": 15,
"type_logement_pieces_a_vivre_superficie_piece_3": 10,
"type_logement_pieces_a_vivre_hauteur_piece_1": "oui",
"type_logement_pieces_a_vivre_hauteur_piece_2": "oui",
"type_logement_pieces_a_vivre_hauteur_piece_3": "non",
"\\": "......."
}
```
Le DTO qui encapsule les données poussées par le formulaire ne peut pas prévoir le nombre de pièces que possède un usager. Il est donc normal de stocker ces données dans un tableau (format cible stocké en base de données), comme le montre la structure du DTO suivante :
```php
namespace …
```
> [Back] Gérer les propriétés dynamiques (repeat) avec le DTO

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Manager/SignalementDraftManager.php
#1597    
Enregiste l'étape courante sous la forme 3:vos_coordonnees_occupant pour réouvrir le parcours au bon endroit
* ajout d'un currentStep au bon format dans formStore.data
* ajout de currentStep dans le DTO
* lors de l'ouverture d'un signalement draft existant, on récupère ce currentStep pour déterminer le nextSlug, et si besoin charger la suite des questions
>  [Front][Back] Stocker l'état de saisie en cours

- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormButton.vue
- assets/vue/components/signalement-form/components/SignalementFormCheckbox.vue
- assets/vue/components/signalement-form/components/SignalementFormCounter.vue
- assets/vue/components/signalement-form/components/SignalementFormDate.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormTime.vue
- assets/vue/components/signalement-form/components/SignalementFormYear.vue
- assets/vue/components/signalement-form/services.ts
#1592    
Correction sur la validation des pages
* Déplacement de l'id au niveau de la plus haute balise pour les composants (car c'est sur ce premier niveau qu'est ajouté la classe fr-hidden, donc c'est pour vérifier si le composant est visible ou non afin de prendre en compte l'attribut validate.required)
* On répercute l'objet validate sur les composants du composant Address pour vérifier la validation de l'adresse 
* Si l'adresse n'est pas indiquée sur un composant obligatoire, on affiche un message d'erreur au plus haut niveau
> [FO - Formulaire] Souci de validation quand un champ n'est pas visible

- src/EventListener/ActivityListener.php
Lorsqu'on fait la synchronisation Esabora, si on reçoit des mises à jour, on crée des suivis.
Lorsqu'on sauvegarde les suivis (`onFlush`), un mail est envoyé aux agents concernés.
La liste des destinataires est ensuite vidée après envoi.
Il arrive cependant qu'on crée un début de liste de destinataires et que l'envoi ne se fasse pas (par exemple, si le signalement est fermé).
Dans ce cas, la liste des destinataires n'était pas vidée et pouvait être gardée pour le `onFlush` suivant.
* On vide la liste des destinataires avant tout envoi de mail
J'avoue que je n'ai pas trouvé de moyen de tester...
> [CRON - Synchro Esabora] Correction pour l'envoi de mail à des destinataires non prévus

- assets/styles/histologe.scss
- assets/vue/components/dashboard/TheHistoDashboardCards.vue
- templates/back/partner/index.html.twig
#1632   
#1633   
#1636   
Plusieurs corrections de couleurs dans le back-office
> [BO] Corrections couleurs liées à la mise à jour du DSFR

- assets/vue/components/signalement-form/components/SignalementFormOnlyChoice.vue
En modifiant le design des boutons radio pour le nouveau formulaire, les anciens formulaires avaient pris l'apparence aussi.
Le design est maintenant limité au nouveau formulaire.
> [DSFR] Correction affichage des boutons radio

- assets/vue/components/signalement-form/components/SignalementFormCheckbox.vue
- assets/vue/components/signalement-form/components/SignalementFormRoomList.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
#1628   
Ajout du composant SignalementFormRoomList (pas stylé du tout, c'est brut de pomme)
Correction sur le composant SignalementFormCheckbox
* Ajout du composant SignalementFormRoomList
* Correction sur le composant SignalementFormCheckbox
* Changement temporaire d'un json pour pouvoir aller sur un écran possédant un SignalementFormRoomList
> [Front] Créer le composant SignalementFormRoomList

- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Service/HtmlCleaner.php
#1650    
Ajouter un contrôle avant le nettoyage du commentaire à envoyer à Esabora afin de corriger l'ErrorException
* Ajout type et contrôle
`make mock`
> [QA] Ne pas accepter de valeur null dans le nettoyage contenu html

- assets/vue/components/signalement-form/components/SignalementFormRoomList.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
#1624    
Création de classes css pour modifier l'affichage des composants Subscreen et RoomList quand ils s'affichent à la sélection d'une checkbox
* Création de classes css
* Utilisation des classes css dans les json
en attendant la création des actions findNextScreen et findPreviousScreen permettant de naviguer dans les désordres, copier les composants de json concernés dans questions_profile_locataire.json par exemple
```
{
"type": "SignalementFormCheckbox",
"slug": "desordres_logement_lumiere_pas_lumiere",
"label": "Le logement n'est pas éclairé par la lumière du jour. Je dois allumer la lumière en plein jour"
},   
{
"type": "SignalementFormRoomList",
"label": "Dans quelle(s) pièce(s) ?",
"slug": "desordres_logement_lumiere_pas_lumiere_pieces",
"customCss": …
```
> [Front] Affichage des subscreen et roomlist à la sélection d'une checkbox

- Makefile
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryItem.vue
- assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryList.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/services/disorderScreenNavigator.ts
- package.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
#1622    
Mise en place du service permettant de naviguer entre les désordres logements, batiments ou les deux
* Gestion des catégories de désordres bâtiment ou logement depuis le store
* Ajout d'un nouveau service gérant la navigation des désordres
* Rendre la fonction handleClickComponent asynchrone afin de récupérer les erreurs de validation stocké dans le store
* Ajout nouvelle commande npm et make pour eslint
* Mise à jour des fichiers json des désordres `resolve:findNextScreen` et `resolve:findPreviousScreen`
> [Front] Créer les actions findNextScreen et findPreviousScreen

- assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/services/disorderScreenNavigator.ts
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1540   
Création du composant de résumé des désordres et navigation avec les écrans autour.
Pour l'instant, des slugs s'affichent pour les titres de catégorie.
Le contenu des parties déroulantes n'existe pas encore.
> [Front - Formulaire] Début du composant de résumé des désordres

- assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryList.vue
#1656    
Suppression des données de désordre quand une catégorie est déselectionnée
> [Front - Formulaire] Suppression des données de désordre quand une catégorie est déselectionnée

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormUpload.vue
- assets/vue/components/signalement-form/components/SignalementFormUploadPhotos.vue
#1623    
Ajout option `multiple` sur les champs d'upload
* Option `multiple` sur le composant `SignalementFormUpload`
* Défini à `true` par défaut sur le composant `SignalementFormUploadPhotos`
> [Front - Formulaire] Ajout option multiple sur les champs d'upload

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormTextarea.vue
- assets/vue/components/signalement-form/store.ts
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1712   
Création d'un composant SignalementFormTextarea et utilisation dans la partie "Procédure" pour la réponse de l'assurance
* Création d'un composant SignalementFormTextarea
* Ajout du composant dans la mécanique du formulaire
* Changement de textfield en textarea dans les json
```
make mock
npm run build
```
>   [Front - formulaire] Ajouter un composant SignalementFormTextarea

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
#1685
#1686
Corrections d'affichage sur la zone d'action smartphone
(sur smartphone)
> [Front - Formulaire] Corrections d'affichage sur la zone d'action smartphone

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- tools/wiremock/src/Resources/Signalement/dictionary.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
#1702   
#1706
- Correction de la place du picto Composition du logement
- Surligne "batiment" et "logement" sur la page d'intro des désordres
> [Front - Formulaire] Correction de place de picto et d'intro des désordres

- assets/vue/components/signalement-form/components/SignalementFormConfirmation.vue
- assets/vue/components/signalement-form/components/SignalementFormInfo.vue
- assets/vue/components/signalement-form/components/SignalementFormWarning.vue
- assets/vue/img/fr--warning-fill.svg
#1715   
#1700    
#1699    
- Corrections de marge sur la conclusion
- Corrections de marge et affichage de composants info et warning
> [Front - Formulaire] Corrections de marge et affichage de composants

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1688   
Changement de slugs dans certains json pour éviter une bloucle infinie lors de la navigation, quand un slug n'existe pas dans un profil
* Changements de slugs dans les json
> [Front - formulaire] Fix problèmes de navigation

- assets/vue/components/signalement-form/components/SignalementFormUpload.vue
#1703   
Ajout de CSS pour découper automatiquement les noms de fichiers dans le composant d'upload
> [Front - Formulaire] Découpe des noms de fichiers longs dans l'upload

- src/DataFixtures/Files/Signalement.yml
- src/Factory/Esabora/DossierMessageSCHSFactory.php
- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Form/SignalementType.php
- src/Utils/EtageParser.php
- tests/Unit/Utils/EtageParserTest.php
#1732    
Nettoiement des données saisi par les utilisateurs à l'édition, Cette PR permet aussi d'éviter les erreurs 400 esabora sur la contrainte de l'étage.
* Mise à jour du type de champs dans le formulaire
* Ajout d'un transformer  afin de déterminer l'étage sur le nouveau format (type=number)
* Ajout d'un parser afin d'envoyer une valeur parsé selon les contrainte ESABORA
```
```
> [FO] Ajout d'une contrainte numérique sur l'étage

- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1714   
Retirer l'écran " info complémentaires" du parcours du signalement, il ne doit être accessible que depuis le récapitulatif
* Changement des actions suivant/et précédent de 2 écrans dans les json concernés
* Modification du composant SignalementFormOverview pour lier cette partie de récap au bon écran, mais seulement pour les profils occupants
>  [New form - info complémentaires] Sortir "Infos complémentaires" du parcours

- src/Factory/Esabora/DossierMessageSCHSFactory.php
- src/Factory/Esabora/DossierMessageSISHFactory.php
- src/Form/SignalementType.php
- src/Utils/EtageParser.php
- tests/Unit/Utils/EtageParserTest.php
#1743    
Suite à de nombreux événements sentry
* Appeler EtageParser uniquement pour les valeurs non null
```
$ make worker-start
$ make mock
```
> [QA] Ne pas passer null lors de la manipulation de l'étage

- src/Command/UpdateSavoieSignalementCommand.php
#1575    
SIgnalements historiques crée à la main par les agents en 2023. 
Cette commande a pour objectif de mettre des dates de création et de fermeture correspondant à la réalité des dossiers avec retraitements des références.
Ces signalements doivent être taggé comme étant importés 
* Ajout d'une commande dédié
```
make load-data
````
Le fichier est dans le bucket
> [BO - Signalement] Modification Historique Savoie 

- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1753 
#1754 
#1755    
#1758 
Pour tous, sur la page où on sélectionne les zones de désordres on supprime le label qui doublonne le titre
Sur la page où on sélectionne les zones de désordres, il a écrit Votre logement il faudrait écrire Le logement pour les tiers
Ajout de  l'option "Je ne sais pas" pour les tiers sur l'écran "travailleur social" pour l'accompagnement
Pour les tiers pro, la case à cocher pour signaler qu'on est le travailleur social est rendu facultative (faute de frappe corrigée) et le texte est simplifié
* Modification des 4 json des déclarants tiers
* Et petite modification sur les 2 json occupant
> [New form - ecrans zone désordre et travailleur social]  quelques corrections

- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#1756    
A la question `Recevez-vous une aide ou allocation logement ?`, on me propose l'option `Je ne sais pas`
-> Pour tous les occupants, on devrait juste avoir `oui` ou `non`
* Changement des json de locataire et bailleur_occupant
> [New form - ecran logement social] Retirer option "je ne sais pas" pour la question logement_social_allocation pour les occupants

- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1746    
Supprimer une des checkbox pour bailleur et bailleur_occupant
Corriger le texte pour les autres tiers
* Changement des json
> [Front] Dans écran de validation de signalement, changer texte première case

- assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- tools/wiremock/src/Resources/Signalement/dictionary.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1589   
Finition du composant SignalementFormOverview
* Ajout de la description de la page dans tous les json
* Intégration du SignalementFormDisorderOverview pour les désordres avec ajustements css
* Affichage des parties Coordonnées  / Type et composition / situation en fonction du profil de l'usager
* Intégration de la partie Procédure
* Css sur les informations Complémentaires
* Utilisation de SignalementFormTextarea pour le message à l'administration
> [Front] Compléter SignalementFormOverview avec données dynamiques

- assets/vue/components/signalement-form/components/SignalementFormCounter.vue
#1752    
Un commentaire html dans le composant était ciblé par l'affectation de la classe fr-hidden à l'évaluation de la conditionnalité d'affiche. Ce qui rendait le composant visible quand il ne devait pas l'être. On n'avait pas le souci si on faisait un `npm run watch`, mais seulement après le `npm run build`
* Suppression du premier commentaire dans la partie html du composant SignalementFormCounter
`npm run build`
**(surtout ne pas faire `npm run watch`)**
> [New form - ecran logement social] Correction de la prise en compte de la conditionnalité d'affichage sur le composant SignalementFormCounter

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
#1768    
Quand on rechargeait un draft sur la page "vos coordonnées", une requête POST était envoyée au lieu d'une requête PUT, car l'uuid du draft n'était pas encore enregistré dans le formStore. On avait donc une duplication de draft en base
* Enregistrement du uuid dès handleInit
> [Front] Correction de la duplication de draft au rechargement sur la page coordonnées

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/store.ts
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1747
#1748 
#1749
* Ajout marges verticales sur l'écran d'intro
* Ajout hauteur minimale sur le menu desktop
* Prolongement de la bordure du menu desktop jusqu'en bas de page
* Ajout d'une propriété customCss sur les screen
> [Formulaire - Front] Ajustements de marges et bordures

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/interfaces/interfaceComponent.ts
- assets/vue/components/signalement-form/store.ts
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1773   
Amélioration de la gestion des composants clonés (paramètre repeat...count) pour mettre à jour le nombre de composant clonés lorsqu'on modifie la valeur du count sur un autre écran
* Modification de la fonction preprocessScreen
> [New form] Bouton Précédent - Affichage écran des pièces a vivre non mise à jour

- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/Suivi.yml
- src/Repository/SuiviRepository.php
- templates/back/table_result.html.twig
- templates/base.html.twig
- tests/Functional/Controller/BackStatistiquesControllerTest.php
- tests/Functional/Controller/SignalementListControllerTest.php
- tests/Functional/Service/Notification/NotificationCounterTest.php
#1684   
Prise en compte du statut "Refusé" à divers endroits : 
- affichage de ce statut dans la liste des signalements (il n'y avait rien)
- ajout du statut "Refusé" dans le filtre par statut
- exclusion des signalements au statut "Refusés" dans le compte des signalements sans suivi depuis 30 jours
* Modification du SuiviRepository pour la prise en compte du statut dans les signalements sans suivi depuis 30 jours
* Modification du twig table_result pour afficher le statut
* Modification du twig de base pour ajouter le statut Refusé dans les filtres
> [BO - Signalement] Signalement refusé par RT

- src/Command/ReinitAdminPasswordsCommand.php
- src/Repository/UserRepository.php
#724   
Ajout d'une commande qui 
- prend la liste des admins actifs
- les désactive
- modifie le mot de passe
- envoie un mail d'activation de compte
> [Sécurité] Ajout commande de réinitialisation des mots de passe pour les admins

- assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryItem.vue
#1786    
Changement de la couleur de bordure des catégories de désordres sélectionnées pour le logement
* SignalementFormDisorderCategoryItem : classe css computed
> 1786 : css on category item

- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
#1787    
Rendre les éléments de menu inactif une fois le signalement déposé
* Changement dans SignalementFormBreadCrumbs, prise en compte du currentScreen pour définir si le menu est actif ou non
>   [New form] Rendre éléments du menu inactifs après dépôt

- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Intervention.yml
- src/DataFixtures/Files/Partner.yml
- src/Repository/UserRepository.php
- src/Service/Signalement/VisiteNotifier.php
- tests/Functional/Repository/PartnerRepositoryTest.php
- tests/Functional/Repository/UserRepositoryTest.php
- tests/Functional/Service/Signalement/VisiteNotifierTest.php
#1804    
Pour le territoire 69, qui a un comportement spécial, nous avons constaté que certains mails concernant les visites ("mail de conclusion de visite" par exemple) étaient envoyés à tous les responsables territoires du 69 et pas seulement à la métropole concernée (COR ou MDL)
* Modification de la fonction findActiveTerritoryAdmins() dans le userRepository, pour lui envoyer le code insee du signalement, et filtrer les responsables de territoires liés à ce code insee
* Créations de fixtures pour faire les tests adéquats
> [BO - Signalement - 69] Mails reçus par la mauvaise communauté de communes

- src/Command/PushFailedEsaboraDossierCommand.php
#1508    
Correction de la commande `push-failed-esabora-dossier` qui échouait si jamais l'affectation n'existe plus (ce qui peut arriver)
* On vérifie l'existence de l'affectation avant de renvoyer les dossiers
> [Esabora] Correction de la commande 'push-failed-esabora-dossier'

- src/Service/Signalement/SignalementBuilder.php
- src/Service/Signalement/SignalementInputValueMapper.php
- tests/Functional/Service/Signalement/SignalementBuilderTest.php
- tests/Unit/Service/Signalement/SignalementInputValueMapperTest.php
#1835    
Centraliser les valeurs à transformer qui sont propre au nouveau formulaire
* Ajout d'un service mapper
* Utilisation de ce service dans signalementBuilder
https://github.com/MTES-MCT/histologe/pull/1788#discussion_r1363882760
> [Back] Créer un service pour la transformation des valeurs d'entrée du formulaire 

- templates/back/cgu_bo.html.twig
- templates/front/cgu.html.twig
#1839    
> Article 3 - Définition
remplacer :
`«l’Administrateur« ou « L’agent » est la personne travaillant dans la structure (collectivité territoriale ou services de l’Etat) ayant conventionné avec Histologe et habilitée à hiérarchiser les signalements et les transférer aux partenaires pour traitement des désordres.`
par
`«l’Administrateur« ou « L’agent » est la personne travaillant dans la structure (collectivité territoriale ou services de l’Etat) habilitée à hiérarchiser les signalements et les transférer aux partenaires pour traitement des désordres.`
* Modifications des 2 twigs de cgu
> [CGU] Modification

- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
#1834    
Dansle formulaire actuel, ajoute la possibilité de mettre un étage négatif pour le sous-sol
* Modification du pattern dans le formType
* Modification de la description et de l'erreur du champ texte
> [FO - Signalement]  Ajoute la possibilité de mettre des étages négatifs

- src/Controller/Back/SignalementController.php
- templates/back/table_result.html.twig
- tests/Functional/Controller/BackSignalementControllerTest.php
#1825 
#1826 
Sécurisation de la route `back_signalement_edit` et suppression du bouton "éditer" dans la liste des signalements si le signalement n'est pas en cours
* Ajout d'une vérification d'accès et de statut du signalement dans la route `back_signalement_edit`
* Ajout d'une condition sur le statut du signalement dans l'affichage de la liste des signalements pour afficher le bouton d'édition
> [BO - signalement] Interdire l'accès à l'édition d'un signalement cloturé (ou archivé)

- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1845 
#1840 
Ajout d'un SignalementFormInfo sur le désordre logement "hulmidité moisissure" (et suppression d'une incohérence de condition d'affichage entre la première checkbox et son subscreen)
Changement de textes pour les tiers
* Changement des 2 json de désordres
* Changement de 3 json de questions pour les tiers
>  [Formulaire] Ajustements json

- public/js/app.js
#1829   
Changement du message d'erreur lors d'un échec de l'envoi de signalement
* Changement du message dans app.js
> [QA] Problème d'enregistrement de signalement 

- src/Controller/Back/SignalementController.php
#1857   
Correction pour faire un suivi public dans tous les cas si c'est une clôture pour tous
> [Back] Correction pour faire un suivi public dans tous les cas si c'est une clôture pour tous

- migrations/Version20231031132907.php
- src/Controller/Back/AffectationController.php
- src/Controller/Back/SignalementActionController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Loader/LoadAffectationData.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Affectation.php
- src/Entity/Enum/MotifRefus.php
- src/Entity/Signalement.php
- src/Manager/AffectationManager.php
- templates/_partials/_modal_refus_affectation.html.twig
- templates/_partials/_modal_refus_signalement.html.twig
- templates/back/signalement/view/header.html.twig
- tests/Functional/Controller/AffectationControllerTest.php
#946
Ajout de liste de motifs de refus pour 
- la modale de refus d'affectation
- la modale de refus de signalement
Pour l'instant, c'est un enregistrement, on n'affiche la sélection nulle part
* Ajout d'un champ motifRefus dans la table affectation et la table signalement
> [BO - Signalement] Ajout d'une liste de motifs de refus d'affectation ou signalement

- src/Controller/Back/SignalementActionController.php
- src/Factory/SuiviFactory.php
#1882   
Ajout du motif de refus sélectionné dans le suivi
> [BO - Signalement] Ajout du motif de refus sélectionné dans le suivi

- src/Controller/Back/SignalementController.php
- src/EventSubscriber/SignalementClosedSubscriber.php
- templates/_partials/_modal_cloture.html.twig
- tests/Functional/EventSubscriber/SignalementClosedSubscriberTest.php
#1884   
Ajout d'une option pour notifier les usagers lors de la clôture pour tous
> [BO - Signalement] Ajout d'une option pour notifier les usagers lors de la clôture pour tous

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormConfirmation.vue
- assets/vue/components/signalement-form/components/SignalementFormLink.vue
- assets/vue/components/signalement-form/store.ts
- src/Controller/FrontNewSignalementController.php
- src/Manager/SignalementDraftManager.php
- tests/Functional/Controller/FrontNewSignalementControllerTest.php
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#1874    
Ajout d'informations sur la page après l'envoi de signalement.
* Modifications de la fin de tous les json de question (confirmation_signalement)
* Modification du FrontSignalementController et du SignalementDraftManager pour envoyer plus d'infos à VueJs quand on transforme le draft en signalement
* SignalementFormLink interprète les variables dans son lien
* Modification de contenu sur SignalementFormConfirmation
* Ajout des variables signalementReference et lienSuivi dans le store
> [Form - page de validation] Modifier le contenu

- src/Controller/Back/SignalementController.php
- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Signalement.yml
- tests/Functional/Controller/BackSignalementControllerTest.php
- tests/Functional/Controller/SignalementListControllerTest.php
#1906
Correction du warning "Warning: Undefined array key "publicSuivi" se produisant lorsqu'un utilisateur n'ayant pas le role "ROLE_ADMIN_TERRITORY" cloture un signalement.
* Correction de l'erreur dans src/Controller/Back/SignalementController.php (viewSignalement)
* Ajout de fixture permettant d'avoir le signalement "2023-26" cloturable pour l'utilisateur "admin-partenaire-13-01@histologe.fr"
* Modification et ajout de tests permettant de verifier le bon fonctionnement du formulaire de cloture pour différents roles en fonction du champ "publicSuivi" 
* Cloture par ROLE_ADMIN avec le champs public à "Non" 
* Cloture par ROLE_ADMIN_TERRITORY avec le champs public a "Oui" 
* Cloture par ROLE_ADMIN_PARTNER sans le champ public
> [QA - Sentry] undefined array key publicSuivi

- src/Factory/Esabora/DossierMessageSCHSFactory.php
#1029
#1830
Correction de l’addition du nombre d'enfant sur le commentaire du dossier ESABORA lorsque que le nombre contient un "+" (4+)
* Modification dans le fichier "DossierMessageSCHSFactory.php" méthode "buildCommentaire"
> [QA] Transformer 4+ en 4 (pb addition d'enfants si "4+")

- templates/_partials/_modal_cloture.html.twig
- templates/_partials/_modal_reopen_signalement.html.twig
#1884   
Correction de la sélection des boutons radio dans les modales de réouverture et cloture
* Identifiants uniques pour les radio buttons ; les doublons empêchaient les choix
> [BO - Signalement] Correction de la sélection des boutons radio dans les modales de réouverture et cloture

- public/js/app.js
- src/Controller/Back/SignalementController.php
- src/Controller/FrontSignalementController.php
- src/Entity/Signalement.php
- src/Service/FormHelper.php
- tests/Functional/Controller/FrontSignalementControllerTest.php
#1799
Ajout de contraintes sur le valeur des emails occupant ou déclarant (doivent être des email valide, au moins un des deux renseigné et de valeurs différentes)
* Ajout des contraintes sur l'entité Signalement
* Modification de app.js pour afficher les erreurs du formulaire
* Modification du FrontSignalementController et Back/SignalementController pour qu'il retourne les erreurs du formulaire
>  [Back] Renforcer la validation de l'email, il faut un email occupant ou déclarant

- assets/vue/components/signalement-form/components/SignalementFormLink.vue
- assets/vue/components/signalement-form/components/SignalementFormModal.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1871 
#1869    
Ajout d'un composant SignalementFormModal, pour préciser la différence entre déclarant occupant/ déclarant tiers, et la différence entre batiment/logement
* Création d'un nouveau composant VueJS
* Modification des json pour utiliser ce composant
> [Form] Ajout d'un composant SignalementFormModal

- templates/back/signalement/view/suivis.html.twig
#1928    
Depuis la mise en place de la sécurité pour ne pas avoir accès au document via simple lien, le lien vers ces documents ajouté dans les suivis ne fonctionne plus.
* Ajout de l'uuid du signalement dans le lien pour pouvoir accéder au document
> [BO - Signalement] Correction accès aux documents via suivis

- src/Factory/Esabora/DossierMessageSISHFactory.php
#1938   
De mauvaises données étaient envoyées
- le téléphone du propriétaire
- le téléphone du déclarant
- le prénom du déclarant
> [Esabora - SISH] Correction données envoyées pour le déclarant

- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
#1867    
Ajout d'une margin-bottom plus importante quand le footer est plus important pour rendre visible le bouton "je n'ai rien à signaler"
* Ajout d'une classe css
> [Formulaire - désordres] Bouton "rien à signaler" non visible sur mobile dans les listes de catégories de désordres

- assets/vue/components/dashboard/TheHistoAppDashboard.vue
- assets/vue/components/dashboard/TheHistoDashboardTables.vue
- src/Messenger/MessageHandler/DossierMessageSCHSHandler.php
- src/Repository/JobEventRepository.php
- src/Service/Esabora/EsaboraSCHSService.php
- src/Service/Esabora/EsaboraSISHService.php
#1941    
#1462 
Le client HTTP de Symfony lève une exception lorsque le code http est supérieur à 300. C'est pour cette raison que le message d'erreur d'origine n'était jamais récupéré.
https://symfony.com/doc/current/http_client.html#handling-exceptions
> When the HTTP status code of the response is in the 300-599 range (i.e. 3xx, 4xx or 5xx), the getHeaders(), getContent() and toArray() methods throw an appropriate exception, all of which implement the [HttpExceptionInterface](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Contracts/HttpClient/Exception/HttpExceptionInterface.php).
> To opt-out from this exception and deal with 300-599 status codes on your own, pass false as the optional argument to every call of those methods, e.g. $response->getHeaders(false);.
> If you do …
> [Esabora] Gestion et affichage des messages d'erreur

- scripts/upload-s3.sh
- src/Command/SlugifyDocumentSignalementCommand.php
- src/Command/UpdateSignalementDocumentFieldsCommand.php
- src/Service/Import/Signalement/SignalementImportLoader.php
- tests/Functional/Service/Import/Signalement/SignalementImportLoaderTest.php
- tests/Unit/Command/UpdateSignalementDocumentFieldsCommandTest.php
#1904    
Gestion des fichiers lors de l'import de signalements via csv
* Modification de la commande de slugification des fichiers à importer pour gérer les fichiers d'imports de signalement
* Modification de la commande d'import de signalements pour prendre en compte les fichiers renseignés
* `export BUCKET_URL=[dev_bucket]`
* Utiliser les fichiers présents sur le drive dans le ticket joint
* Utiliser le fichier csv joint à cette PR (correspond au fichier du drive, mais modifié pour éviter les erreurs) : [signalement_67.csv](https://github.com/MTES-MCT/histologe/files/13267144/signalement_67.csv)
Dans le dossier `/data/images` :
Dans le dossier `/tmp` :
Importer :
> [Import] Ajout de la gestion des fichiers lors de l'import de signalements via csv

- src/Factory/Esabora/DossierMessageSCHSFactory.php
- src/Service/Esabora/EsaboraManager.php
- src/Service/Esabora/Response/DossierStateSCHSResponse.php
- src/Service/Esabora/Response/DossierStateSISHResponse.php
- tests/Functional/Manager/Esabora/EsaboraManagerTest.php
- tests/Unit/Factory/Esabora/DossierMessageSCHSFactoryTest.php
#1942   
Ne pas envoyer de mail pour les suivi généré par Esabora `remis en attente via`
* Passer de suivi automatique à suivi technique
- Mettre les identifiants esabora-test à un partenaire ARS
- Ouvrir et purger Mailcatcher
> [BO - Notification Email] SISH/SCHS

- assets/styles/histologe.scss
- src/Controller/Back/SignalementEditController.php
- src/Controller/Back/SignalementListController.php
- src/Validator/TelephoneFormatValidator.php
- templates/_partials/_modal_affectation.html.twig
- templates/_partials/_modal_dpe.html.twig
- templates/_partials/_modal_edit_nde.html.twig
- templates/_partials/signalement/add_suivi.html.twig
- templates/back/signalement/view/edit-modals/edit-address.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-bailleur.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-foyer.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig
- templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig
- templates/back/signalement/view/edit-modals/edit-procedure-demarches.html.twig
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/header.html.twig
- templates/back/signalement/view/information.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-add.html.twig
#1896 
#1900 
#1898 
#1899 
#1901 
#1909 
#1910 
#1907 
#1896 : ajouter icone au lien modifier
#1898 : en cas de bailleur occupant, cacher le bloc "coordonnées du bailleur" et ajouter une info dans le bloc "coordonnées du foyer"
#1899 : dans l'édition des procédures et démarches, mettre un textarea pour la réponse de l'assurance
#1900 : dans les modales d'édition, ajouter un picto pour les boutons fermer annuler et valider
#1901 : augementer l'espace entre les lignes pour les différents blocs d'infos
#1909 : changer les messages de succès lors de l'édition des blocs d'info
#1910 : préciser le type de déclarant dans l'en-tête de la fiche signalement
#1907 : fix de l'édition de signalement en cas de non-admin
* Ajout d'une classe css
* Modification du SignalementEditController
* …
> [BO - Signalement] Quelques améliorations UI

- src/Factory/Esabora/DossierMessageSCHSFactory.php
#1961 
Contrôle de la valeur du 3ème paramètre passé a str_replace
* Méthode "buildNbEnfants" de "src/Factory/Esabora/DossierMessageSCHSFactory.php"
>  [QA - Sentry] Deprecated str_replace

- src/Factory/Esabora/DossierMessageSCHSFactory.php
- tests/Unit/Factory/Esabora/DossierMessageSCHSFactoryTest.php
#1912   
Sur certaines bases de données, l'encodage des données d'observation des pièces jointes bloque l'enregistrement sur Esabora.
On prend à présent les noms de fichiers slugifiés (donnée filename).
`make mock-start`
> [Esabora] Modification de la donnée d'observation des pièces jointes

- src/Controller/Back/SignalementController.php
#1946   
Export PDF accessible pour tous les agents affectés même si le signalement est clôturé
> [BO - Signalement] Export PDF pour tous les agents affectés même si le signalement est clôturé

- migrations/Version20231121140808.php
- src/Command/CreateSignalementPhotoVariantsCommand.php
- src/Controller/FrontSignalementController.php
- src/Controller/Security/SecurityController.php
- src/Entity/File.php
- src/Repository/FileRepository.php
- src/Service/ImageManipulationHandler.php
- src/Service/Signalement/SignalementBuilder.php
- src/Service/Signalement/SignalementFileProcessor.php
- src/Service/UploadHandlerService.php
#1929 
Création de la commande "app:create-signalement-photo-variants [numero_departement]" permettant de générer les miniature et redimensionnements de toutes les photos existantes sur les signalement du département (optionnel) passé en paramètre.
* Ajout d'un champ "variants" (booléen) sur File afin de savoir si les variantes de l'image ont été générés
* Création de la commande qui parcours les images des signalements (du département) afin de générer les variantes et d'enregistrer la taille des images redimensionnées
* Petit refactoring sur le traitement des images
Lancer les migrations
> [BO - Traitement image] Commande de traitement de photos (Miniature, Resize)

- assets/vue/components/stats/TheHistoStatsFilters.vue
#1838    
A priori, suite à la mise à jour du DSFR (bizarre qu'on l'ait pas vu avant), les listes déroulantes des multiselect ne s'affichaient plus correctement.
(a priori, pas d'effet de bord sur la correction effectuée)
> [BO - Statistiques] Correction de l'affichage des listes déroulantes (communes, étiquettes)

- templates/back/signalement/view/visites/visite-item.html.twig
- templates/emails/nouveau_suivi_visite_confirmed_to_user_email.html.twig
#1980   
Suite à un correctif sur la gestion de permission des fichiers 
https://github.com/MTES-MCT/histologe/pull/1902/files#r1385008863
Le lien de rapport de visite n'a pas été mise à jour
* Mise à jour du lien de rapport de visite
* Mise à jour du template d'email d'envoi du rapport à l'usager (car il n'est actuellement pas envoyé => https://github.com/MTES-MCT/histologe/issues/1983)
> [BO - Signalement] Rapport de visite non consultable

- src/Controller/Back/SignalementEditController.php
- src/Dto/Request/Signalement/AdresseOccupantRequest.php
- src/Dto/Request/Signalement/CoordonneesBailleurRequest.php
- src/Dto/Request/Signalement/CoordonneesFoyerRequest.php
- src/Dto/Request/Signalement/CoordonneesTiersRequest.php
- src/Dto/Request/Signalement/InformationsLogementRequest.php
- src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
- src/Dto/Request/Signalement/SituationFoyerRequest.php
- src/Entity/Signalement.php
- src/Service/Signalement/SignalementBuilder.php
#1905 
Copie des contraintes existantes sur le nouveaux formulaire (dépôt) sur les modale d'édition coté (bo, contraintes coté serveur)
* Ajout de contraintes et groupes de validation et utilisation de ces groupes et contraintes à l'édition du signalement ("src/Controller/Back/SignalementEditController.php", "src/Dto/Request/Signalement/AdresseOccupantRequest.php"...)
* Fix function "getTelProprioDecoded" / "getTelProprioDecoded" qui tombe sinon en erreur suite à une édition coté back ("src/Entity/Signalement.php")
* Fix function setProprietaireData pour qu'elle copie bien le nom du bailleur occupant ("src/Service/Signalement/SignalementBuilder.php")
>  [BO - Signalement] Mettre en place des groupes de validation pour les différents formulaires d'édition

- src/Service/Mailer/Mail/Signalement/SignalementAskBailDpeMailer.php
- src/Service/Mailer/Mail/Signalement/SignalementValidationMailer.php
- templates/emails/accuse_reception_email.html.twig
- templates/emails/ask_bail_dpe_signalement_email.html.twig
- templates/emails/validation_signalement_email.html.twig
#1972   
Afin de déterminer correctement si c'est l'occupant ou le déclarant qui crée un suivi usager, on sépare l'envoi en deux mails différents.
> [Mails] Envoi de 2 mails séparés pour occupant et déclarant

- .docker/nginx/default.conf
- .scalingo/nginx/server.location
- composer.json
- docker-compose.yml
Merci de lire la PR qui traite du même sujet coté punaises
https://github.com/MTES-MCT/stop-punaises/pull/478
#1951 
Dans le rapport fourni par https://dashlord.mte.incubateur.net/dashlord/url/histologe-beta-gouv-fr/securite/#http, il n'y'a pas d'en tête `X-Frame-Options`.
> L'en-tête de réponse [HTTP](https://developer.mozilla.org/fr/docs/Web/HTTP) X-Frame-Options peut être utilisé afin d'indiquer si un navigateur devrait être autorisé à afficher une page au sein d'un élément [<frame>](https://developer.mozilla.org/fr/docs/Web/HTML/Element/frame), [<iframe>]. 
Les sites peuvent utiliser cet en-tête afin d'éviter les attaques de [clickjacking](https://fr.wikipedia.org/wiki/Clickjacking) (ou « détournement de clic ») pour s'assurer que leur contenu ne soit pas embarqué dans d'autres sites. …
> [Sécurité] Rendre le site invisible dans une iframe

- src/Entity/Partner.php
#1974    
Suppression des vérifications caduques de mails utilisateurs quand on édite un partenaire
> [BO - Partenaires] Suppression des vérifications caduques de mails utilisateurs

- .github/workflows/main.yml
- templates/back/notifications/index.html.twig
#2011   
Suite  à la sécurité mise en place au niveau des accès aux fichiers, un oubli identifié dans la page notification qui redirige donc les liens des fichiers vers le tableau de bord
```php
#[Route('/_up/{filename}/{uuid?}', name: 'show_uploaded_file')]
```
* Mise à jour du lien avec l'uuid du signalement sur la page notification
> [BO - Notifications] Les liens redirigent vers le tableau de bord

- config/packages/security.yaml
- templates/security/login.html.twig
#734 
Configuration de la durée du cookie a 1 mois (au lieu de 1  an par défaut) et ajout d'une case à cocher "Se souvenir de moi" sur le formulaire de connexion
>  Mettre en place la déconnexion automatique des sessions d'accès après une durée déterminée

- migrations/Version20231201140751.php
- src/Controller/FrontSignalementController.php
- src/DataFixtures/Files/Territory.yml
- src/DataFixtures/Loader/LoadTerritoryData.php
- src/Entity/Territory.php
- src/EventSubscriber/SignalementDraftCompletedSubscriber.php
- src/Repository/PartnerRepository.php
- src/Service/Signalement/AutoAssigner.php
- tests/Functional/Repository/PartnerRepositoryTest.php
- tests/Unit/Service/AutoAssignerTest.php
#1894   
Mise en place de l'affectation automatique d'un signalement dès sa création avec les règles suivantes :
- ajout d'une propriété sur les territoires pour autoriser l'affectation automatique
- les partenaires doivent avoir 
- au moins un agent
- un code Insee correspondant au signalement
- un type COMMUNE_SCHS
Dans les fixtures, le territoire de l'Ain autorise l'affectation automatique, le partenaire Partenaire 01-02 (code insee 01173 - commune Gex) correspond.
> [Signalement] Affectation automatiques pour territoires et partenaires définis

- templates/back/signalement/view/information.html.twig
#1898    
en cas de bailleur, cacher le bloc "coordonnées du bailleur" et ajouter une info dans le bloc "coordonnées du tiers déclarant"
* Modifications de twig
> [BO - Nouveau signalement] Modifier l'affichage des coordonnées quand bailleur

- templates/back/signalement/view/edit-modals/edit-procedure-demarches.html.twig
#2010   
Affichage de la vraie valeur pour "souhaite garder le logement après travaux" dans la modale d'édition de la partie "Informations procédures"
* Changement du twig de la modale
> [BO - Signalement] Mauvaise donnée affichée dans partie procédure

- src/Command/Cron/AbstractSynchronizeEsaboraCommand.php
- src/Command/Cron/SynchronizeInterventionSISHCommand.php
- src/Command/PushEsaboraDossierCommand.php
- src/Repository/AffectationRepository.php
- tests/Unit/Command/PushEsaboraDossierCommandTest.php
#2022   
Les derniers territoires ouverts sont restés non sync depuis leur ouvertures, une reprise des dossiers affectés à l'ARS  est nécessaire.
https://mattermost.incubateur.net/betagouv/pl/qqh13c8pupn69qnepgc8qajhge
> [!CAUTION]
> 13 et 06 ont un fonctionnement différent avec 2 ARS (à renseigner dans https://github.com/MTES-MCT/histologe/issues/1680)
> *Mail du 11/07/2023 15:45*  
* Ajout d'une commande pour synchroniser un dossier ou un territoire **(pas possible pour le 13 et le 06 en prod)**
```
make work-start
```
* Désactiver la synchronisation [d'un partenaire ARS](http://localhost:8080/bo/partenaires/7/voir) 
* Affecter `PARTENAIRE 13-06 ESABORA ARS` [au dossier 2023-9](http://localhost:8080/bo/signalements/00000000-0000-0000-2023-000000000009) (celui ci aura la …
> [BO - Esabora] SI-SH Reprise des dossiers non sync des derniers territoires

- CONTRIBUTING.md
- README.md
- templates/footer.html.twig
#719   
Ajout d'informations dans footer et GitHub pour contacter l'équipe ou contribuer au projet
> [Sécurité] Ajout d'informations dans footer et GitHub pour contacter l'équipe ou contribuer au projet

- src/Service/Signalement/SignalementBuilder.php
- templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig
#2019    
Le lien entre déclarant et occupant a été rendu facultatif. Mais il y avait un bug à l'enregistrement si il n'était pas renseigné.
> [Front - Nouveau formulaire] Enregistrement facultatif du lien déclarant - occupant

- src/Controller/Security/UserAccountController.php
#1816   
Lorsqu'un usager crée un signalement, on lui crée un compte utilisateur avec le ROLE_USAGER.
Jusqu'à présent, aucun test ne venait bloquait sa progression quand :
- il demande un nouveau mot de passe
- il tente d'activer son compte
Ajout d'un test lors de ces deux procédures pour éviter qu'il puisse accéder au BO
> [FO - Comptes utilisateurs] Bloquer l'activation pour les usagers

- templates/base.html.twig
#2033   
Certaines personnes parviennent à se connecter en ROLE_USAGER mais le tracking avancé Matomo n'est pas d'actualité pour ces personnes. On désactive donc l'envoi de données complémentaires pour ces personnes.
> [Matomo] Ajout de test pour éviter le tracking précis Matomo

- migrations/Version20231218162844.php
- src/Entity/Signalement.php
#2040 
Retrait de la contrainte NotBlank sur le chjamp détails de l'entité Signalement et conversion du champ en nullable
> [BO - Signalement] Enlever l'obligation sur le champ "details"

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormModal.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/store.ts
- src/Controller/FrontSignalementController.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Validator/IsTerritoryActive.php
- src/Validator/IsTerritoryActiveValidator.php
- templates/front/nouveau_formulaire.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#1532 
Ajout d'un contrôle de la paire "code postal/code INSEE" lors de la sélection d'une adresse sur le nouveau formulaire afin de pouvoir afficher (via modale) si le territoire n'est pas ouvert.
Ajout d'un contrôle identique coté serveur.
* Appel de la route "front_signalement_check_territory" lors de la sélection d'une des adresse proposé du nouveau formulaire et eventuel affichage d'une modale d'erreur si le territoire n'est pas actif.
* Ajout d'une contrainte de validation "IsTerritoryActive" pour appliquer un contrôle similaire coté serveur.
* Ajout d'un contrôle de cohérence entre le code postal et code INSEE
> Gérer les signalements sur des territoires non-ouverts

- assets/styles/histologe.scss
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- src/Dto/Request/Signalement/CoordonneesBailleurRequest.php
- src/Dto/Request/Signalement/CoordonneesFoyerRequest.php
- src/Dto/Request/Signalement/CoordonneesTiersRequest.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Entity/Signalement.php
- src/Form/SignalementType.php
- templates/_partials/_signalement_steps_tabs.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-bailleur.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-foyer.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig
- templates/back/signalement/view/information.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_service_secours.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#2015 
Ajout de contraintes de validation sur la longueur de tous les nom et prénom des signalement
* Ajout de contraintes sur les nom et prénom de façon globales (ancien et nouveau formulaire, ancienne et nouvelle édition) autant coté client que serveur
> [FO - Signalement] Ajout de contrainte de validation sur la longueur des champs (nom et prénom)

- src/Controller/Back/SignalementFileController.php
- templates/back/signalement/view/header.html.twig
#2047 
Retrait de la limitation au signalement contenant moins de 21 image pour pouvoir exporter le signalement en PDF
> [BO - Export PDF] Retirer la limitation des 20 images

- migrations/Version20231213171924.php
#2029    
Problème remonté par le 06, ~ 1700 fichiers sont rattaché à un utilisateur qui n'est pas du bon territoire. Il n'existe pas de bug à l'heure actuelle. Problème provenant sans doute lors de la migration (sept - oct 2022)  des territoires vers la plateforme unique
https://histologe-metabase.osc-fr1.scalingo.io/question/1103-fichiers-dont-lutilisateur-nappartient-pas-au-bon-territoire
* Ajout d'une migration pour supprimer la relation
```sql
SELECT COUNT(*)
FROM file f
INNER JOIN signalement s ON     s.id = f.signalement_id 
INNER JOIN user u ON u.id = f.uploaded_by_id 
WHERE u.territory_id != s.territory_id 
AND u.roles NOT LIKE '["ROLE_ADMIN"]';
```
> [BO - Document] Migration Sept 2022- Anonymiser les documents n'appartenant pas au bon territoire

- migrations/Version20231222094349.php
#2056   
Migration pour attribuer la compétence visite à différents types de partenaires :
- OPERATEUR_VISITES_ET_TRAVAUX,
- ARS,
- CAF_MSA,
- COMMUNE_SCHS,
- DISPOSITIF_RENOVATION_HABITAT
> [BO - Partenaires] Migration pour attribuer la compétence visite

- assets/vue/components/signalement-form/store.ts
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
#2057   
Puisque la plateforme Stop Punaises est à présent ouverte sur l'ensemble du territoire, on modifie le message et on affiche la plateforme pour tout le monde.
> [FO - Formulaire] Suppression de la vérification de l'ouverture de Stop Punaises

- src/Entity/User.php
#2051   
On a une erreur Sentry lorsque le prénom est vide.
J'ai tenté de reproduire en supprimant le prénom d'un utilisateur, mais je n'ai pas d'erreur.
J'ai ajouté un test et testé les dommages collatéraux.
> [QA - Sentry] Vérification sur nom et prénom avant de retourner le Nom complet

- migrations/Version20240103121522.php
#2083    
Migration pour rendre la Seine-St-Denis en auto-affectation
* Migration
> [Ouverture] Enable auto-affectation in Seine St-Denis 93

- cron.json
- scripts/sync-db.sh
#1152    
Metabase sera déconnecté de la production afin d’être connecté à l'application histologe-preprod, ce script servira à faire la mise à jour de la base de prod de prod vers la preprod
* Ajout d'un script de synchro
* Définition d'un cron
* Ajout de variables d'environnements uniquement pour histologe-preprod ou review app si besoin **MAIS NE FONCTIONNERA PAS EN PRODUCTON**
| Variable d'environnement         | Description            |
|------------------------------------------|------------------------------|
| RUN_SYNC_DB               |  Permet d’exécuter le script                |
| DUPLICATE_ADDON_KIND      | Permet de définir le type d'addon scalingo            |
| DUPLICATE_API_TOKEN       | Token d’autorisation  d'API Scalingo  (doit être généré sur un compte ayant acces au …
> [Performance] Script de synchronisation de base de donnée

- assets/styles/histologe.scss
- assets/vue/components/signalement-form/components/SignalementFormDisorderOverview.vue
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- templates/back/signalement/view/user-declaration.html.twig
- templates/pdf/signalement.html.twig
#2062
Échappement de l'affichage du champ "details" d'un signalement en BO
Ajout d'un saut de ligne manquant dans le récap du nouveau formulaire
> [Sécurité] Ne pas afficher le champ details d'un signalement en raw

- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- migrations/Version20231218154729.php
- src/DataFixtures/Files/signalement_draft_payload/step/validation_signalement/bailleur.json
- src/Dto/Request/Signalement/CompositionLogementRequest.php
- src/Dto/Request/Signalement/CoordonneesBailleurRequest.php
- src/Dto/Request/Signalement/CoordonneesFoyerRequest.php
- src/Dto/Request/Signalement/CoordonneesTiersRequest.php
- src/Dto/Request/Signalement/InformationsLogementRequest.php
- src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Dto/Request/Signalement/SituationFoyerRequest.php
- src/Entity/Enum/ProprioType.php
- src/Entity/Model/InformationComplementaire.php
- src/Entity/Signalement.php
- src/Factory/Signalement/InformationComplementaireFactory.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementBuilder.php
- templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-bailleur.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-foyer.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-tiers.html.twig
- templates/back/signalement/view/edit-modals/edit-informations-logement.html.twig
- templates/back/signalement/view/edit-modals/edit-procedure-demarches.html.twig
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/information.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
#2037    
Toutes les informations qui étaient dans la partie cachée des "informations complémentaires" étaient (en partie) enregistrées, mais n'étaient pas affichées, ni éditables.
* Gestion des différents champs dans différentes zones de la fiche signalement
* Ajout d'une colonne typeProprio dans l'entité Signalement
* Correction de la date d'emménagement pour son affichage et son édition dans la fiche
* Ajout civilité quand nécessaire
* Séparation date d'emmenagement et date d'effet du bail dans l'enregistrement des données
> [BO - Signalement] Ajout des infos complémentaires à la fiche signalement

- migrations/Version20240104143200.php
- public/js/app.js
- src/Command/UpdateCommunesCommand.php
- src/Command/UpdatePartnerAndCommuneNDECommand.php
- src/Controller/FrontSignalementController.php
- src/DataFixtures/Loader/LoadCommuneData.php
- src/Entity/Commune.php
- src/Form/PartnerType.php
- src/Validator/IsTerritoryActiveValidator.php
- templates/_partials/_modal_closed_territory.html.twig
#2081 
- Correction des fixtures de chargements des communes
- Commande `update-communes` de mise à jour des communes
- Remise en place du contrôle de cohérence code postal / code insee. L'erreur existante étant due au données non importées par erreur (cas d'un même code INSEE sur plusieurs code postaux)
* Ajout d'une contrainte d'unicité sur la paire "code_postal" et "code_insee" de la table commune
* Impact du fait que plusieurs ligne de commune peuvent avoir le même code INSEE, changement de `findOneBy` en `findBy`
Jouer la migration `make execute-migration name=Version20240104143200 direction=up`
> Import/Mise à jour des données de la table commune

- .env
- .env.sample
- .scalingo/nginx/server.location
- public/index.php
#1952    
En-têtes de sécurité manquantes https://dashlord.incubateur.net/url/histologe-beta-gouv-fr/securite/
Présentation des différentes directives utilisés de CSP (Content Security Policy)
| Directive        | Signification                                      |
| ----------------- | -------------------------------------------------- |
| `default-src`     | Sources par défaut pour toutes les catégories.    |
| `script-src`      | Sources autorisées pour les scripts.               |
| `style-src`       | Sources autorisées pour les styles.                |
| `img-src`         | Sources autorisées pour les images.                |
| `font-src`        | Sources autorisées pour les polices de caractères. |
| `connect-src`     | Sources autorisées pour les connexions réseau.     |
* …
> [Sécurité] Ajout en-têtes de sécurité manquantes dont la CSP

- src/Command/UpdateCommunesCommand.php
- src/DataFixtures/Loader/LoadCommuneData.php
- src/Utils/ImportCommune.php
#2107
Fix de la commande update-communes afin qu'elle ne dépende plus du DoctrineFixtureBundle
> [bug] La commande de maj des commune ne dépends plus des fixtures

- public/js/maps.js
#2106   
Dans le nouveau formulaire, selon les profils, le nom de l'occupant est facultatif.
Sur la cartographie, lorsqu'on affiche les signalements, on met le nom de l'occupant en majuscule.
Si on appelle la méthode pour mettre en majuscule sur du vide, on a une erreur JS.
> [BO - Cartographie] Correction pour éviter l'absence d'affichage si le nom de l'occupant est vide

- .scalingo/nginx/server.location
#2113    
Erreur de non reconnaissance de header remonté par dashlord
* Correction typo
```bash
docker compose build histologe_nginx
make down && make run
```
```bash
curl -I http://127.0.0.1:8080
```
> [Sécurité] Correction typo X-Content-Type-Options

- src/Service/Intervention/InterventionDescriptionGenerator.php
- tests/Unit/Service/Intervention/InterventionDescriptionGeneratorTest.php
#1815    
Changer le message quand la visite envoyée par SISH est dans le passé.
* Changement de `InterventionDescriptionGenerator` et du test associé
`make mock-start`
> [SISH - Visite] Message notification

- migrations/Version20240115155416.php
#2006
Migration pour remettre la date_entree à null si elle est postérieure à created_at
* Nouvelle migration
> [BO - Export PDF] Date entree dans les lieux

- .scalingo/nginx/server.location
#2136   
La conf actuelle empêche la suppression de photo et de document (Erreur 404) sachant que la requête de suppresson ne devrait pas respecter les deux directives déjà présentes 
* Ajout d'une nouvelle directives qui renvoie la requête de suppression à symfony 
```
docker compose build histologe_nginx && make down && make run
```
> [HOTFIX] [BO] Pouvoir supprimer les photo/document d'un signalement

- src/Entity/SignalementQualification.php
#2142    
L'une des dernières migrations applique `null` comme valeur par défaut pour `desordre_precision_ids`, alors que l'attribut de la classe est de type tableau uniquement ce qui provoque l'erreur 500 après que  l'objet `signalementQualification` soit hydraté.
Autoriser donc que l'attribut de la classe puisse accepter `null` comme valeur.
* Mise à jour du typage `desordrePrecisionIds`
> [BO][Staging] Des signalements avec qualifications sont non accessibles

- assets/vue/components/signalement-form/components/SignalementFormCounter.vue
- assets/vue/components/signalement-form/components/SignalementFormDate.vue
- assets/vue/components/signalement-form/components/SignalementFormDisorderCategoryItem.vue
- assets/vue/components/signalement-form/components/SignalementFormEmailfield.vue
- assets/vue/components/signalement-form/components/SignalementFormRoomList.vue
- assets/vue/components/signalement-form/components/SignalementFormTextarea.vue
- assets/vue/components/signalement-form/components/SignalementFormTextfield.vue
- assets/vue/components/signalement-form/components/SignalementFormTime.vue
- assets/vue/components/signalement-form/components/SignalementFormUpload.vue
- assets/vue/components/signalement-form/components/SignalementFormYear.vue
- src/DataFixtures/Files/DesordrePrecision.yml
#2101
Correction des labels des éléments de formulaires
* Correction des labels des éléments de formulaires dans plusieurs composants
* Correction du slug d'un DesordrePrecision
> [Nouveau formulaire][Accessibilité] L'élément label n'est pas associé au champ

- src/Controller/Back/SignalementFileController.php
- src/Controller/Back/SignalementVisitesController.php
- src/Service/UploadHandlerService.php
- templates/back/signalement/view/visites/visite-item.html.twig
- templates/back/signalement/view/visites/visites-form-confirm-fields.html.twig
#2071 
Ajout d'un bouton permettant de supprimer le rapport d'une visite (ce qui permet ensuite d'en uploader un autre via le bouton "Editer le rapport"
* Refactoring dans `UploadHandlerService` pour avoir une fonction `deleteFileInBucket`
> [BO - Signalement] Rapport de visite non modifiable

- src/DataFixtures/Files/signalement_draft_payload/locataire.json
- src/Service/Signalement/SignalementDocumentTypeMapper.php
- tests/Unit/Factory/FileFactoryTest.php
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#2139   
De la même manière que pour le bail ou le DPE, ajouter un bouton d'upload pour l'état des lieux quand on coche "Oui" à la question Avez-vous fait un état des lieux quand vous avez emménagé ? (ou Avez-vous réalisé un état des lieux à l'entrée des locataires ? pour les bailleurs)
* Modification des json de questions
* Modification d'une fixture
* Ajout d'un test
* Modification du SignalementDocumentTypeMapper
> [Signalement - bail-dpe] Ajouter bouton upload état des lieux

- src/DataFixtures/Files/DesordreCritere.yml
#2165    
Changement du label d'un critère dans les fixtures
:warning: j'ai mis à jour la bdd de staging avec la commande, donc le test ici ne concerne que la fixture
* Changement d'une fixture
> [BO - Désordres] Label critère - Structure Equipements

- assets/styles/histologe.scss
- templates/back/signalement/view/information.html.twig
#2173   
Ajout de gouttières dans les blocs d'information pour éviter que certaines informations soient collées, selon les tailles d'écran et les informations affichées.
> [BO - Signalement] Ajout de marges verticales dans les blocs d'information

- src/Controller/Back/SignalementController.php
- src/Manager/SignalementManager.php
- templates/_partials/_modal_edit_nde.html.twig
- templates/_partials/signalement/qualification.html.twig
- templates/back/signalement/view/address-qualifications.html.twig
#2184   
Le TAG NDE doit s afficher pour tous dès lors que la NDE est constatée
* Suppression de contraintes
> [BO - Signalement] TAG NDE

- src/Manager/SignalementManager.php
#2175   
Quand on changeait la valeur d'allocataire dans Situation du foyer, le tag Suroccupation n'était pas mis à jour, car les valeurs `setLogementSocialAllocationCaisse` et  `setLogementSocialAllocation` de situationFoyer n'étaient pas mises à jour
* Mise à jour du SignalementManager
> [BO - Edition] Recalcul Suroccupation

- src/Factory/SignalementQualificationFactory.php
- templates/back/signalement/view/information.html.twig
#2189   
Lorsqu'on sauvegarde la situation du foyer, la date de dernier bail est mise à jour en fonction de la date d'entrée ou de la date de bail.
Si la date d'entrée était après 2023, lors de la sauvegarde de la situation du foyer, il y avait un souci de typage de la date. (DateTimeInterface vs DateTimeImmutable)
J'en ai profité pour corriger l'affichage de la date d'effet du bail qui s'affichait au format YYYY-MM-DD
> [BO - Signalement] Correction enregistrement date dernier bail

- templates/back/signalement/view/address-qualifications.html.twig
- templates/back/signalement/view/information.html.twig
- templates/back/signalement/view/suivis.html.twig
#2174   
Un agent qui n'a pas encore accepté une affectation ne peut pas éditer un signalement, ni ajouter de suivi
> [BO - Signalement] Bloquer l'édition pour les agents qui n'ont pas accepté l'affectation

- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- src/Controller/FrontNewSignalementController.php
- src/Controller/HomepageController.php
- src/Dto/Request/Signalement/CompositionLogementRequest.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Specification/Signalement/SuroccupationSpecification.php
- tests/Functional/Controller/HomepageControllerTest.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Specification/Signalement/SuroccupationSpecificationTest.php
- tools/histologe/histologe.postman_collection.json
- tools/wiremock/src/Resources/Signalement/dictionary.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#2160 
#2170 
#2171 
#2172    
#2163 
Recette du nouveau formulaire
* Correction d'une faute de frappe dans le dictionnaire
* Rendre obligatoires les champs "nom" et "occupant" pour tous les profils, sauf le service secours
* Correction de l'erreur 500 si la superficie n'est pas renseignée pour les profils ties, particuliers, pro et service de secours
* Rendre le nombre de pièces obligatoire en mode édition
* Filtrer l'adresse de l’auto-complétion de l'occupant par le code postal saisi
* Mise à jour de la collection Postman
Charger la nouvelle collection Postman (j'ai mis tous les profils en POST et en PUT)
L'UUID se charge automatiquement
Faire une requête POST en tant que locataire, puis enchainer avec le PUT en tant que locataire
> [FO][BO] Recette du nouveau formulaire - Filtre adresse, contraintes de validation dépôt , typo

- src/Controller/Back/SignalementEditController.php
- src/Controller/Back/SignalementFileController.php
- src/EventListener/SignalementUpdatedListener.php
#2054   
Ajout de suivis automatiques lorsqu'on modifie les différents blocs d'un signalement
| Déclencheur | Auteur | Contenu | Partagé à l'usager 
| :--- | :--- | :--- | :---: | 
| Edition de l'adresse | Nom de l'agent + nom du partenaire | L'adresse du logement a été modifiée par {{nom partenaire}} | Non
| Edition des coordonnées occupant | Nom de l'agent + nom du partenaire | Les coordonnées du foyer ont été modifiées par {{nom partenaire}} | Non
| Edition des coordonnées tiers déclarant | Nom de l'agent + nom du partenaire | Les coordonnées du tiers déclarant ont été modifiées par {{nom partenaire}} | Non
| Edition des coordonnées bailleur | Nom de l'agent + nom du partenaire | Les coordonnées du bailleur ont été modifiées par {{nom partenaire}} | Non
| Edition des info logement | …
> [BO - Signalement] Créer des suivis automatiques lors de la modification d'un signalement

- assets/vue/components/dashboard/TheHistoAppDashboard.vue
- src/Repository/JobEventRepository.php
- src/Service/DashboardWidget/WidgetLoader/EsaboraEventWidgetLoader.php
#1967 
- Limitation du nombres de résultats retourné au widget "Connexions ESABORA" à 1000 pour éviter erreur sur la masse des données pour les admin
- Conversion des données de réponse retourné par le web service en message clair
> [BO - Esabora]Tableau de bord - Normaliser les messages d'erreurs

- src/DataFixtures/Files/DesordrePrecision.yml
- src/Manager/DesordreCritereManager.php
- src/Service/Signalement/DesordreTraitement/DesordreTraitementPieces.php
- tools/wiremock/src/Resources/Signalement/desordres_profile_occupant.json
- tools/wiremock/src/Resources/Signalement/desordres_profile_tiers.json
#2183    
Les désordres liés à "aucun type de chauffage" n'étaient pas pris en compte, dû à une forme différente dans le payload. Car ce n'est pas un critère qu'on coche à proprement parler (comme par exemple `"desordres_batiment_proprete_facades": 1`) mais un choix de type de chauffage qu'on met sur "aucun" : `"desordres_logement_chauffage_type": "aucun",`
* Mise à jour des fixtures et des questions de désordres car il manquait "_type" par endroit
* Mise à jour de la fonction `getCriteresSlugsInDraft` dans le `DesordreCritereManager` pour prendre en compte ce cas particulier
* Mise à jour de `DesordreTraitementPieces` pour prendre en compte ce cas particulier
Recharger les fixtures ou jouer la commande `make console app="import-desordres-tables"`
> [BO - Signalement] Désordres - Absence de chauffage

- src/Entity/Enum/ChauffageType.php
- src/Service/Signalement/SignalementBuilder.php
- templates/back/signalement/view/user-declaration-desordre.html.twig
#2166   
On affiche le type de chauffage sélectionné par l'usager
* Changement du SignalementBuilder pour enregistrer le type de chauffage dans jsonContent (comme on a fait pour la précision sur les nuisibles)
* Modification du twig d'affichage de désordre pour afficher d'éventuels éléments liés à une catégorie de désordres.
>  [BO - Désordres] Affichage du type de chauffage

- src/Controller/Back/SignalementEditController.php
- src/Serializer/SignalementDraftRequestNormalizer.php
#2160    
Commentaire de @hmeneuvrier lié à [ce lien](https://github.com/MTES-MCT/histologe/pull/2186)
> En éditant un signalement pour un profil tiers particulier, la superficie et le nombre de pièces sont obligatoires, ce que je trouve étrange étant donné qu'ils ne sont pas obligatoires sur le FO (au moins la superficie).
En fait, c'est la contrainte positive qui bloque la chaîne vide comparée à 0. Quant aux chaînes de caractères avec de vraies valeurs, elles ne s'appliqueront pas à la contrainte positive (il faudrait que ce soit de vrais nombres (float, int)).
Et Il manquait la contrainte lié au profile
Il y aura un travail à faire à terme au niveau des types de données des payload et des DTO (pas urgent vu l'usage via des formulaires). En effet, lorsque l'on ne passe pas par le …
> [BO] Correction effet de bord transformation de chaîne vide à null

- src/Entity/Suivi.php
- src/Repository/SuiviRepository.php
#2181   
Certains signalements (voir ticket joint) ne recevaient pas de relance automatique.
Après étude, les signalements dont la valeur de `is_usager_abandon_procedure` était à NULL n'était pas retourné.
Etrangeté de MySQL qui ne considère pas les valeurs `NULL` dans `!= 1`
> [Relances auto] Correction requête pour ne pas exclure les abandons de procédures NULL

- src/Entity/Suivi.php
#2181   
Modification du nombre de relances max par type de relance : on passe de 400 à 200 (donc 3 x 400 à 3 x 200)
> [Relances automatiques] Modification du nombre de relances max par type de relance

- src/Service/Signalement/DesordreTraitement/DesordreCompositionLogementLoader.php
#2207    
Sur un signalement fait pas un tiers, la superficie n'est pas obligatoire. Si c'est une pièce unique, on a le désordre suivant par erreur
"La superficie du logement < 9m"
et du coup, les scores et qualifs qui vont avec.
Dans le calcul des désordres liés à la composition du logement, vérifier que la superficie est bien définie.
DesordreCompositionLogementLoader->load() ligne 51
* Ajout d'une condition avant d'ajouter le désordre
> [BO - signalement] Création d'un désordre par erreur si superficie non définie

- .env
- .env.sample
- config/packages/sentry.yaml
#973    
Configurer la partie https://docs.sentry.io/platforms/php/guides/symfony/performance/
* Rendre l'environnement configurable
* Ajout d'options pour le monitoring de la performance
On peut aussi aller à 100% du trafic en production sachant qu'on a pas de millions d'utilisateurs
```
```
Review app configuré avec 100% du traffic
https://histologe-staging-pr2209.osc-fr1.scalingo.io/
> [Performance] Mise en place outil APM (Application performance monitoring) pour monitorer la plateforme

- src/Security/Voter/UserVoter.php
#2217   
Les widgets NDE appraissaient sur le dashboard pour les partenaires ayant la compétence NDE mais n'étant pas dans le territoire d'expérimentation, alors que le nouveau formulaire n'est pas encore activé
* Correction du UserVoter
> [BO - dahsboard] Apparition des widgets NDE pour tous ceux qui ont la compétence, alors que le formulaire n'est pas activé

- src/Controller/Back/SignalementController.php
#2223 
Retrait de l'affichage des compétences des partenaires dans la liste de la modale d'affectation des partenaires
> [BO - Signalement] Liste partenaire a affecter

- src/Dto/Request/Signalement/ProcedureDemarchesRequest.php
- src/Dto/Request/Signalement/SituationFoyerRequest.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementBuilder.php
- templates/back/signalement/view/edit-modals/edit-procedure-demarches.html.twig
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/information.html.twig
#2161   
L'info concernant les demandes de relogement est posée de deux manières différentes dans le formulaire, selon qu'on soit occupant ou tiers.
Les deux réponses étaient affichées dans 2 blocs différents dans le BO.
On regroupe donc les deux réponses, affichées selon le profil, dans le même bloc `Situation du foyer`.
> [BO - Signalement] Déplacement de l'info concernant le relogement

- assets/controllers/view_signalement.js
- assets/styles/histologe.scss
- public/js/app.js
- src/Entity/Enum/DocumentType.php
- templates/back/signalement/view.html.twig
- templates/back/signalement/view/photos-album.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- templates/back/signalement/view/user-declaration-desordre-photo.html.twig
#2095    
Mise en place d'un album photo pour visionner les photos liées à un signalement.
Voir "Mode album" dans les specs : https://github.com/MTES-MCT/histologe/wiki/Ajout-documents
- Quand on clique sur une photo, ça ouvre l'album sur la photo cliquée.
- Quand on clique sur précédent / suivant, on se déplace dans la liste des photos
- Des informations sur la photo sont affichées
> [BO - Signalement] Affichage des photos dans un album

- src/Controller/FrontSignalementController.php
- src/Service/UploadHandlerService.php
- tests/Functional/Service/UploadHandlerServiceTest.php
#2211 #2212
- Correction de l'erreur "Error: Call to a member function setKey() on array" si l'upload d'une image ne se passe pas correctement
- Correction de l'erreur "Argument https://github.com/MTES-MCT/histologe/pull/1 ($filename) must be of type string, array given" lors de la soumission du formulaire
Je n'ai pas su reproduire les erreurs via une utilisation normale, voici comment on peux tester :
> [QA - Sentry] setKey on Array / TypeError

- migrations/Version20240205143843.php
- src/Controller/Back/SignalementFileController.php
- src/Controller/FrontSignalementController.php
- src/DataFixtures/Loader/LoadInterventionData.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/File.php
- src/Entity/User.php
- src/EventSubscriber/SignalementCreatedSubscriber.php
- src/Factory/FileFactory.php
- src/Manager/FileManager.php
- src/Manager/InterventionManager.php
- src/Service/Signalement/SignalementFileProcessor.php
- templates/back/signalement/view/photos-documents.html.twig
- tests/Functional/Manager/FileManagerTest.php
- tests/Unit/Factory/FileFactoryTest.php
- tests/Unit/Service/Signalement/SignalementFileProcessorTest.php
#2155 
#2203 
#2202   
Mise à jour des types de documents dans les possibilités actuelles
Ajouter une colonne description pour les fichiers (utilisée pour les photos de visite)
Migration pour passer les documents et photos existantes en type "Autre"
Mise à jour du uploadedBy sur les fichiers lors de la création de signalement et de l'ajout de suivis
Mise à jour de l'affichage du bouton "supprrimer le fichier" en fonction des specs https://github.com/MTES-MCT/histologe/wiki/Ajout-documents#bo---supprimer-les-documents-et-photos
* Création d'une migration
* Mise à jour des controllers
* Mise à jour des loaders de fixtures
* Mise à jour de l'entité File pour ajouter la description et des fonctions isUsagerFile et isPartnerFile
* Mise à jour de la FileFactory
* Mise à jour des FileManager et …
> [FO/BO - Signalement] Mise à jour des types de documents

- assets/app.ts
- assets/controllers/activate_account/activate_account.js
- public/js/app.js
- src/Command/AddUserCommand.php
- src/Entity/User.php
- templates/security/reset_password_new.html.twig
- tests/Functional/Controller/UserAccountControllerTest.php
- tests/Unit/Entity/UserTest.php
#721 #2145
Ajout de contraintes de validation pour des mot de passe plus fort : 
- 8 caractères minimum
- 1 caractère majuscule minimum
- 1 caractère minuscule minimum
- 1 chiffre minimum
- 1 caractère spécial minimum
Suppression de l'affichage de la modale CGU lors de la modification d'un mot de passe
Modification du mot de passe par défaut de la commande `app:add-user` pour matcher les contraintes
> Fixer des contraintes de longueur et de complexité des mots de passe

- src/EventListener/MaintenanceListener.php
- templates/security/login.html.twig
- tests/Functional/EventListener/MaintenanceListenerTest.php
#2237    
Il faudrait aussi empêcher les actions lié à la gestion du compte et la fiche usager
* Rendre inaccessible les pages suivantes:
* Fiche usager signalement 
* Mot de passe perdu
* Activation
> [FO] Empêcher toutes accès lors de la phase de maintenance

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
#2134 
La pop d'alerte de message est vide si timeout axios
* Ajout d'un message si vide
> [Nouveau formulaire] Ajout message d'erreur si timeout axios

- assets/styles/histologe.scss
- templates/back/signalement/view/tags.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur.json
- tools/wiremock/src/Resources/Signalement/questions_profile_bailleur_occupant.json
- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_particulier.json
- tools/wiremock/src/Resources/Signalement/questions_profile_tiers_pro.json
#2241    
Les désordres et les photos ne sont pas cliquables qui est contraignant pour la qualification des désordres
* Suppression du z-index 
```m̀ake npm-build```
> [BO - Signalement] Accès Désordres Impossible

- .docker/php-worker/supervisord.conf
- Procfile
- config/packages/messenger.yaml
- config/packages/sentry.yaml
- src/DataFixtures/Files/NewSignalement.yml
- src/DataFixtures/Files/SignalementDraft.yml
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/EventSubscriber/SignalementDraftCompletedSubscriber.php
- src/Messenger/Message/SignalementDraftFileMessage.php
- src/Messenger/MessageHandler/SignalementDraftFileMessageHandler.php
- src/Service/Signalement/SignalementBuilder.php
- tests/Functional/Controller/BackStatistiquesControllerTest.php
- tests/Functional/Messenger/MessageHandler/PdfExportMessageHandlerTest.php
- tests/Functional/Messenger/MessageHandler/SignalementDraftFileMessageHandlerTest.php
- tests/Functional/Service/Signalement/SignalementBuilderTest.php
#2240   
Review app : https://histologe-staging-pr2245.osc-fr1.scalingo.io
Les temps de traitements peuvent être assez longs lors de la soumission d'un draft
* Déplacement de la logique vers un message handler
* Mise en place d'une queue dédiée et prioritaire pour le traitement des images et pdf 
* Mise à jour du container phpworker pour la prise en charge de la nouvelle queue
* Mise à jour du worker scalingo
Mettez à jour le container phpworker
```
docker compose build histologe_phpworker
```
```
make worker-stop
```
> [FO - Nouveaux formulaire] Soumission du formulaire sans le traitement des fichiers (asynchrone)

- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/information.html.twig
#2254   
Dans le BO, la valeur de isAllocataire ne s'enregistre pas correctement (et du coup, n'affiche pas la valeur du numéro d'allocataire)
> [BO - Signalement] Correction de l'enregistrement de la valeur isAllocataire

- tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json
#2167 
Affichage d'alerte si le bailleur n'a pas été prévenu par le locataire dans le formulaire de signalement
> [FO - Signalement] Affichage d'alerte si le bailleur n'a pas été prévenu par le locataire

- assets/vue/components/signalement-form/requests.ts
#2255   
Le timeout de 30 sec est assez limité pour de l'upload multiple car la même instance axios est utilisé pour les différents upload
* Ajout d'une méthode dédiée pour gérer l'uplad de fichier avec une création d'une nouvelle instance avec un timeout de 120s
```
make npm-build
```
> [BO - Nouveau formulaire] Timeout upload multiple avec de nombreux fichiers

- src/Entity/Enum/ProfileDeclarant.php
#2243    
La notion de Bailleur occupant n'existe pas, on affiche plutôt Propriétaire occupant.
J'ai tenté de voir les endroits où c'était utilisé :
- la fiche signalement BO
- l'envoi à Oilhi
> [BO - Signalement] Remplacement du terme Bailleur occupant par Propriétaire occupant

- assets/vue/components/signalement-form/requests.ts
#2261 
Suite au rallongement de la durée du timeout sur l'upload, il y'a quelques evenements qui dépasse les 120s. 
Un timeout sur un upload n'est pas adapté du aux différentes vitesse de connexion des uns et des autres. 
La suite dans [le thread suivant](https://mattermost.incubateur.net/betagouv/pl/6xqqozugqjbf8fzzffu8po1mxe)
* Suppression du timeout 
`make npm build`
> [BO - Nouveau formulaire] Suppression du timeout à l'upload

- src/Messenger/MessageHandler/PdfExportMessageHandler.php
- templates/pdf/partial_desordre.html.twig
- templates/pdf/signalement.html.twig
#2141
#1554
Les nouveaux désordres n'étaient pas mis en place dans l'export PDF.
Ajout aussi de la date de création du signalement et du complément d'adresse.
Si déjà lancé :
`make worker-stop`
> [BO - Export PDF] Prise en compte des nouveaux désordres

- src/DataFixtures/Files/Affectation.yml
- src/DataFixtures/Files/Signalement.yml
- src/Repository/AffectationRepository.php
- tests/Functional/Controller/BackStatistiquesControllerTest.php
#2269    
Les signalements archivés ne devraient pas être synchronisé
* Ajout d'un filtre pour ignorer les signalement archivé dans la requête
* Ajout d'un signalement archivé affecté à un partenaire SCHS qui sync dans les fixtures
* Mise à jour des tests (statistiques sur signalements archivés)
```
```
```
make console app="sync-esabora-sish"
```
```
make console app="sync-esabora-schs"
```
```
make console app="sync-esabora-sish-intervention"
```
> [BO - Esabora] Synchronisation - Ignorer les dossiers archivés

- src/Command/PushEsaboraDossierCommand.php
- src/Controller/Back/AffectationController.php
- src/DataFixtures/Files/Affectation.yml
- src/Manager/AffectationManager.php
- src/Messenger/MessageHandler/Esabora/DossierMessageSCHSHandler.php
- src/Messenger/MessageHandler/Esabora/DossierMessageSISHHandler.php
- src/Messenger/MessageHandler/Oilhi/DossierMessageHandler.php
- src/Service/Esabora/Handler/AbstractDossierSISHHandler.php
- src/Service/Esabora/Handler/DossierSISHHandlerInterface.php
- src/Service/Signalement/AutoAssigner.php
- tests/Unit/Messenger/MessageHandler/Esabora/DossierMessageHandlerTest.php
- tests/Unit/Messenger/MessageHandler/Oilhi/DossierMessageHandlerTest.php
#2277    
L'envoi de dossier se fait de manière asynchrone, il est donc pas pertinent de le tagger synchronisé au moment du dispatching il faut plutôt le faire quand tout s'est bien passé afin d'éviter des messages  comme 
`Le dossier n'a pas été trouvé` lors de la synchronisation
Ainsi on pourra trouver des dossiers affectés mais non synchronisé  à envoyer  d'un territoire en exécutant la commande
```
php bin/console app:push-esabora-dossier schs --zip=69
``` 
* Déplacement de la logique dans une méthode
* Appel de la méthode de synchronisation dans chaque handler 
```
```
et Partenaire 13-05 ESABORA SCHS
Vérifier que vos affectations sont bien tagué comme synchronisé
```
SELECT * FROM `affectation` WHERE is_synchronized = 1;
```
Que les événements …
> [BO - Esabora] Taguer les dossiers comme synchronisés uniquement en cas de succès

- templates/back/signalement/view/suivis.html.twig
#2256   
Dans le cas où le mail de déclarant et de l'occupant était le même, on affichait Déclarant.
Correction pour afficher Occupant à la place.
`Avec la base de prod sur le signalement du ticket`
> [BO - Signalement] Correction de l'affichage Occupant dans les suivis si le mail Occupant et Déclarant est le même

- src/Entity/Signalement.php
- src/EventSubscriber/SignalementClosedSubscriber.php
- src/EventSubscriber/SignalementDraftCompletedSubscriber.php
- src/Service/Signalement/VisiteNotifier.php
#2282
Lorsque l'email usager et déclarant d'un signalement est le même, une seule notification est envoyé à l'usager
- Modification de la fonction `getMailUsagers` du Signalement
- Optimisation de quelques process d’envois d'email
> [BUG Notification] envoyer email de suivi unique quand email occupant et déclarant sont identique

- src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
#2274    
Après la réception de la dernière version 1.5, tronquer certaines données  (numéro appartement et prénom) qui pourraient empêcher l'envoi du dossier
https://github.com/MTES-MCT/histologe/wiki/Esabora/_compare/afa5f60bcba3629c4a80e619ace3377a591bac6b...e4a176d0b6f6d5aab12f1113fbf5916e4cb4e249#diff-ea2859ede85fe148055587646d12c111ea20095845b1616ebb34a6e45fb6cbe6R35
Pour le reste c'est pas utile (soit des champs standardisé ou on est aligné au niveau des contraintes)
* Récupérer les 6 premiers caractères du numéro d'appartement
* Les 25 premiers caractères d'un prénom
```
```
**EDIT**
> [BO - Esabora] Revue des contraintes SCHS

- src/Factory/Interconnection/Esabora/AbstractDossierMessageFactory.php
- src/Factory/Interconnection/Esabora/DossierMessageSCHSFactory.php
- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
#2283   
Les désordres des signalements du nouveau formulaire n'étaient pas envoyés, depuis le changement de structure.
> [Esabora] Envoi des nouveaux désordres lors du push vers Esabora

- .env
#2295    
Réduire le nombre de transaction sur le projet histologe-front (au build), pour le projet back c'est via la variable d'environnement
* Mise à jour du fichier env utilisé lors de la phase de build ( npm run-build)
Editer votre fichier .env.local
> [OPS] Réduire le nombre transactions envoyés à Sentry sur le projet histologe-front

- src/Factory/Interconnection/Esabora/AbstractDossierMessageFactory.php
#2299   
Suppression du HTML car non interprété coté esabora
* Suppression du html dans les désordres
Voir https://github.com/MTES-MCT/histologe/pull/2287
> [BO - Esabora] Suppression html sur les désordres

- src/Dto/Request/Signalement/AdresseOccupantRequest.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- templates/back/signalement/view/edit-modals/edit-address.html.twig
- tools/wiremock/src/Resources/Signalement/questions_profile_tous.json
#2270
Restriction de la limitation du champ "Numéro d'appartement" à 5 caractères au dépôt et à l'édition du signalement
> [FO- Nouveau formulaire] Réduire la contrainte du numéro d'appartement

- src/Service/Mailer/Mail/Suivi/SuiviNewCommentFrontMailer.php
#2271   
Modification du texte du bouton lorsqu'un suivi est partagé aux usagers, afin d'encourager à répondre via le formulaire.
Ancien texte : `Accéder à mon signalement`
Nouveau texte : `Accéder à mon signalement et répondre`
> [Mails] Modification du texte du bouton lorsqu'un suivi est partagé aux usagers

- migrations/Version20240305090700.php
- src/Command/Cron/AskFeedbackUsagerCommand.php
- src/Controller/Back/SignalementActionController.php
- src/Controller/FrontSignalementController.php
- src/Entity/Signalement.php
- src/Entity/Suivi.php
- src/EventListener/ActivityListener.php
- src/EventSubscriber/SignalementClosedSubscriber.php
- src/Service/Signalement/SignalementBuilder.php
#1324
- Le code suivi d'un signalement ne doit plus changer
- En cas d'accès a une URL incorrecte de suivi d'un signalement, redirection vers la homepage et modification du message d'erreur
- A la validation/refus d'un signalement la notification de suivi automatique qui faisait doublon n'est plus transmise
> [QA] Call to a member function getCodeSuivi() on null / fix duplicate email notif

- src/Command/UpdateSignalementDesordreIncurieCommand.php
- src/Manager/DesordreCritereManager.php
- src/Service/Signalement/DesordreTraitement/DesordreTraitementPieces.php
#2305    
Correction sur la prise en compte des désordres liés à l'incurie
* Correction dans le DesordreCritereManager et DesordreTraitementPieces pour prendre en compte les désordres
* Création d'une commande pour corriger l'existant
**Avant de descendre la branche**
* faire un ou des signalements en tiers déclarant en renseignant des désordres liés à l'incurie (logement  /propreté)
* vérifier que les désordres n'apparaissent pas dans le BO
> [FO - Signalement] Désordre d'incurie renseigné en tiers pas repris dans le fiche signalement

- src/Security/Voter/FileVoter.php
#2317    
Permet la visualisation des documents pour les usagers (voir thread mattermost pour le choix technique)
Régression https://github.com/MTES-MCT/histologe/releases/tag/2.0.2
* Mise à jour du voter
* Mise à jour des templates afin que la route soit la même que les agents
> [FO - Fiche signalement] Documents non accessible pour usagers

- src/Command/UpdateSignalementDesordresCommand.php
- src/Entity/Signalement.php
- src/Service/Signalement/DesordreTraitement/DesordreCompositionLogementLoader.php
#2312   
Après analyse, pour le problème des désordres liés à la composition du logement, on affectait les désordres au signalement si la réponse à certaines questions était différente de "oui". Je change ce fonctionnement pour n'avoir le désordre que si on répond "non".
* correction du DesordreCompositionLogementLoader.php pour ne pas lier les désordres si on répond "je ne sais pas", ou si c'est un signalemnt créé avec l'ancien formulaire
* création d'une commande pour corriger l'existant
**Avant de descendre la branche :** 
Faire un signalement en tiers (si possible tiers pro car il manque une question), et répondre le plus possible "je ne sais pas" (pour hauteur, pièce 9m, wc, sdb et cuisine) 
Vérifier que les désordres liés apparaissent dans la liste
Editer un signalement fait avec …
> [BO - signalement] Erreur sur l'attribution de désordres liés à la composition du logement

- migrations/Version20240304151459.php
- src/Controller/Back/SignalementFileController.php
- src/DataFixtures/Loader/LoadInterventionData.php
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Entity/Enum/DocumentType.php
- src/EventSubscriber/InterventionConfirmedSubscriber.php
- src/EventSubscriber/InterventionEditedSubscriber.php
- src/Factory/FileFactory.php
- src/Manager/InterventionManager.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementDocumentTypeMapper.php
- templates/back/signalement/view/photos-album.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- tests/Functional/Manager/FileManagerTest.php
- tests/Functional/Manager/InterventionManagerTest.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Unit/Factory/FileFactoryTest.php
#1983 
#2307
Lorsqu'un rapport de visite est saisi ou édité, le fichier de rapport de visite n'apparaissait pas dans les suivis générés automatiquement.
Le rapport de visite n'était pas non plus accessible via la liste des documents de la procédure.
* Ajout d'un lien vers le rapport dans les suivis générés lors de la confirmation ou l'édition d'une visite
* Ajout du rapport de visite dans la partie document des signalements
* Migration pour modifier les types possibles de photos et documents, pour que ce soit plus parlant
> [BO - Signalement] Mise à disponibilité des rapports de visite

- src/Factory/Interconnection/Oilhi/DossierMessageFactory.php
- src/Service/Oilhi/HookZapierService.php
#2323    
Les champs non mappés bloquent l'enregistrement sur Airtable
* Suppression des champs `partnerId` et `signalementId`
* Suppression du html des précisions
* Mise à jour du keepass
* Récupérer les identifiants Zapier 
* Activer Oilhi et récupérer autres variables d'environnements
```
FEATURE_OILHI_ENABLE=1 
ZAPIER_OILHI_TOKEN=
ZAPIER_OILHI_USER_ID=
ZAPIER_OILHI_CREATE_AIRTABLE_RECORD_ZAP_ID=
```
* make worker-start
> [Oilhi] Supprimer champs problématiques à l'enregistrement Airtable

- .env
- .env.sample
- .github/workflows/main.yml
- README.md
- config/packages/doctrine.yaml
- docker-compose.yml
- scripts/sync-db.sh
#2102   
Scalingo nous propose de passer rapidement à MySQL 8, puisqu'ils vont arrêter la maintenance de MySQL 5.7 et migreront à partir du 1er juillet.
Par ailleurs, on pourra en profiter pour utiliser des fonctionnalités plus avancées à présent.
Afin de passer en MySQL 8, il y avait 2 vérifications à faire sur les tables (cf ici : https://doc.scalingo.com/databases/mysql/mysql-8-prerequisites) :
- Toutes les tables utilisent le moteur InnoDB
- Toutes les tables ont des clés primaires
C'est bien le cas.
J'ai fait pas mal de tests, le passage à la version 8 semble indolore.
Lors du passage sur develop (lors du merge), il faudra 
- faire une sauvegarde de la base
- passer MySQL en version 8 via le dashboard Scalingo sur l'app de staging
- faire des tests sur staging
* Modification de la …
> [INFRA] Migration de MySQL 5.7 vers 8.0

- assets/app.ts
- assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
- assets/controllers/back_signalement_view/back_signalement_view.js
- assets/controllers/back_signalement_view/form_upload_documents.js
- assets/styles/histologe.scss
- migrations/Version20240301152552.php
- src/Controller/Back/SignalementFileController.php
- src/Entity/File.php
- src/Entity/Signalement.php
- src/Factory/FileFactory.php
- src/Manager/SuiviManager.php
- src/Service/Signalement/SignalementFileProcessor.php
- templates/_partials/_modal_upload_files.html.twig
- templates/back/base_bo.html.twig
- templates/back/signalement/view.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- tests/Functional/Manager/SuiviManagerTest.php
- tests/Unit/Factory/FileFactoryTest.php
#2200
- Création de la modale d'upload des document (https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/0c3f48bb-09e0-49bd-9251-1d45685f6cf8/) qui s'active via le feature flipping `FEATURE_DOCUMENTS_ENABLE`
- Création de la modale d'upload de photos (https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/2d6299ec-c7ff-4f4b-ae2e-b311cd6932d0/) qui s'active via le feature flipping `FEATURE_DOCUMENTS_ENABLE`
> [BO - signalement] Créer la modale d'upload de photos/documents

- src/Repository/AffectationRepository.php
- tests/Functional/Repository/AffectationRepositoryTest.php
#2331    
Régression  v2.0.2
[PR2272](https://github.com/MTES-MCT/histologe/pull/2272/files#diff-8e559732bcddf447751ccb9dbbd2f43782d7cb489e236dfea1452d76a2e2f7d7)
Possibilité d'avoir une même jointure en double qui provoque une erreur sur la requête d'exécution
* Suppression de la jointure en double
* Ajout d'un test 
`make mock`
> [Esabora] Commande - Correction requête sur un envoi de dossier unique

- src/Specification/Signalement/SuroccupationSpecification.php
- tests/Functional/Specification/Signalement/SuroccupationSpecificationTest.php
#2290   
Sur les signalements où le nombre de pièces n'est pas précisé, le calcul de suroccupation si on n'est pas allocataire peut planter
> [QA] Correction calcul suroccupation si le nombre de pièces n'est pas précisé

- src/Service/SearchFilterService.php
#2292   
Si on souhaitait exporter une liste de signalements avec le filtre de visite activé, on avait un doublon d'identifiant `i` de jointure sur `interventions`.
> [QA] Correction export csv avec filtre visite activé

- src/Command/Cron/AbstractCronCommand.php
- src/EventListener/MaintenanceListener.php
- tests/Functional/EventListener/MaintenanceListenerTest.php
#2350   
Les crons ainsi que la page de contact doivent être bloqué pour éviter toute interaction avec la base de données, notamment le cron SCHS à 18H UTC
* Ajout condition dans `AbstractCronCommand`
* Inclure la page de contact dans les pages inaccessibles
* `make console app="remind-inactive-user"`
* `make console app="sync-esabora-sish"`
* `make console app="sync-esabora-schs"`
> [BO - Maintenance] Bloquer les crons et la page de contact

- src/Manager/SignalementManager.php
- src/Repository/PartnerRepository.php
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Repository/PartnerRepositoryTest.php
#2345
- Dans la modale partenaires à affecter : affichage des partenaires par ordre alphabétique
- Suppression du paramètre addCompetences inutilisé
> [BO - Signalement] Liste Partenaire Affectation

- src/Controller/FrontSignalementController.php
- src/Manager/UserManager.php
- templates/back/signalement/view/suivis.html.twig
- templates/back/table_result.html.twig
- templates/front/suivi_signalement.html.twig
- tests/Functional/Manager/UserManagerTest.php
#2248
Sur la fiche signalement usager lors de la soumission d'un message/document : contrôle de l'email passé en parametre afin de ne pas permettre l'enregistrement du suivi/file avec l'id d'un utilisateur n'étant pas sur le signalement
> [BUG] route : front_suivi_signalement_user_response

- src/Service/Signalement/ZipcodeProvider.php
#2353 
Ajout des code DOM/TOM dans le ZipcodeProvider
> [Bug] ouverture Guyane

- src/DataFixtures/Files/Affectation.yml
- src/Service/Mailer/Mail/Signalement/AssignementNewMailer.php
- src/Service/Mailer/Mail/Signalement/SignalementClosedToAllPartnersMailer.php
- src/Service/Mailer/Mail/Signalement/SignalementClosedToOnePartnerMailer.php
- src/Service/Mailer/Mail/Signalement/SignalementNewMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviNewCommentBackMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteAbortedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteConfirmedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteCreatedToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteFutureReminderToPartnerMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisiteNeededMailer.php
- src/Service/Mailer/Mail/Suivi/SuiviVisitePastReminderToPartnerMailer.php
- tests/Functional/Command/NotifyVisitsCommandTest.php
#2360
- Modification du lien dans le mail "Date de visite à renseigner" qui pointe maintenant vers la fiche du signalement en BO au lieu de FO
- Modification des mail utilisant des sujets dynamique pour que le sujet change bien lors d'envoi multiple d'email de même type sur des signalements différents
- Ajout d'une fixture et d'un test permettant de vérifier le second point
> [Bug] Sujets des notifications

- src/Command/Cron/SynchronizeInterventionSISHCommand.php
- src/Service/Esabora/Handler/InterventionVisiteServiceHandler.php
- templates/emails/cron_email.html.twig
#2374
- Gestion des erreur PHP et exception dans la `SynchronizeInterventionSISHCommand.php`
- Gestion spécifique du cas des visites sans dates retournés par Esabora (lève une exception)
> [Bug] cron Esabora

- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Serializer/SignalementDraftRequestNormalizer.php
- src/Service/Signalement/SignalementBuilder.php
#2251   
Certaines personnes saisissent un nombre float pour le nombre de personnes (Ex : 3.5). On l'arrondit à l'entier supérieur.
Le ticket signale une autre conversion, mais elle a été corrigée par ailleurs.
**EDIT**
> [QA] Conversion en nombre entier pour le nombre de personnes

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormModalContinueFromDraft.vue
#2371 
#2372 
Ajustements sur l'UI de la modale, et réactivation des boutons du footer quand on clique hors de la modale
* LModification de 2 composants du formulaire
>  [FO - Reprise de brouillon] UI modale et comportement clic hors modale

- templates/back/table_result.html.twig
#2373   
Remettre "Aucun" dans la colonne dernier suivi quand pas de suivi
* Changement du twig
> [BO - Liste signalements] Remettre "Aucun" dans la colonne dernier suivi quand pas de suivi

- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementBuilder.php
#2394   
Ne pas chercher à récupérer de bailleur si l'usager à  cocher non ou je ne sais pas
* Méthode privée afin de savoir si le logement est social
* Prise en compte des valeurs `ne-sais-pas` et `nsp` dans les méthode `evalBoolean`
*En tant que Service de secours*
*En tant que Locataire*
* Appliquer les mêmes tests
> [FO] Ne pas récupérer de bailleur social si l'usager a coché non ou je ne sais pas sur logement social

- assets/app.ts
- assets/controllers/back_signalement_view/form_cloture_modal.js
- templates/_partials/_modal_cloture.html.twig
#2392    
Modifier le message dans la modale de cloture suivant qu'on choisisse de partager à l'usager ou non
* Ajout d'un fichier js
* Modification du twig
> [BO - Clôture du signalement] Modifier les messages warning 

- src/Dto/Request/Signalement/SituationFoyerRequest.php
- src/Entity/Model/SituationFoyer.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-situation-foyer.html.twig
- templates/back/signalement/view/information.html.twig
#2403    
Après investigation on utilise pas la bonne valeur dans le BO
`travailleur_social_accompagnement_declarant` est la case à cocher du screenshoot, la question est posé uniquement aux tiers pro
Il faudrait donc utiliser `travailleur_social_accompagnement` dans le BO 
Les pro du BO remplissait cette valeur en pensant répondre à `Accompagnement par un ou une travailleuse sociale`
Comme la valeur `travailleur_social_accompagnement_declarant` n'a jamais été affiché de manière intentionnelle, on peut laisser comme ça et poser la question à Mathilde avant d'envisager une action (la seule que je vois c'est de remettre ce toute les valeur à null en base) 
* Ajout du champ `$travailleurSocialAccompagnement` dans `SituationRequest`
* Affichage `$travailleurSocialAccompagnement` au  lieu de …
> [Front / BO] Champ accompagnement par travailleur social : impossible de sélectionner "Non"

- assets/controllers/component_search_address.js
- templates/form/dsfr_theme.html.twig
#2383    
Afficher la sélection dans le champ adresse sur les pages accueil et contact
* Correction du js pour ne pas attacher les fonctions d'autocomplete à la div parente de l'input qui a aussi l'attribut data-fr-adresse-autocomplet
> [FO - home et contact] Afficher la sélection dans le champ adresse

- src/Controller/FrontSignalementController.php
- src/Repository/SignalementRepository.php
- templates/front/suivi_signalement.html.twig
- tests/Functional/Controller/FrontSignalementControllerTest.php
#2378
- Route `front_suivi_signalement`, `front_suivi_procedure` et `front_suivi_signalement_user_response` non accessible pour des signalements archivé
- On bloque la possibilité d'envoyer des message sur les signalement clôturé/refusé (avec message informatif)
- Refacto (regroupement de ce qui concerne le suivi de procédure sans la route correspondante)
- Ajout et adaptation des tests sur cette partie
> [Bug] Bloquer page front signalement si archivé

- src/EventSubscriber/InterventionCreatedSubscriber.php
- tests/Functional/EventSubscriber/InterventionCreatedSubscriberTest.php
#2407 
L'email de notification usager "Une visite de votre logement est prévue" est envoyé uniquement si : 
- Le type de l'intervention est VISITE
- La date est dans le futur
- Ajout de test permettant de vérifier que les mails ne sont pas envoyés quand les conditions ne sont pas réunis
> Fix email de notification usager "Une visite de votre logement est prévue"

- migrations/Version20240322123431.php
- src/Controller/Back/BackArchivedAccountController.php
- src/Controller/Back/BackArchivedPartnerController.php
- src/Controller/Back/PartnerController.php
- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/User.yml
- src/DataFixtures/Loader/LoadPartnerData.php
- src/DataFixtures/Loader/LoadUserData.php
- src/Entity/User.php
- src/Repository/PartnerRepository.php
- src/Repository/UserRepository.php
- src/Service/Sanitizer.php
- src/Twig/AppExtension.php
- templates/back/account/_form.html.twig
- templates/back/account/edit.html.twig
- templates/back/account/index.html.twig
- templates/back/nav_bo.html.twig
- templates/back/partner/index.html.twig
- templates/back/partner/view.html.twig
- templates/back/partner_archived/index.html.twig
- tests/Functional/Controller/Back/BackArchivedPartnerControllerTest.php
- tests/Functional/Controller/BackArchivedAccountControllerTest.php
- tests/Functional/Controller/CartographieControllerTest.php
- tests/Functional/Controller/PartnerControllerTest.php
- tests/Functional/Controller/SignalementListControllerTest.php
- tests/Functional/Service/Token/ActivationTokenGeneratorTest.php
#2035   
Lorsqu'on archive un user ou un partenaire, on tag le champ email pour qu'il n'y ait plus de doublon `.archived@yyyymmddhhmm`
- ajout d'une page des partenaires archivés
- à l'archivage d'un utilisateur et d'un partner on tag le mail avec `.archived@yyyymmddhhmm`
- au désarchivage, on vérifie que le mail n'est pas utilisé ailleurs, et on affiche une alerte si besoin (et on retire le tag si ok)
- à l'affichage on masque le tag
- on fait une commande pour taguer les mails de tous les utilisateurs et partenaires archivés
> [BO] Tagger les mails des comptes et partenaires archivés pour éviter les doublons

- src/Repository/SignalementRepository.php
#2417    
Tri manquant sur le filtre ville
* Ajout d'un tri ascendant
> [BO - Liste signalement] Trier les villes du filtre par ordre alphabétique

- src/Controller/Back/PartnerController.php
- src/EventListener/UserUpdatedListener.php
#2414    
Correction sur la notification lors de suppression d'utilisateur
* Notifier l'utilisateur de la suppression de son compte avant de changer l'email avec le suffixe archived
* Faire en sorte de ne pas notifier l'utilisateur du changement d'adresse e-mail si l'utilisateur est archivé
> [Back - Suppression utilisateur] Notifier avant de changer l'email 

- .env
- .env.sample
- config/services.yaml
- migrations/Version20240402090719.php
- migrations/Version20240402091719.php
- src/Controller/Back/CartographieController.php
- src/Controller/Back/SignalementListController.php
- src/Dto/Request/Signalement/SignalementSearchQuery.php
- src/Dto/SignalementAffectationListView.php
- src/Entity/Enum/SignalementStatus.php
- src/Factory/SignalementAffectationListViewFactory.php
- src/Manager/SignalementManager.php
- src/Repository/AffectationRepository.php
- src/Repository/SignalementRepository.php
- src/Service/Signalement/SearchFilter.php
- templates/back/index.html.twig
- templates/back/table_result.html.twig
#2117    
Sur la base **des données et filtres existants**, la nouvelle route doit fournir la liste au format JSON triable et filtrable selon les specs
https://github.com/MTES-MCT/histologe/wiki/liste-signalements
* Nouvelle route qui fournit la liste de signalement au format JSON
* Nouveau DTO qui permet de gérer les filtres 
* Légère  adaptation du SearchFilter prise en charge du nouveau DTO
* Filtre prise en charge dans cette PR
| Champ  | PR| Lien 
| :--- | :--- |  :--- 
| Territoire | ✅ | http://localhost:8080/bo/list/signalements/?page=1&territory=13
| Recherche | ✅ | http://localhost:8080/bo/list/signalements/?page=1&searchTerms=2022
| Statut | ✅ | http://localhost:8080/bo/list/signalements/?page=1&status=ferme
| Commune / EPCI | ✅ | …
> [BO - Liste signalement][Back] Gestion liste et filtre existants signalements sous format JSON

- migrations/Version20240405080750.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Service/Signalement/SignalementBuilder.php
- tests/Functional/Service/Signalement/SignalementBuilderTest.php
#2413
- Correction du nom de la propriété concernant la ville du proprio de `SignalementDraftRequest.php`
- Utilisation de cette propriété dans le  `SignalementBuilder.php`
- Ajout d'une migration permettant de récupérer les ville des propriétaire dans le draft (pour les signalement en provenance d'un draft ayant un code postal mais pas de ville d'enregistré pour le proprio)
- Ajout de tests sur les infos proprio
> [Back - Signalement] Il manque très souvent la ville du propriétaire

- src/Manager/SignalementDraftManager.php
#2433
- Correction du lien de suivi proposé en fin de dépôt d'un signalement pour qu'il contienne toujours l’e-mail déclarant.
> [FO - Suivi] Mail nouvelle MAJ en trop

- Makefile
- config/packages/doctrine.yaml
- migrations/Version20240402143605.php
- src/Service/Esabora/EsaboraSISHService.php
#2370
- Configuration doctrine du `charset` et `collate` par défaut pour qu'il soit en `utf8mb4` lors des migrations auto-générées des futures tables/colonnes
- Passage de la table `messenger_messages` en `utf8mb4`
- Suppression des émojis du champs détails des signalement avant envoi vers Esabora
`make execute-migration name=Version20240402143605 direction=up`
Je n'ai pas réussi a appliquer les tests suivant en local (impossible d'enregistrer une emojis dans le champs détails d'un signalement et de l'afficher correctement sur la fiche signalement, alors que ca fonctionne sur Staging)
> [QA] Interdire (ou supprimer) les emojis dans les champs textes

- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
#1190   
Je suis responsable de territoire
Mon partenaire est la DDTM 13
Sur mon tableau de bord, je clique sur la carte "Mes affectations"
J'arrive sur la liste de tous les signalements, sans filtrage
Comportement attendu : avoir le filtre partenaire actif avec le partenaire du user en cours
* Ajout d'un paramètre pour le lien avec l'id du partenaire (dans WidgetDataKpiBuilder)
> [BO - Dashboard] Manque filtrage depuis la carte "Mes affectations

- src/Controller/Back/CartographieController.php
#2454    
Filtre les villes et les partenaires dans les filtres de la cartographie pour les RT 
Lors de ce commit https://github.com/MTES-MCT/histologe/commit/af0ad350b771e6ce218e13f246b470e25b89aea5 en septembre 2022, les filtres de la cartographie avaient été volontairement non filtrés en fonction du territoire (villes et partenaires) pour les SA (normal) et pour les RT
On supprime cette exception pour les RT
* Modification du controller pour les RT
> [BO - Cartographie] Filtres "non zonés

- assets/controllers/back_signalement_view/form_upload_documents.js
#2435
Contrôle du format des photo envoyé via la modale d'upload de photos, pour restreindre uniquement au jpg, png et gif.
> [BO - Ajout photos situation] Ne pas uploader les photos aux formats non pris en charge

- src/Controller/Back/SignalementFileController.php
#2447   
Correction du suivi automatique de suppression document. (document au lieu de photo)
* Modification du controller
> [BO - Signalement] Erreur suivi auto de suppression document situation et partenaire

- assets/controllers/back_signalement_edit_file/back_signalement_edit_file.js
- assets/controllers/back_signalement_view/form_upload_documents.js
- migrations/Version20240410151123.php
- src/Entity/File.php
- templates/back/signalement/view/edit-modals/edit-file.html.twig
- templates/back/signalement/view/visites/visite-item.html.twig
#2438    
Limiter la taille du champ description pour les fichiers
* Migration + limitation dans l'entité
* Limitation dans les champs lors de l'ajout et de l'édition
> [BO - Edition de photos] Ajouter limite de caractères pour la description

- assets/controllers/view_signalement.js
- assets/styles/histologe.scss
- templates/back/signalement/view/photos-album.html.twig
#2439    
- Ajouter une marge sous la photo, avant la description
- Augmenter l'espace entre la description et l'auteur de la photo
- Ajouter l'icône fr-icon-close-line dans le bouton "Fermer"
- Modifier la couleur des boutons (accessibilité) : il faut utiliser les boutons du thème "sombre" [dans le DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/bouton) (je n'ai pas réussi à activier le passage en mode sombre en js, ni à utiliser les variables, mais en utilisant les codes rgb c'est ok, ouvert à amélioration)
* css et txig
> [BO - Affichage mode album] Améliorations UI

- templates/front/suivi_signalement.html.twig
#2436    
Suite à un ticket de Mathilde, on s'est aperçus que l'ouverture de la page de suivi juste après le déôt du signalement pouvait ne pas montrer les photos ajoutées dans le signalement (traitement asynchrone du worker).
Pour ne pas laisser penser à un bug on change le texte.
* changement du twig
> [FO - page de suivi] Changement du texte si on n'a pas de photo

- src/Entity/Enum/DocumentType.php
- src/Entity/File.php
- src/Manager/SuiviManager.php
- templates/_partials/_modal_upload_files.html.twig
- templates/back/signalement/view/photos-documents.html.twig
- templates/back/signalement/view/visites/modals/visites-modal-upload-files.html.twig
#2440    
- Ajouter une marge avant le message warning
- Ajouter le texte Pour ajouter des documents concernant la procédure ou le bailleur, rendez-vous dans la partie "Documents partenaires". (cf. [specs](https://github.com/MTES-MCT/histologe/wiki/Ajout-documents#ajouter-des-documents-sur-la-situation-usager))
- Modifier le message warning pour Ces documents seront partagés à l'usager.
- Modifier l'ordre des éléments dans la liste déroulante des types de documents pour que "Photo de désordre" soit en avant dernier et "Autre" en dernier"
- 
* Changement des twig et des document types
> [BO - Modale ajout documents] Amélioration de la modale (UX et contenu)

- migrations/Version20240411120500.php
- src/Entity/File.php
- src/Entity/Signalement.php
- src/Messenger/MessageHandler/SignalementDraftFileMessageHandler.php
- tests/Functional/Messenger/MessageHandler/SignalementDraftFileMessageHandlerTest.php
#2437    
Suite aux modifications de File.setDesordreSlug() dans ce commit (https://github.com/MTES-MCT/histologe/commit/757f67028975867568c13180c0a0bc7e6a090efa#diff-efb705be4240485a34a0a7cca55154c6f3c2e2c8e0f7706b504b260ec3f5d9f6), les photos des signalements n'étaient plus rattachées à leur désordre depuis le 4 avril
* Correction de File.setDesordreSlug()  pour chercher aussi dans les slugs de catégorie (et création de Signalement.getDesordreCategorieSlugs())
* Passage du signalement à FileFactory->createFromFileArray() dans SignalementDraftFileMessageHandler.php
* Ajout d'assertions dans SignalementDraftFileMessageHandlerTest.php
* Création d'une migration pour corriger l'existant
> [BO - Signalement] Photos non rattachées aux désordres

- config/packages/twig.yaml
#1194   
Le lien de démo a changé depuis au moins un an. Il fallait le mettre à jour...
> [E-mail inscription] Mise à jour du lien de démo

- templates/back/signalement/view/suivis.html.twig
#2478
Retrait du nom prénom sur les suivi BO qui faisait doublon en cas de dépot par un partenaire
> fix doublon nom suivi

- src/DataFixtures/Files/Partner.yml
- src/DataFixtures/Files/Signalement.yml
- src/DataFixtures/Files/Territory.yml
- src/DataFixtures/Files/User.yml
- tests/Functional/Controller/BackStatistiquesControllerTest.php
- tests/Unit/Service/AutoAssignerTest.php
#2125   
Les territoires actifs n'étaient plus mis à jour.
* Mise à jour des données de territoires des fixtures
* Ajout de données partenaires et signalement
* Ajustement tests automatisés
> [QA] Mise à jour des fixtures de territoire en fonction de la prod

- src/Controller/Back/SignalementEditController.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-composition-logement.html.twig
- templates/back/signalement/view/information.html.twig
#2484   
Suite aux retours du 13, 06 et 62, il faudrait modifier l'intitulé du bloc "Composition du logement" dans le BO pour Description du logement
* Changement dans le twig et dans SignalementManager
>  [BO - Fiche signalement] Changer l'intitulé du bloc composition du logement #2484 

- src/Service/Import/Signalement/SignalementImportLoader.php
#2481
Certains partenaire du Pas de calais (62) contenant des virgule "," : ajout d'une condition pour éviter d'utiliser les virgule comme séparateur de partenaire sur ce territoire.
> [BO - Signalement] Reprise de données Pas de Calais

- assets/controllers/view_signalement.js
#2439    
En local, le switch au thme dark quand on ouvre l'album-photo fonctionne très bien. Mais sur la staging, le switch ne fonctionne pas à la première ouverture de l'album photo, il fonctionne par contre à la deuxième ouverture : la première fois que j'ouvre l'album photo, le theme ne change pas (il est `null` d'après la console), puis je ferme l'album photo il devient `light`. Je reouvre une 2è fois l'album photo il devient bien `dark`. 
J'ai donc tenté une première correction à l'aveugle.
Si ça ne fonctionne pas, il faudra peut-être passer par des callbacks...
> [BO - Affichage mode album] Theme Dark sur Album photo

- src/Command/PushEsaboraDossierCommand.php
- tests/Unit/Command/PushEsaboraDossierCommandTest.php
#2426    
Dans la commande `app:push-esabora-dossier` qui permet de pousser un dossier sans passer par la fiche signalement
Lorsque qu'on pousse un dossier unique via l'uuid du signalement et que la synchronisation a un statut à 0 cad colonne `is_synchronized` de la table `Affectation`,  le dossier ne peut être pas poussé.
```sh
php bin/console app:push-esabora-dossier schs --uuid=e81e633a-a5ca-469d-a6f6-a3c460314efd
```
Pour plus de souplesse, on devait pouvoir pousser ou repousser un dossier en ligne de commande peu importe son statut de synchronisation (la gestion des doublons est géré coté esabora)
* Passer le paramètre status à null afin de lever le filtre sur le statut
```sh
```
> [Esabora] Pouvoir pousser en ligne de commande un dossier peu importe l'état de synchronisation

- migrations/Version20240424073643.php
- templates/base.html.twig
#2500    
Les courriers DPE qui sont déclarés comme des assets devraient être accessible publiquement
* Supprimer le placeholder token sur les liens de courriers
* Ajout d'une migration pour supprimer le placeholder `__TOKEN__` sur les courriers
*  Ajouter un suivi avec tous les courriers sur un signalement qui a la situation NDE, les liens devraient renvoyées une 404
> [BO - Suivi] Les courriers ajoutés dans le message de suivi ne sont plus accessible

- src/Manager/SuiviManager.php
- templates/_partials/_modal_upload_files.html.twig
#2504   
Suite à des retours, on a modifié l'intitulé de la partie Documents partenaires en Documents liés à la procédure.
Il faut le répercuter dans le message d'info de la modale -> mettre Documents liés à la procédure
* Modifier le titre de la modale et le suivi
> [BO - Fiche usager - modale ajout documents] Modifier le texte

- src/Form/PartnerType.php
- templates/back/partner/_form.html.twig
#2126   
Restreindre l'édition des données d'authentification aux super admin  en laissant aux RT la possibilité de désactiver l'interfaçage
* Passage de disable au form_widget() dans le twig
> [BO - Partenaire][Esabora] Restreindre l'édition des données d'authentification aux super admin

- migrations/Version20240424122241.php
- src/Controller/Back/SignalementFileController.php
- src/EventSubscriber/SignalementCreatedSubscriber.php
- src/Manager/FileManager.php
- src/Manager/UserManager.php
- src/Messenger/MessageHandler/SignalementDraftFileMessageHandler.php
#2450 : [FO / BO - Signalement] Auteur document & photo non identifié quand ajout depuis formulaire
#2447 : [BO - Signalement] Erreur suivi auto de suppression document situation et partenaire
Correction du suivi de suppression de documents
Ajout de l'utilisateur sur les fichiers ajoutés depuis le formulaire (mais honnêtement j'étais persuadée que ça fonctionnait )
* Correction du SignalementFileController.php
* Dans le SignalementDraftFileMessageHandler, on enregistre l'utilisateur à l'origine de la création du signalement sur les fichiers, mais je pensais que c'était fait avec l'appel à `$this->fileManager->updateSignalementFilesUser` dans le SignalementCreatedSubscriber donc je suis un peu dubitative
> [FO / BO - Signalement] Auteur document & photo non identifié quand ajout depuis formulaire 

- assets/app.ts
- assets/vue/components/signalement-list/TheHistoAppSignalementList.vue
- assets/vue/components/signalement-list/TheHistoSignalementListCard.vue
- assets/vue/components/signalement-list/TheHistoSignalementListFilter.vue
- assets/vue/components/signalement-list/TheHistoSignalementListHeader.vue
- assets/vue/components/signalement-list/TheHistoSignalementListPagination.vue
- assets/vue/components/signalement-list/requests.ts
- assets/vue/components/signalement-list/store.ts
- assets/vue/signalement-list.ts
- src/Controller/Back/SignalementListController.php
- templates/back/signalement/list/index.html.twig
- templates/base.html.twig
#2123   
Maquette
* [Maquette super admin](https://xd.adobe.com/view/8ebe18a2-c737-48b6-af34-e79b9f189d9d-dbed/)
* [Maquette agent](https://xd.adobe.com/view/9511c189-dcc2-4668-8d33-1b6e6bf3e250-c042/)
Mise en place du socle vuejs de la nouvelle page, le découpage a été fait de la sorte 
* Création des différents composants
* Intégration de la carte signalement
* Activer la variable d'environnement
```
FEATURE_LIST_FILTER_ENABLE=1
```
* Exécuter la commande
```
make npm-build
```
> [BO - Liste signalement] [Front] Structure en VueJS

- templates/back/index.html.twig
#2519    
Propriété accessible via l'objet pagination
* Correction accès propriété twig
> [QA] Régression pagination signalement

- assets/vue/components/common/HistoFranceMap.vue
- assets/vue/components/common/external/chartjs/HistoChartBar.vue
- assets/vue/components/common/external/chartjs/HistoChartDoughnut.vue
- assets/vue/components/common/external/chartjs/HistoChartLine.vue
- assets/vue/components/common/external/chartjs/HistoChartPie.vue
- assets/vue/components/front-stats/TheHistoAppFrontStats.vue
- assets/vue/components/front-stats/TheHistoFrontStatsGlobal.vue
- assets/vue/components/front-stats/TheHistoFrontStatsTerritory.vue
- assets/vue/components/front-stats/TheHistoFrontStatsTerritoryItem.vue
- assets/vue/components/front-stats/TheHistoFrontStatsYearToggle.vue
- assets/vue/components/front-stats/store.ts
- src/Controller/FrontStatistiquesController.php
- src/Repository/SignalementRepository.php
- src/Service/Statistics/BatimentDesordresStatisticProvider.php
- src/Service/Statistics/DesordresCategoriesStatisticProvider.php
- src/Service/Statistics/GlobalAnalyticsProvider.php
- src/Service/Statistics/LogementDesordresStatisticProvider.php
- src/Service/Statistics/MotifClotureStatisticProvider.php
- tests/Functional/Controller/FrontStatistiquesControllerTest.php
- tests/Functional/Repository/SignalementRepositoryTest.php
- tests/Functional/Service/Statistics/BatimentDesordresStatisticProviderTest.php
- tests/Functional/Service/Statistics/DesordresCategoriesStatisticProviderTest.php
- tests/Functional/Service/Statistics/GlobalAnalyticsProviderTest.php
- tests/Functional/Service/Statistics/LogementDesordresStatisticProviderTest.php
- tests/Functional/Service/Statistics/MotifClotureStatisticProviderTest.php
#1550    
Mise à jour des statistiques publiques http://localhost:8080/statistiques
Le [prototype de la nouvelle page](https://xd.adobe.com/view/8959c3fa-ca2e-4042-9983-5db664d3009e-dc0a/screen/c61af72f-bd7c-4361-a079-db7b1cba595e/) dispo sur Adobe Xd.
* Mise à jour des composants Vue
* Création de nouveaux providers
> [Front] Mettre à jour les stats publiques

- assets/controllers/back_signalement_view/form_upload_documents.js
- migrations/Version20240430120311.php
- src/Controller/Back/SignalementFileController.php
- src/Entity/Enum/DocumentType.php
#2553
- Ajout du type de document "AUTRE_PROCEDURE"
- Ajout de ce type par défaut lors de l'ajout d'un document via la partie procédure
- Ajout de ce type dans la liste ds choix disponible pour les document procédure
- Migration injectant le type AUTRE_PROCEDURE sur tous les document de type AUTRE ajoutés par un agent.
> Ajouter un DocumentType "AUTRE_PROCEDURE"

- migrations/Version20240503102522.php
#2526
Migration du `documentType` des fichiers : 
- de `fileType` = "document" et `documentType` = "AUTRE" ou "AUTRE_PROCEDURE"
- Concernant des signalement actif
Suivant cet algo : 
Certains document pouvant répondre à plusieurs critères la priorité va sur le type "AUTRE_PROCEDURE"
`make execute-migration name=Version20240503102522 direction=up`
Ex la requete suivante ne devrait pas retourner de résultat : 
```
SELECT * FROM `file` f INNER JOIN signalement s ON s.id = f.signalement_id 
WHERE (s.statut = 1 OR s.statut = 2) 
and f.title like '%courrier%' 
and f.file_type = 'document' 
and (f.document_type = 'AUTRE');
```
> [BO - Document] Mise à jour des types de documents

- src/Manager/UserManager.php
- src/Repository/UserRepository.php
- src/Security/BackOfficeAuthenticator.php
- tests/Functional/Command/Cron/RemindInactiveUserCommandTest.php
- tests/Functional/Repository/UserRepositoryTest.php
#2032
- Les utilisateur USAGER restent au `STATUS_INACTIVE` à la création
- La commande `app:remind-inactive-user` exclus les utilisateur de `ROLE_USAGER`
- Le système de login, permet le login des user au `STATUS_ACTIVE` uniquement
> [Sécurité - Login] Ne pas activer par défaut les user avec ROLE_USAGER

- assets/vue/components/common/HistoFranceMap.vue
#2533    
Sur la carte
Ajouter un espace avant la ligne du rectangle gris -territoire non déployé
Ajouter un espace à la fin de la légende (pour que le texte ne soit pas collé au bord)
* Ajout d'une classe css de margin
> [FO - Stats] Ajouter une marge sous la légende

- src/Controller/BailleurController.php
- tests/Functional/Controller/BailleurControllerTest.php
#2534   
La récupération des bailleurs (auto-complete) en front ne fonctionne pas comme prévu avec plusieurs termes. 
*Exemple:* 
Bien qu'en base de donnée le bailleur se nomme **13 Habitat**, la recherche sur `habitat 13` ou `13 habitat` doit retourner le même résultat
* Ajout d'une condition pour traitement uniquement sur le bailleur avec la mention radié et non sur tous les bailleur
* Dans la fonction de filtrage, travailler uniquement avec le premier terme
Pour ne pas se limiter au bailleur des fixtures
```
make console app="import-bailleur"
```
> [FO - Bailleur] Problème sur la recherche multi-terme quand l'option de nettoyage ([RADIE]) est activé

- src/Service/Import/Signalement/SignalementImportLoader.php
#2539
- Fix de la commande `app:import-signalement` en cas d’affectation sur un partenaire sans utilisateurs (voir erreur https://sentry.incubateur.net/organizations/betagouv/issues/99549/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream)
> [QA] App\Manager\AffectationManager::createAffectationFrom(): Argument #3 ($user) must be of type ?App\Entity\User

- src/Controller/Back/ExportSignalementController.php
#2253    
Le problème n'a pas été résolu, réouverture du ticket
* Suppression de l'appel de la méthode send(), retourner uniquement la réponse résoud le problème
ouvrir les logs
```
tail -f var/log/dev.log
```
```
tail -f var/log/dev.log | grep "CRITI"
```
```
[2024-05-10T10:30:51.846792+00:00] request.CRITICAL: Uncaught PHP Exception ErrorException: "Warning: Cannot modify header information - headers already sent by (output started at /app/src/Service/Signalement/Export/SignalementExportLoader.php:19)" at SessionUtils.php line 52 {"exception":"[object] (ErrorException(code: 0): Warning: Cannot modify header information - headers already sent by (output started at /app/src/Service/Signalement/Export/SignalementExportLoader.php:19) at …
```
> [QA] Warning: Cannot modify header information - headers already sent by

- composer.json
- composer.lock
- config/packages/html_sanitizer.yaml
- src/Controller/SignalementController.php
- src/Entity/Suivi.php
- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
- templates/back/notifications/index.html.twig
- templates/back/signalement/view/suivis.html.twig
- templates/back/signalement/view/visites/visite-item.html.twig
- templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
- templates/pdf/signalement.html.twig
#2499
Correction de l'affichage des suivis qui pouvant contenir de L’HTML peuvent casser l'affichage
* Ajout du composant Symfony [HTML Sanitizer](https://symfony.com/doc/current/html_sanitizer.html)
* Configuration du composant afin qu'il autorise uniquement les balise et attribut HTML attendu lors de l'affichage des suivi / rapport de visite
* Ne plus convertir les saut de ligne en en entité mais en html simple lors du dépot suivi usager (+ conversion avant affichage des ancien `br` enregistré en entité html pour un affichage correct)
`make composer`
- Une fois validé, penser à intégrer dans la PR #2514 pour la nouvelle version de la page de suivi
> [BUG BO] affichage des suivis

- assets/styles/histologe.scss
- src/Controller/Back/SignalementActionController.php
- templates/back/signalement/view.html.twig
- tests/Functional/Controller/Back/SignalementActionControllerTest.php
#2531
- Suppression d'une partie du code qui semble inutilisé et qui contenait la faille de sécurité
> [QA - Sécurité] Alerte github historique

- assets/styles/histologe.scss
- src/Controller/SignalementController.php
- templates/_partials/_modal_send_lien_suivi.html.twig
- templates/back/signalement/view.html.twig
- templates/back/signalement/view/header.html.twig
#2480    
Permettre au SA le renvoi du lien de suivi directement depuis la fiche de signalement.Penser a proposer les deux options mail déclarant / mail occupant quand le cas se présente (éventuellement afficher le lien transmis pour contourner un blocage Brevo par exemple)
* Création d'une nouvelle modale et d'un bouton visible par les SA
* Modification de la route `send_mail_get_lien_suivi`
> [BO - Signalement] Renvoyer lien de suivi / SA

- templates/back/nav_bo.html.twig
#1634
Correction d'item du menu BO pour qu’ils s'affichent bien comme activé lors qu'on est sur la page correspondante
> [BO] Items de menu non actif

- templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
#2552   
L'auteur des suivis automatiques visibles aux usagers étaient faux sur la page de suivi usager (mais correct dans le BO)
* Modification du twig
>   [FO - Suivi usager] Mauvais affichage de l'auteur des rappels de visites sur la page de suivi usager 

- assets/json/Signalement/desordres_profile_occupant.json
- assets/json/Signalement/desordres_profile_tiers.json
- assets/json/Signalement/questions_profile_bailleur.json
- assets/json/Signalement/questions_profile_bailleur_occupant.json
- assets/json/Signalement/questions_profile_locataire.json
- assets/json/Signalement/questions_profile_service_secours.json
- assets/json/Signalement/questions_profile_tiers_particulier.json
- assets/json/Signalement/questions_profile_tiers_pro.json
- assets/json/Signalement/questions_profile_tous.json
- assets/vue/components/signalement-form/components/SignalementFormBreadCrumbs.vue
- assets/vue/components/signalement-form/components/SignalementFormButton.vue
- assets/vue/components/signalement-form/components/SignalementFormLink.vue
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
#2546    
Revue des liens dans le formulaire de signalement
* ajustement des `title` quand on ouvre une nouvelle fenêtre
* remplacement de composants liens par des composants boutons quand on ouvre une modal
> [FO - Formulaire - Accessibilité] Revue des liens

- assets/json/Signalement/desordres_profile_occupant.json
- assets/json/Signalement/desordres_profile_tiers.json
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
- assets/vue/components/signalement-form/store.ts
#2362    
Ajout de warning sur les 3 récap du formulaires si aucun désordre n'a été sélectionné
* Ajout d'une fonction dans le store pour vérifier si des désordres ont été cochés
* ajout de warning dans les json
* ajout d'un warning dans le composant `SignalementFormOverview`
> [FO - Form étape désordres] Ajouter des messages warning sur les récap désordres 

- assets/vue/components/signalement-form/address_subscreen.json
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormTextfield.vue
- assets/vue/components/signalement-form/services/subscreenManager.ts
- migrations/Version20240507143556.php
- src/Dto/Request/Signalement/SignalementDraftRequest.php
- src/Entity/Signalement.php
- src/Manager/SignalementManager.php
- src/Service/Signalement/SignalementBuilder.php
- templates/back/signalement/view/address-qualifications.html.twig
- templates/back/signalement/view/edit-modals/edit-address.html.twig
- templates/back/signalement/view/edit-modals/edit-coordonnees-bailleur.html.twig
#2342    
Sur certains département, les adresses recherchées ne se trouvent pas dans la BAN.
On ouvre donc la possibilité aux gens de saisir directement leur adresse.
Inconvénient : le code INSEE et la géolocalisation seront faux pour ces adresses.
> [FO - Signalement] Saisie des adresses hors-BAN

- assets/json/Signalement/questions_profile_bailleur.json
- assets/json/Signalement/questions_profile_bailleur_occupant.json
- assets/json/Signalement/questions_profile_locataire.json
- assets/json/Signalement/questions_profile_service_secours.json
- assets/json/Signalement/questions_profile_tiers_particulier.json
- assets/json/Signalement/questions_profile_tiers_pro.json
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/requests.ts
- src/EventSubscriber/SignalementDraftCompletedSubscriber.php
- src/Manager/SignalementDraftManager.php
- src/Service/Signalement/SignalementBuilder.php
#2363    
Au dépôt d'un signalement, si le signalement n'a aucun désordre, renvoyer l'usager vers une page l'invitant à compléter son signalement ou l'abandonner.
* Ajout d'une nouvelle page `signalement_incomplet` dans les json
* Dans l'app, vérifier qu'on a bien la référence su signalement créé lorsqu'on navigue vers la page "`confirmation_signalement`" sinon on redirige vers la nouvelle page 
* Création 'une action `archive` pour les boutons du formulaire et remaniement de la fonction `archiveDraft` (pour ne pas la limiter à la détection de doublon)
* Dans le `signalementBuilder` on vérifie que le signalement créé a des désordres et un score supérieur à 0 pour le builder, sinon on renvoie null et on n'enregistre pas le signalement en base (et on ne change pas le statut du draft)
`npm …
> [FO - Form - nouvelle étape] Renvoyer les signalements "vides" vers une nouvelle page

- templates/_partials/macros.html.twig
- templates/back/account/index.html.twig
- templates/back/notifications/index.html.twig
- templates/back/partner/index.html.twig
- templates/back/partner_archived/index.html.twig
#2518   
Rendre la pagination dynamique sur les listes paginées (hors ancienne liste de signalements) à l'instar de ce qui est fait sur la nouvelle liste de signalements.
Exemple pour la page 8 sur 51, au lieu de 
`1 2 3 .... 49 50 51`
avoir
`1 ... 6 7 8 9 10 ... 51`
* Création d'une macro twig
* utilisation de la macro pour la liste des notifications, des partenaires, des partenaires archivés et des comptes archivés
> [BO - listes] Rendre la pagination dynamique

- assets/json/Signalement/questions_profile_bailleur.json
- assets/json/Signalement/questions_profile_bailleur_occupant.json
- assets/json/Signalement/questions_profile_locataire.json
- assets/json/Signalement/questions_profile_service_secours.json
- assets/json/Signalement/questions_profile_tiers_particulier.json
- assets/json/Signalement/questions_profile_tiers_pro.json
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormEmailfield.vue
- assets/vue/components/signalement-form/components/SignalementFormPhonefield.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/components/SignalementFormSubscreen.vue
- assets/vue/components/signalement-form/components/SignalementFormTextfield.vue
#2236    
[Critère 11.13](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-13) [AA] : La finalité d'un champ de saisie peut-elle être déduite pour faciliter le remplissage automatique des champs avec les données de l'utilisateur ?
* Ajout de données d'autocomplete dans les json du formulaire
* Prise en charge de ces attributs d'autocomplete pour les composants SignalementFormTextfield, SignalementFormPhonefield, SignalementFormAdress et SignalementFormEmailfield
* Ajout d'une balise form et d'un bouton submit caché dans l'app pour faire marcher l'autocomplete
> [FO - Formulaire - Accessibilité - 11.13] Faciliter remplissage automatique des champs

- src/Repository/SignalementRepository.php
#2591    
Pour les stats front, on groupe les desordreCritere par label plutôt que par id, pour ne pas se retrouver avec les 3 désordres les plus courants ayant exactement le même label (cf en prod)
* Changement du SignalementRepository
> [FO - Stats] Les intitulés des désordres les plus courants dans le logement ne sont pas clairs

- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/requests.ts
#2595
- Correction : Lorsque que l'on saisie une adresse totalement manuellement, le champ "adresse_logement_adresse" est envoyé vide.
- Modification : Utilisation de l'étape pour déterminer si on envoie la requête de soumission des données du formulaire
- Modification : augmentation de la latence avant appel du checkterritory pour éviter popup intempestive en cas d'erreur de frappe ou frappe lente
> [BUG] corriger envoie de requêtes nouveau formulaire

- src/Controller/StatistiquesController.php
- src/EventListener/SeoPageNotFoundRedirectListener.php
#2603    
passer la route de /statistiques à /stats pour être en cohérence avec les autres startups
* Changement de la route du controller
> [FO - stats] Changer l'url de la route stats

- assets/styles/histologe.scss
- templates/front/aides_travaux.html.twig
- templates/front/contact.html.twig
- templates/front/obligations_entretien.html.twig
#2606
Inverser l'alerte et le bouton envoyer un mail sur la page contact
J'ai aussi virer un style css dans `histologe.scss` car il ajoutait de l'espacement autour de tous les `h2` et `h3` et cassait la mise en page, par exemple dans cette alerte : 
Comme ce style avait été ajouté dans ce commit https://github.com/MTES-MCT/histologe/commit/dd1d4b48ed5306c6249da6054b7fcbd82b2e43ea pour la mise en page des pages aides-travau et obligations-entretien, j'ai plutôt ajouté un `fr-mt-4w` sur les titres concernés de ces pages
* Modification des twig
* Modification de `histologe.scss`
> [FO - contact] Inverser l'alerte et le bouton envoyer un mail sur la page contact

- assets/controllers/component_search_address.js
- assets/json/Signalement/questions_profile_tous.json
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- src/Dto/Request/Signalement/AdresseOccupantRequest.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/address-qualifications.html.twig
- templates/back/signalement/view/edit-modals/edit-address.html.twig
#2342    
Suite aux retours d'Arnaud, quelques modifications nécessaires pour les adresses hors BAN.
Dans le BO, 
- quand on édite une adresse à la main, il faut l'alerte pour les autres agents
- mise à jour du code Insee, de la géolocalisation et du nom de la ville, en cas de modification du couple code postal / ville
Dans le FO, 
- modification mineure sur l'indication de la saisie d'adresse
- mise à jour de la géolocalisation et du nom de la ville, en cas de modification du couple code postal / ville
> [BO - Signalement] Réinitialisation de la géolocalisation quand édition de l'adresse

- cron.json
- migrations/Version20240524151828.php
- src/Command/Cron/AnonymizeExpiredAccountCommand.php
- src/Controller/Back/BackArchivedAccountController.php
- src/Controller/Back/PartnerController.php
- src/DataFixtures/Files/User.yml
- src/DataFixtures/Loader/LoadUserData.php
- src/Entity/User.php
- src/Repository/UserRepository.php
- src/Security/Voter/UserVoter.php
- tests/Functional/Command/Cron/AnonymizeExpiredAccountCommandTest.php
- tests/Functional/Controller/BackArchivedAccountControllerTest.php
- tests/Functional/Controller/BackExpiredAccountControllerTest.php
- tests/Functional/Controller/PartnerControllerTest.php
- tests/Unit/Entity/UserTest.php
#2429
#2554
- Ajout de la commande `app:anonymize-expired-account` qui anonymize les comptes agent sans activité depuis plus de deux ans à condition qu'il soit archivé (ce qui est fait automatiquement sans réponse de leur part via la commande `app:notify-and-archive-inactive-accounts`
- Correction du process de désarchivation d'un compte afin que l'utilisateur en cours de désarchivage ne soit pas bloqué par son propre e-mail (cas de soumission du formulaire sur un utilisateur sans partenaire/territoire non archivé)
> Anonymisation des comptes agents expiré 

- assets/controllers/component_search_address.js
- assets/json/Signalement/questions_profile_tous.json
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormAddress.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- src/Dto/Request/Signalement/AdresseOccupantRequest.php
- src/Manager/SignalementManager.php
- templates/back/signalement/view/edit-modals/edit-address.html.twig
- tests/Functional/Manager/SignalementManagerTest.php
- tests/Functional/Service/Signalement/PhotoHelperTest.php
#2601   
Suite à la possibilité donnée aux usagers et agents de modifier à la main les adresse, l'UX n'était pas idéale pour vérifier et mettre à jour le code Insee en cas d'édition manuelle.
* Côté FO : la mise à jour de la géolocalisation et la vérification de l'ouverture du territoire se fait au clic sur le bouton Suivant
* J'ai donc ajouté un nouveau type d'action dans le json `checkloc` qui vient remplacer `save` sur le premier écran
* J'ai déplacé la modale de territoire fermé à la racine de l'app plutôt que dans le composant d'adresse : c'est l'app elle-même qui fait cette vérification
* Côté BO : cela se fait à la validation du formulaire, côté back
* le js ne sert plus qu'à signaler qu'une modification manuelle a été faite ou non
Pour avoir des messages corrects : `make console …
> [Signalement] Modification des événements qui mettent à jour le code Insee de l'adresse des occupants

- src/Service/Mailer/Mail/Suivi/SuiviNewCommentFrontMailer.php
- templates/_partials/_modal_send_lien_suivi.html.twig
- templates/front/_partials/_suivi_signalement_tab_infos.html.twig
- templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
#2631 
#2632
#2634   
- Suppression d'un point dans la modale d'envoi de lien
- Lien direct vers le dernier suivi pour les usagers
- Mise en valeur de la partie qui conseille de prévenir son bailleur
> [FO - Page Suivi usager] Ajustement graphique et lien vers dernier suivi

- assets/json/Signalement/questions_profile_tiers_pro.json
#2593   
Ajout de la question type_logement_commodites_piece_a_vivre_9m pour les tiers pro
* Modification du json
> [FO - form] Ajout de la question type_logement_commodites_piece_a_vivre_9m pour les tiers pro

- assets/controllers/activate_account/activate_account.js
- src/Entity/User.php
- templates/front/cgu_agents.html.twig
- templates/security/reset_password_new.html.twig
- tests/Functional/Controller/UserAccountControllerTest.php
- tests/Unit/Entity/UserTest.php
#2638
Passe la longueur minimum des mot de passe de 8 a 12 caractères
> [Technique] [Socle sécurité] Complexifier les mots de passe 

- .env
- .env.sample
- config/services.yaml
- src/Service/Mailer/Mail/AbstractNotificationMailer.php
- templates/emails/base_email.html.twig
#2605   
Mise en place d'une adresse `ne-pas-repondre@histologe.beta.gouv.fr` pour toutes les notifications par e-mail
> [Notifications - Emails] Mise en place d'une adresse no-reply

- assets/controllers/front_suivi_signalement/front_suivi_signalement.js
- templates/front/_partials/_suivi_signalement_tab_infos.html.twig
- templates/front/_partials/_suivi_signalement_tab_suivi.html.twig
- templates/front/suivi_signalement.html.twig
#2629
#2630
#2635   
- Ajustement affichage de la liste de fichiers ajoutés avant envoi de suivi
- Déplacement de la date de dépôt
- Mise en forme données de l'onglet Mes infos
> [FO - Page Suivi usager] Ajustements graphiques

- src/Controller/Security/UserAccountController.php
- templates/security/login_link_sent.html.twig
- templates/security/reset_password.html.twig
#2644
Le système d'activation du compte et de réinitialisation du mot de passe retourne toujours la même page sans préciser si le compte existe ou pas, ni son statut afin d'éviter de pouvoir lister les comptes existants
> [Technique] [Sécurité] La demande de récup du mot de passe doit retourner une réponse unique

- composer.json
- composer.lock
- config/bundles.php
- config/packages/scheb_2fa.yaml
- config/packages/security.yaml
- config/routes/scheb_2fa.yaml
- migrations/Version20240605094114.php
- src/Entity/User.php
- src/Service/Mailer/AuthCodeMailer.php
- symfony.lock
- templates/bundles/SchebTwoFactorBundle/Authentication/form.html.twig
- tests/Functional/Controller/UserAccountControllerTest.php
#722
Ajout d'une authentification a deux facteurs pour les admin
`make composer`
> [Technique] Activer l'authentification multifacteur pour l'accès des administrateurs au service

- assets/vue/components/common/AppSearch.vue
- assets/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-list/TheSignalementAppList.vue
- assets/vue/components/signalement-list/components/SignalementListFilters.vue
- assets/vue/components/signalement-list/components/SignalementListHeader.vue
- assets/vue/components/signalement-list/services/badgeFilterLabelBuilder.ts
- assets/vue/components/signalement-list/store.ts
- src/DataFixtures/Loader/LoadSuiviData.php
- src/Dto/Request/Signalement/SignalementSearchQuery.php
- tests/Functional/Controller/Back/SignalementListControllerTest.php
- tests/Unit/Dto/Request/Signalement/SignalementSearchQueryTest.php
#2597    
Quand on commence par un tri alphabétique croissant, le tri alphabétique décroissant reste en croissant, et vice-versa, le tri n'est plus pris en compte quand on ajoute un filtre
Changer le tri "plus récent"/"plus ancien" en utilisant la date de dernier suivi plutôt que la date de dépôt (qui est redondant avec la référence)
* Correction tri
* Remplacement tri de date de dépôt par tri date de dernier suivi
* Correction url filtre territoires (`territoires[]=13` par `territoire=13`)
* Composant AppSearch, écouter uniquement sur l'evenement onInput
* Correction comportement suppression de la saisie
* Mise à jour fixtures pour les suivi(s)
```
make npm-watch
```
Les données de liste déroulante provenant de la base de données sont en cache, si besoin
```sh
make clear-pool …
```
> [BO - Filtre signalement] Correction tri 

- src/Security/Voter/FileVoter.php
#2668    
Fix de l'erreur `Uncaught PHP Exception TypeError: "App\Security\Voter\FileVoter::isAdminOrRTonHisTerritory(): Argument #2 ($user) must be of type App\Entity\User, null given, called in /app/src/Security/Voter/FileVoter.php on line 39" at FileVoter.php line 94` (ouverture d'un fichier non visible à l'usager en dehors d'une connexion à la plateforme)
* Changement du voter
> [QA] Pb sur FileVoter

- src/Controller/Back/SignalementVisitesController.php
#2670   
Ajout d'une vérification supplémentaire dans le SignalementVisitesController pour éviter une erreur sentry et afficher un message clair
* Changement du controlleur, on vérifie que la visite est bien dans le futur avant d'annuler la visite
Vérifier l'heure de php/symfony en local
>  [QA] Erreur annulation de visite

- src/Controller/Back/SignalementVisitesController.php
- src/Exception/File/EmptyFileException.php
- src/Service/Signalement/SignalementFileProcessor.php
- src/Service/UploadHandlerService.php
- tests/Functional/Service/UploadHandlerServiceTest.php
#2669   
Ajout d'une nouvelle exception pour les fichiers vides (sera plus clair que `Le format application/x-empty n'est pas supporté`)
Ajout d'unfo sur le fichier dans l'erreur loguée dans Sentry (pour vérifier s'il faut ajouter des formats, extensions, autoriser l'absence d'extension etc.)
* Ajout d'une exception
* Modification de SignalementFileProcessor
> [QA] Formats de fichiers non détectés

- src/Controller/Back/BackSignalementQualificationController.php
- src/Controller/Back/SignalementController.php
- src/Security/Voter/SignalementVoter.php
#2678   
La route back_signalement_qualification_editer est trop permissive, elle ne contient pas tous les contrôles présent sur back_signalement_view (voir $canEditNDE) pour savoir si le bloc est éditable sur le signalement
* Ajout d'une option de Voter à SignalementVoter
* utilisation de ce voter dans `back_signalement_qualification_editer` et `back_signalement_view`
`make console app="update-partners-communes-nde"` --> pour avoir des partenaires avec la compétence NDE dans le 63 et le 89
>  [Sécurité][BO] Cohérence des controles sur route back_signalement_qualification_editer

- src/Controller/Back/AffectationController.php
- src/Controller/Back/BackStatistiquesController.php
- src/Controller/Back/SignalementController.php
- src/Controller/Back/SignalementFileController.php
- src/Controller/Back/SignalementVisitesController.php
- src/Controller/Security/SecurityController.php
- src/Controller/SignalementController.php
- src/DataFixtures/Files/SignalementDraft.yml
- src/Security/Voter/FileVoter.php
- src/Security/Voter/SignalementVoter.php
- templates/back/signalement/view/header.html.twig
- templates/back/signalement/view/tags.html.twig
- tests/Functional/Controller/AffectationControllerTest.php
- tests/Functional/Controller/SignalementControllerTest.php
#2645
/SignalementController
- Mettre un Not Found sur reprise la de signalement en statuts : EN_SIGNALEMENT / ARCHIVE
- Bloquer la soumission d’un signalementDraft archivé
/Security/SecurityController
- Suppression de la route “app_csrf_token” plus utilisé
- Fix contrôles sur la route /_up et FileVoter (erreur amené suite à la nouvelle page suivi usager)
/Back/AffectationController
- Ajout de tests sur la route ‘back_signalement_toggle_affectation’
- Bloquer la possibilité de supprimer une affectation sur un signalement différent (+ tests)
/Back/BackTagController
- mise en cohérence du contrôle de la route ‘back_tag_create’ et du twig ‘tags.html.twig’
/Back/SignalementEditController
- Modification du voter sur ‘SIGN_EDIT’ afin que le contrôle vérifie les statuts du signalement …
> [Sécurité] Cloisonnement des rôles (+ divers)

- assets/vue/components/signalement-list/TheSignalementAppList.vue
- assets/vue/components/signalement-list/components/SignalementListFilters.vue
#2684 
#2683 
#2695 
#2693
2684 : Dans les filtres, les 2 filtres avec sélection multiple doivent avoir un fond gris
2683 : Pour le filtre étiquette, afficher les étiquettes par ordre alphabétique
2693 : Pour le filtre partenaires, afficher les partenaires par ordre alphabétique
2695 : Dans le filtre EPCI, il faudrait déplacer le numéro insee derrière le nom de l'EPCI et (entre parenthèses)
* Changement de l'app Vue
```
npm run watch
make clear-pool pool="--all"
make console app="load-epci"
```
> [BO - Liste signalement] Améliorations UI sur les filtres 

- assets/vue/components/common/AppAutoComplete.vue
- assets/vue/components/common/external/HistoDatePicker.vue
- assets/vue/components/dashboard/TheHistoDashboardCards.vue
- assets/vue/components/signalement-list/TheSignalementAppList.vue
- assets/vue/components/signalement-list/components/SignalementListFilters.vue
- assets/vue/components/signalement-list/components/SignalementListPagination.vue
- assets/vue/components/signalement-list/interfaces/filters.ts
- assets/vue/components/signalement-list/store.ts
- config/app/widgets.php
- config/app/widgets_new.yaml
- config/services.yaml
- src/Dto/Request/Signalement/SignalementSearchQuery.php
- src/Service/DashboardWidget/WidgetDataKpiBuilder.php
- src/Service/Signalement/SearchFilter.php
- tests/Unit/Dto/Request/Signalement/SignalementSearchQueryTest.php
#2636
#2120    
Permettre la recherche depuis la barre d'adresse
Faire pointer le tableau de bord sur la nouvelle liste lorsque la variable d'environnement est activée
* Récupération de tous les paramètres d'URL depuis le composant parent
* Ajout d'un nouveau fichier de configuration pour le tableau de bord
* Ajout d'une configuration dynamique du tableau de bord
Supprimer tous les pools de cache
```bash
make clear-pool pool="--all"
```
```bash
make npm-build # ou make npm-watch
```
```bash
FEATURE_LIST_FILTER_ENABLE=1
```
Les tests sont à faire avec tous les profils.
| Filtre                   | URL                                                                                                    |
|--------------------------|--------------------------------------------------------------- …
> [BO - Liste signalement] Pouvoir filtrer la liste des signalement à travers l'url

- src/Command/Cron/NotifyVisitsCommand.php
#2598    
Lorsqu'une affectation par un partenaire avec la compétence VISITE est passée depuis 15 jours et qu'aucune visite n'est prévue, le partenaire reçoit un mail et un suivi est créé.
On modifie le texte du suivi.
> [BO - Visite] Modification du suivi créé lorsqu'une visite doit être effectuée

- src/Controller/BailleurController.php
- src/Repository/BailleurRepository.php
- tests/Functional/Controller/BailleurControllerTest.php
- tests/Functional/Repository/BailleurRepositoryTest.php
- tests/Functional/Service/Signalement/SignalementBuilderTest.php
#2700
- Correction du `BailleurRepository` afin que la recherche du bailleur utilisé à la création d'un draft en signalement fonctionne que le bailleur soit radié ou pas (pour rappel le nom du bailleur est toujours retourné sans la partie "[Radié(e)]" coté front mais pas coté BO)
- Correction d'un filtre dans la fonction `sanitizeBailleurs` afin que l'on retrouve les bailleur radié malgré des différences de case/accentuation
> [FO - Signalement]Vérifier la liaison avec la table bailleur dans le parc public

- assets/json/Signalement/desordres_profile_tiers.json
- assets/json/Signalement/questions_profile_service_secours.json
- assets/json/Signalement/questions_profile_tiers_particulier.json
- assets/json/Signalement/questions_profile_tiers_pro.json
- src/Entity/Model/InformationProcedure.php
#2275   
Les questions concernant le bail/dpe et la procédure n'étaient pas posées aux tiers jusque là.
Elles sont donc ajoutées aux parcours tiers particulier, tiers pro et service de secours.
> [FO - Formulaire] Ajout de questions de bail et de procédure pour les tiers

- src/Service/Esabora/EsaboraManager.php
- src/Service/Esabora/Response/DossierPushSISHResponse.php
- src/Service/Esabora/Response/DossierResponseInterface.php
- src/Service/Esabora/Response/DossierStateSCHSResponse.php
- src/Service/Esabora/Response/DossierStateSISHResponse.php
- tests/Functional/Manager/Esabora/EsaboraManagerTest.php
#2705   
Modification du message de suivi lors de la mise à jour d'un dossier sur SISH :
- ajout du numéro de dossier Esabora
- remplacement de `SI-SH` par `SI-Santé Habitat (SI-SH)`
> [Esabora - SISH] Intégration du numéro de dossier aux messages de suivi de statut

- src/DataFixtures/Files/NewSignalement.yml
- src/DataFixtures/Loader/LoadSignalementData.php
- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
- src/Service/Esabora/CiviliteMapper.php
- src/Service/Esabora/Enum/PersonneQualite.php
- src/Service/Esabora/EsaboraSISHService.php
- src/Service/Esabora/Model/DossierMessageSISHPersonne.php
- tests/FixturesHelper.php
- tests/Functional/Service/Esabora/CiviliteMapperTest.php
#2704    
Il est possible de transmettre les données de civilité à SISH pour utilisation dans leur logiciel.
* Pour l'occupant : on a la civilité en option
* Si vide : on envoie `MADAME_MONSIEUR`
* Sinon, on envoie selon ce qu'on sait : `MADAME` ou `MONSIEUR`
* Pour le déclarant : on n'envoie rien
* Pour le proprio, on utilise typeProprio
* Si le typeProprio est `ORGANISME_SOCIETE` : on envoie `SOCIETE`
* Sinon, on n'envoie rien
> [Esabora - SISH] Envoi de la civilité

- assets/app.ts
- assets/controllers/back_archived_signalements/back_archived_signalements_reactiver.js
- src/Controller/Back/ArchivedSignalementController.php
- src/Repository/SignalementRepository.php
- templates/back/nav_bo.html.twig
- templates/back/signalement_archived/index.html.twig
- tests/Functional/Controller/ArchivedSignalementControllerTest.php
- tests/Functional/Repository/SignalementRepositoryTest.php
#2659   
Avoir une page avec la liste des signalements archivés, filtrable par territoire et par référence, et un bouton pour les désarchiver. 
* Création du controlleur et de la route
* Création du template twig et du controlleur js associé
* Création des tests
> [BO - Admin] Avoir accès à la liste des signalements qu'on peut désarchiver

- assets/vue/components/signalement-list/components/SignalementListCards.vue
- src/Service/Signalement/SearchFilter.php
#2723    
#2718 (régression + correction compteur)
Le badge NDE ne s'affiche pas. 
La PR #2718 applique une régression qui limite l'affichage des badges uniquement au badge du signalement filtré. 
* Ajout d'une condition pour afficher le badge NDE
* Correction de la sous-requête du filtre procédure
* Ignorer les signalements pour le filtre NDE lorsque celui ci est archivé (corrige le compteur)
```
make load-data
```
> [BO - Listes des signalements] Problème d'affichage des procédures suspectées sur la carte

- src/Entity/Signalement.php
- src/Security/Voter/SuiviVoter.php
- templates/back/signalement/view/suivis.html.twig
#2729   
Un admin partenaire pouvait ajouter des suivi sur un signalement qu'il n'avait pas accepté. Correction de ce bug
* Durcissement du SuiviVoter
* Utilisation du voter COMMENT_CREATE dans le twig
> [BO - Signalement] Un admin partenaire ne peut plus ajouter des suivis sur un signalement sans avoir accepté l'affectation

- migrations/Version20240625095546.php
- src/Command/Cron/NotifyAndArchiveInactiveAccountCommand.php
#2726
#2730   
A l'occasion du ticket #2726 on a découvert qu'il y avait en prod 1755 utilisateurs archivés n'ayant pas le suffixe ".archived@" dans leur adresse mail : https://histologe-metabase.osc-fr1.scalingo.io/question/1198-users-archives-sans-suffixe-archived
Cela vient de la commande `notify-and-archive-inactive-accounts` qui change le statut de l'utilisateur sans tagger le mail.
Outre la correction à apporter à la commande, cela offre un bon moyen d'accéder à la demande d'Arnaud de désarchiver tous les utilisateurs ayant été archivés par cette commande (#2730)
* Fix de la commande
* Création d'une migration pour désarchiver ces 1755 utilisateurs (on remet le statut à 0 si l'utilisateur ne s'est jamais logué, à 1 s'il s'est logué)
Passer plusieurs utilisateurs au statut 2 sans …
> [BO - Command] Fix de la commande d'archivage des utilisateurs

- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/components/SignalementFormModalAlreadyExists.vue
- assets/vue/components/signalement-form/components/SignalementFormScreen.vue
- assets/vue/components/signalement-form/requests.ts
- assets/vue/components/signalement-form/store.ts
- src/Controller/SignalementController.php
- src/Manager/SignalementDraftManager.php
- templates/front/nouveau_formulaire.html.twig
- tests/Functional/Manager/SignalementDraftManagerTest.php
#2677   
Ne pas renvoyer l'uuid du signalement draft dans la route `check_signalement_or_draft_already_exists`
* Dans l'app Vue, on remplace formStore.alreadyExists.uuidDraft par formStore.alreadyExists.draftExists et on ne met plus l'uuid dans les routes appelées (par contre on envoie formStore.data)
* Dans le controller, création d'une fonction findSignalementDraft qui renvoie un SignalementDraft à partir d'un SignalementDraftRequest, et on utilise cette fonction dans les 3 routes pour retrouver l'uuid du draft concerné
> [Sécurité] [FO] Masquer l'uuid des SignalementDraft en doublon trouvés

- assets/json/Signalement/questions_profile_service_secours.json
- assets/json/Signalement/questions_profile_tiers_particulier.json
- assets/json/Signalement/questions_profile_tiers_pro.json
- assets/vue/components/signalement-form/components/SignalementFormOverview.vue
#2275   
Dans le formulaire de signalement, la réponse de l'assurance est un champ facultatif pour les tiers.
> [FO - Signalement] Pour les tiers, la réponse de l'assurance est un champ facultatif

- migrations/Version20240626180734.php
- src/Controller/Back/SignalementFileController.php
- src/Controller/SignalementController.php
- src/Controller/SignalementFileController.php
- src/Entity/Signalement.php
- src/Service/UploadHandlerService.php
- tests/Functional/Service/UploadHandlerServiceTest.php
#2734
Correction de l'utilisation du flag is_waiting_suivi sur les documents envoyé depuis la popup d'upload : 
- Les docs ayant ce flag ne sont à présent jamais affichés sur le signalement (auparavant ils l'étaient même sans validation du popup)
- Une migration passe le flag a false pour ceux existant afin que des doc ne disparaissent pas sur de signalement ou ils étaient affichés
- Lors de la validation de la popup un suivi contenant les doc ayant ce flag est généré : ajout du contrôle de l'utilisateur ayant uploadé le fichiers + suppression du fichier si il date de plus d'une heure.
Le principe d'un flag temporaire existant aussi coté fiche signalement usager, pour éviter tout problème lors de la validation si le fichier temporaire à été uploadé il y'a plus d'une heure on le supprime. …
> [BUG] photo en attente de suivi pouvant rester en attente plusieurs jours

- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
- tests/FixturesHelper.php
- tests/Unit/Factory/Esabora/DossierMessageSISHFactoryTest.php
#2744    
Ajouter une précision d'un chiffre après la virgule
* Ajout de la précision dans le dossier SISH
```sh
```
Chercher un signalement du 13 avec un score.
> [Esabora - SI-SH] Arrondir le score avec 1 chiffre après la virgule

- src/Factory/Interconnection/Esabora/DossierMessageSISHFactory.php
- src/Messenger/Message/Esabora/DossierMessageSISH.php
- tests/FixturesHelper.php
- tests/Unit/Factory/Esabora/DossierMessageSISHFactoryTest.php
#2743    
*Requête*
```
"sitLogementSuperficie":66.19,
````
*Réponse*
```json
{
"sasId": null,
"statusCode": 400,
"errorReason": "{\"code\":\"WS_ERR_SQL\",\"message\":\"22P02 - ERROR:  invalid input syntax for integer: \\\"66.19\\\"\"}",
"sasEtat": null,
"sasCauseRefus": null,
"etat": null,
"nameSI": "SI-SH"
}
```
```sh
```
En base de données, chercher un signalement du 13 et mettez un nombre décimal sur la superficie.
> [Esabora - SI-SH] Envoi impossible de dossier lorsque la superficie n'est pas un entier

- migrations/Version20240701083800.php
- src/Service/Esabora/EsaboraManager.php
- tests/Functional/Manager/Esabora/EsaboraManagerTest.php
#2756    
Tous les appels à Esabora SISH créaient un suivi même s'il n'y avait aucun changement, car on ajoutait dans tous les cas le numéro de dossier dès qu'on l'avait
* Changement dans EsaboraManager->updateStatusFor() pour n'ajouter le numéro de dossier reçu que s'il y a un changement à indiquer dans un suivi
* Ajout d'un test fonctionnel pour vérifier que si on joue 2 fois de suite la fonction, seulement un suivi est créé
* Ajout d'une migration pour supprimer les suivis inutiles créés depuis la mise en prod du vendredi 28 juin 2024
AVANT de charger la branche
```
make console app="sync-esabora-sish"
make console app="sync-esabora-sish"
```
Deux suivis doivent être créés dans le signalement http://localhost:8080/bo/signalements/00000000-0000-0000-2023-000000000012 …
> [Esabora] Correction de la création de suivi automatique lors des appels à Esabora

- src/Service/UploadHandlerService.php
#2771
Utilisation des images et document au format réduit lors de la synchronisation des dossier afin d'eviter des time out due à leurs poids
Modification de la fonction `getTmpFilepath` afin qu'elle retourne toujours la version "resize" d'un document (si cette version existe)
> [Esabora SCSH] envoyer les document en format "resize" quand il s'agit d'image

- .scalingo/nginx/server.location
- assets/vue/components/signalement-form/TheSignalementAppForm.vue
- assets/vue/components/signalement-form/matomo.ts
- templates/base.html.twig
#2604    
Envoi à Matomo des changements d'écran dans le formulaire de signalement.
Dans un premier temps, j'avais imaginé modifier le hash au sein de l'url. Mais il s'avère que ce n'est pas nécessaire.
Matomo a une fonction pour cela : utiliser des événements qui peuvent être catégorisés.
* Reprise des corrections sur les headers que Hélène a fait par ailleur pour l'utilisation de Matomo
* Ajout d'un push de type `trackEvent` à Matomo lors d'un changement d'écran, en précisant le slug de l'écran en cours
`make down`
`make run`
`make tools-run`
`make matomo-disable-ssl`
> [FO - Formulaire] Envoi des changements d'écran à Matomo sous forme d'événement
